### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Review by julianbrost — COMMENTED** [review]
Can you explain why you think the grammar is broken here? For me, these continue the sentence before as that one ended with a comma, so I think it's fine to start with a lower-case letter.

**Comment by Al2Klimov** [comment]
I hoped _you_ could tell _me_ as https://github.com/Icinga/icinga2/pull/8841#discussion_r657118537 .

**Comment by julianbrost** [comment]
There, these list items follow after a complete sentence ending with a colon and the previous two items already start with an upper-case letter.

**Comment by Al2Klimov** [comment]
Fine. 🤷‍♂️

**Pull request closed without merging**
