### PR TITLE
socket/apilistener: Use integer for service identification

### PR DESCRIPTION
**Pull request by lazyfrosch**
refs #6511

cc @nilmerg

Please review :)

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Note to self: `std::pair<String, uint>` does not work on Windows ...

**Comment by nilmerg** [comment]
Same as #6556, would be nice to get this in the master soon.

**Comment by dnsmichi** [comment]
We shouldn't change the function interfaces just because we need a number instead of a string. A more simple approach would be to just call Convert::ToLong(details.second) before writing the data into the json file. This also avoids the C-style with atoi(). I'll fix this in a separate PR.

**Comment by dnsmichi** [comment]
Closing in favour of #6567.

**Pull request closed without merging**
