### PR TITLE
Run event handler only for state changes

### PR DESCRIPTION
**Pull request by Al2Klimov**
not for not changed soft states.

refs #8704

### CODE REVIEW

**Comment by julianbrost** [comment]
Did #9259 make this PR obsolete?

**Comment by Al2Klimov** [comment]
I'd say no.

**Comment by julianbrost** [comment]
But this PR changes the behavior away from [the documented behavior](https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/#event-commands). So if you'd want to change that, there has to be a good reason for this.

**Comment by Al2Klimov** [comment]
You're right. We'd have to adjust the docs. But before annoying everyone via GHA let’s get another opinion...

**Comment by Al2Klimov** [comment]
I'd say: no state change – no (unnecessary) run, as with hard states.

**Comment by julianbrost** [comment]
Wasn't this PR opened as an attempt to fix #8704? Now that issue is closed but this PR is still open. I don't see a reason why we'd want to do a breaking change here nobody asked for and doesn't seem to really make anything better for us either.

**Comment by julianbrost** [comment]
The documentation says that event commands are run for soft states. The purpose of the PR is to change this behavior. That's a breaking change in the sense that is changes user-visible behavior that users might rely on. Of course, it's not like we could never ever do this, but if we do, there should be a good reason for it. And so far, this PR does not provide one.

**Comment by Al2Klimov** [comment]
## Reason

Running on _every_ soft state

1. is unnecessary,
2. inconsistent with running only on hard state _changes_ and
3. has to be worked around in the handler if even possible.

**Comment by lippserd** [comment]
> Running on _every_ soft state
> 
> 1. is unnecessary,

This can only be an assumption. Event handlers might attempt to solve a problem before reloading, restarting or killing a service.

Let's close this PR.

**Comment by julianbrost** [comment]
I fear doing a change like this could result in a similar mess like we have right now due to that disjunctive/conjunctive dependencies change.

> 3. has to be worked around in the handler if even possible.

Sounds like an assumption or claim to me. Can you provide a practical example that wouldn't work with the current implementation but would be enabled by this PR?

**Comment by Al2Klimov** [comment]
I mean if you want to handle only state _changes_ your event handler has to check whether the context is a state change.

**Comment by julianbrost** [comment]
That's merely the PR description rephrased. I asked for a *practical* example, i.e. a realistic situation that shows why this change would be desirable.

**Comment by Al2Klimov** [comment]
Maybe to give the service a chance to recover from soft state by itself before intervention. That's what soft states are for after all.

**Comment by julianbrost** [comment]
After multiple requests, you can only provide something that sounds like a wild guess why someone could potentially want this. This just does not justify doing an incompatible change to a behavior that has been like this before and nobody really asked for.

**Pull request closed without merging**
