### PR TITLE
Utility::ValidateUTF8(): use UTF8-CPP

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Substitutes #7013.

**Comment by dnsmichi** [comment]
Which license does the library use? I wasn't able to figure it out from the headers.

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icinga2/blob/3ec0268cb48dc005f8a7719e007c53ef111035cd/third-party/utf8cpp/source/utf8.h

**Comment by Al2Klimov** [comment]
Looks like MIT.

**Comment by dgoetz** [comment]
Looks more like https://opensource.org/licenses/BSL-1.0

**Comment by lazyfrosch** [comment]
Please document the license with name and URL reference inside the `third-party/utf8cpp/` directory.

Packagers will thank you.

**Comment by Al2Klimov** [comment]
@lazyfrosch nemtrif/utfcpp#23

**Comment by dnsmichi** [comment]
Thanks for clarification, much appreciated 👍

**Pull request merged**
