### PR TITLE
icinga2 daemon --close-stdio: keep console log open during first config validation

### LINKED ISSUE #7394: New umbrella system seems to break startup logging under systemd
## Describe the bug

It seems that on systemd, the new umbrella system hides the startup errors when starting with `--close-stdio`.

## To Reproduce

1. Create a syntax error
2. Restart the systemd service

## Expected behavior

Icinga should log the syntax error

## Screenshots

With `--close-stdio`:
```
systemd[1]: Starting Icinga 2 monitoring system...
icinga2[31289]: [2019-08-04 14:59:49 +0200] information/cli: Icinga application loader (version: r2.11.0-rc1-1)
icinga2[31289]: [2019-08-04 14:59:49 +0200] information/cli: Closing console log.
systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: icinga2.service: Killing process 31393 (.icinga2-wrappe) with signal SIGKILL.
systemd[1]: icinga2.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Icinga 2 monitoring system.
```

Without `--close-stdio`:
```
systemd[1]: Starting Icinga 2 monitoring system...
icinga2[2101]: [2019-08-04 15:00:35 +0200] information/cli: Icinga application loader (version: r2.11.0-rc1-1)
icinga2[2101]: [2019-08-04 15:00:35 +0200] information/cli: Loading configuration file(s).
icinga2[2101]: [2019-08-04 15:00:35 +0200] critical/config: Error: syntax error, unexpected new-line
[…]
systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: icinga2.service: Killing process 2210 (.icinga2-wrappe) with signal SIGKILL.
systemd[1]: icinga2.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Icinga 2 monitoring system.
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 2.11
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

cc @Al2Klimov because of #7320

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7394

### CODE REVIEW

**Comment by dnsmichi** [comment]
Freshly built v2.11.0-rc1-39-g6418c2e; debug in CentOS 7 with systemd enabled.

## Systemd

```
[root@icinga2-centos7-dev icinga2]# systemctl status icinga2
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-08-06 16:01:25 CEST; 39s ago
  Process: 17003 ExecStart=/usr/local/icinga2/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 16992 ExecStartPre=/usr/local/icinga2/lib/icinga2/prepare-dirs /usr/local/icinga2/etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 17003 (code=exited, status=1/FAILURE)

Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(16):  */
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(17):
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(18): oobject Host...ame {
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: ^^^^
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(19):   /* Import ...`. */
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[17003]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(20):   import "ge...host"
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: icinga2.service: main process exited, code=exited, status=1/FAILURE
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: Failed to start Icinga host/service/network monitoring system.
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: Unit icinga2.service entered failed state.
Aug 06 16:01:25 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: icinga2.service failed.
Warning: icinga2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hint: Some lines were ellipsized, use -l to show in full.
```

That works fine.

## error.log

Still, the error.log is not created.

```
[Unit]
Description=Icinga host/service/network monitoring system
Requires=network-online.target
After=syslog.target network-online.target postgresql.service mariadb.service carbon-cache.service carbon-relay.service

[Service]
Type=notify
Environment="ICINGA2_ERROR_LOG=/usr/local/icinga2/var/log/icinga2/error.log"
EnvironmentFile=/usr/local/icinga2/etc/sysconfig/icinga2
ExecStartPre=/usr/local/icinga2/lib/icinga2/prepare-dirs /usr/local/icinga2/etc/sysconfig/icinga2
ExecStart=/usr/local/icinga2/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG}
PIDFile=var/run/icinga2/icinga2.pid
ExecReload=/usr/local/icinga2/lib/icinga2/safe-reload etc/sysconfig/icinga2
TimeoutStartSec=30m
KillMode=mixed

# Systemd >228 enforces a lower process number for services.
# Depending on the distribution and Systemd version, this must
# be explicitly raised. Packages will set the needed values
# into /etc/systemd/system/icinga2.service.d/limits.conf
#
# Please check the troubleshooting documentation for further details.
# The values below can be used as examples for customized service files.

#TasksMax=infinity
#LimitNPROC=62883

[Install]
WantedBy=multi-user.target
```.

**Comment by dnsmichi** [comment]
Indeed, error.log always is empty with 2.10.5. That's a different problem then, but nothing for 2.11. We may consider scratching that log anyways, but that's a different story.

**Comment by dnsmichi** [comment]
The PR is fine, I was just testing a small addition with logging and encouraging the user to fix the config and re-run config validation.

```
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: [2019-08-07 11:53:43 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
```

```
[root@icinga2-centos7-dev icinga2]# systemctl status icinga2 -l
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-08-07 11:53:43 CEST; 10s ago
  Process: 22031 ExecStart=/usr/local/icinga2/sbin/icinga2 daemon --close-stdio -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 22022 ExecStartPre=/usr/local/icinga2/lib/icinga2/prepare-dirs /usr/local/icinga2/etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 22031 (code=exited, status=1/FAILURE)

Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(17):
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(18): oobject Host NodeName {
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: ^^^^
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(19):   /* Import the default host template defined in `templates.conf`. */
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: /usr/local/icinga2/etc/icinga2/conf.d/hosts.conf(20):   import "generic-host"
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com icinga2[22031]: [2019-08-07 11:53:43 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: icinga2.service: main process exited, code=exited, status=1/FAILURE
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: Failed to start Icinga host/service/network monitoring system.
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: Unit icinga2.service entered failed state.
Aug 07 11:53:43 icinga2-centos7-dev.vagrant.demo.icinga.com systemd[1]: icinga2.service failed.
```

**Comment by dnsmichi** [comment]
@Al2Klimov if you agree on this, I'll add this to this PR in a separate commit.

**Comment by Al2Klimov** [comment]
Ok.

**Pull request merged**
