### PR TITLE
rough fix for ServicesTable::AddColumns replacing LogTable::HostNameA…

### PR DESCRIPTION
**Pull request by spaolo**
I think the real problem lays in the line below but i can't affoard a full debug on it

https://github.com/Icinga/icinga2/blob/aad100aa6a4a5b0669aec8449a14826bfeefb8b6/lib/livestatus/servicestable.cpp#L141

Currently using this fix without any apparent problem

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks. Can you please explain the problem a little more, e.g. what it does need to reproduce the issue and test your patch?

**Comment by spaolo** [comment]
As described in the issue #5698 it should be enough restarting icinga2 istance to have a bunch of "CURRENT HOST STATE" row to be written into compat log and then run  the following query from the livestatus socket.

----------------------------------------------------------
GET log
Columns: type host_name
Filter: type = HOST NOTIFICATION
Filter: type = CURRENT HOST STATE
Or: 2
OutputFormat: csv
ResponseHeader: fixed16

-----------------------------------------------------------
you will receive a list like 
CURRENT HOST STATE;
CURRENT HOST STATE;
instead of 
CURRENT HOST STATE;hostname1
CURRENT HOST STATE;hostname2

with the hostname in the second column as asked in the "Column:" query attribute.

**Comment by dnsmichi** [comment]
I'd be happy if someone else could also test this PR.

**Comment by dnsmichi** [comment]
Unfortunately we won't put any effort into this feature anymore. Thanks for your contribution though.

**Pull request closed without merging**
