### PR TITLE
DbObject#SendConfigUpdateHeavy(): ensure the group memberships to be in the same transaction

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by julianbrost** [comment]
Do you plan to finish this PR soon so that we can consider it for 2.13? If not, please remove the milestone.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by Al2Klimov** [comment]
ref/IP/33545

**Comment by Al2Klimov** [comment]
Awaits feedback from partner.

**Pull request closed without merging**
