### PR TITLE
Replace origin of check_sar-perf.py, since it not not maintained ther…

### PR DESCRIPTION
**Pull request by RincewindsHat**
…e anymore.
I would offer to maintain it.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@N-o-X Do you consider this required?

**Comment by julianbrost** [comment]
I think we should rather discuss if we want to move it to the Icinga namespace rather than into the next person's account.

**Comment by Al2Klimov** [comment]
Would you maintain it in the Icinga namespace?

**Comment by julianbrost** [comment]
Just saying:
> RincewindsHat
> Member of Icinga

**Comment by RincewindsHat** [comment]
I don't really care, where it is. Choose whatever fits you best.

**Comment by RincewindsHat** [comment]
https://github.com/NETWAYS/check-sar-perf
happy?

**Review by julianbrost — CHANGES_REQUESTED** [review]
Can you squash the commits and set the author to your @netways.de e-mail address? Then cla-bot should be happy and then I will be happy :D

**Comment by bobapple** [comment]
@cla-bot check

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
