### PR TITLE
Tests: _Exit() in main()

### LINKED ISSUE #7334: Unit tests for checkresult are unstable
Possible follow up for #7257 

There still seem to be some issues with `icinga_checkresult/service_1attempt`

Happens not every time, with a retry it worked fine.

```
 76/106 Test  #76: base-icinga_checkresult/service_1attempt ................................***Exception: SegFault  2.01 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Notification triggered: Problem
Second check result (ok)
Notification triggered: Recovery
Third check result (critical)
Notification triggered: Problem
Fourth check result (ok)
Notification triggered: Recovery

*** No errors detected
```

* First try failed: https://git.icinga.com/packaging/deb-icinga2/-/jobs/13894
* Retry worked: https://git.icinga.com/packaging/deb-icinga2/-/jobs/13908

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7334

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Seems like this has a type conversion problem on Windows. I'm running tests with the Debian builds based on this branch:

https://git.icinga.com/packaging/deb-icinga2/pipelines/4334

**Comment by lazyfrosch** [comment]
Note: Does not fix the Bionic x86 problem: https://git.icinga.com/packaging/deb-icinga2/-/jobs/14168

**Comment by Al2Klimov** [comment]
Strange, the Windows build doesn't work in our build system either..

**Comment by Al2Klimov** [comment]
Strange, the Windows build doesn't work in our build system either..

**Comment by Al2Klimov** [comment]
Strange, the Windows build doesn't work in our build system either..

**Comment by Al2Klimov** [comment]
Strange, the Windows build doesn't work in our build system either..

**Comment by dnsmichi** [comment]
Seems that the `main()` override doesn't work this way, and the test-checkable binary fails to lookup the missing header symbol. Or the signature is wrong, I did not research deeper.

```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /IC:\Libraries\boost_1_67_0 /I"C:\OpenSSL-v111-Win64\include" /I"C:\projects\icinga2\third-party\nlohmann_json" /I"C:\projects\icinga2\third-party\utf8cpp\source" /IC:\projects\icinga2 /IC:\projects\icinga2\lib /IC:\projects\icinga2\Build /IC:\projects\icinga2\Build\lib /IC:\projects\icinga2\Build\test /I"C:\Tools\vcpkg\installed\x64-windows\include" /Zi /nologo /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D I2_DEBUG /D BOOST_COROUTINES_NO_DEPRECATION_WARNING /D BOOST_FILESYSTEM_NO_DEPRECATED /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHs /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"boosttest-test-base.dir\Debug\\" /Fd"boosttest-test-base.dir\Debug\vc141.pdb" /Gd /TP /errorReport:queue  /bigobj /GL- C:\projects\icinga2\Build\test\base_unity.cpp "C:\projects\icinga2\test\test-runner.cpp"
  base_unity.cpp
  test-runner.cpp
  Generating Code...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\icinga2\Build\Bin\Debug\Debug\boosttest-test-base.exe" /INCREMENTAL /NOLOGO /LIBPATH:"C:/Libraries/boost_1_67_0/lib64-msvc-14.1" /LIBPATH:"C:/Libraries/boost_1_67_0/lib64-msvc-14.1/Debug" /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\debug\lib" /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\debug\lib\manual-link" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_context-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_coroutine-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_date_time-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_filesystem-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_thread-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_system-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_program_options-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_regex-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_chrono-vc141-mt-gd-x64-1_67.lib" "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_atomic-vc141-mt-gd-x64-1_67.lib" "C:\OpenSSL-v111-Win64\lib\VC\libssl64MDd.lib" "C:\OpenSSL-v111-Win64\lib\VC\libcrypto64MDd.lib" ws2_32.lib dbghelp.lib shlwapi.lib msi.lib "C:\Libraries\boost_1_67_0\lib64-msvc-14.1\libboost_unit_test_framework-vc141-mt-gd-x64-1_67.lib" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\Tools\vcpkg\installed\x64-windows\debug\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/projects/icinga2/Build/Bin/Debug/Debug/boosttest-test-base.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/icinga2/Build/Bin/Debug/Debug/boosttest-test-base.lib" /MACHINE:X64  /machine:x64 "boosttest-test-base.dir\Debug\test-runner.obj"
  "boosttest-test-base.dir\Debug\base_unity.obj"
  "C:\projects\icinga2\Build\third-party\mmatch\mmatch.dir\Debug\mmatch.obj"
  "C:\projects\icinga2\Build\third-party\socketpair\socketpair.dir\Debug\socketpair.obj"
  "C:\projects\icinga2\Build\lib\base\base.dir\Debug\application-version.obj"
  C:\projects\icinga2\Build\lib\base\base.dir\Debug\base_unity.obj
  C:\projects\icinga2\Build\lib\config\config.dir\Debug\config_lexer.obj
  C:\projects\icinga2\Build\lib\config\config.dir\Debug\config_parser.obj
  C:\projects\icinga2\Build\lib\config\config.dir\Debug\config_unity.obj
  C:\projects\icinga2\Build\lib\remote\remote.dir\Debug\remote_unity.obj
  "C:\projects\icinga2\Build\lib\icinga\icinga.dir\Debug\icinga-itl.obj"
  C:\projects\icinga2\Build\lib\icinga\icinga.dir\Debug\icinga_unity.obj
test-runner.obj : error LNK2019: unresolved external symbol "int __cdecl boost::unit_test::unit_test_main(bool (__cdecl*)(void),int,char * * const)" (?unit_test_main@unit_test@boost@@YAHP6A_NXZHQEAPEAD@Z) referenced in function main [C:\projects\icinga2\Build\test\boosttest-test-base.vcxproj]
C:\projects\icinga2\Build\Bin\Debug\Debug\boosttest-test-base.exe : fatal error LNK1120: 1 unresolved externals [C:\projects\icinga2\Build\test\boosttest-test-base.vcxproj]
Done Building Project "C:\projects\icinga2\Build\test\boosttest-test-base.vcxproj" (default targets) -- FAILED.
Project "C:\projects\icinga2\Build\ALL_BUILD.vcxproj" (1) is building "C:\projects\icinga2\Build\test\boosttest-test-icinga_checkable.vcxproj" (14) on node 1 (default targets).
Project "C:\projects\icinga2\Build\test\boosttest-test-icinga_checkable.vcxproj" (14) is building "C:\projects\icinga2\Build\lib\cli\cli.vcxproj" (15) on node 1 (default targets).
InitializeBuildStatus:
  Creating "cli.dir\Debug\cli.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
```

**Comment by Al2Klimov** [comment]
The joke is that it works on \*nix.

**Comment by dnsmichi** [comment]
http://boost.2283326.n4.nabble.com/Boost-Tests-Unit-test-defines-own-main-function-why-td2638225.html

seems to be a problem static vs. dynamic linking. That always differs on Windows vs *nix.

**Comment by dnsmichi** [comment]
# Tests

Screen Shot 2019-07-23 at 12 35 02
Screen Shot 2019-07-23 at 12 35 54
Screen Shot 2019-07-23 at 12 37 01

**Pull request merged**
