### PR TITLE
Boost v1.81, OpenSSL v1.1.1t

### PR DESCRIPTION
**Pull request by Al2Klimov**
Backport of:
* #9673
* #9667
* #9624
* #9566
* #9456
* #9549

### CODE REVIEW

**Comment by julianbrost** [comment]
I'd have preferred separate PRs, but please at least mention the source PRs (also for the cross-reference there to be able to find the backport).

**Comment by Al2Klimov** [comment]
* #9673
* #9667
* merge conflict dependencies

**Comment by julianbrost** [comment]
> merge conflict dependencies

The PRs where those come from should also be mentioned.

**Comment by Al2Klimov** [comment]
* #9624
* #9566
* #9456
* #9549

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
