### PR TITLE
ThreadPool: use the Boost ASIO thread pool under the hood

### LINKED ISSUE #6985: Re-write thread pool
According to @lippserd we have several issues originated by the thread pool. I shall try to make a better one.

Edit by @dnsmichi: Add details below.

## Usage

The TP is used literally everywhere in Icinga:

```
michi@mbpmif ~/dev/icinga/icinga2 (master=) $ grep -r Utility::QueueAsync lib/
lib//checker/checkercomponent.cpp:		Utility::QueueAsyncCallback(std::bind(&CheckerComponent::ExecuteCheckHelper, CheckerComponent::Ptr(this), checkable));
lib//icinga/scheduleddowntime.cpp:		Utility::QueueAsyncCallback(std::bind(&ScheduledDowntime::CreateNextDowntime, this));
lib//icinga/notification.cpp:		Utility::QueueAsyncCallback(std::bind(&Notification::ExecuteNotificationHelper, this, type, user, cr, force, author, text));
lib//livestatus/livestatuslistener.cpp:				Utility::QueueAsyncCallback(std::bind(&LivestatusListener::ClientHandler, this, client), LowLatencyScheduler);
lib//base/process.cpp:			Utility::QueueAsyncCallback(std::bind(callback, m_Result));
lib//base/process.cpp:		Utility::QueueAsyncCallback(std::bind(m_Callback, m_Result));
lib//base/timer.cpp:		Utility::QueueAsyncCallback(std::bind(&Timer::Call, ptimer));
lib//base/utility.cpp:void Utility::QueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy)

gmichi@mbpmif ~/dev/icinga/icinga2 (master=) $ grep -r EnqueueAsyncCallback lib/
lib//remote/apilistener.cpp:void ApiListener::EnqueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy)
lib//remote/apilistener.cpp:			EnqueueAsyncCallback(std::bind(&ApiListener::NewClientHandler, this, client, String(), RoleServer), LowLatencyScheduler);
lib//remote/apilistener.cpp:			EnqueueAsyncCallback(std::bind(&ApiListener::AddConnection, this, endpoint), LowLatencyScheduler);
lib//remote/apilistener.hpp:	static void EnqueueAsyncCallback(const std::function<void ()>& callback, SchedulerPolicy policy = DefaultScheduler);
```

Global Application TP:

* Check execution
* Notification and event command execution
* Process spawning
* Timmer calls
* SD Downtime creation and Livestatus client handling

Dedicated TP instance:

* since 2.10: Incoming client connections and active outbound connection attempts

## Problems

- The original TP implementation targets a global thread pool for everything. With 2.10 we've created another instance inside the ApiListener with high priority schedules. This might overlap or cause troubles with context switches and tasks.
- The code implements locks, waits and starving on its own and doesn't abstract that much. Meaning to say, fixing a bug or analysing a problem has been black magic for many years now.

- The TP sort of rate limits incoming connections (different problem handled with the network I/O rewrite) and might not reliably close threads.
- TP initialization must take place after daemonize() with systems not running systemd. 

## Future Benefits

- Use boost thread, mutex, functions, etc. again in an abstracted way
  * Note: I suspect the move to std::thread and variants with 2.9 being the culprit with different behaviour and bugs caused by different compiler versions. With just relying on one packaged boost version also for the TP, we can consolidate the mixed code again.
- Library code abstracted and tested by many
- Boost Asio's thread_pool can be used with network I/O resources too

https://stackoverflow.com/questions/14265676/using-boostasio-thread-pool-for-general-purpose-tasks

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #6985

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Waiting for the branch f765602cc is borrowed from to be merged.

**Comment by Al2Klimov** [comment]
I.e. waiting for #7005.

**Comment by Al2Klimov** [comment]
Quite bad idea as the enqueued callbacks may throw.

**Comment by dnsmichi** [comment]
A bit undecided how to get back the usage timer logs which sometimes help with debugging and insights.

**Comment by dnsmichi** [comment]
Related offline discussion: This is an externally tested library, no self-written scheduling and whatnot. The notice logs aren't really necessary then.

It feels faster on macOS with cpu count * 2 instead of 16 * 4. Will look into the Windows parts in my VM.

Note for developers @Crunsher @N-o-X @htriem @Al2Klimov @lippserd - stack traces change. The below is a valid thread inside the pool.

```
  thread #13
    frame #0: 0x00007fff7eae286a libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff7eb9b56e libsystem_pthread.dylib`_pthread_cond_wait + 722
    frame #2: 0x0000000105b3c414 icinga2`void boost::asio::detail::posix_event::wait<boost::asio::detail::conditionally_enabled_mutex::scoped_lock>(this=0x00007ff198712888, lock=0x00007000011a2df8) at posix_event.hpp:106:7
    frame #3: 0x0000000105b3b9ed icinga2`boost::asio::detail::conditionally_enabled_event::wait(this=0x00007ff198712880, lock=0x00007000011a2df8) at conditionally_enabled_event.hpp:89:14
    frame #4: 0x0000000105b3ae52 icinga2`boost::asio::detail::scheduler::do_run_one(this=0x00007ff198712800, lock=0x00007000011a2df8, this_thread=0x00007000011a2e30, ec=0x00007000011a2ea8) at scheduler.ipp:409:21
    frame #5: 0x0000000105b3aa1f icinga2`boost::asio::detail::scheduler::run(this=0x00007ff198712800, ec=0x00007000011a2ea8) at scheduler.ipp:154:10
    frame #6: 0x0000000105cf3850 icinga2`boost::asio::thread_pool::thread_function::operator(this=0x00007ff19870bfc8)() at thread_pool.ipp:33:17
    frame #7: 0x0000000105cf3819 icinga2`boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run(this=0x00007ff19870bfc0) at posix_thread.hpp:86:7
    frame #8: 0x0000000105cf3761 icinga2`boost_asio_detail_posix_thread_function(arg=0x00007ff19870bfc0) at posix_thread.ipp:74:13
    frame #9: 0x00007fff7eb982eb libsystem_pthread.dylib`_pthread_body + 126
    frame #10: 0x00007fff7eb9b249 libsystem_pthread.dylib`_pthread_start + 66
    frame #11: 0x00007fff7eb9740d libsystem_pthread.dylib`thread_start + 13
```

**Comment by dnsmichi** [comment]
The appveyor error seems SDK related, I cannot reproduce this with an older version of the Windows 10 SDK in my VM.

```
"C:\projects\icinga2\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\icinga2\Build\plugins\check_nscp_api.vcxproj" (default target) (21) ->
(ClCompile target) -> 
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\mswsock.h(638): error C2146: syntax error: missing ')' before identifier 'DataBuffer' [C:\projects\icinga2\Build\plugins\check_nscp_api.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\mswsock.h(666): error C3646: 'RIORegisterBuffer': unknown override specifier [C:\projects\icinga2\Build\plugins\check_nscp_api.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\mswsock.h(666): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\projects\icinga2\Build\plugins\check_nscp_api.vcxproj]
    78 Warning(s)
    3 Error(s)
Time Elapsed 00:07:25.22
```

**Comment by dnsmichi** [comment]
I'll come back to this once I've rewritten check_nscp_api with asio.

**Comment by Al2Klimov** [comment]
As far as I can remember according to @lazyfrosch they have a lot of different Boost versions. Would be interesting if they also have lot of different SDKs.

**Comment by lazyfrosch** [comment]
Our Windows builds stop at. I guess we need to rebase this branch...

```
lib\base/object.cpp(31): error C2065: 'm_LockOwner': undeclared identifier
```

https://git.icinga.com/packaging/windows-icinga2/-/jobs/10397

If you have rebased you can just start a new build for the `feature/thread-pool-6985` branch there...

**Comment by dnsmichi** [comment]
Doesn't solve the problem, mswsock.h is detected by cmake and cache included into the build. My Windows VM is using an older SDK 240 which works.

**Comment by lazyfrosch** [comment]
Same on our current Windows build system:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\mswsock.h(638): error C2146: syntax error: missing ')' before identifier 'DataBuffer' [C:\Build\builds\1S4CJi7y\1\packaging\windows-icinga2\icinga2\Build\plugins\check_nscp_api.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\mswsock.h(666): error C3646: 'RIORegisterBuffer': unknown override specifier [C:\Build\builds\1S4CJi7y\1\packaging\windows-icinga2\icinga2\Build\plugins\check_nscp_api.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\mswsock.h(666): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int 
```

https://git.icinga.com/packaging/windows-icinga2/-/jobs/10418

@mcktr an idea what fails here?

**Comment by mcktr** [comment]
As far as I found out boost asio includes the `winsock.h` header file, but in our `win32.hpp` we include the `winsock2.h` header file. `winsock.h` and `winsock2.h` are not compatible.

Maybe we need a workaround like in `check_ping`? 
https://github.com/Icinga/icinga2/blob/87ae58f13da49481857590b59386df7eb354771e/plugins/check_ping.cpp#L3-L5

Currently I am busy, but I can have a deeper look this afternoon.

**Comment by lazyfrosch** [comment]
Testing if this is just a header ordering problem...

**Comment by lazyfrosch** [comment]
That did the trick, thanks for pointers @mcktr @LordHepipud :smile:

**Comment by dnsmichi** [comment]
Thanks a lot all of you, I'm doing some more offline tests prior to merging.

**Pull request merged**
