### PR TITLE
Fix Windows reload

### PR DESCRIPTION
**Pull request by Crunsher**
If it's seriously this easy I deserve a medal for both being an idiot AND being a genius. Still needs some more thorough testing but I'm optimistic.

Also some details need straightening out but it works.

refs #6112

### CODE REVIEW

**Comment by Crunsher** [comment]
There is one small problem: If the service is not named "icinga2", it fails. Also the config staging is missing, which will mean lots of confusion and frustration for users. To mitigate this, until config staging works on Windows, I'd cause the service to quit when it receives faulty config.

**Comment by Crunsher** [comment]
>To mitigate this, until config staging works on Windows, I'd cause the service to quit when it receives faulty config.

This is not implemented. We need to update the docs to inform the user about this unexpected behaviour

**Comment by dnsmichi** [comment]
Mh that's not a good change then. It still should validate the configuration and **not** restart if invalid. The old service should continue to run.

**Comment by Crunsher** [comment]
That's what it does, but received config is written to disk and will make problems at the next restart

**Comment by dnsmichi** [comment]
`I'd cause the service to quit when it receives faulty config` reads like it will exit the process instead of keeping the old service running, that's why I am asking.

**Comment by N-o-X** [comment]
Did you guys test this with Icinga running as a service and not in foreground? It seems like the user "NT Authority" is not allowed to restart services.
The validating instance is logging the following:

`[2018-05-18 09:28:47 +0200] critical/cli: Failed to open service manager. Error code: 5`

Which results in "Access denied".

**Comment by Crunsher** [comment]
What's the output of `icinga2 daemon -C`?

**Comment by N-o-X** [comment]
Nothing special:

```
[2018-05-18 10:16:32 +0200] information/cli: Icinga application loader (version: v2.8.4-709-g120eb070d; debug)
[2018-05-18 10:16:32 +0200] information/cli: Loading configuration file(s).
[2018-05-18 10:16:32 +0200] information/ConfigItem: Committing config item(s).
[2018-05-18 10:16:33 +0200] information/ApiListener: My API identity: DESKTOP-GP0UJAR
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 Service.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 213 CheckCommands.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 2 Endpoints.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 4 Zones.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 Host.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 1 EventCommand.
[2018-05-18 10:16:34 +0200] information/ConfigItem: Instantiated 2 FileLoggers.
[2018-05-18 10:16:34 +0200] information/ScriptGlobal: Dumping variables to file 'C:\ProgramData\icinga2\var/cache/icinga2/icinga2.vars'
[2018-05-18 10:16:34 +0200] information/cli: Finished validating the configuration file(s).
```

**Comment by Crunsher** [comment]
What is the user the service was installed as?
Is that user running the service?
How was the reload triggered? 

All that and more please document in a new fresh issue referencing this

**Comment by dnsmichi** [comment]
Apparently this doesn't fix anything on 2.8.x, will be superseeded by a new implementation in 2.9 and #6353

**Pull request merged**
