### PR TITLE
doc/5-advanced-topics: add example how to use custom functions in attributes

### PR DESCRIPTION
**Pull request by rudis**
I tried to use this on my own, but failed to find a solution. Thanks to shroud in #icinga I got a working solution. As this might be useful to others, I wrote this patch to document it.

PS: Sorry for the second pull requests shortly after another, forgot to merge it in the first request.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you please create a ticket for this at dev.icinga.org? :)

**Comment by rudis** [comment]
Is this really necessary? I'd like to avoid registering at another site.

**Comment by dnsmichi** [comment]
Yes it is. That's how we organise issues for our releases. Thanks in advance.

https://accounts.icinga.org

**Comment by rudis** [comment]
Sorry, having to use Github is enough work for me. Either drop it or create the ticket on your own.

**Comment by Crunsher** [comment]
https://dev.icinga.org/issues/10947

**Pull request closed without merging**
