### PR TITLE
ConfigWriter: Fix don't also write ignore_on_error attr into the config

### PR DESCRIPTION
**Pull request by Yonas-net**
Just created a host object via API with ``ignore_on_error`` flag set and the ``ConfigWriter`` mistakenly writes this flag in the config file, which leads to a config validation error and crashes icinga2 occasionally.

Please test this with (#8819), the error only appears after that fix.

### CODE REVIEW

**Comment by Yonas-net** [comment]
**Before**:

```bash
[2021-06-01 17:58:24 +0200] notice/ConfigObject: Ignoring config object 'example' of type 'Host' due to errors: Error: Validation failed for object 'example' of type 'Host'; Attribute 'check_command': Attribute must not be empty.
Location: in /Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf: 1:0-1:48
/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf(1): object Host "example" ignore_on_error {
```

**After**:
See https://github.com/Icinga/icinga2/pull/8819#issuecomment-852280035

**Comment by julianbrost** [comment]
> [2021-06-01 17:58:24 +0200] notice/ConfigObject: Ignoring config object 'example' of type 'Host' due to errors: Error: Validation failed for object [...]

This doesn't look like a crash to me. Also this removes `ignore_on_error` completely from generated config, including for comments and downtimes. But there it's needed in case the referenced checkable gets removed.

**Comment by Yonas-net** [comment]
> This doesn't look like a crash to me

Doesn't that look like a crash to you?

```bash
[2021-06-02 09:53:11 +0200] notice/ConfigObject: Ignoring config object 'example' of type 'Host' due to errors: Error: Validation failed for object 'example' of type 'Host'; Attribute 'check_command': Attribute must not be empty.
Location: in /Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf: 1:0-1:48
/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf(1): object Host "example" ignore_on_error {
                                                                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf(2):  address = "192.168.1.1"
/Users/yhabteab/Workspace/icinga2/prefix/var/lib/icinga2/api/packages/_api/ca7c22f6-3eed-426c-bd2e-04b9cf04c267/conf.d/hosts/example.conf(3):  vars["os"] = "Linux"
[2021-06-02 09:53:11 +0200] debug/configitem: Committed 1 items of type 'Host'.
[2021-06-02 09:53:11 +0200] debug/configitem: Committed 1 items.
[2021-06-02 09:53:11 +0200] debug/configitem: Committing 1 new items.
icinga2(17414,0x70000bcf4000) malloc: Incorrect checksum for freed object 0x7fd44fe42c68: probably modified after being freed.
Corrupt value: 0x7fff807f87a0
icinga2(17414,0x70000bcf4000) malloc: *** set a breakpoint in malloc_error_break to debug
Caught SIGABRT.
Current time: 
```

And as for the ``ignore_on_error`` flag, it is not an object attribute but just a flag to ignore errors that occurred when creating the object. Therefore, in my opinion, this has nothing to do with the config file.

**Comment by julianbrost** [comment]
Well, that does, but you only pasted the first 3 lines in https://github.com/Icinga/icinga2/pull/8820#issuecomment-852294219.

**Comment by Al2Klimov** [comment]
> Also this removes `ignore_on_error` completely from generated config, including for comments and downtimes. But there it's needed in case the referenced checkable gets removed.

Full ack. Whatever the actual problem is it shall be fixed not like this.

**Pull request closed without merging**
