### PR TITLE
Add macro "check_source" for hosts and services to use them in notification mails

### PR DESCRIPTION
**Pull request by paalsteek**
This commit adds macros "$host.check_source$" and "$service.check_source$" in order to add the check_source to notification mails in a cluster setup.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Your patch appears to be missing the documentation update. Also, can you please submit a ticket for this at dev.icinga.org?

**Comment by gunnarbeutner** [comment]
Oh, one more thing: please update the "Author" attribute for your Git commit so as to include your full name. This is required so we can update the AUTHORS file.

**Comment by paalsteek** [comment]
I updated the documentation (didn't find the relevant section before), the author and submitted a feature request on dev.icinga.org (https://dev.icinga.org/issues/8277).

**Comment by gunnarbeutner** [comment]
Merged. Thanks.

**Pull request closed without merging**
