### PR TITLE
Cluster Config Sync: Ensure that empty production environment is populated with new sync

### LINKED ISSUE #7296: Staging config not copied to production
This is a followup for #7282 

Config sync is not working for master master for me anymore. Config is synced, but not moved to production. The comparison of staging and production is regarded as equal even if it clearly is not.

## Setup
Version dfws: v2.10.5-883-g09fe57039 (master)
Version icigna vagrant: bugfix/cluster-sync-checksum-change

Zones.conf:
```
object Endpoint "dfws" {
	host = "127.0.0.1"
}
object Endpoint "icinga2.vagrant.demo.icinga.com" {
	host = "192.168.33.5"
}
object Zone "double" {
	endpoints = [ "dfws", "icinga2.vagrant.demo.icinga.com"]
}
```

icinga vagrant box has accept config and commands set to true.

cat dfws/zones.d/double:
```
object Host "Horst" {
	check_command = "dummy"
	check_interval = 2s
	vars.foo = 2
}
```

Log on the master:
```
[2019-07-08 15:28:37 +0200] information/ApiListener: New client connection for identity 'icinga2.vagrant.demo.icinga.com' from [192.168.33.5]:50838
[2019-07-08 15:28:37 +0200] information/ApiListener: Sending config updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing configuration files for zone 'double' to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending config file updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing runtime objects to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Sending replay log for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending replay log for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished syncing endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Applying config update from endpoint 'icinga2.vagrant.demo.icinga.com' of zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Ignoring config update from endpoint 'icinga2.vagrant.demo.icinga.com' for zone 'double' because we have an authoritative version of the zone's config.
[2019-07-08 15:28:37 +0200] information/ApiListener: Received configuration from endpoint 'icinga2.vagrant.demo.icinga.com' is equal to production, not triggering reload.
```
So far so good, on the other master:
```
[2019-07-08 15:33:09 +0200] information/ApiListener: New client connection for identity 'dfws' from [192.168.33.1]:33720
[2019-07-08 15:33:09 +0200] information/ApiListener: Sending config updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Syncing configuration files for zone 'double' to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending config file updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Syncing runtime objects to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Sending replay log for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Replayed 33 messages.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending replay log for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished syncing endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Applying config update from endpoint 'dfws' of zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Received configuration for zone 'double' from endpoint 'dfws'. Comparing the checksums.
[2019-07-08 15:33:09 +0200] information/ApiListener: Stage: Updating received configuration file '/var/lib/icinga2/api/zones-stage/double//_etc/host.conf' for zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones-stage/double' (237 Bytes).
[2019-07-08 15:33:09 +0200] warning/ApiListener: Ignoring config update from endpoint 'dfws' for unknown zone 'global-templates'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Received configuration from endpoint 'dfws' is equal to production, not triggering reload.
```
Querying the config replica:
```
[root@icinga2 zones]# curl -ks -u root:ecf17b9f3bbb583c https://127.0.0.1:5665/v1/objects/hosts/Horst | python -m json.tool
{
    "error": 404.0,
    "status": "No objects found."
}

[root@icinga2 zones]# cat /var/lib/icinga2/api/zones-stage/double/_etc/host.conf 
object Host "Horst" {
	check_command = "dummy"
	check_interval = 2s
	vars.foo = 2
}

[root@icinga2 zones]# cat /var/lib/icinga2/api/zones/double/_etc/host.conf 
cat: /var/lib/icinga2/api/zones/double/_etc/host.conf: No such file or directory
```

### PR DESCRIPTION
**Pull request by dnsmichi**
This PR fixes the problem that old checksums = 0 would not be populated
with a new checksum update for production.

It also counts the applicable updates and logs them
at the end.

```
[2019-07-10 12:34:27 +0200] information/ApiListener: Received configuration updates (2) from endpoint 'master1' are equal to production, not triggering reload.
```

fixes #7296

### CODE REVIEW

**Comment by dnsmichi** [comment]
Test protocol: https://github.com/Icinga/icinga2/issues/7296#issuecomment-510004636

**Comment by Crunsher** [comment]
The following does not work:
1. M1: `touch zones.d/double/hosts.conf` && restart icinga
2. M2: syncs the file an restarts
3. M1: `echo 'object Host "horst" { check_command = "dummy" }' > zones.d/double/hosts.conf`
4. M2: 
```
[2019-07-10 14:00:30 +0200] information/ApiListener: Received configuration for zone 'double' from endpoint 'icinga2.vagrant.demo.icinga.com'. Comparing the checksums.
[2019-07-10 14:00:30 +0200] debug/ApiListener: Checking for config change between stage and production. Old (2): '{"/.checksums":"1c7977acfcd78ae246a4264c6c258169063b953bfb93456ac329ad4a4345574b","/.timestamp":"2f64105160c6f19559c11b4b2205560f9aed30c28c46ab01da07ab363315389d"}' vs. new (3): '{"/.checksums":"8183566055410487cff5eb5e8bc3e3f879271405fbbed5fe62ac4854da82ec5b","/.timestamp":"08676f499a823c616c87e0b49f4a1790c79fb0b265144aa49a4bc5f7e65f2a85","/_etc/hosts.conf":"360972ab6b3fab08d8a358b03b8cf5c39d8ebda5dd0e93cad5fff6f8d6152f25"}'.
[2019-07-10 14:00:30 +0200] information/ApiListener: Stage: Updating received configuration file '/home/dflach/i2/var/lib/icinga2/api/zones-stage/double//_etc/hosts.conf' for zone 'double'.
[2019-07-10 14:00:30 +0200] information/ApiListener: Applying configuration file update for path '/home/dflach/i2/var/lib/icinga2/api/zones-stage/double' (250 Bytes).
[2019-07-10 14:00:30 +0200] information/ApiListener: Received configuration updates (1) from endpoint 'icinga2.vagrant.demo.icinga.com' are equal to production, not triggering reload.
```

**Comment by dnsmichi** [comment]
Right, this is where your attempt comes into play. I've written some code during the meeting and tested the above case with it, just pushed it here.

**Comment by dnsmichi** [comment]
Will be continued in #7303

**Pull request closed without merging**
