### PR TITLE
Allow to disable thresholds for ipmi CheckCommand

### LINKED ISSUE #5579: ITL: ipmi-sensor missing argument
The option --nothresholds is missing in /usr/share/icinga2/include/plugins-contrib.d/ipmi.conf

## Expected Behavior
I would expect something like that:

                "--nothresholds" = {
                        set_if = "$ipmi_no_thresholds$"
                        description = "turn off performance data thresholds from output-sensor-thresholds"
                }

## Current Behavior
The option is missing

## Possible Solution
Change the ipmi.conf
[patch_ipmi_nothresholds.txt](https://github.com/Icinga/icinga2/files/1301966/patch_ipmi_nothresholds.txt)

## Your Environment

* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):     2.4.1

### PR DESCRIPTION
**Pull request by konstantin-kelemen**
fixes #5579

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks 👍  Can you please add the new configuration setting to the documentation table too?

**Comment by konstantin-kelemen** [comment]
@dnsmichi Done!

**Comment by dnsmichi** [comment]
Thanks. Please do me a favour and amend/squash the commits into a single one next time. Done here during review this time.

**Comment by dnsmichi** [comment]
Something went wrong with the rebase, now it is fixed.

**Comment by dnsmichi** [comment]
Thanks for your contribution 👍

**Pull request merged**
