### PR TITLE
ProcessHandler(): cd /

### LINKED ISSUE #7756: set cwd to / in non systemd init script
hi,
If I restart icinga2 on RHEL 6 from the root home directory several of my checkcommands fail upon pushd&popd, because the icinga user is unable to enter /root/.

I think the best way fix this would be to change the cwd to / prior to the double fork. This is fairly common in SysV style init scripts.

## Your Environment

* Version used (`icinga2 --version`): 2.11.2-1
* Operating System and version: RHEL 6
* Enabled features (`icinga2 feature list`): api checker mainlog

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7756

### CODE REVIEW

**Comment by Al2Klimov** [comment]
```
➜  icinga2 git:(bugfix/cd-root-7756) rm prefix/etc/icinga2/conf.d/hosts.conf
➜  icinga2 git:(bugfix/cd-root-7756) rm prefix/etc/icinga2/conf.d/services.conf
➜  icinga2 git:(bugfix/cd-root-7756) vi prefix/etc/icinga2/conf.d/pwd.conf
➜  icinga2 git:(bugfix/cd-root-7756) cat prefix/etc/icinga2/conf.d/pwd.conf
object CheckCommand "pwd" {
	command = [ "bash", "-c", "pwd; exit 128" ]
}

object Host "pwd" {
	check_command = "pwd"
	check_interval = 1s
}
➜  icinga2 git:(bugfix/cd-root-7756) prefix/sbin/icinga2 daemon -x notice
[2020-01-30 18:15:56 +0100] information/cli: Icinga application loader (version: v2.11.0-480-g67ddf8d39; debug)
[2020-01-30 18:15:56 +0100] notice/cli: Spawning seemless worker process doing the actual work
[2020-01-30 18:15:56 +0100] notice/cli: Spawned worker process (PID 9331), waiting for it to load its config
[2020-01-30 18:15:56 +0100] information/cli: Loading configuration file(s).
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/icinga2.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/constants.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/zones.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/itl
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/command-icinga.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/command-plugins.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/big-data.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/databases.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/hardware.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/icingacli.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/ipmi.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/logmanagement.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/metrics.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/network-components.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/network-services.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/operating-system.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/raid-controller.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/smart-attributes.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/storage.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/virtualization.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/vmware.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/plugins-contrib.d/web.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/manubulon
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/command-plugins-manubulon.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/windows-plugins
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/command-plugins-windows.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/nscp
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/share/icinga2/include/command-nscp-local.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/features-enabled/checker.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/features-enabled/mainlog.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/features-enabled/notification.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/app.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/commands.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/downtimes.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/groups.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/pwd.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/templates.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/timeperiods.conf
[2020-01-30 18:15:56 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/users.conf
[2020-01-30 18:15:56 +0100] information/ConfigItem: Committing config item(s).
[2020-01-30 18:15:56 +0100] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-01-30 18:15:56 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
[2020-01-30 18:15:56 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
[2020-01-30 18:15:56 +0100] warning/ApplyRule: Apply rule 'backup-downtime' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 3 Zones.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 UserGroup.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 236 CheckCommands.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 2 HostGroups.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 1 User.
[2020-01-30 18:15:56 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-01-30 18:15:56 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-01-30 18:15:56 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-01-30 18:15:56 +0100] notice/cli: Notifying umbrella process (PID 9316) about the config loading success
[2020-01-30 18:15:56 +0100] notice/cli: Worker process successfully loaded its config
[2020-01-30 18:15:56 +0100] notice/cli: Waiting for the umbrella process to let us doing the actual work
[2020-01-30 18:15:56 +0100] notice/cli: The umbrella process let us continuing
[2020-01-30 18:15:56 +0100] information/ConfigItem: Triggering Start signal for config items
[2020-01-30 18:15:56 +0100] information/FileLogger: 'main-log' started.
[2020-01-30 18:15:57 +0100] information/NotificationComponent: 'notification' started.
[2020-01-30 18:15:57 +0100] information/CheckerComponent: 'checker' started.
[2020-01-30 18:15:57 +0100] information/ConfigItem: Activated all objects.
[2020-01-30 18:15:57 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonCommand::Run'
[2020-01-30 18:15:57 +0100] notice/ConfigObjectUtility: Package _api doesn't exist yet, creating it.
[2020-01-30 18:15:57 +0100] notice/ApiListener: Updating object authority for local objects.
[2020-01-30 18:15:57 +0100] notice/Process: Running command 'bash' '-c' 'pwd; exit 128': PID 9333
[2020-01-30 18:15:57 +0100] notice/Process: PID 9333 ('bash' '-c' 'pwd; exit 128') terminated with exit code 128
[2020-01-30 18:15:57 +0100] warning/PluginCheckTask: Check command for object 'pwd' (PID: 9333, arguments: 'bash' '-c' 'pwd; exit 128') terminated with exit code 128, output: /

[2020-01-30 18:15:57 +0100] notice/Checkable: State Change: Checkable 'pwd' soft state change from DOWN to DOWN detected.
[2020-01-30 18:16:02 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
^C[2020-01-30 18:16:03 +0100] notice/cli: Got signal 2, forwarding to seemless worker (PID 9331)
[2020-01-30 18:16:03 +0100] information/Application: Received request to shut down.
[2020-01-30 18:16:03 +0100] information/Application: Shutting down...
[2020-01-30 18:16:03 +0100] information/CheckerComponent: 'checker' stopped.
[2020-01-30 18:16:03 +0100] information/NotificationComponent: 'notification' stopped.
[2020-01-30 18:16:03 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-01-30 18:16:03 +0100] information/IcingaApplication: Icinga has shut down.
[2020-01-30 18:16:03 +0100] notice/cli: Seemless worker (PID 9331) stopped, stopping as well
➜  icinga2 git:(bugfix/cd-root-7756)
```

**Comment by dnsmichi** [comment]
@dgoetz Please add your thoughts on this, also with regard on SELinux.

**Comment by dgoetz** [comment]
A service should not work in `/` instead of its own working directory. User `icinga` has a home directory of `/var/spool/icinga2` which would be better suited. From SELinux perspective `/` is `root_t` which I will not allow access to for anything.

**Comment by mphilipps** [comment]
I am by no means an expert on SELinux, but I would think that as long as icinga isn't trying to do any actual work in it's working directory it shouldn't trigger any SELinux rules.  
However I also don't mind changing it to a cd to the icinga user's home directory, which however can't be expected to be `/var/spool/icinga2`. On debian systems icinga2 runs as nagios and if the user already exists (like from a nagios -> icinga migration) the home directory of the user isn't changed.

**Comment by dnsmichi** [comment]
I had a read about this. For systemd, this works already automatically and we should not mangle with chdir our own. This originates from the times when systemvinit was cool (sorry).

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Options

```
WorkingDirectory=

Takes a directory path relative to the service's root directory specified by RootDirectory=, or the special value "~". Sets the working directory for executed processes. If set to "~", the home directory of the user specified in User= is used. 

If not set, defaults to the root directory when systemd is running as a system instance and the respective user's home directory if run as user. 

If the setting is prefixed with the "-" character, a missing working directory is not considered fatal. If RootDirectory=/RootImage= is not set, then WorkingDirectory= is relative to the root of the system running the service manager. Note that setting this parameter might result in additional dependencies to be added to the unit (see above).
```

That being said, thanks for your thoughts. 

The fix for SystemVInit should be done inside the init scripts - mimicking the behavior of systemd. 
Something like [this](https://github.com/coreybutler/node-linux/pull/44/files) or [this](https://stackoverflow.com/questions/7363946/how-do-i-execute-an-arbitrary-script-with-a-working-directory-of-the-directory-i).

Closing this PR.

**Pull request closed without merging**
