### PR TITLE
CMake: require a GCC version according to INSTALL.md

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
> CMake Error at CMakeLists.txt:250 (message):
>  Your version of GCC (4.6) is too old for building Icinga 2 (GCC >= 4.7.0 is
>  required).

-- [Travis CI](https://travis-ci.org/Icinga/icinga2/builds/229074757?utm_source=github_status&utm_medium=notification)

**Comment by dnsmichi** [comment]
Travis CI still uses Ubuntu Precise, we'll need to adopt that to trusty beta then (since Precise is EOL anyways).

**Comment by lazyfrosch** [comment]
Could we document what the problem with 4.6.0 is?

This is relevant for package builds as well...

**Comment by dnsmichi** [comment]
Selected C++11 features we've been using are only available with gcc 4.7 and above. That's already listed in the requirements and originates from #4558.

We could use more C++11 if we would raise the requirement to modern compilers, but that's not gonna work on older platforms we support. gcc 4.7 is the common pattern we can require currently.

**Comment by dnsmichi** [comment]
References to C++11 selected changes:

- #4559
- #4536 
- #4575
- #4571

**Comment by lazyfrosch** [comment]
@dnsmichi Thanks for summary, could we put that "recommendation" info into INSTALL.md and close this PR?

I'm trying out Travis-Trusty right now...

**Comment by dnsmichi** [comment]
The changes to CMakeLists are valid, but I would with a merge wait until travis is fixed. Otherwise all tests will fail in the future.

**Comment by lazyfrosch** [comment]
Please rebase, or allow contributors access to your branches.

**Comment by Al2Klimov** [comment]
@lazyfrosch done.

**Comment by dnsmichi** [comment]
Thanks 👍

**Pull request merged**
