### PR TITLE
Adding a forgotten parameter in manubulon doc : snmp_v3_use_authprotocol

### PR DESCRIPTION
**Pull request by Niflou**
https://github.com/Icinga/icinga2/issues/5010#issuecomment-280112932

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you please update the Git commit to include your real name in the 'Author' attribute?

**Comment by Niflou** [comment]
Just forget about it

**Comment by dnsmichi** [comment]
Hey, no worries. Gunnar was just kindly asking you for an update. If you don't like to do so, that is not an issue and we'll deal with it. We've just talked about that offline, and will certainly reconsider the authors requirement. 

Would it be ok for you if we still merge your existing patch? :-)

**Comment by Niflou** [comment]
Hi, 
Sorry, I'm not mad at you guys just at git ^^, I'm a mercurial user and I really don't understand all the complexity around git commands... I guess this is also the case when git users come to mercurial ;-)
No problem for merging !

**Comment by dnsmichi** [comment]
Hi, no idea about Mercurial. But you are right, sending in a patch should be as easy as possible. Especially if it is "just" a text file change for docs or configuration templates. 

Thanks to the move to GitHub, you can also edit them online more easily, and just apply for a PR. Source code patches still require offline compilation and tests, but we're gonna work on CI tests too in the next weeks.

**Pull request closed without merging**
