### PR TITLE
IDO: customvariables: fix duplicate entry error

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
[2020-09-16 16:05:16 +0000] information/ConfigItem: Activated all objects.
[2020-09-16 16:05:17 +0000] information/IdoMysqlConnection: 'ido-mysql' resumed.
[2020-09-16 16:05:17 +0000] information/DbConnection: Resuming IDO connection: ido-mysql
[2020-09-16 16:05:17 +0000] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.14.3')
[2020-09-16 16:05:18 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 895, rate:  0/s (0/min 0/5min 0/15min); empty in 9 seconds
[2020-09-16 16:05:28 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 15211, rate:  0/s (0/min 0/5min 0/15min); empty in 10 seconds
[2020-09-16 16:05:37 +0000] critical/IdoMysqlConnection: Error "Duplicate entry '17942-1-project ' for key 'object_id_2'" when executing query "...
```

## After

```
[2020-09-16 17:11:57 +0000] information/ConfigItem: Activated all objects.
[2020-09-16 17:11:58 +0000] information/IdoMysqlConnection: 'ido-mysql' resumed.
[2020-09-16 17:11:58 +0000] information/DbConnection: Resuming IDO connection: ido-mysql
[2020-09-16 17:11:58 +0000] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.14.3')
[2020-09-16 17:12:04 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 18404, rate:  0/s (0/min 0/5min 0/15min); empty in 9 seconds
[2020-09-16 17:12:14 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 92035, rate:  0/s (0/min 0/5min 0/15min); empty in 12 seconds
[2020-09-16 17:12:24 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 180687, rate:  0/s (0/min 0/5min 0/15min); empty in 20 seconds
[2020-09-16 17:12:35 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 252579, rate:  0/s (0/min 0/5min 0/15min); empty in 35 seconds
[2020-09-16 17:12:45 +0000] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 254831, rate:  0/s (0/min 0/5min 0/15min); empty in 18 minutes and 52 seconds
[2020-09-16 17:12:48 +0000] information/ConfigObjectUtility: Deleted object '...
```

**Comment by lippserd** [comment]
Isn't `customvariablestatus` also affected? Stupid question maybe, but how does the IDO feature handle Inserts w/ a WHERE?

**Comment by Al2Klimov** [comment]
1. No, it's already protected with the same mechanism.
2. AFAIK there's only one way at all: UPDATE -> nothing affected -> INSERT

**Comment by Al2Klimov** [comment]
_bump_

**Review by lippserd — APPROVED** [review]

**Review by N-o-X — APPROVED** [review]

**Pull request merged**
