### PR TITLE
Allow setting the SNMP version for check_iftraffic.pl

### PR DESCRIPTION
**Pull request by episodeiv**
This is not supported in check_iftraffic.pl master yet but there's a pull request at https://github.com/NETWAYS/check_iftraffic/pull/4

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please also add the documentation bits :-)

**Comment by episodeiv** [comment]
Sorry, I missed that. Added!

**Comment by dnsmichi** [comment]
Released 1.0.2 of that plugin, this should cover this better.

**Comment by dnsmichi** [comment]
Thanks for your contribution 👍

**Pull request merged**
