### PR TITLE
Print errors during opening log files

### LINKED ISSUE #8004: icinga crashes during startup without error if wrong permisson to write a log
## Describe the bug

I discovered this, because we had to change uid/gid of the icinga user. We forgot to adjust /var/log/icinga2.
Systemd fails to start icinga and when using icinga2 daemon the process just ends with exitcode 1.

Config validates with exitcode 0.

## To Reproduce

1. Stop icinga
2. change owner/group of /var/log/icinga2 to something else than icinga process user
3. Start icinga with _icinga2 daemon_
4.

## Expected behavior

I would expect some kind of error message, that no logfile could be created.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 --version
* Operating System and version: RHEL 7.7
* Enabled features (`icinga2 feature list`): api checker mainlog

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #8004

### CODE REVIEW

**Comment by Yonas-net** [comment]
Testprotocol:

So far icinga2 has just crashed without reporting an error if you change the owner and group of ``var/log/icinga2/*``.
And the issue looked like this..
```
[2020-06-19 11:30:20 +0200] information/cli: Icinga application loader (version: v2.12.0-rc1-48-g6f708dfe1; debug)
[2020-06-19 11:30:20 +0200] information/cli: Loading configuration file(s).
[2020-06-19 11:30:20 +0200] information/ConfigItem: Committing config item(s).
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 User.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 3 Zones.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 11 Services.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-06-19 11:30:20 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-06-19 11:30:20 +0200] information/ScriptGlobal: Dumping variables to file '/PATH/TO/var/cache/icinga2/icinga2.vars'
[2020-06-19 11:30:20 +0200] information/ConfigItem: Triggering Start signal for config items
```
but now the output looks like this..
```
[2020-06-19 11:21:21 +0200] information/cli: Icinga application loader (version: v2.12.0-rc1-12-gff13e18e4; debug)
[2020-06-19 11:21:21 +0200] information/cli: Loading configuration file(s).
[2020-06-19 11:21:21 +0200] information/ConfigItem: Committing config item(s).
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 User.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 3 Zones.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 11 Services.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-06-19 11:21:21 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-06-19 11:21:21 +0200] information/ScriptGlobal: Dumping variables to file '/PATH/TO/var/cache/icinga2/icinga2.vars'
[2020-06-19 11:21:21 +0200] information/ConfigItem: Triggering Start signal for config items
Could not open logfile 'PATH/TO//var/log/icinga2/icinga2.log'
```

**Review by julianbrost — COMMENTED** [review]
What do you think of doing this similar to the console log using `StreamLogger::ProcessLogEntry()`?

https://github.com/Icinga/icinga2/blob/014dbb3bc0667214263cb6718db0611088060ec5/lib/base/logger.cpp#L238-L245

This would make the message consistent with the others.

**Comment by Al2Klimov** [comment]
```
[2021-03-09 12:28:47 +0100] critical/FileLogger: Could not open logfile '/icinga2.log'
```

**Comment by julianbrost** [comment]
Do we still need this? I believe this is already fixed by #8614, at least when I run this PR now, I get two errors:
```
[2021-06-16 06:39:41 +0000] critical/FileLogger: Could not open logfile '//icinga2.log'
[2021-06-16 06:39:41 +0000] critical/cli: Exception in main process: Error: Could not open logfile '//icinga2.log'

	(0) icinga2: void boost::exception_detail::throw_exception_<std::runtime_error>(std::runtime_error const&, char const*, char const*, int) (+0x53) [0x55c3f3e3b033]
	(1) icinga2: icinga::FileLogger::ReopenLogFile() (+0x201) [0x55c3f3e0aa61]
	(2) icinga2: icinga::FileLogger::Start(bool) (+0x29) [0x55c3f3e0aac9]
	(3) icinga2: icinga::ConfigObject::Activate(bool, icinga::Value const&) (+0x1f7) [0x55c3f3dae377]
	(4) icinga2: icinga::ConfigItem::ActivateItems(std::vector<boost::intrusive_ptr<icinga::ConfigItem>, std::allocator<boost::intrusive_ptr<icinga::ConfigItem> > > const&, bool, bool, bool, icinga::Value const&) (+0x246) [0x55c3f3eb2b86]
	(5) icinga2: <unknown function> (+0x777c85) [0x55c3f3fd8c85]
	(6) icinga2: icinga::DaemonCommand::Run(boost::program_options::variables_map const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const (+0x968) [0x55c3f3fd9888]
	(7) icinga2: <unknown function> (+0x530b5e) [0x55c3f3d91b5e]
	(8) icinga2: main (+0xe6) [0x55c3f3d803f6]
	(9) libc.so.6: __libc_start_main (+0xeb) [0x7fb703b3d09b]
	(10) icinga2: _start (+0x2a) [0x55c3f3d8f12a]


	(0) Activating object 'main-log' of type 'FileLogger'
```

**Pull request closed without merging**
