### PR TITLE
DSL: warn on x=y if x is a global variable

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Test protocol

```
➜  icinga2 git:(feature/warn-set-global-var) cat CENSORED/etc/icinga2/conf.d/gv.conf
a = 1
globals.b = 2
var c = 3
c = 4
➜  icinga2 git:(feature/warn-set-global-var) CENSORED/sbin/icinga2 daemon -C
[2019-08-27 13:21:21 +0200] information/cli: Icinga application loader (version: v2.11.0-rc1-74-g8c739fe33; debug)
[2019-08-27 13:21:21 +0200] information/cli: Loading configuration file(s).
[2019-08-27 13:21:21 +0200] warning/config: Global variable 'NscpPath' has been set implicitly via 'NscpPath = ...'. Please set it explicitly via 'globals.NscpPath = ...' instead.
[2019-08-27 13:21:21 +0200] warning/config: Global variable 'a' has been set implicitly via 'a = ...'. Please set it explicitly via 'globals.a = ...' instead.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Committing config item(s).
[2019-08-27 13:21:21 +0200] information/ApiListener: My API identity: CENSORED
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 234 CheckCommands.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 ApiUser.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 Host.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 11 Services.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 3 Zones.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2019-08-27 13:21:21 +0200] information/ConfigItem: Instantiated 1 User.
[2019-08-27 13:21:21 +0200] information/ScriptGlobal: Dumping variables to file 'CENSORED/var/cache/icinga2/icinga2.vars'
[2019-08-27 13:21:21 +0200] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(feature/warn-set-global-var)
```

**Comment by Al2Klimov** [comment]
## Test protocol

```
➜  icinga2 git:(feature/warn-set-global-var) cat CENSORED/etc/icinga2/conf.d/gv.conf
a = 1
globals.b = 2
var c = 3
c = 4
➜  icinga2 git:(feature/warn-set-global-var) CENSORED/sbin/icinga2 daemon -C
[2019-08-27 13:30:45 +0200] information/cli: Icinga application loader (version: v2.11.0-rc1-75-g429080ee1; debug)
[2019-08-27 13:30:45 +0200] information/cli: Loading configuration file(s).
[2019-08-27 13:30:45 +0200] warning/config: Global variable 'NscpPath' has been set implicitly via 'NscpPath = ...' in CENSORED/share/icinga2/include/command-nscp-local.conf: 4:2-4:85. Please set it explicitly via 'globals.NscpPath = ...' instead.
[2019-08-27 13:30:45 +0200] warning/config: Global variable 'a' has been set implicitly via 'a = ...' in CENSORED/etc/icinga2/conf.d/gv.conf: 1:0-1:4. Please set it explicitly via 'globals.a = ...' instead.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Committing config item(s).
[2019-08-27 13:30:45 +0200] information/ApiListener: My API identity: CENSORED
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 234 CheckCommands.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 ApiUser.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 Host.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 11 Services.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 3 Zones.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 User.
[2019-08-27 13:30:45 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-08-27 13:30:45 +0200] information/ScriptGlobal: Dumping variables to file 'CENSORED/var/cache/icinga2/icinga2.vars'
[2019-08-27 13:30:45 +0200] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(feature/warn-set-global-var)
```

**Comment by Al2Klimov** [comment]
Note: This prevents issues like #7441.

**Comment by dnsmichi** [comment]
Good point. I hope that users will reflect upon setting something globally, but we'll see. I've read the linked issue, but I didn't want to join the discussion, it seemed quite heated (and my only recommendation would have been to write better code).

**Pull request merged**
