### PR TITLE
Fix reload handling by updating the PID file before process overtake

### LINKED ISSUE #6082: PID file removed after reload
After a reload of icinga2 there is no icinga2 process via /etc/init.d/icinga2 reload there is no icinga2 process anymore.

OS: Debian 9.3
Icinga Version: 

```
icinga2                                   2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 amd64
icinga2-bin                               2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 amd64
icinga2-common                            2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 all
icinga2-doc                               2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 all
icinga2-ido-mysql                         2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 amd64
libicinga2                                2.8.1+406.g407a2d052.2018.02.07+1.stretch-0 amd64
```

Debug Logfile output:
```
[2018-02-07 09:11:06 +0100] information/Application: Got reload command: Starting new instance.
[2018-02-07 09:11:06 +0100] notice/Process: Running command '/usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2' '--no-stack-rlimit' 'daemon' '-e' '/var/log/icinga2/error.log' '--reload-internal' '27264': PID 27446
[2018-02-07 09:11:07 +0100] debug/IdoMysqlConnection: Query: COMMIT
[2018-02-07 09:11:07 +0100] debug/IdoMysqlConnection: Query: BEGIN
[2018-02-07 09:11:07 +0100] information/Application: Reload requested, letting new process take over.
```

After that no output anymore and no icinga2 process is running anymore.

### LINKED ISSUE #6127: Satellite reload fails with Systemd on config sync (git master only)
## Expected Behavior

Automated config reload takes place.

## Current Behavior

Config reload takes place, but child process cannot take over as the socket is not entirely closed.

```
[root@icinga2-satellite1 ~]# ps aux | grep icinga2
root     12267  0.0  0.0 112660   976 pts/0    S+   16:46   0:00 grep --color=auto icinga2
[root@icinga2-satellite1 ~]# systemctl status icinga2
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; enabled; vendor preset: disabled)
   Active: reloading (reload) (Result: exit-code) since Tue 2018-02-27 16:26:00 CET; 26min ago
  Process: 11248 ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 10019 ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/sysconfig/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 11248 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/icinga2.service

Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Finished syncing endpoint 'icing...aster'.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Applying config update from endp...aster'.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Updating configuration file: /va...mestamp
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com systemd[1]: icinga2.service: Supervising process 11248 which is not our child. We'll most likely not ... exits.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Updating configuration file: /va...ts.conf
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Applying configuration file upda...02212).
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/ApiListener: Restarting after configuration change.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/Application: Got reload command: Starting new instance.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com icinga2[10025]: [2018-02-27 16:28:15 +0100] information/Application: Reload requested, letting new pr...e over.
Feb 27 16:28:15 icinga2-satellite1.vagrant.demo.icinga.com systemd[1]: icinga2.service: main process exited, code=exited, status=1/FAILURE
Hint: Some lines were ellipsized, use -l to show in full.
```

```
[2018-02-27 16:28:15 +0100] warning/TlsStream: TLS stream was disconnected.
[2018-02-27 16:28:15 +0100] warning/JsonRpcConnection: API client disconnected for identity 'icinga2-master1.vagrant.demo.icinga.com'
[2018-02-27 16:28:15 +0100] warning/ApiListener: Removing API client for endpoint 'icinga2-master1.vagrant.demo.icinga.com'. 0 API clients left.
[2018-02-27 16:28:15 +0100] information/ApiListener: New client connection for identity 'icinga2-master1.vagrant.demo.icinga.com' from [192.168.33.101]:34026
[2018-02-27 16:28:15 +0100] information/ApiListener: Requesting new certificate for this Icinga instance from endpoint 'icinga2-master1.vagrant.demo.icinga.com'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Sending config updates for endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Finished sending config file updates for endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Syncing runtime objects to endpoint 'icinga2-master1.vagrant.demo.icinga.com'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'icinga2-master1.vagrant.demo.icinga.com'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Sending replay log for endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Replayed 4 messages.
[2018-02-27 16:28:15 +0100] information/ApiListener: Finished sending replay log for endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Finished syncing endpoint 'icinga2-master1.vagrant.demo.icinga.com' in zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Applying config update from endpoint 'icinga2-master1.vagrant.demo.icinga.com' of zone 'master'.
[2018-02-27 16:28:15 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/satellite//.timestamp
[2018-02-27 16:28:15 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/satellite//_etc/hosts.conf
[2018-02-27 16:28:15 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/satellite' (2730 Bytes). Received timestamp '2018-02-27 16:28:15 +0100' (1519745295.591368), Current timestamp '2018-02-27 16:14:02 +0100' (1519744442.402212).
[2018-02-27 16:28:15 +0100] information/ApiListener: Restarting after configuration change.
[2018-02-27 16:28:15 +0100] information/Application: Got reload command: Starting new instance.
[2018-02-27 16:28:15 +0100] information/Application: Reload requested, letting new process take over.
[2018-02-27 16:28:15 +0100] information/NotificationComponent: 'notification' started.
[2018-02-27 16:28:15 +0100] information/ApiListener: 'api' started.
[2018-02-27 16:28:15 +0100] information/ApiListener: Adding new listener on port '5665'
[2018-02-27 16:28:15 +0100] critical/TcpSocket: Invalid socket: Address already in use
Context:
	(0) Activating object 'api' of type 'ApiListener'

[2018-02-27 16:28:15 +0100] critical/ApiListener: Cannot bind TCP socket for host '' on port '5665'.
Context:
	(0) Activating object 'api' of type 'ApiListener'

[2018-02-27 16:28:15 +0100] critical/ApiListener: Cannot add listener on host '' for port '5665'.
Context:
	(0) Activating object 'api' of type 'ApiListener'

^C
```

```
[root@icinga2-satellite1 ~]# cat /var/run/icinga2/icinga2.pid
10025
[root@icinga2-satellite1 ~]# ps aux | grep icinga2
root     12267  0.0  0.0 112660   976 pts/0    S+   16:46   0:00 grep --color=auto icinga2
```

## Possible Solution

Investigate on why Systemd thinks that the process failed with exit code 1. It seems that the FDs are not properly closed on reload, which causes the child process not to entirely take over.

Seems to come from the change with the reload in #5996

```
commit c418a9611e82dd6694f09b46a88ae478fab3c161
Author: Jean Flach <jean-marcel.flach@icinga.com>
Date:   Wed Jan 17 13:52:23 2018 +0100

    Add systemd watchdog and adjust reload behaviour
```

## Steps to Reproduce (for bugs)

```
git clone https;//github.com/icinga/icinga-vagrant
cd icinga-vagrant/distributed
vagrant up
```

Terminal 2
```
vagrant ssh icinga2-satellite1
sudo -i
tail -f /var/log/icinga2/icinga2.log

systemctl status icinga2
ps aux | grep icinga2
```

Terminal 1

```
vagrant ssh icinga2-master1
sudo -i
vim /etc/icinga2/zones.d/hosts.conf

<add something in the object, save and exit>

systemctl restart icinga2
```

## Context

Testing the latest development snapshot.

## Your Environment

* Version used (`icinga2 --version`):

```
[root@icinga2-satellite1 ~]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.8.1-488-g98bcca5)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```

* Operating System and version: CentOS 7.4
* Enabled features (`icinga2 feature list`): 

```
[root@icinga2-satellite1 ~]# icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
```

* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

```
[root@icinga2-satellite1 ~]# cat /etc/icinga2/zones.conf
# This file is managed by Puppet. DO NOT EDIT.

object Endpoint "icinga2-master1.vagrant.demo.icinga.com"  {
}

object Endpoint "icinga2-satellite1.vagrant.demo.icinga.com"  {
  host = "192.168.33.102"
}

object Zone "global-templates"  {
  global = true
}

object Zone "master"  {
  endpoints = [ "icinga2-master1.vagrant.demo.icinga.com", ]
}

object Zone "satellite"  {
  endpoints = [ "icinga2-satellite1.vagrant.demo.icinga.com", ]
  parent = "master"
}
```

### PR DESCRIPTION
**Pull request by Crunsher**
Make sure we have written the new PID before letting it take over.

fixes #6082 
fixes #6127

### CODE REVIEW

**Comment by Crunsher** [comment]
Is it possible to test this? @tmatthaeus @lazyfrosch

**Comment by lazyfrosch** [comment]
Will do asap

**Comment by lazyfrosch** [comment]
Dev build: https://build.icinga.com/job/icinga2-dev/job/deb-debian-stretch-1binary/4/arch=x86_64/

**Comment by lazyfrosch** [comment]
This should also fix #6127.

I can confirm that this works under Debian stretch with systemd:
```
root@debian:~/archive# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: v2.8.1-527-ga742e64e4)

root@debian:~/archive# systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: active (running) since Mon 2018-03-19 13:24:25 CET; 7s ago
 Main PID: 1533 (icinga2)
   CGroup: /system.slice/icinga2.service
           ├─1533 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log
           └─1571 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log

root@debian:~/archive# systemctl reload icinga2.service
root@debian:~/archive# systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: active (running) since Mon 2018-03-19 13:24:25 CET; 15s ago
  Process: 1902 ExecReload=/usr/lib/icinga2/safe-reload /usr/lib/icinga2/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 1946 (icinga2)
    Tasks: 12
   CGroup: /system.slice/icinga2.service
           ├─1946 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 1533
           └─1962 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon -e $ICINGA2_LOG_DIR/error.log --reload-internal 1533
```

Other changes are pending with #6157

**Comment by lazyfrosch** [comment]
Only concern: This fix should **not** be related to 2.8, >= 2.9 only.

systemd notify handling should be introduced with the next feature release...

**Pull request merged**
