### PR TITLE
Doc: warn about not setting Comment#entry_time

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by dnsmichi** [comment]
I will restructure the docs in a separate branch to highlight actual config objects, features and other runtime objects like downtimes/comments. No-one should declare downtime/comment objects in a static config file, this design failure came in with 2.4 and REST API Url endpoints in /v1/objects/<type>s.

**Comment by Al2Klimov** [comment]
IMO this change won't harm as long as you're not ready.

**Comment by Al2Klimov** [comment]
... compared to the current docs.

**Comment by dnsmichi** [comment]
My point is - I won't put more details than needed for read-only access to these objects into the documentation.

**Pull request merged**
