### PR TITLE
Indicate too many nested dependencies

### PR DESCRIPTION
**Pull request by Al2Klimov**
... by making the checkable unknown.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
```
object CheckerComponent "c" { }

object CheckCommand "0" {
        command = [ "true" ]
}

object CheckCommand "2" {
        command = [ "sh", "-c", "exit 2" ]
}

object Host "recu1" {
        check_command = "0"
        check_interval = 5s
        retry_interval = 5s
}

object Host "recu2" {
        check_command = "0"
        check_interval = 5s
        retry_interval = 5s
}

object Dependency "recu1" {
        parent_host_name = "recu1"
        child_host_name = "recu2"
        disable_checks = true
}

object Dependency "recu2" {
        parent_host_name = "recu2"
        child_host_name = "recu1"
        disable_checks = true
}

object Host "2" {
        check_command = "2"
        check_interval = 5s
        retry_interval = 5s
}

object Host "0" {
        check_command = "0"
        check_interval = 5s
        retry_interval = 5s
}

object Dependency "2" {
        parent_host_name = "2"
        child_host_name = "0"
        disable_checks = true
}
```

```
[2020-11-11 14:11:28 +0100] warning/Checkable: Too many nested dependencies (>256) for checkable 'recu1': Dependency failed.
[2020-11-11 14:11:28 +0100] notice/Checkable: State Change: Checkable 'recu2' soft state change from DOWN to DOWN detected.
```

```
[2020-11-11 14:11:31 +0100] warning/Checkable: Too many nested dependencies (>256) for checkable 'recu2': Dependency failed.
[2020-11-11 14:11:31 +0100] notice/Checkable: State Change: Checkable 'recu1' soft state change from DOWN to DOWN detected.
```

```
[2020-11-11 14:11:45 +0100] notice/CheckerComponent: Skipping check for object '0': Dependency failed.
```

**Comment by Al2Klimov** [comment]
```
➜  icinga2 git:(feature/dependency-recursion-unknown) curl -fksSLu root:icinga -H 'Accept: application/json' -X GET 'https://localhost:5665/v1/objects/hosts/recu2' -d '{ "attrs": [ "last_check_result" ], "pretty": true }'; echo
{
    "results": [
        {
            "attrs": {
                "last_check_result": {
                    "active": true,
                    "check_source": "Alexanders-MacBook-Pro.local",
                    "command": null,
                    "execution_end": 1605190992.640682,
                    "execution_start": 1605190992.640682,
                    "exit_status": 0.0,
                    "output": "Too many nested dependencies (>256) for checkable 'recu2': Dependency failed.",
                    "performance_data": null,
                    "schedule_end": 1605190992.640682,
                    "schedule_start": 1605190992.640682,
                    "state": 3.0,
                    "ttl": 0.0,
                    "type": "CheckResult",
                    "vars_after": {
                        "attempt": 1.0,
                        "reachable": false,
                        "state": 3.0,
                        "state_type": 1.0
                    },
                    "vars_before": {
                        "attempt": 1.0,
                        "reachable": false,
                        "state": 3.0,
                        "state_type": 1.0
                    }
                }
            },
            "joins": {},
            "meta": {},
            "name": "recu2",
            "type": "Host"
        }
    ]
}
➜  icinga2 git:(feature/dependency-recursion-unknown)
```

**Comment by lippserd** [comment]
@Al2Klimov Since we will forbid recursion with #8472 shouldn't this read `Indicate too many nested dependencies`?

**Comment by Al2Klimov** [comment]
@cla-bot check

**Pull request closed without merging**
