### PR TITLE
Add LogstashWriter feature

### LINKED ISSUE #4054: [dev.icinga.com #11436] Add LogstashWriter for Logstash in addition to GelfWriter
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11436

**Created by twidhalm on 2016-03-22 15:49:55 +00:00**

Assignee: _mfriedrich_
Status: _Assigned_ 
Target Version: _2.7.0_
Last Update: _2016-11-09 15:11:53 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

The GELF protocol can use UDP or TCP according to the documentation.

Since some GELF receivers (like Logstash) can only receive UDP and the Icinga 2 GELF writer can only send TCP we have the situation that 2 tools talking the same protocol still can't talk to each other.

Could you add a protocol switcher to the GELF writer object?

**Changesets**

_2016-06-15 13:21:28 +00:00_ by _kgoller_ 8ad95bdfed83601492ad2e6dde263e348645829f

    Delete unused files
    
    refs #11436

_2016-06-15 13:27:26 +00:00_ by _kgoller_ ce7a23cf049153662b83d092a776b5cd0fa4f7ec

    Delete more unused files
    
    refs #11436

_2016-07-06 11:51:59 +00:00_ by _kgoller_ cd785ae577e4a81de76d3fb0fc7ca17649ee8699

    add UDP support
    
    - icinga can now use UDP to communicate with logstash;
    	switch protocol in logstash.conf
    
    refs #11436

_2016-07-06 12:07:15 +00:00_ by _kgoller_ 50e4c35bc9d4c65d3a7a70cd494e5a614c9d2b8f

    delete comment
    
    refs #11436

_2016-07-11 19:03:41 +00:00_ by _kgoller_ ea5aadf8eb0f719d5998e22740573a9936335ae0

    fix several small issues
    
    -removed some unneeded changes
    -fixed several typo errors
    -moved TcpSocket::Connect() into class Socket
    
    refs #11436

_2016-07-14 07:21:20 +00:00_ by _kgoller_ 1db4852d8eb4c0aa5928d8c536dfd16dfd324209

    Remove pointer
    
    refs #11436

---

**Relations**:

* blocks [#11436](https://dev.icinga.com/issues/11436)

### PR DESCRIPTION
**Pull request by dnsmichi**
fixes #4054

### CODE REVIEW

**Comment by sgovaerts** [comment]
Hmm according to the documentation it mentioned logstash-plugin install logstash-input-json.
[Documentation 14-features](https://github.com/Icinga/icinga2/blob/master/doc/14-features.md)
Yet it doesn't exist?

image

**Comment by dnsmichi** [comment]
You're right, thanks. Copy paste error.

`logstash-codec-json` is the correct name.

**Comment by sgovaerts** [comment]
@dnsmichi Ok, I'm almost there I think.
I've still got the problem that LogstashWriter is unknown.
image

According to the docs I also included the `library "perfdata"` like gelfwriter.
[gelfwriter example](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/object-types#objecttype-gelfwriter)

I've installed it on Ubuntu 16.04, do I need to wait for a new release or would I have to clone from git to get that feature?

**Comment by sgovaerts** [comment]
Ok, I didn't see any target, good to know.
Btw shouldn't the documentation still include the `library "perfdata"` in the `/etc/icinga2/features-available/logstash.conf` example?

**Comment by dnsmichi** [comment]
I did intentionally leave out the header and library include and only added the object modifications. The full object type is explained inside the config object types chapter.

**Comment by dnsmichi** [comment]
I'm reverting this PR, see my comment in https://github.com/Icinga/icinga2/issues/4054#issuecomment-303332996

**Pull request merged**
