### PR TITLE
Ensure all perfdata to be written

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Notes as discussed offline:
- Defer borrowed from Golang makes sense
- activation priority as no effect on Stop(), needs to be re-visited

@lippserd putting this on-hold for now up until @Al2Klimov looks into it again.

**Comment by Al2Klimov** [comment]
@lippserd I've corrected the mistake @dnsmichi pointed out. What about building "snapshot packages" from #6882 + this one and let the customer test?

**Comment by dnsmichi** [comment]
Are you able to reproduce the mentioned "killed" checks in #6873?

**Comment by Al2Klimov** [comment]
I didn't even try. But the user affected by the problem could test snapshot packages.

**Comment by dnsmichi** [comment]
Ok, then let's go.

**Pull request merged**
