### PR TITLE
Fix that TimePeriod segments are not cleared on restart

### LINKED ISSUE #6385: TimePeriod segments are not cleared after restart
Restarting does not clear the segments of a timeperiod. This results in segments being active even after removing them from configuration and include/exclude only being added/removed after a second restart.

Example Config:
```
object TimePeriod "testperiod" {
   ranges = {
      "tuesday" = "00:00-24:00"
   }
   excludes = ["testexcludeperiod"]
}

object TimePeriod "testexcludeperiod" {
   ranges = {
      "tuesday" = "09:00-12:00"
   }
}
```

First start: 1 segment (exclude not applied)
```
{
   "begin": 1529359200 (GMT+2: Monday, June 18, 2018 12:00:00 PM),
   "end": 1529445600 (GMT+2: Tuesday, June 19, 2018 12:00:00 PM)
}
```

Second start: 2 segments (exclude applied)
```
{
   "begin": 1529359200 (GMT+2: Monday, June 18, 2018 12:00:00 PM),
   "end": 1529391600 (GMT+2: Tuesday, June 19, 2018 9:00:00 AM)
},
{
   "begin": 1529402400 (GMT+2: Tuesday, June 19, 2018 12:00:00 AM),
   "end": 1529445600 (GMT+2: Tuesday, June 19, 2018 12:00:00 PM)
}
```

### PR DESCRIPTION
**Pull request by N-o-X**
fixes #6385 
refs #6282

### CODE REVIEW

**Comment by dnsmichi** [comment]
How's your tests looking like, and is that a requirement for solving #6311 ?

**Comment by N-o-X** [comment]
No this is not required to solve #6311. It's a different problem.

I used the config I mentioned in #6385 and checked `https://localhost:5665/v1/objects/timeperiods`:

**Before fix:** 
First start: 1 segment (exclude not applied)
```
{
   "begin": 1529359200 (GMT+2: Monday, June 18, 2018 12:00:00 PM),
   "end": 1529445600 (GMT+2: Tuesday, June 19, 2018 12:00:00 PM)
}
```

Second start: 2 segments (exclude applied)
```
{
   "begin": 1529359200 (GMT+2: Monday, June 18, 2018 12:00:00 PM),
   "end": 1529391600 (GMT+2: Tuesday, June 19, 2018 9:00:00 AM)
},
{
   "begin": 1529402400 (GMT+2: Tuesday, June 19, 2018 12:00:00 AM),
   "end": 1529445600 (GMT+2: Tuesday, June 19, 2018 12:00:00 PM)
}
```

**After fix:**
Every start: 2 segments (exclude applied)
```
{
   "begin": 1529359200 (GMT+2: Monday, June 18, 2018 12:00:00 PM),
   "end": 1529391600 (GMT+2: Tuesday, June 19, 2018 9:00:00 AM)
},
{
   "begin": 1529402400 (GMT+2: Tuesday, June 19, 2018 12:00:00 AM),
   "end": 1529445600 (GMT+2: Tuesday, June 19, 2018 12:00:00 PM)
}

**Comment by dnsmichi** [comment]
It needs at least one review, I am not sure if we can stem that before 2.9. Thanks though :)

**Comment by dnsmichi** [comment]
We'll look into this after 2.9. We have a fixed issue set, a long freeze already and will just focus on the last remaining tasks.

**Pull request merged**
