### PR TITLE
Improve path handling in cmake and daemon

### PR DESCRIPTION
**Pull request by lazyfrosch**
## Concept

This PR wants to get rid of using high level paths `/etc` and `/var` everywhere.

It introduces new constants:
* `ConfigDir` `/etc/icinga2`
* `DataDir` `/var/lib/icinga2`
* `CacheDir` `/var/cache/icinga2`
* `LogDir` `/var/log/icinga2`
* `SpoolDir` `/var/spool/icinga2`

The idea is to make that paths configurable, not just by setting the (now deprecated) vars:

* `SysConfDir` `/etc`
* `LocalStateDir` `/var`

These vars where used everywhere and have now largely been removed.

## Claims

1. Default paths stay the same - unless they get changed on compile or daemon config
1. Setting `SysconfDir` and `LocalstateDir` still works (preference over the new defaults)
1. Reducing code repetition of `yadada + "/yada/icinga2"`
1. Old constants used in config files should still work the same - unless admin decides to reconfigure, for e.g. `LogDir`
1. Functions in `Application` have been cleaned up (`Declare*` and `Get*`) and replaced by (`DeclareConst` and `GetConst`)

## TODO

- [x] Introducing new vars and implement handling
- [x] Ensuring windows paths work
- [x] Updating docs for new constants
- [ ] Preparing a note for changelog

### CODE REVIEW

**Comment by lazyfrosch** [comment]
With the new cmake options, paths can be tweaked:

```
cmake .. \
  -DCMAKE_BUILD_TYPE=Debug \
  -DICINGA2_USER=markus -DICINGA2_GROUP=markus -DICINGA2_UNITY_BUILD=OFF \
  -DICINGA2_COMMAND_GROUP=markus \
  -DCMAKE_INSTALL_PREFIX=/opt/icinga2 \
  -DICINGA2_INITRUNDIR=/opt/icinga2/run \
  -DICINGA2_SYSCONFIGFILE=/opt/icinga2/etc/sysconfig \
  -DICINGA2_PLUGINDIR=/opt/icinga2/libexec \
  -DICINGA2_CONFIGDIR=/opt/icinga2/etc \
  -DICINGA2_DATADIR=/opt/icinga2/data \
  -DICINGA2_CACHEDIR=/opt/icinga2/cache \
  -DICINGA2_LOGDIR=/opt/icinga2/log \
  -DICINGA2_SPOOLDIR=/opt/icinga2/spool \
  -DICINGA2_PKGDATADIR=/opt/icinga2/share
```

```
$ icinga2 -V
Closed FD 6 which we inherited from our parent process.
icinga2 - The Icinga 2 network monitoring daemon (version: v2.9.1-49-ge582f4821; debug)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:

  Config directory: /opt/icinga2/etc
  Data directory: /opt/icinga2/data
  Log directory: /opt/icinga2/log
  Cache directory: /opt/icinga2/cache
  Spool directory: /opt/icinga2/spool
  Run directory: /opt/icinga2/run

Older paths (deprecated):
  Installation root: /opt/icinga2
  Sysconf directory: /opt/icinga2/etc
  Run directory (base): /opt/icinga2/var/run
  Local state directory: /opt/icinga2/var

Internally used paths:
  Package data directory: /opt/icinga2/share
  State path: /opt/icinga2/data/icinga2.state
  Modified attributes path: /opt/icinga2/data/modified-attributes.conf
  Objects path: /opt/icinga2/cache/icinga2.debug
  Vars path: /opt/icinga2/cache/icinga2.vars
  PID path: /opt/icinga2/run/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: Unknown
  Kernel: Linux
  Kernel version: 4.17.0-1-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.1.0
  Build host: amalia
```

**Comment by dnsmichi** [comment]
I've started reading the diff, I will switch to the shell soon and fix some typos myself (that's faster than a full review, that doesn't make sense). I will post my summary here next week.

**Comment by dnsmichi** [comment]
Tested with a wrongly rewritten configuration to see what happens when users make mistakes.

```
object FileLogger "main-log" {
  severity = "information"
  //path = LocalStateDir + "/log/icinga2/icinga2.log"
  path = LogDir + "/log/icinga2/icinga2.log"
}

[2018-08-07 17:16:49 +0200] critical/Application: Error: Could not open logfile '/usr/local/icinga2/var/log/icinga2/log/icinga2/icinga2.log'
```

**Comment by lazyfrosch** [comment]
I'm not sure if we can catch this kind of mistake...

**Comment by dnsmichi** [comment]
Oh, I am just fine with the logging here. I wanted to give an update what I am currently testing and doing. I won't test the typical cases, only some edge cases which come to my mind. I've also updated the upgrading docs while studying the changes.

**Comment by dnsmichi** [comment]
Refined the log messages a bit. (sorry, I am a perfectionist, learned from the best)

```
mbmif /usr/local/icinga2/etc/icinga2 (master *) # icinga2 daemon -DSysconfDir=/bla
[2018-08-07 17:57:20 +0200] warning/icinga-app: Please do not set the deprecated 'Sysconfdir' constant, use the 'ConfigDir' constant instead! For compatibility reasons, their value is set based on the 'SysconfDir' constant.
```

**Comment by dnsmichi** [comment]
The reason why I asked to remove the "old paths" section in the version output from the meeting last week was merely that the path information table is not very useful to me. It is nice to have, but during community support I don't look at it in deep - users normally don't modify the paths as they fear breaking packages (which is a good educated behaviour) and I just scroll it over.

Instead, the most interesting bits in today's support are the system details we automatically extract, and the build details to see whether someone uses custom packages or a local source installation. I've therefore modified the output of `--version`, and while at it, I've removed some of the shift operators which are somewhat expensive with concat string to string. Doesn't hurt for versions details, just some code quality.

```
mbmif /usr/local/icinga2/etc/icinga2 (master *) # icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.9.1-67-ga2a1f5c8d; debug)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Mac OS X
  Platform version: 10.13.6
  Kernel: Darwin
  Kernel version: 17.7.0
  Architecture: x86_64

Build information:
  Compiler: Clang 9.1.0.9020039
  Build host: mbmif.local

Application information:

General paths:
  Config directory: /usr/local/icinga2/etc/icinga2
  Data directory: /usr/local/icinga2/var/lib/icinga2
  Log directory: /usr/local/icinga2/var/log/icinga2
  Cache directory: /usr/local/icinga2/var/cache/icinga2
  Spool directory: /usr/local/icinga2/var/spool/icinga2
  Run directory: /usr/local/icinga2/var/run/icinga2

Old paths (deprecated):
  Installation root: /usr/local/icinga2
  Sysconf directory: /usr/local/icinga2/etc
  Run directory (base): /usr/local/icinga2/var/run
  Local state directory: /usr/local/icinga2/var

Internal paths:
  Package data directory: /usr/local/icinga2/share/icinga2
  State path: /usr/local/icinga2/var/lib/icinga2/icinga2.state
  Modified attributes path: /usr/local/icinga2/var/lib/icinga2/modified-attributes.conf
  Objects path: /usr/local/icinga2/var/cache/icinga2/icinga2.debug
  Vars path: /usr/local/icinga2/var/cache/icinga2/icinga2.vars
  PID path: /usr/local/icinga2/var/run/icinga2/icinga2.pid
```

This probably could need better table formatting, one could steal from the troubleshooting cli command. But that's something for a separate PR.

**Comment by dnsmichi** [comment]
I see one problem here, and that's likely the thing with local string variables:

`Value Application::GetConst(const String& name)` is different to the previous getters for the paths which implicitly cast the returned values to string so that one can use them with string concatenation. On Windows for example you'll sometimes get something from the filesystem namespace which can be converted into a string, but it does transform this automatically. That's the reason for this local change which I think is ugly and can be easily forgotten.

https://github.com/Icinga/icinga2/pull/6506/files#diff-e8b23cce1118fe8cabeb821498fef0cbR208

I would instead implement a new function which explicitly returns a string and throws an error (for developers) if the requested path constant does not return a string (optional).

**Comment by dnsmichi** [comment]
Will continue tomorrow with that.

**Comment by dnsmichi** [comment]
I don't like the generic Value interface from Application::GetConst(), but those path getters generally need an overhaul. I'll move this into a separate task, this can be implemented independent of this issue.

**Pull request merged**
