### PR TITLE
Support Boost 1.74

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Don’t worry about Travis, we have #8791.

**Comment by julianbrost** [comment]
This should probably also include #7780 as otherwise running CMake without the workaround mentioned there (`-DBoost_NO_BOOST_CMAKE=ON`)

**Comment by Al2Klimov** [comment]
#8802

**Review by julianbrost — APPROVED** [review]
Merged #8793 and #8802 locally and compiling against Boost 1.75 worked fine.

**Pull request merged**
