### PR TITLE
Replace Load Dependency with Load Priority

### PR DESCRIPTION
**Pull request by Crunsher**
See #6589

### CODE REVIEW

**Comment by Crunsher** [comment]
No real change in performance:
```
master
< real	0m30.157s
< user	5m9.776s
< sys	0m10.156s
---
pr
> real	0m29.725s
> user	5m7.528s
> sys	0m10.612s
```

TODO: make sure get_host works as it should

**Comment by Crunsher** [comment]
And done:
```
object Host "test-miau" {
  check_command = "dummy"
  vars.my_var = "abc"
}
object Service "test-wauwau" {
  check_command = "dummy"
  host_name = "test-miau"
  var my_host = get_host(host_name)

  vars.my_host_override = my_host.vars.my_var
}


Object 'test-miau!test-wauwau' of type 'Service':
  % declared in '/home/jflach/i2/etc/icinga2/zones.d/master/hosts.conf', lines 5:1-5:28
  * __name = "test-miau!test-wauwau"
  * action_url = ""
  * check_command = "dummy"
    % = modified in '/home/jflach/i2/etc/icinga2/zones.d/master/hosts.conf', lines 6:3-6:25
  * host_name = "test-miau"
    % = modified in '/home/jflach/i2/etc/icinga2/zones.d/master/hosts.conf', lines 7:3-7:25
  * templates = [ "test-wauwau" ]
    % = modified in '/home/jflach/i2/etc/icinga2/zones.d/master/hosts.conf', lines 5:1-5:28
  * type = "Service"
  * vars
    * my_host_override = "abc"
      % = modified in '/home/jflach/i2/etc/icinga2/zones.d/master/hosts.conf', lines 10:3-10:45
  * volatile = false
  * zone = "master"
```

**Comment by dnsmichi** [comment]
Still testing this, will take until Friday.

**Comment by Al2Klimov** [comment]
Rebased.

**Comment by Al2Klimov** [comment]
AFAIK activation prio is lowest first, but this one seems highest first. @dnsmichi, isn't this a bit confusing?

**Comment by dnsmichi** [comment]
Yep, it is turned around. Highly likely the source code originates from a time where activation priority wasn't clear enough yet. Can you please adjust this?

Basically the order is defined as follows:

```
Zone -> Endpoint -> ApiListener (for the cluster parts)

-> Host -> Service -> other config objects (for cluster membership and apply rules)
```

**Comment by dnsmichi** [comment]
Discussed this offline with @Crunsher and @Al2Klimov - in its current state, there's no benefit of implementing this. We'll come back to this at a later point when touching the config compiler parts again.

**Pull request closed without merging**
