### PR TITLE
API Actions: Add downtime for all host services (child objects)

### PR DESCRIPTION
**Pull request by dnsmichi**
# Hosts with all services

`all_services` = true/false

This avoids a secondary roundtrip for a typical host maintenance.

## child_options with all services

Also implemented, dependent hosts will also schedule a service downtime if `all_services` is enabled.

## Delete downtimes created through this action (all_services, child_options)

Create a runtime sequence id for this action call and store it inside the downtime objects. This is returned to the caller and as well available via GET query.

The client can use this `sequence_id` in order to filter on `remove-downtime` actions. This deletes any matching downtime object.

# Tests

Below, since this feature was enhanced quite a bit over multiple iterations.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Screen Shot 2019-06-03 at 15 58 37

**Comment by dnsmichi** [comment]
Also available for child hosts.

## Test config

```
const count = 10

for (i in range(count)) {
  var c = i

  object Host c {
    check_command = "random"
  }
  apply Service c {
    check_command = "random"
    assign where host.check_command == "random"
  }

  c = i + count

  object Dependency "dep-" + i use (i, c) {
    parent_host_name = i
    child_host_name = c
  }

  object Host c {
    check_command = "random"
  }
  apply Service c {
    check_command = "random"
    assign where host.check_command == "random"
  }
}
```

## Sample output

```
curl -k -s -u root:icinga -X POST -H 'Accept: application/json' 'https://localhost:5665/v1/actions/schedule-downtime' -d "$(jo -p pretty=true type=Host filter=true author=michi comment='are you crazy?' fixed=true start_time=$(gdate +%s -d "+0 hour") end_time=$(gdate +%s -d "+1 hour") all_services=true child_options=1)"

        {
            "child_downtimes": [
                {
                    "legacy_id": 1008.0,
                    "name": "12!b13f9e6d-15d2-4365-8bbd-c81b95684a07",
                    "service_downtimes": [
                        {
                            "legacy_id": 1009.0,
                            "name": "2!0!d6d8245b-664e-4986-8392-ed84cffd8d44"
                        },
                        {
                            "legacy_id": 1010.0,
                            "name": "2!1!e76d4bb6-dc44-4bbd-a42d-bea46855fb45"
                        },
                        {
                            "legacy_id": 1011.0,
                            "name": "2!10!5702313b-b4ef-46a2-b099-53d4bdb5f3c5"
                        },
                        {
                            "legacy_id": 1012.0,
                            "name": "2!11!c8de5be6-d4aa-4171-92e9-aad3e0f46022"
                        },
                        {
                            "legacy_id": 1013.0,
                            "name": "2!12!18bf8c28-ae62-40f5-bd41-5cce107ba46d"
                        },
                        {
                            "legacy_id": 1014.0,
                            "name": "2!13!89c1e5fe-47f6-4adb-880d-21ce6410e94f"
                        },
                        {
                            "legacy_id": 1015.0,
                            "name": "2!14!7c99e068-e738-4923-bb74-0ccb46cef2ac"
                        },
                        {
                            "legacy_id": 1016.0,
                            "name": "2!15!f97357f9-e95f-4876-abb0-22d61f837c6c"
                        },
                        {
                            "legacy_id": 1017.0,
                            "name": "2!16!9b80206b-dc31-4d06-ba4a-f0488c609949"
                        },
                        {
                            "legacy_id": 1018.0,
                            "name": "2!17!44f8f333-3858-498b-ab45-5e0565c74ee7"
                        },
                        {
                            "legacy_id": 1019.0,
                            "name": "2!18!83a3dc08-1b14-4211-9ee0-fe065590672f"
                        },
                        {
                            "legacy_id": 1020.0,
                            "name": "2!19!1b9f67cb-721e-4db8-85ea-9fb4f8f90224"
                        },
                        {
                            "legacy_id": 1021.0,
                            "name": "2!2!14ab8580-f987-449d-9161-6b172db5896b"
                        },
                        {
                            "legacy_id": 1022.0,
                            "name": "2!3!9fa7ab0c-d772-4a28-8f4d-ce3d7c8fab96"
                        },
                        {
                            "legacy_id": 1023.0,
                            "name": "2!4!adeb2f1c-77d2-4be1-af71-883cb6c85cad"
                        },
                        {
                            "legacy_id": 1024.0,
                            "name": "2!5!08e5f5d4-bd1f-4c70-b557-82c860a30b52"
                        },
                        {
                            "legacy_id": 1025.0,
                            "name": "2!6!9374fefd-b7ae-4142-9ee9-a0a01aab49ee"
                        },
                        {
                            "legacy_id": 1026.0,
                            "name": "2!7!58fd93aa-f25c-4cf9-b715-1a1f72b906fd"
                        },
                        {
                            "legacy_id": 1027.0,
                            "name": "2!8!2339ca0d-8cc9-4299-938e-15c6473ee176"
                        },
                        {
                            "legacy_id": 1028.0,
                            "name": "2!9!ee19c0ad-8291-4221-ade9-1dea42a7d1ff"
                        }
                    ]
                }
            ],
            "code": 200.0,
            "legacy_id": 987.0,
            "name": "2!442c7c32-c84f-478d-beb5-5b1d5dfef004",
            "service_downtimes": [
                {
                    "legacy_id": 988.0,
                    "name": "2!0!675564aa-d0e4-4c54-91ed-ed5d6e7adf92"
                },
                {
                    "legacy_id": 989.0,
                    "name": "2!1!c2f3e700-c4e1-43f7-abb9-82c954ee1679"
                },
                {
                    "legacy_id": 990.0,
                    "name": "2!10!b4b22276-b6b8-4f87-8282-962cfea4a71b"
                },
                {
                    "legacy_id": 991.0,
                    "name": "2!11!3eef145c-f87c-42e8-82ef-d4239d4d5c4d"
                },
                {
                    "legacy_id": 992.0,
                    "name": "2!12!6550c9db-c21c-48d4-a1e4-62993b9ebd53"
                },
                {
                    "legacy_id": 993.0,
                    "name": "2!13!d1fee9fb-8e22-45c9-abcb-5fa3f56e91a9"
                },
                {
                    "legacy_id": 994.0,
                    "name": "2!14!44c5abc2-9706-4d26-a0f7-ecb1bb680b87"
                },
                {
                    "legacy_id": 995.0,
                    "name": "2!15!6fa262af-442c-4086-80df-e22a140d2e00"
                },
                {
                    "legacy_id": 996.0,
                    "name": "2!16!96d9b3c1-cac3-4b95-89e0-7ae31379d192"
                },
                {
                    "legacy_id": 997.0,
                    "name": "2!17!229c338b-89ea-4fdb-b7e7-014518233d01"
                },
                {
                    "legacy_id": 998.0,
                    "name": "2!18!4b8ae17f-c9dd-461f-bdb0-c0e4bffc1b74"
                },
                {
                    "legacy_id": 999.0,
                    "name": "2!19!407c4fd3-8883-4675-aa93-36b99fab621b"
                },
                {
                    "legacy_id": 1000.0,
                    "name": "2!2!26238781-542c-48f4-bafe-556ef0e86ea3"
                },
                {
                    "legacy_id": 1001.0,
                    "name": "2!3!669b2208-5128-4f7f-acb8-53217ccd926e"
                },
                {
                    "legacy_id": 1002.0,
                    "name": "2!4!8bc3db2c-3778-4568-8759-0af27b66047f"
                },
                {
                    "legacy_id": 1003.0,
                    "name": "2!5!0c28b49d-54c0-4ac6-b612-407f4b188741"
                },
                {
                    "legacy_id": 1004.0,
                    "name": "2!6!9859ede8-8c1f-4f2e-bf0f-f02f2fa8fb23"
                },
                {
                    "legacy_id": 1005.0,
                    "name": "2!7!fb9e2e71-8087-43a3-8a58-01b4d17b0301"
                },
                {
                    "legacy_id": 1006.0,
                    "name": "2!8!4bfd2079-680e-429c-82a8-172bb763b8c6"
                },
                {
                    "legacy_id": 1007.0,
                    "name": "2!9!d5fed789-30f4-4b46-98c9-fec9bfcbbcc8"
                }
            ],
            "status": "Successfully scheduled downtime '2!442c7c32-c84f-478d-beb5-5b1d5dfef004' for object '2'."
        },
        {
            "child_downtimes": [],
            "code": 200.0,
            "legacy_id": 1029.0,
            "name": "15!9fe6bc5c-150c-4c9a-9227-8f431ace3f43",
            "service_downtimes": [
                {
                    "legacy_id": 1030.0,
                    "name": "15!0!fd562de5-d902-47fb-9a32-71e1089187cf"
                },
                {
                    "legacy_id": 1031.0,
                    "name": "15!1!683ad0f6-e736-4e0f-9777-96bba5c890b7"
                },
                {
                    "legacy_id": 1032.0,
                    "name": "15!10!f833d194-a06d-44a9-a9ac-3f6efcb52af1"
                },
                {
                    "legacy_id": 1033.0,
                    "name": "15!11!887b0977-a53b-4a25-a191-00702980cd22"
                },
                {
                    "legacy_id": 1034.0,
                    "name": "15!12!f37c019b-93ab-4c7b-81d0-53ab756bef62"
                },
                {
                    "legacy_id": 1035.0,
                    "name": "15!13!f79cfc34-430a-47bd-b820-c47965d123e3"
                },
                {
                    "legacy_id": 1036.0,
                    "name": "15!14!9d8cf7b1-bf13-41a3-91c5-2be787b053eb"
                },
                {
                    "legacy_id": 1037.0,
                    "name": "15!15!69255755-4324-465d-9b1d-b8d419262fc8"
                },
                {
                    "legacy_id": 1038.0,
                    "name": "15!16!e493fd0d-ebdb-4ce6-9fc6-92783772ae10"
                },
                {
                    "legacy_id": 1039.0,
                    "name": "15!17!4e77d0d1-0ece-4df1-afba-0cbfd3921a45"
                },
                {
                    "legacy_id": 1040.0,
                    "name": "15!18!9f683090-913a-4f50-adb6-fb6dbceb634c"
                },
                {
                    "legacy_id": 1041.0,
                    "name": "15!19!c7b84de2-f832-44cb-8d1a-460c49c31804"
                },
                {
                    "legacy_id": 1042.0,
                    "name": "15!2!7fdf49d0-e8ee-4433-a036-a3cecd5c2283"
                },
                {
                    "legacy_id": 1043.0,
                    "name": "15!3!2d871052-ecb0-4a0b-a733-5e672ffcfb47"
                },
                {
                    "legacy_id": 1044.0,
                    "name": "15!4!561cea45-4936-4054-8984-cab027d15870"
                },
                {
                    "legacy_id": 1045.0,
                    "name": "15!5!b1bfcf45-f7f4-44dd-a03c-a8f3fe093538"
                },
                {
                    "legacy_id": 1046.0,
                    "name": "15!6!9391944b-66d7-45f8-9e1f-319bd73dd450"
                },
                {
                    "legacy_id": 1047.0,
                    "name": "15!7!bafcfc3d-a8da-4f7b-b6a8-f22bd99fed8d"
                },
                {
                    "legacy_id": 1048.0,
                    "name": "15!8!684903df-7e03-4959-baff-254f839e5828"
                },
                {
                    "legacy_id": 1049.0,
                    "name": "15!9!438c9d30-3d6b-4b2e-adbe-cbf3b7606fa3"
                }
            ],
            "status": "Successfully scheduled downtime '15!9fe6bc5c-150c-4c9a-9227-8f431ace3f43' for object '15'."
        },
        {
            "child_downtimes": [],
            "code": 200.0,
            "legacy_id": 1050.0,
            "name": "14!d7c091aa-f0a5-463c-89f7-b15208e8ee50",
            "service_downtimes": [
                {
                    "legacy_id": 1051.0,
                    "name": "14!0!68d563ec-3556-46bf-a9fa-df864bc16d11"
                },
                {
                    "legacy_id": 1052.0,
                    "name": "14!1!f12adfad-6c16-41bb-a8b7-51f95284f3d0"
                },
                {
                    "legacy_id": 1053.0,
                    "name": "14!10!90733bbc-8f37-4d59-9019-4c3e7aa57f58"
                },
                {
                    "legacy_id": 1054.0,
                    "name": "14!11!fab05725-bac0-455f-b570-83ea8aaeea54"
                },
                {
                    "legacy_id": 1055.0,
                    "name": "14!12!b7215e2d-6056-482e-a0aa-c86d453466b8"
                },
                {
                    "legacy_id": 1056.0,
                    "name": "14!13!c9eaf3b0-76a9-420d-9631-ec2ee6477f99"
                },
                {
                    "legacy_id": 1057.0,
                    "name": "14!14!dbcb9e48-b83b-41a8-ae2b-a8ad058e88d6"
                },
                {
                    "legacy_id": 1058.0,
                    "name": "14!15!66c707e5-0152-44ea-a513-392cebf23a17"
                },
                {
                    "legacy_id": 1059.0,
                    "name": "14!16!aa49023b-1a41-48b4-b650-c6bbacd3a2b4"
                },
                {
                    "legacy_id": 1060.0,
                    "name": "14!17!dea9fcf4-167e-4230-8c2b-bf41a4a86c01"
                },
                {
                    "legacy_id": 1061.0,
                    "name": "14!18!9650b149-2a0c-483b-a8d4-ff0cbbb36b93"
                },
                {
                    "legacy_id": 1062.0,
                    "name": "14!19!8270f84c-719d-4ead-8b3f-3db355e10ca0"
                },
                {
                    "legacy_id": 1063.0,
                    "name": "14!2!67913d86-efcf-423e-a310-3a44a8ad7524"
                },
                {
                    "legacy_id": 1064.0,
                    "name": "14!3!7f4ec8a5-d411-4ba4-a924-d27c4e57f344"
                },
                {
                    "legacy_id": 1065.0,
                    "name": "14!4!022cb6a0-641e-4f32-88cb-3deb850c238a"
                },
                {
                    "legacy_id": 1066.0,
                    "name": "14!5!67f73279-1114-4bd9-b610-e3dafecd6ed1"
                },
                {
                    "legacy_id": 1067.0,
                    "name": "14!6!38f31b75-4eed-473c-bb3a-0841c22be521"
                },
                {
                    "legacy_id": 1068.0,
                    "name": "14!7!d1e995cb-08b5-4c32-bbe1-491045024a29"
                },
                {
                    "legacy_id": 1069.0,
                    "name": "14!8!bbe86b96-9978-4339-9c50-1c87c10b5f9b"
                },
                {
                    "legacy_id": 1070.0,
                    "name": "14!9!4c5f0600-7b7a-4110-9c0c-296102a18909"
                }
            ],
            "status": "Successfully scheduled downtime '14!d7c091aa-f0a5-463c-89f7-b15208e8ee50' for object '14'."
        }
    ]
```

**Comment by dnsmichi** [comment]
```
                {
                    "legacy_id": 607.0,
                    "name": "7!7!4f2ee136-df5a-49e5-990c-befecb4f7543",
                    "sequence_id": "2708f16a-a286-42f9-ad44-f72104b4e98f"
                },
                {
                    "legacy_id": 608.0,
                    "name": "7!8!839ee358-cd7f-4d11-a755-9c527c8dd9f0",
                    "sequence_id": "2708f16a-a286-42f9-ad44-f72104b4e98f"
                },
                {
                    "legacy_id": 609.0,
                    "name": "7!9!c60a2ec1-b1a7-4d0f-8c90-2c0c183728d8",
                    "sequence_id": "2708f16a-a286-42f9-ad44-f72104b4e98f"
                }
```

**Comment by dnsmichi** [comment]
## Sequence IDs for chained removal

Requested by @lippserd 

@Crunsher pointed me to the fact that one can just filter for type Downtime and the sequence_id for removal. A short test via debug console:

```
<2> => get_objects(Downtime).filter(d => d.sequence_id == "d4b924be-53ab-4d5a-a76d-d5f4152a6f69")
```

```
curl -k -s -u root:icinga -X POST -H 'Accept: application/json' 'https://localhost:5665/v1/actions/remove-downtime' -d "$(jo -p pretty=true type=Downtime filter='downtime.sequence_id=="d4b924be-53ab-4d5a-a76d-d5f4152a6f69"')"

        {
            "code": 200.0,
            "status": "Successfully removed downtime '11!8!42f8c7e4-2dbd-4272-9d47-aed815856895'."
        },
        {
            "code": 200.0,
            "status": "Successfully removed downtime '11!9!63abc3e5-ead4-4237-afb8-a07d2500836b'."
        }
    ]
}
```

**Comment by dnsmichi** [comment]
@lippserd Just a design review, not a code review please :)

**Comment by lippserd** [comment]
Talked with @dnsmichi about this and we came to the conclusion that it's best to put the sequence handling into a new PR.

**Comment by dnsmichi** [comment]
As discussed, splitting this again into 'all_services' and the sequence IDs. The latter needs a proper design and things like id, count, origin.

**Pull request merged**
