### PR TITLE
Fix operator precedence table

### LINKED ISSUE #5573: mixed up operator precedence in the documenation
The operator precedence

https://www.icinga.com/docs/icinga2/latest/doc/17-language-reference/#expression-operators

in the operator precedence table is mixed up. The table should be in descending precedence but the 'Logical AND' with precedence 13 is before the 'Assignment' with precedence 12. The same is with the 'Logical OR'.

Most probably either the descending precedence or the precedence column is not right.

### PR DESCRIPTION
**Pull request by Crunsher**
Fixes #5573

### CODE REVIEW

**Comment by mcktr** [comment]
The order looks correct now but the format of the operator precedence table is weirdly messed up. 

doc-operators-table

Maybe we should put the operators in back-ticks ( e.g. `!=` )?

**Comment by mcktr** [comment]
In a local MkDocs test environment \`|\` and \`||\` (in backticks) worked. When we put the Result column in backticks as well, we can use `|` and `||`.

**Comment by dnsmichi** [comment]
What's the status of this PR?

**Comment by Crunsher** [comment]
I'm not sure, while backticks work in mkdocs it would break the doc viewer on GitHub. Wanna flip a coin?

**Comment by mcktr** [comment]
A bit dirty but the following works in MkDocs and the GitHub Viewer.

```
<code>&#124;</code>
```

This will render a vertical bar as inline code. 

<code>|</code>

MkDocs:

auswahl_011

GitHub:

Can be watched here: 
https://gist.github.com/mcktr/c54e74604d02fd9108311e068613ddd6

What do you think about the example column in code tags? I think this helps a bit to differentiate between example an result.

**Comment by Crunsher** [comment]
Nice, works like a charm. Those who read plain text get shafted but that's nothing new with Markdown :disappointed: 

I'll go ahead and squash the commits

**Pull request merged**
