### PR TITLE
ITL: Implement various options for the Snmp CheckCommand, including mib-list

### PR DESCRIPTION
**Pull request by Freeaqingme**
Resolves #8498

https://dev.icinga.org/issues/8498

### CODE REVIEW

**Comment by Freeaqingme** [comment]
Let me also add support for getnext. Tomorrow.

**Comment by lazyfrosch** [comment]
Seems sane to me, can you pls update the docs with the new params?

http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/configuring-icinga2#plugin-check-command-snmp

**Comment by Freeaqingme** [comment]
@larsengels Had missed those. Added now!

**Comment by gunnarbeutner** [comment]
Can you rebase your patches against the master branch?
Also, your previous commits use this author: 'Dolf Schimmel <dolf@transip.nl>'
Which one do you want to use in the AUTHORS file?

**Comment by gunnarbeutner** [comment]
Merged. Thanks.

**Pull request closed without merging**
