### PR TITLE
Docs: Add a note on required configuration updates for new notification scripts in v2.7.0

### PR DESCRIPTION
**Pull request by dnsmichi**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Collected issues #5473 #5472 #5471 #5453

**Comment by dnsmichi** [comment]
- [x] backported.

**Comment by ronator** [comment]
Could you also show needed changes to notifications.conf? Only commands.conf is shown.

"The safest way is to incorporate the configuration updates from v2.7.0 inside the commands.conf and notifications.conf configuration files."

**Comment by dnsmichi** [comment]
https://www.icinga.com/2017/08/23/advisory-for-icinga-2-v2-7-update-and-mail-notification-scripts/

**Pull request merged**
