### PR TITLE
Fix build errors with Boost v1.70

### LINKED ISSUE #7237: Upcoming Icinga 2.11: Build error on FreeBSD (boost related)
## Describe the bug
The upcoming Icinga 2.11 fails to build on FreeBSD:

```
[1/82] /usr/bin/c++  -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -Ithird-party/nlohmann_json -Ithird-party/utf8cpp/source -I. -Ilib -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -Qunused-arguments -fcolor-diagnostics -pthread -Winvalid-pch -std=c++0x -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -MD -MT plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o -MF plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o.d -o plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o -c plugins/check_nscp_api.cpp          
FAILED: plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o
/usr/bin/c++  -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -Ithird-party/nlohmann_json -Ithird-party/utf8cpp/source -I. -Ilib -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -Qunused-arguments -fcolor-diagnostics -pthread -Winvalid-pch -std=c++0x -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -MD -MT plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o
-MF plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o.d -o plugins/CMakeFiles/check_nscp_api.dir/check_nscp_api.cpp.o -c plugins/check_nscp_api.cpp                 
In file included from plugins/check_nscp_api.cpp:14:
In file included from lib/base/io-engine.hpp:12:
In file included from /usr/local/include/boost/asio/deadline_timer.hpp:24:
In file included from /usr/local/include/boost/asio/basic_deadline_timer.hpp:26:
/usr/local/include/boost/asio/detail/io_object_impl.hpp:87:40: error: no member named 'get_executor' in 'boost::asio::execution_context'                                     
      implementation_executor_(context.get_executor(),
                               ~~~~~~~ ^
/usr/local/include/boost/asio/ip/basic_resolver.hpp:118:7: note: in instantiation of function template specialization 'boost::asio::detail::io_object_impl<boost::asio::detail::resolver_service<boost::asio::ip::tcp>, boost::asio::executor>::io_object_impl<boost::asio::execution_context>' requested here                                             
    : impl_(context)
      ^
lib/base/tcpsocket.hpp:40:16: note: in instantiation of function template specialization 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::executor>::basic_resolver<boost::asio::execution_context>' requested here
        tcp::resolver resolver (socket.get_executor().context());
                      ^
plugins/check_nscp_api.cpp:189:11: note: in instantiation of function template specialization 'icinga::Connect<boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::executor> >' requested here
                icinga::Connect(stream->lowest_layer(), host, port);
                        ^
1 error generated.
ninja: build stopped: subcommand failed.
*** Error code 1

```

The commit tag I used is 00ea2d5.

FreeBSD 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64

```
pkg info -x boost
boost-libs-1.70.0_2
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7237

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@bsdlme Once approved please, **don't merge**, but let @dnsmichi review. Thanks.

**Comment by bsdlme** [comment]
I'm on vacation and can't try it for the next two weeks.

**Comment by dnsmichi** [comment]
Homebrew/homebrew-core#38890

**Comment by dnsmichi** [comment]
Master breaks on my Macbook, PR works fine, thanks.

**Pull request merged**
