### PR TITLE
Allow to create API User w/ password

### LINKED ISSUE #8164: Can't create API user w/ password
```
root@icinga-master-1:~# curl -sSku root:4bef1a71e105776a https://127.0.0.1:5665/v1/objects/apiusers/global\?pretty=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{"zone":"global","password":"global"}}'
{
    "results": [
        {
            "code": 500.0,
            "errors": [
                "Error: Attribute is marked for internal use only and may not be set: password\n"
            ],
            "status": "Object could not be created."
        }
    ]
}root@icinga-master-1:~#
```

### PR DESCRIPTION
**Pull request by Yonas-net**
fixes #8164

### CODE REVIEW

**Comment by Yonas-net** [comment]
Testprotocol:

**Before**:
Command: ``curl -sSku root:icinga https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{ "zone":"master",  "password": "secret" }}'`` 

Output:
```
{
    "results": [
        {
            "code": 500.0,
            "errors": [
                "Error: Validation failed for object 'global' of type 'ApiUser'; Attribute 'zone': Object 'global' of type 'Zone' does not exist.\nLocation: in /icinga2/prefix/var/lib/icinga2/api/packages/_api/5985f3ee-5a10-4fdd-bc84-b0f1c52ff149/conf.d/apiusers/icinga.conf: 3:2-3:16"
            ],
            "status": "Object could not be created."
        }
    ]
}%  
```

**After**:
Command: ``curl -sSku root:icinga https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X PUT -H 'Accept: application/json' -d '{"attrs":{ "zone":"master",  "password": "secret" }}'`` 

**Result**:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}% 
```

After restarting icinga2, fetch the user with curl.

**Command**: ``curl -sSku root:af2c18268fe250b7 https://127.0.0.1:5665/v1/objects/apiusers/icinga\?pretty\=1 -X GET -H 'Accept: application/json' -d '{}' ``

**Result**: no password visible 
```
{
    "results": [
        {
            "attrs": {
                "__name": "icinga",
                "active": true,
                "client_cn": "",
                "ha_mode": 0.0,
                "name": "icinga",
                "original_attributes": null,
                "package": "_api",
                "paused": false,
                "permissions": null,
                "source_location": {
                    "first_column": 0.0,
                    "first_line": 1.0,
                    "last_column": 22.0,
                    "last_line": 1.0,
                    "path": "/../icinga2/prefix/var/lib/icinga2/api/packages/_api/c0d54f92-7f8b-4a57-aaa3-e601e18b9154/conf.d/apiusers/icinga.conf"
                },
                "templates": [
                    "icinga"
                ],
                "type": "ApiUser",
                "version": 1602267218.199853,
                "zone": "master"
            },
            "joins": {},
            "meta": {},
            "name": "icinga",
            "type": "ApiUser"
        }
    ]
}% 
```

**Comment by mcktr** [comment]
An API user with the permission `object/modify/apiuser` can now change the password from a more privileged user e.g. the root user, now the user gained full access. 

The following API users are given:

```
object ApiUser "root" {
  password = "icinga"
  permissions = [ "*" ]
}

object ApiUser "bob" {
  password = "secret"
  permissions = [ "status/query", "objects/modify/apiuser" ]
}
```
API query to update the password:
```
$ curl -sSku bob:secret https://172.17.0.2:5665/v1/objects/apiusers/root\?pretty\=1 -X POST -H 'Accept: application/json' -d '{"attrs":{ "password": "catdog" }}'
```

I think this shouldn't be possible.

Best regards
Michael

**Comment by Al2Klimov** [comment]
@mcktr Feel free to restrict the permission w/ a filter.

@Yonas-net Looks fine. This one doesn't occur anymore, right?

>                 "original_attributes": {
>                     "password": "secret"
>                 },

**Comment by Yonas-net** [comment]
> @Yonas-net Looks fine. This one doesn't occur anymore, right?

I have tested it several times and nothing came out.

**Review by Al2Klimov — APPROVED** [review]
Fine.

**Review by julianbrost — APPROVED** [review]

**Comment by julianbrost** [comment]
> An API user with the permission `object/modify/apiuser` can now change the password from a more privileged user e.g. the root user, now the user gained full access.

@mcktr The permission `object/modify/apiuser` allows you to update an API user without restrictions, which means that in this case, the escalation you described is already possible: the "restricted" user may also update its own `permissions` attribute to `["*"]`. So if this was a problem for you, you might want to check your setup.

**Pull request merged**
