### PR TITLE
RPM: Fix builds on Amazon Linux

### PR DESCRIPTION
**Pull request by dnsmichi**

### CODE REVIEW

**Comment by lazyfrosch** [comment]
https://github.com/icinga/icinga-packaging please too

**Comment by dnsmichi** [comment]
I have that in mind. I'll test the change tomorrow on CentOS before merging it.

**Comment by dnsmichi** [comment]
Reference: https://monitoring-portal.org/index.php?thread/40864-building-of-a-icinga2-agent-installation-on-aws-ami-2017-03-is-not-possible/&postID=250095#post250095

**Comment by lazyfrosch** [comment]
Push it to `rpm/snapshot` and it will be built tonight

**Comment by dnsmichi** [comment]
Tested on both, AMI and CentOS 7.

**Pull request merged**
