### PR TITLE
Add child_options to ScheduledDowntime

### PR DESCRIPTION
**Pull request by N-o-X**
refs #3935

I couldn't really find good names for those global variables:
- DowntimeNoChildren
- DowntimeTriggeredChildren
- DowntimeNonTriggeredChildren

@dnsmichi if you got some ideas, please go ahead :D

### CODE REVIEW

**Comment by dnsmichi** [comment]
How's that configuration value exposed via API? String or number? If it isn't a string, we need to document the integer values too.

**Comment by N-o-X** [comment]
The API returns `"child_options": "DowntimeNonTriggeredChildren"` so it should be fine.

**Comment by dnsmichi** [comment]
@lippserd the code contains backward compatibility with the REST API action `schedule-downtime` and numbers 0,1,2. We should adopt this for future versions of Icinga Web 2 into the specific string portions instead of numbers.

**Comment by dnsmichi** [comment]
Minor c&p error in the docs, will fix it when adding upgrading docs.

**Comment by dnsmichi** [comment]
I'm fine with the constants and their naming, those specific downtime variants are hard to understand for users anyways. They'll need to consult the documentation for such.

**Pull request merged**
