### PR TITLE
Fix file endings

### PR DESCRIPTION
**Pull request by Al2Klimov**
```bash
git ls-files -z \
	|grep -zEe '^lib/' \
	|grep -zEe '\.[ch]pp$' \
	|xargs -0 perl -p0i -e 's/\n*(?!(?:.|\n))/\n/'
```

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] #7798

**Comment by Al2Klimov** [comment]
## Test protocol

It compiles.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by julianbrost** [comment]
@Al2Klimov Since when are we merging changes without review?

**Comment by Al2Klimov** [comment]
This didn't actually _change_ anything (if you don't count whitespace).

But actual changes – of course not. 👍

**Comment by julianbrost** [comment]
I disagree. Merging an unapproved PR triggers a "what the hell is going on here" for me and forces me to review the PR immediately. So please don't do that.

Regarding the change: it doesn't hurt but it's also quite useless.

**Pull request merged**
