### PR TITLE
Main(): don't call Process::InitializeSpawnHelper()

### LINKED ISSUE #7614: Icinga2 creating defunct/Zombie processes on clients for checks
## Describe the bug

FYI:   Attempted to reach out to community on this issue:
[https://community.icinga.com/t/zombies-service-checks-are-becoming-defunct-on-client/2633/9](url)

Every 1 or 2 days we are seeing defunct/zombie processes show up on our Redhat clients

```
[user@client1 ~ 351]$ ps aux|grep defunct|grep -v grep
icinga   28352  0.0  0.0      0     0 ?        ZNs  Nov07   0:00 [check_vas_statu] <defunct>

[user@client2 ~ 200]$ ps aux|grep defunct|grep -v grep
icinga   26184  0.0  0.0      0     0 ?        ZNs  Nov07   0:00 [check_vas_statu] <defunct>
```

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. start icinga2 client
2. wait a day to 2, check for defunct processes (or I have a disk check for "Z" processes to monitor within icinga2
3. restart icinga2 client, defunct/zombies clear 
4. rinse/repeat

## Expected behavior

Should not have defunct/zombies

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):  **client=2.11.1-1  masters=2.11.1-1**
* Operating System and version: **Redhat v6.7/v7.6**
* Enabled features (`icinga2 feature list`): 
**clients=api mainlog
masters=api checker ido-mysql influxdb mainlog notification**
* Icinga Web 2 version and modules (System - About):  **Web=v2.7.3**
* Config validation (`icinga2 daemon -C`):

**CLIENT**

```
[user@client1 ~ 362]$ sudo icinga2 daemon -C
[2019-11-08 10:37:54 -0700] information/cli: Icinga application loader (version: 2.11.1-1)
[2019-11-08 10:37:54 -0700] information/cli: Loading configuration file(s).
[2019-11-08 10:37:54 -0700] information/ConfigItem: Committing config item(s).
[2019-11-08 10:37:54 -0700] information/ApiListener: My API identity: client1
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 1 FileLogger.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 33 HostGroups.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 4 Zones.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 3 Endpoints.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 16 UserGroups.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 1 ApiListener.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 239 CheckCommands.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 3 TimePeriods.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 32 Users.
[2019-11-08 10:37:54 -0700] information/ConfigItem: Instantiated 14 ServiceGroups.
[2019-11-08 10:37:54 -0700] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-11-08 10:37:54 -0700] information/cli: Finished validating the configuration file(s).
```

**MASTER**

```
[user@icinga01 global-templates 14953]$ sudo icinga2 daemon -C
[2019-11-08 10:37:01 -0700] information/cli: Icinga application loader (version: 2.11.1-1)
[2019-11-08 10:37:01 -0700] information/cli: Loading configuration file(s).
[2019-11-08 10:37:01 -0700] information/ConfigItem: Committing config item(s).
[2019-11-08 10:37:01 -0700] information/ApiListener: My API identity: icinga01
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 FileLogger.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 523 Dependencies.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 643 Notifications.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 33 HostGroups.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 42 Hosts.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 11 Downtimes.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 Comment.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 43 Zones.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 42 Endpoints.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 3 ApiUsers.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 16 UserGroups.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 ApiListener.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 239 CheckCommands.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 3 TimePeriods.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 32 Users.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 601 Services.
[2019-11-08 10:37:01 -0700] information/ConfigItem: Instantiated 14 ServiceGroups.
[2019-11-08 10:37:01 -0700] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-11-08 10:37:01 -0700] information/cli: Finished validating the configuration file(s).]
```

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**CLIENT1**

```
[user@client1 ~ 363]$ sudo icinga2 object list --type Endpoint
Object 'client1' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 7:1-7:28
  * __name = "client1"
  * host = ""
  * log_duration = 86400
  * name = "client1"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 7
    * last_column = 28
    * last_line = 7
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "client1" ]
    % = modified in '/etc/icinga2/zones.conf', lines 7:1-7:28
  * type = "Endpoint"
  * zone = ""

Object 'icinga01' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 11:1-11:27
  * __name = "icinga01"
  * host = ""
  * log_duration = 86400
  * name = "icinga01"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 11
    * last_column = 27
    * last_line = 11
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "icinga01" ]
    % = modified in '/etc/icinga2/zones.conf', lines 11:1-11:27
  * type = "Endpoint"
  * zone = ""

Object 'icinga02' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 14:1-14:27
  * __name = "icinga02"
  * host = ""
  * log_duration = 86400
  * name = "icinga02"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 14
    * last_column = 27
    * last_line = 14
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "icinga02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 14:1-14:27
  * type = "Endpoint"
  * zone = ""
```

```
[user@client1 ~ 364]$ sudo icinga2 object list --type Zone
Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 26:1-26:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 27:5-27:17
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 26
    * last_column = 30
    * last_line = 26
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 26:1-26:30
  * type = "Zone"
  * zone = ""

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 30:1-30:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 31:5-31:17
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 30
    * last_column = 29
    * last_line = 30
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 30:1-30:29
  * type = "Zone"
  * zone = ""

Object 'client1' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 21:1-21:24
  * __name = "client1"
  * endpoints = [ "client1" ]
    % = modified in '/etc/icinga2/zones.conf', lines 22:5-22:32
  * global = false
  * name = "client1"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 23:5-23:21
  * source_location
    * first_column = 1
    * first_line = 21
    * last_column = 24
    * last_line = 21
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "client1" ]
    % = modified in '/etc/icinga2/zones.conf', lines 21:1-21:24
  * type = "Zone"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 17:1-17:20
  * __name = "master"
  * endpoints = [ "icinga01", "icinga02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 18:5-18:44
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 17
    * last_column = 20
    * last_line = 17
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 17:1-17:20
  * type = "Zone"
  * zone = ""
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
... to avoid zombie processes after reload.

fixes #7614

### CODE REVIEW

**Comment by N-o-X** [comment]
This prevents zombie processes as intended, but still doesn't kill the running ones on reload. Is this really something we want?

**Comment by Al2Klimov** [comment]
It may be not what we want, but this PR is just about the zombies and it didn't introduce the fact that the processes aren't killed, right?

**Comment by fireheadman** [comment]
how does this issue prevent zombie processes from happening?    from what I am reading it is to address after a zombie has occurred.  just looking for clarification/understanding as my bug report was closed/merged into this one.

**Comment by fireheadman** [comment]
....Bueller?   .....Bueller?   ....Bueller?
[https://www.yourdictionary.com/bueller](https://www.yourdictionary.com/bueller )

**Comment by dnsmichi** [comment]
@fireheadman I kindly ask you not to bump issues this way. This is impolite and won't make developers reply anytime soon.

**Comment by fireheadman** [comment]
Sure no problem.    Just a lil American movie humor.   Wasn’t meant to offend.... guess you guys didn’t get it.  

So what’s a guy gotta do to get a response to a reasonable question I originally asked?

**Comment by fireheadman** [comment]
Unsure which BUG report to update.... so....

UPDATE:

Until the BUG is corrected, I created a workaround based on the event handler documentation.
I’m sure this may not be to everyone’s likings, but its working for what I need at the moment (feel free to tear it apart and use it as you see fit)

**Deployed the script in plugins dir (on each client)**

```
[user@client01 ]$ sudo cat /usr/lib64/nagios/plugins/restart_service

#!/bin/bash

while getopts "s:t:a:S:" opt; do
  case $opt in
    s)
      servicestate=$OPTARG
      ;;
    t)
      servicestatetype=$OPTARG
      ;;
    a)
      serviceattempt=$OPTARG
      ;;
    S)
      service=$OPTARG
      ;;
  esac
done

if ( [ $servicestate == "CRITICAL" ] && [ $servicestatetype == "HARD" ] ); then
    sudo /sbin/service icinga2 restart > /dev/null
fi
```

**Service definition to check zombies:**

```
apply Service "Zombie Procs" {
    import "service-check-alarm-settings"
    check_command = "procs"
    event_command = "restart_service"
    command_endpoint = host.vars.client_endpoint
    vars.grafana_graph_disable = true
    vars.procs_warning = 0
    vars.procs_critical = 1
    vars.procs_state = "Z"
    enable_notifications = false
    assign where host.address && host.vars.os == "linux"
}
```

**eventhandler.conf definition:**

```
object EventCommand "restart_service" {
    command = [ PluginDir + "/restart_service" ]
    arguments = {
        "-s" = "$service.state$"
        "-t" = "$service.state_type$"
        "-a" = "$service.check_attempt$"
        "-S" = "$restart_service$"
    }
    vars.restart_service = "$procs_commands$"
}
```

…I still see the warnings when there are 1 zombie running, but once it increments to “2”, they are zapped back to “0”. From what I am seeing, the BUG is triggered when I perform configuration reloads on the master nodes. If I do a restart (instead of a reload), I am not seeing the zombies being created.

**Comment by fireheadman** [comment]
@dnsmichi  @Al2Klimov 
...**this is a tad off topic**, but I just watched your 1hr 45min video (youtube) on Icinga Insights this evening.    That video was very informative and I wanted to thank you for posting it.    After watching it I gotta say I have a different perspective on Icinga and knowing how much you guys have gone through and what you do for the community.

So, I would like to apologize for the previous nag "bump" in trying to get a response on this issue.... You guys are a small, but very amazing team and I understand more now (than before) the challenges and tasks you endure everyday.    So instead rubbing the developers the wrong way I would like to help where I can.

**TO get back on track...**. You mentioned the fix is in the snapshot builds, so let me see what I can do to help test this issue out and report back.    I need to perform a backup and checkpoint in my environment this week in order to deploy the snapshot.

....and thanks!

**Comment by dnsmichi** [comment]
Thanks for the kind words. It is always good to see both sides, especially if you're waiting for responses and it feel like no-one is responsible. 

In terms of testing, maybe you'll have the chance to go with the [Vagrant boxes](https://github.com/Icinga/icinga-vagrant) as well. They already incorporate the snapshot packages by default, just need your configuration then.

**Comment by fireheadman** [comment]
Apologies on getting to this now, the thanksgiving holidays in US prevented work (moratorium).

I have prepped my icinga masters for the "snapshot" pkg update to test the fix, however I am not see anything to update in the repo.   We use RedHat Satellite for our repos, so I have sync'd all of content from [https://packages.icinga.com/epel/7/snapshot/](url)     

It appears I am running a version of icinga2 greater than the snapshots?   ...so yum will not update anything.

```
[user@icinga01 ~ ]$ sudo yum --showduplicates list icinga2-2.11.*
Loaded plugins: product-id, rhnplugin, search-disabled-repos
This system is receiving updates from RHN Classic or Red Hat Satellite.
Installed Packages
icinga2.x86_64                      2.11.1-1.el7.icinga                                                     @icinga2-rhel7-2019-10-22
Available Packages
icinga2.x86_64                      2.11.0-1.el7.icinga                                                     icinga2-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.2.g8b877e2-0.20190726.1551.el7.icinga                        icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.4.gf034829-0.20190729.1720.el7.icinga                        icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.8.ga9d5fe4-0.20190730.1548.el7.icinga                        icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.51.gf9812ee-0.20190808.0848.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.56.gfcca964-0.20190813.1447.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.63.g43ea6fb-0.20190814.1430.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.74.g8c739fe-0.20190819.1351.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.83.ge2f461c-0.20190827.1200.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.90.g3f509c4-0.20190827.1720.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.98.gbea8527-0.20190828.1720.el7.icinga                       icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.104.g426c26f-0.20190830.1720.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.110.g2cf38ba-0.20190902.1733.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.117.g897b81d-0.20190906.1725.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.133.g195f22f-0.20190909.1720.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.139.g6a059e9-0.20190912.1720.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.143.g358d951-0.20190913.1720.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.rc1.162.g8c1f263-0.20190918.1310.el7.icinga                      icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.11.gcd71b97-0.20190923.1721.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.19.gf0fcfdf-0.20190925.1726.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.21.g43f7d35-0.20190927.1721.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.23.g0629617-0.20191008.1724.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.29.g3e6fc9b-0.20191018.1721.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.53.g50dd839-0.20191024.1721.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.58.g0a2aee7-0.20191025.1810.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.62.g7e369c0-0.20191101.1821.el7.icinga                           icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.286.g3059755-0.20191104.1824.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.288.g280dbf6-0.20191107.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.291.g1e64b71-0.20191108.1822.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.293.g7fb5921-0.20191111.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.295.gfa892b6-0.20191112.1826.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.297.g5caf4e7-0.20191113.1836.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.304.g09892a9-0.20191114.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.330.g1a503b5-0.20191115.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.330.g1a503b5-0.20191119.1313.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.330.g1a503b5-0.20191119.1822.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.330.g1a503b5-0.20191120.0815.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.332.gc231123-0.20191120.1822.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.334.g7849da0-0.20191121.1820.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.336.g287e4c3-0.20191122.1823.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.350.ged1cede-0.20191126.1823.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.359.gce4409d-0.20191127.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.373.g5af93f1-0.20191202.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.0.399.g92e51a3-0.20191204.1821.el7.icinga                          icinga2-snapshot-rhel7-2019-10-22
icinga2.x86_64                      2.11.1-1.el7.icinga                                                     icinga2-rhel7-2019-10-22
```

**Comment by fireheadman** [comment]
checking in on this to see if there are any new solutions or suggestions to try?

**Comment by fireheadman** [comment]
Quick update:    
I'm running this version on both master and client (updated this the past week)
And still seeing this issue.
Was wondering if the fixes were made available to this version?

image

**Comment by N-o-X** [comment]
Hi @fireheadman, this PR is assigned to milestone 2.12, so it's not in any released version yet.

**Comment by Obihoernchen** [comment]
Have the same issues as described in #7614 on RHEL7.6 ppc64le hosts with Icinga 2.11.3 as well.
On some hosts it's only 1 or 2 processes after a few hours, but on 3 nodes it was > 1000 and Icinga couldn't spawn new processes anymore because of ulimits. I will monitor and might compile a new RPM with this fix included to see if it improves the situation.

**Pull request merged**
