### PR TITLE
Fix crash on API queries with Fedora 28 hardening and GCC 8

### LINKED ISSUE #6533: Icinga2 crashes after using some api-commands on Fedora 28
I am experiencing crashes while using the icinga-api. At first I notices it, after trying to install the icinga-director, the director-kickstarter got an "empty result", because icinga crashed.
But it's not necessary to install the director, the problem occurs much earlier...

## Current Behavior
Some curl-commands let icinga crashing immediately.  For example:
```
CRASH: curl -k  -u USER:PASSWORD 'https://icinga.fqdn:5665/v1/status'
CRASH: curl -k  -u USER:PASSWORD 'https://icinga.fqdn:5665/v1/objects/hosts'
```
This commands are working:
```
OK:  curl -k  -u root:PASSWORD 'https://icinga.fqdn:5665/v1'
OK:  curl -k  -u root:PASSWORD 'https://icinga.fqdn:5665/v1/objects/hosts/icinga.fqdn'
```

## Steps to Reproduce (for bugs)
1. dnf install icinga2
2. icinga2 api setup
3. service icinga2 restart
4.  curl -k  -u USER:PASSWORD 'https://icinga.fqdn:5665/v1/status'

## Your Environment
* icinga2 --version:

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Fedora
  Platform version: 28 (Twenty Eight)
  Kernel: Linux
  Kernel version: 4.17.11-200.fc28.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.1.1
  Build host: unknown
```

* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker debuglog mainlog notification
```

* Config validation (`icinga2 daemon -C`):
```
[2018-08-08 15:34:30 +0200] information/cli: Icinga application loader (version: r2.9.1-1)
[2018-08-08 15:34:30 +0200] information/cli: Loading configuration file(s).
[2018-08-08 15:34:30 +0200] information/ConfigItem: Committing config item(s).
[2018-08-08 15:34:30 +0200] information/ApiListener: My API identity: icinga.fqdn
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 11 Services.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 2 FileLoggers.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 Host.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 3 Zones.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 ApiUser.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 213 CheckCommands.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2018-08-08 15:34:30 +0200] information/ConfigItem: Instantiated 1 User.
[2018-08-08 15:34:30 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-08-08 15:34:30 +0200] information/cli: Finished validating the configuration file(s).
```

Debug-Error-Message:
```
[2018-08-08 15:07:05 +0200] information/ApiListener: New client connection from [10.11.12.13]:43428 (no client certificate)
[2018-08-08 15:07:05 +0200] notice/ApiListener: New HTTP client
[2018-08-08 15:07:05 +0200] debug/HttpRequest: line: GET /v1/status HTTP/1.1, tokens: 3
[2018-08-08 15:07:05 +0200] information/HttpServerConnection: Request: GET /v1/status (from [10.11.12.13]:43428, user: root)
[2018-08-08 15:07:05 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
[New Thread 0x7fffb4ff9700 (LWP 22238)]
/usr/include/c++/8/bits/unique_ptr.h:328: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = icinga::Expression; _Dp = std::default_delete<icinga::Expression>; typename std::add_lvalue_reference<_Tp>::type = icinga::Expression&]: Assertion 'get() != pointer()' failed.
[Thread 0x7fffd9ffb700 (LWP 22229) exited]
Thread 35 "icinga2" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb4ff9700 (LWP 22238)]
0x00007ffff4f05feb in raise () from /lib64/libc.so.6
```

debug.log from daemon-start till crash:
```
[2018-08-08 14:30:22 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'ApiListener, RelayQueue'
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'friday' => 1533852000 -> 1533938400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'monday' => 1534111200 -> 1534197600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'saturday' => 1533938400 -> 1534024800, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'sunday' => 1534024800 -> 1534111200, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'thursday' => 1533765600 -> 1533852000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'tuesday' => 1534197600 -> 1534284000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'wednesday' => 1533679200 -> 1533765600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'friday' => 1533852000 -> 1533938400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'monday' => 1534111200 -> 1534197600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'saturday' => 1533938400 -> 1534024800, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'sunday' => 1534024800 -> 1534111200, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'thursday' => 1533765600 -> 1533852000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'tuesday' => 1534197600 -> 1534284000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'wednesday' => 1534284000 -> 1534370400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: Legacy timeperiod update returned 2 segments.
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Removing segment 'Wed Aug  8 14:30:22 2018' <-> 'Thu Aug  9 14:30:22 2018' from TimePeriod '24x7'
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Adding segment 'Wed Aug  8 00:00:00 2018' <-> 'Thu Aug  9 00:00:00 2018' to TimePeriod '24x7'
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Adding segment 'Thu Aug  9 00:00:00 2018' <-> 'Fri Aug 10 00:00:00 2018' to TimePeriod '24x7'
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'friday' => 1533852000 -> 1533938400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'monday' => 1534111200 -> 1534197600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'thursday' => 1533765600 -> 1533852000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'tuesday' => 1534197600 -> 1534284000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'wednesday' => 1533679200 -> 1533765600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'friday' => 1533852000 -> 1533938400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'monday' => 1534111200 -> 1534197600, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'thursday' => 1533765600 -> 1533852000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'tuesday' => 1534197600 -> 1534284000, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: ParseTimeRange: 'wednesday' => 1534284000 -> 1534370400, stride: 1
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: Legacy timeperiod update returned 2 segments.
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Removing segment 'Wed Aug  8 14:30:22 2018' <-> 'Thu Aug  9 14:30:22 2018' from TimePeriod '9to5'
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Adding segment 'Wed Aug  8 09:00:00 2018' <-> 'Wed Aug  8 17:00:00 2018' to TimePeriod '9to5'
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Adding segment 'Thu Aug  9 09:00:00 2018' <-> 'Thu Aug  9 17:00:00 2018' to TimePeriod '9to5'
[2018-08-08 14:30:22 +0200] debug/LegacyTimePeriod: Legacy timeperiod update returned 0 segments.
[2018-08-08 14:30:22 +0200] debug/TimePeriod: Removing segment 'Wed Aug  8 14:30:22 2018' <-> 'Thu Aug  9 14:30:22 2018' from TimePeriod 'never'
[2018-08-08 14:30:22 +0200] notice/ApiListener: Relaying 'config::UpdateObject' message
[2018-08-08 14:30:22 +0200] information/ApiListener: 'api' started.
[2018-08-08 14:30:22 +0200] information/ApiListener: Adding new listener on port '5665'
[2018-08-08 14:30:22 +0200] information/CheckerComponent: 'checker' started.
[2018-08-08 14:30:22 +0200] information/NotificationComponent: 'notification' started.
[2018-08-08 14:30:22 +0200] debug/ApiListener: Not connecting to Endpoint 'icinga.fqdn' because that's us.
[2018-08-08 14:30:22 +0200] information/ConfigItem: Activated all objects.
[2018-08-08 14:30:22 +0200] notice/ApiListener: Current zone master: icinga.fqdn
[2018-08-08 14:30:22 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonCommand::Run'
[2018-08-08 14:30:22 +0200] notice/ApiListener: Connected endpoints: 
[2018-08-08 14:30:22 +0200] notice/ApiListener: Removing old log file: /var/lib/icinga2/api/log/1533731058
[2018-08-08 14:30:22 +0200] debug/IcingaApplication: In IcingaApplication::Main()
[2018-08-08 14:30:23 +0200] notice/ThreadPool: Pool #1: Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.00304747%
[2018-08-08 14:30:27 +0200] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 12; Checks/s: 0
[2018-08-08 14:30:32 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 0.216667/s (13/min 13/5min 13/15min);
[2018-08-08 14:30:32 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-08-08 14:30:32 +0200] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 12; Checks/s: 0
[2018-08-08 14:30:34 +0200] debug/CheckerComponent: Scheduling info for checkable 'icinga.fqdn!disk' (2018-08-08 14:30:34 +0200): Object 'icinga.fqdn!disk', Next Check: 2018-08-08 14:30:34 +0200(1.53373e+09).
[2018-08-08 14:30:34 +0200] debug/CheckerComponent: Executing check for 'icinga.fqdn!disk'
[2018-08-08 14:30:34 +0200] debug/Checkable: Update checkable 'icinga.fqdn!disk' with check interval '60' from last check time at 2018-08-08 14:25:26 +0200 (1.53373e+09) to next check time at 2018-08-08 14:31:32 +0200(1.53373e+09).
[2018-08-08 14:30:34 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:34 +0200] notice/Process: Running command '/usr/lib64/nagios/plugins/check_disk' '-c' '10%' '-w' '20%' '-X' 'none' '-X' 'tmpfs' '-X' 'sysfs' '-X' 'proc' '-X' 'configfs' '-X' 'devtmpfs' '-X' 'devfs' '-X' 'mtmfs' '-X' 'tracefs' '-X' 'cgroup' '-X' 'fuse.gvfsd-fuse' '-X' 'fuse.gvfs-fuse-daemon' '-X' 'fdescfs' '-X' 'overlay' '-X' 'nsfs' '-m': PID 20624
[2018-08-08 14:30:34 +0200] debug/CheckerComponent: Check finished for object 'icinga.fqdn!disk'
[2018-08-08 14:30:34 +0200] notice/Process: PID 20624 ('/usr/lib64/nagios/plugins/check_disk' '-c' '10%' '-w' '20%' '-X' 'none' '-X' 'tmpfs' '-X' 'sysfs' '-X' 'proc' '-X' 'configfs' '-X' 'devtmpfs' '-X' 'devfs' '-X' 'mtmfs' '-X' 'tracefs' '-X' 'cgroup' '-X' 'fuse.gvfsd-fuse' '-X' 'fuse.gvfs-fuse-daemon' '-X' 'fdescfs' '-X' 'overlay' '-X' 'nsfs' '-m') terminated with exit code 0
[2018-08-08 14:30:34 +0200] debug/Checkable: Update checkable 'icinga.fqdn!disk' with check interval '60' from last check time at 2018-08-08 14:30:34 +0200 (1.53373e+09) to next check time at 2018-08-08 14:31:32 +0200(1.53373e+09).
[2018-08-08 14:30:34 +0200] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-08-08 14:30:34 +0200] debug/DbEvents: add checkable check history for 'icinga.fqdn!disk'
[2018-08-08 14:30:34 +0200] notice/ApiListener: Relaying 'event::CheckResult' message
[2018-08-08 14:30:37 +0200] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 12; Checks/s: 0.0166667
[2018-08-08 14:30:38 +0200] notice/ThreadPool: Pool #1: Pending tasks: 0; Average latency: 0ms; Threads: 4; Pool utilization: 0.0418877%
[2018-08-08 14:30:38 +0200] information/ApiListener: New client connection from [10.11.12.13]:43358 (no client certificate)
[2018-08-08 14:30:38 +0200] notice/ApiListener: New HTTP client
[2018-08-08 14:30:38 +0200] debug/HttpRequest: line: GET /v1/status HTTP/1.1, tokens: 3
[2018-08-08 14:30:38 +0200] information/HttpServerConnection: Request: GET /v1/status (from [10.11.12.13]:43358, user: root)
[2018-08-08 14:30:38 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
[2018-08-08 14:30:38 +0200] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1533731438.652956'
```

### PR DESCRIPTION
**Pull request by dnsmichi**
The actual fix is to handle nullptr references differently
for an empty filter expression. The other changes include
oob checks not necesarily involved.

fixes #6533

### CODE REVIEW

**Comment by dnsmichi** [comment]
Tested this on macOS so it doesn't break anything else.

**Comment by dnsmichi** [comment]
This affects any request handler in the API, so I've tested other URL endpoints with and without the filter parameter too. Please do the same when reviewing this PR.

**Comment by lazyfrosch** [comment]
How about a Unit test for FilterUtility? Should not be complicated since it is all static

**Comment by lazyfrosch** [comment]
Started some test package builds, but that should be fine either way:

* https://build.icinga.com/job/icinga2-dev/job/rpm-fedora-28-1binary/1/
* https://build.icinga.com/job/icinga2-dev/job/rpm-centos-6-1binary/3/
* https://build.icinga.com/job/icinga2-dev/job/deb-debian-jessie-1binary/6/

**Pull request merged**
