### PR TITLE
Use new I/O engine in CLI commands and features

### PR DESCRIPTION
**Pull request by Al2Klimov**
# CLI Commands
- [x] node wizard/setup
- [ ] debug console
- [ ] check_nscp_api

# Features

- [x] InfluxDB
- [ ] Elasticsearch

# Cleanup

- Drop ApiClient and HttpClientConnection classes

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Substitutes #6990. Waiting until #7005 purrs like a cat.

**Comment by Al2Klimov** [comment]
... and has been merged.

**Comment by dnsmichi** [comment]
The first part of the debug console works, the auto complete script needs rework. The 2 callbacks with exception looks are horrible to understand and refactor into readable code.

Screen Shot 2019-04-05 at 16 03 18

**Comment by dnsmichi** [comment]
Will be split into separate PRs.

**Comment by dnsmichi** [comment]
Closing in favour of the split PRs.

**Pull request closed without merging**
