### PR TITLE
Windows: bump OpenSSL v1.1 (soon EOL) -> v3.0

### LINKED ISSUE #9786: [reminder] Bump OpenSSL to v1.1.1${X}
There seems to be an upcoming OpenSSL version on the horizon, see their changelog.

# To do

* Wait as long as possible, but don’t delay v2.14 any more than needed
* Bump it!

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #9786

## TODO

* [x] GHA ok
* [ ] dev VM ok
* [x] build server ok

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Let's not _merge_ this yet, see

* #9786

**Comment by julianbrost** [comment]
What exactly in there would prevent this from being merged?

I'd rather not merge it due to the unchecked todo item. What exactly do you mean by dev VM? Instructions on setting up the VM in the docs? The script we have to install dependencies on Windows? Or something totally different?

**Comment by Al2Klimov** [comment]
Sure: https://git.icinga.com/packaging/windows-icinga2/-/pipelines/30258

**Comment by Al2Klimov** [comment]
I'm sorry. I've completely overseen this comment:

> What exactly in there would prevent this from being merged?

There is an upcoming 3.0.10. I want IT, not 3.0.9.

> I'd rather not merge it due to the unchecked todo item. What exactly do you mean by dev VM? Instructions on setting up the VM in the docs? The script we have to install dependencies on Windows? Or something totally different?

I meant whether it builds on my dev VM. But my dev VM doesn’t matter.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
