### PR TITLE
IDO: update program status on stop

### LINKED ISSUE #8727: IDO `programstatus` table not updated when Icinga 2 is stopped
## Describe the bug

When I stop Icinga 2 gracefully, Icinga Web 2 still shows that it's running.

## To Reproduce

1. Stop Icinga 2 gracefully
2. See that Icinga Web 2 still shows something like this: `icinga2_mysql has been up and running with PID 70 for 30m 20s`

## Expected behavior

Icinga Web 2 should be able to know that Icinga 2 isn't running anymore.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): master
* Operating System and version: https://hub.docker.com/r/icinga/icinga2

## Additional context

The IDO `programstatus` table doesn't get updated once Icinga 2 stops. I'd expect the columns `is_currently_running`, `program_end_time` and `process_id` to change if so.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #8727

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
*************************** 1. row ***************************
is_currently_running: 1
    program_end_time: NULL
          process_id: 88545
1 row in set (0.007 sec)
```

```
-[ RECORD 1 ]--------+------
is_currently_running | 1
program_end_time     |
process_id           | 92072
```

## After

```
*************************** 1. row ***************************
is_currently_running: 0
    program_end_time: 2021-04-20 17:31:51
          process_id: NULL
1 row in set (0.004 sec)
```

```
-[ RECORD 1 ]--------+--------------------
is_currently_running | 0
program_end_time     | 2021-04-20 17:38:07
process_id           |
```

**Comment by julianbrost** [comment]
If I understand correctly, 306a0f476c06d174f468ac93ad716bfd75c89f40 changes the behavior in a way that if a field is set to `ValueEmpty`, it will now be set to NULL instead of not being updated. Have you verified that there's no caller that relies on the old behavior?

Regarding 3d8586ccec4b32fe415c2c32ad881d78d0e1aef2: Have you considered adding some kind of "execute even if paused" flag instead? `GetPauseCalled()` looks more like an implementation detail of `ConfigItem` to me, than something other classes should rely on.

**Comment by Al2Klimov** [comment]
1. All occurrences of `Empty` in `lib/db_ido*/` seem to be desired NULLs.
2. That’s not my intention. Id like to do that only _while pausing_.

**Comment by julianbrost** [comment]
I still find the use of `GetPauseCalled()` pretty confusing and think that it doesn't help with the understandability of the code. What do you think of just adding some kind of "queries suspended" flag, then it would be clear that queries are running until they are suspended when `Pause()` is done and sets that flag.

**Comment by Al2Klimov** [comment]
The same way you could read out the ticket salt via API and compute the ticket by yourself instead of using the API for the latter.

This method seems to have exactly the purpose I'm using it for.

**Review by N-o-X — APPROVED** [review]
I think it's perfectly fine to use `GetPauseCalled()` this way. LGTM 👍 

### Tests

Script:
```
LAST=0
while true; do
        NOW=$(mysql icinga -e "select status_update_time, process_id, is_currently_running, program_end_time from icinga_programstatus;";)
        if [[ "$NOW" != "$LAST" ]]; then
                echo $(date): $NOW
                LAST=$NOW
        fi
        sleep 0.5;
done
```

Before:
```
Tue Jul 6 17:57:34 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:57:33 1405 1 NULL
Tue Jul 6 17:57:44 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:57:43 1405 1 NULL
Tue Jul 6 17:57:54 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:57:53 1405 1 NULL
# Restarted Icinga
# -> no change in DB
Tue Jul 6 17:58:56 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:58:56 1958 1 NULL
Tue Jul 6 17:59:06 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:59:06 1958 1 NULL
Tue Jul 6 17:59:16 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:59:16 1958 1 NULL
# Stopped Icinga
# -> no change in DB
```

After:
```
Tue Jul 6 17:52:12 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:52:10 98614 1 NULL
Tue Jul 6 17:52:21 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:52:20 98614 1 NULL
Tue Jul 6 17:52:31 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:52:30 98614 1 NULL
# Restarted Icinga
Tue Jul 6 17:52:32 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:52:30 NULL 0 2021-07-06 17:52:32
Tue Jul 6 17:53:20 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:53:19 99578 1 NULL
Tue Jul 6 17:53:30 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:53:29 99578 1 NULL
Tue Jul 6 17:53:40 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:53:39 99578 1 NULL
# Stopped Icinga
Tue Jul 6 17:53:41 CEST 2021: status_update_time process_id is_currently_running program_end_time 2021-07-06 17:53:39 NULL 0 2021-07-06 17:53:41
```

**Pull request merged**
