### PR TITLE
Icinga DB: make icinga:history:stream:*#event_id deterministic

### PR DESCRIPTION
**Pull request by Al2Klimov**
... i.e. UUID -> SHA1(env, eventType, x...) given that SHA1(env, x...) = type-specific ID.
    Rationale: allow both masters to write the same history concurrently (while not
    in split-brain), so that REPLACE INTO deduplicates the same events written twice.

    * ack: SHA1(env, "ack_set"|"ack_clear", checkable.name, setTime)
    * comment: SHA1(env, "comment_add"|"comment_remove", comment.name)
    * downtime: SHA1(env, "downtime_start"|"downtime_end", downtime.name)
    * flapping: SHA1(env, "flapping_start"|"flapping_end", checkable.name, startTime)
    * notification: SHA1(env, "notification", notification.name, notificationType, sendTime)
    * state: SHA1(env, "state_change", checkable.name, changeTime)

PR with corresponding changes to Icinga DB: https://github.com/Icinga/icingadb/pull/392

### CODE REVIEW

**Comment by eaeye** [comment]
@Al2Klimov `SHA1` is considered unsafe because of collision attacks. 

* https://www.computerworld.com/article/3173616/the-sha1-hash-function-is-now-completely-unsafe.html
* https://en.wikipedia.org/wiki/SHA-1#Attacks

**Comment by Al2Klimov** [comment]
And how do they apply to our specific use case?

**Comment by Al2Klimov** [comment]
... or by just merging this (once https://github.com/Icinga/icinga2/pull/9029#issuecomment-938920849 done) which in contrast won't uselessly run yet another GHA.

**Review by julianbrost — CHANGES_REQUESTED** [review]
In the PR description, the hashed data for notification seems to miss the notification type. Also please double-check that the remaining information is also up-to-date.

Apart from that, looks fine to me, so I think we can merge this soon, so please also set the Redis schema version to 2.

**Comment by Al2Klimov** [comment]
> double-check that the remaining information is also up-to-date

Noo.. I'm too talented on overseeing 🐘🐘 for this.

**Comment by julianbrost** [comment]
Sorry, that was the wrong terminal to push from, I'll push back the previous version.

**Comment by julianbrost** [comment]
@lippserd By the way, I requested your review as you still showed as "changes requested". Please state if you still want to perform further review on this or if I should just merge it when I'm happy with it.

**Review by lippserd — APPROVED** [review]

**Comment by lippserd** [comment]
> @lippserd By the way, I requested your review as you still showed as "changes requested". Please state if you still want to perform further review on this or if I should just merge it when I'm happy with it.

Merge it when you're happy with it.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
