### PR TITLE
[WIP] Doc: add dependencies matrix

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Note: The "Dependencies matrix" table isn't complete, yet. I'll need some help from @lazyfrosch to setup the complete info sources for the missing parts.

**Comment by lazyfrosch** [comment]
We should move that kind of information to a central place.

I had that listed on [packages.icinga.com](https://github.com/Icinga/packages.icinga.com/commit/6cac313cbc3104b2775c3920fc998f22e219bad0#diff-04c6e90faac2675aa89e2176d2eec7d8) for a while. The general information is now on the website.

Can we put this to https://github.com/Icinga/icinga-packaging, and later also include other packages for products we  are shipping? E.g. PHP for Icinga Web 2 again.

**Comment by Al2Klimov** [comment]
The "OS EOL matrix" will make cleaning up both the *Dependencies matrix* and the [support matrix](https://icinga.com/support/details/) a lot easier. Unfortunately Fedora's EOL dates are quite nothing-saying, but IMO that doesn't matter as they ship the latest bleeding edge hipster stuff anyway.

**Comment by Al2Klimov** [comment]
@lazyfrosch Please ask @dnsmichi. (https://github.com/Icinga/icinga2/issues/6933#issuecomment-461443341)

**Comment by lazyfrosch** [comment]
Yes, EOL information is not project relevant at least. Package versions maybe, but please do so in [icinga-packaging](https://github.com/Icinga/icinga-packaging).

Please:
* add under docs an `icinga2.md`
* Put EOL information into the README

I'll incorporate parts of the original matrix into this.

**Comment by dnsmichi** [comment]
I'm fine with a dependency matrix kept inside the development docs, at the minimum level of update maintenance (once or twice a year). We shouldn't document OS EOL dates, that is something we keep track of ourselves and can create issues for package/infra updates on-demand. Keeping them documented requires one to take care - from my experience, those files run stale after some time.

**Comment by Al2Klimov** [comment]
Stalled until the linked PR has been merged or closed.

**Comment by lazyfrosch** [comment]
Documented in https://github.com/Icinga/icinga-packaging/pull/129

**Pull request closed without merging**
