### PR TITLE
DB IDO: Don't enqueue queries when the feature is paused (HA)

### LINKED ISSUE #5876: IDO Work queue on the inactive node growing when switching connection between redundant master servers
When the IDO connection switches between two Icinga 2 servers in a redundant cluster (e.g. after the master currently running the IDO database connection reboots), in some cases the other server does not properly yield the connection. This results in error messages in the log, and potentially to data loss. 

## Steps to reproduce

The setup is pretty classic: Two master servers running Icinga 2 (2.8.0, but the problem also occurs with older versions), IDO on PostgreSQL 9.6 (in a HA setup, but that should not be the cause of the problem):

```
library "db_ido_pgsql"

object IdoPgsqlConnection "ido-pgsql" {
    user = "icingaido"
    password = "xxxxxxx"
    host = "192.168.106.50"
    database = "icingaido"
}
```

Nothing fancy here. 

Now stop the icinga2 service on the node currently holding the IDO connection and the connection is taken over by the other node after about one minute. No problems. 

After bringing up the primary node, it takes back control of the IDO service:

```
[2017-12-16 21:23:12 +0000] information/DbConnection: 'ido-pgsql' started.
...
[2017-12-16 21:23:14 +0000] information/DbConnection: Resuming IDO connection: ido-pgsql
[2017-12-16 21:23:14 +0000] information/IdoPgsqlConnection: 'ido-pgsql' resumed.
...
[2017-12-16 21:23:18 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 0, rate: 0.2/s (12/min 12/5min 12/15min);
```

No problems here as well. But the picture is different on the secondary node that formerly had the connection to the IDO database:

```
[2017-12-16 21:23:14 +0000] information/IdoPgsqlConnection: 'ido-pgsql' paused.
[2017-12-16 21:23:14 +0000] information/DbConnection: Pausing IDO connection: ido-pgsql
[2017-12-16 21:23:16 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 122, rate: 12.0833/s (725/min 3421/5min 9032/15min); empty in 20 seconds
[2017-12-16 21:23:22 +0000] information/IdoPgsqlConnection: pgSQL IDO instance id: 1 (schema version: '1.14.3')
[2017-12-16 21:23:22 +0000] information/IdoPgsqlConnection: Finished reconnecting to PostgreSQL IDO database in 0.445331 second(s).
[2017-12-16 21:24:06 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 18, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 9 seconds
[2017-12-16 21:24:16 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 401, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 10 seconds
[2017-12-16 21:24:26 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 552, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 36 seconds
[2017-12-16 21:24:36 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 594, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 2 minutes and 21 seconds
[2017-12-16 21:24:46 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 699, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 1 minute and 6 seconds
...
[2017-12-16 21:41:26 +0000] information/WorkQueue: #7 (IdoPgsqlConnection, ido-pgsql) items: 10757, rate: 4.51667/s (271/min 2816/5min 9303/15min); empty in 21 minutes and 35 seconds
[2017-12-16 21:41:33 +0000] critical/IdoPgsqlConnection: Error "SSL SYSCALL error: Connection timed out
" when executing query "COMMIT"
[2017-12-16 21:41:33 +0000] warning/IdoPgsqlConnection: Exception during database operation: Verify that your database is operational!
```

After correctly detecting that the other node has come back and pausing the connection to the database, the WorkQueue still grows longer and does not get emptied for more than 20 minutes, until finally there is a timeout and the connection drops. Afterwards, all is well again and the node continues to run normally. 

## Expected Behavior

After the IDO connection is paused on the secondary node, it should no longer put requests into the IDO work queue as the IDO connection is paused.

## Current Behavior

The IDO work queue on the node with the paused IDO connection grows longer until a timeout on the database occurs. I can't say at this point whether data loss occurs or whether the data the secondary node tries to write have already been written by the primary node, but the state and history looks fine at first glance. 

## Your Environment
* Icinga 2 version 2.8.0
* CentOS 7.4
* Icinga Web 2 version 2.4.2

```
object Zone "global" {
  global = true
}

object Endpoint "master1.example.com" {
    host = "master1.example.com"
}
object Endpoint "master2.example.com" {
    host = "master2.example.com"
}

object Zone "master" {
    endpoints = [ "master1.example.com", "master2.example.com" ]
}
```

### PR DESCRIPTION
**Pull request by dnsmichi**
fixes #5876
refs #6739

### CODE REVIEW

**Comment by Mikesch-mp** [comment]
What happens to the queue when it gets paused? will it be synced to other master or waits until it is not paused anymore?

**Comment by dnsmichi** [comment]
Such queues cannot be synced, it stops when the feature is paused. This already is the case now, only the enqueues were wrong.

**Comment by Mikesch-mp** [comment]
So all the data is lost?

**Comment by dnsmichi** [comment]
There always is an overlap when one nodes decides to take over, causing the other one to pause. There's no data loss in between, and the stream from both instances is the same.

**Pull request merged**
