### PR TITLE
ApiListener#max_anonymous_clients: default to amount of endpoints x 2

### PR DESCRIPTION
**Pull request by Al2Klimov**
Origin: #8444

### CODE REVIEW

**Review by N-o-X — APPROVED** [review]

**Review by julianbrost — COMMENTED** [review]
Should this change also be reflected in the docs? Currently there is no default value documented for `max_anonymous_clients`. What is the old behavior? Unlimited?

Also what happens if endpoints are created using the API (not using packages)?

In general, I see that we might want to have a sane default for this option if it is indeed unlimited so far. But do we really want to change this in the support branches? I'd rather prefer a fix for the too many open files issue closer to where these connections are actually opened.

**Comment by Al2Klimov** [comment]
1. Good point.
2. Won't work.
3. @lippserd Feel free to reject this if just #8471 is fine.

**Comment by julianbrost** [comment]
refs #8478

**Comment by julianbrost** [comment]
Superseded by #8482 for support/2.11, this is more like an enhancement for new major versions.

**Pull request closed without merging**
