### PR TITLE
Icinga DB: HDEL also icinga:checksum:*:state, not only icinga:*:state

### PR DESCRIPTION
**Pull request by Al2Klimov**
... as they belong together.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
1626956715.971981 [0 127.0.0.1:61562] "HDEL" "icinga:host" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
1626956715.972031 [0 127.0.0.1:61562] "XADD" "icinga:runtime" "MAXLEN" "~" "1000000" "*" "redis_key" "icinga:host" "id" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb" "runtime_type" "delete"
1626956715.972104 [0 127.0.0.1:61562] "HDEL" "icinga:host:state" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
1626956715.972140 [0 127.0.0.1:61562] "ZREM" "icinga:nextupdate:host" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
```

## After

```
1626956818.377510 [0 127.0.0.1:61599] "HDEL" "icinga:host" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
1626956818.377623 [0 127.0.0.1:61599] "XADD" "icinga:runtime" "MAXLEN" "~" "1000000" "*" "redis_key" "icinga:host" "id" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb" "runtime_type" "delete"
1626956818.377680 [0 127.0.0.1:61599] "HDEL" "icinga:host:state" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
1626956818.377692 [0 127.0.0.1:61599] "HDEL" "icinga:checksum:host:state" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
1626956818.377703 [0 127.0.0.1:61599] "ZREM" "icinga:nextupdate:host" "f1ab6f1fd99deed97a1408ed2ce7618b45713acb"
```

**Comment by Al2Klimov** [comment]
## Blocked by

* #8917

**Comment by Al2Klimov** [comment]
## Will conflict after

* #8915

**Comment by julianbrost** [comment]
Reviewing under the assumption that the draft state is now obsolete given that all references PRs are merged.

Only new commit is fcda3a7283786588c899f1633bb941c2e8f0de66 (8a30657ce95964ea65fce55359fe08071e2d446d and ae9b3711287ad97efa57e8a2916c874aeb219b75 are from #8915 and 392fd8a75cfe32a0583157d28d39a65174b8e14d is from #8917)

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
