### PR TITLE
Fix unsafe concurrent access to m_DataBuffer in InfluxdbWriter

### PR DESCRIPTION
**Pull request by yhabteab**
Backport of #9137

### CODE REVIEW

**Review by julianbrost — COMMENTED** [review]
This also includes half of #8719. Have you had any discussion with @Al2Klimov about this? I'd rather apply just the fix from #9137 to the old code (it's mostly the same code, it's just in a different file).

**Comment by Al2Klimov** [comment]
Discussion? That was my instruction.

**Review by julianbrost — CHANGES_REQUESTED** [review]
The PR contains changes that are not supposed to be part of this PR, namely `lib/perfdata/graphite*` and `lib/perfdata/reportplugincheck.*`.

> Discussion? That was my instruction.

Just read it as "any kind of interaction that resulted in it being done this way". But that's why I asked, I wanted to avoid giving conflicting instructions.

But to be honest, I'm not a huge fan of this plan as it bloats up a somewhat small fix into a huge change that's not just a backport of another PR but just a part. Shouldn't simply applying the patches for `influxdbcommonwriter.*` to `influxdbwriter.*` just work? I'd expect that to be less work for both creating and reviewing the PR.

**Review by Al2Klimov — COMMENTED** [review]
For creating: no. For reviewing: yes.

@yhabteab Give the conflict resolution a try.

**Review by julianbrost — APPROVED** [review]

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Have a look at the failed checks.

**Review by Al2Klimov — APPROVED** [review]

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
