### PR TITLE
Don't delete downtimes in satellite zones

### PR DESCRIPTION
**Pull request by Al2Klimov**
refs #6542

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@dnsmichi Please review whether this would be the way to go – w/o proofs of concept or reproducing. If yes, please help me (offline) to get this actually working.

**Comment by dnsmichi** [comment]
This will likely solve case 2 here. I'm not yet sure whether it is needed @lippserd 

img_2544

**Comment by Al2Klimov** [comment]
If any satellite sends notifications, this is definitively needed.

**Comment by dnsmichi** [comment]
Backport only when master-snapshot tests succeed.

**Pull request merged**
