### PR TITLE
Notification#BeginExecuteNotification(): SetNextNotification() correctly

### LINKED ISSUE #5561: Set the notification mode times.begin is not 0, the first notification has a delay
## Current Behavior

There are three kinds of notifications for each of my monitoring items:
### mail-notification:
```
object Notification "mail-notification" {
	import "mail-service-notification"

	host_name = "l-jyftest1.ops.beta.cn0"
	interval = 300.000000
	service_name = "check_load"
	times = {
		begin = 0.000000
	}
	users = [ "mika.liu", "yufeng.ji", "kai.duan", "liangliang.pan", "zhangj.zhang", "jiwei.zhao", "yinan.gao", "yankun.zhu" ]
	version = 1504145701.727930
	zone = "master"
}
```
### push-notification:
```
object Notification "mail-notification" {
	import "push-service-notification"

	host_name = "l-jyftest1.ops.beta.cn0"
	interval = 300.000000
	service_name = "check_load"
	times = {
		begin = 0.000000
	}
	users = [ "qunaropspush" ]
	vars["userlist"] = "mika.liu,yufeng.ji,kai.duan,liangliang.pan,zhangj.zhang,jiwei.zhao,yinan.gao,yankun.zhu"
	version = 1504145701.562974
	zone = "master"
}
```
### ivr-notification:
```
object Notification "ivr-notification" {
	import "ivr-service-notification"

	host_name = "l-jyftest1.ops.beta.cn0"
	interval = 300.000000
	service_name = "check_load"
	times = {
		begin = 900.000000
	}
	users = [ "qunaropsivr" ]
	vars["userlist"] = "mika.liu,yufeng.ji,kai.duan,liangliang.pan,zhangj.zhang,jiwei.zhao,yinan.gao,yankun.zhu"
	version = 1504145701.873894
	zone = "master"
}
```
The current situation has been found, ivr-notification when the first notification, there are some delays, than the "times.begin" set the time later.

## Possible Solution

Now set the "times.begin = 900" will probably be delayed for more than 1 minute, if there is no way to solve, we may be in the normal begin time: "times.begin = 900" - 60s

### as the picture shows:
image

Theoretically speaking, "ivr-notification" The first notice should be (19:39:51 + 15min) = 19:54:51; 
but now "ivr-notification" The first notice is "19:56:10"; 

delay time: (19:56:10 - 19:54:51) = 1min 19s;

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.26.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version:
```
CentOS Linux release 7.3.1611 (Core)
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog gelf graphite ido-pgsql influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
icinga2 daemon -C
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/Zone: The Zone object 'zone-cn0' has more than two endpoints. Due to a known issue this type of configuration is strongly discouraged and may cause Icinga to use excessive amounts of CPU time.
information/ApiListener: My API identity: l-cn0qicingam1.ops.cn2
information/ConfigItem: Instantiated 5 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 5 Endpoints.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 41614 Notifications.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 274 CheckCommands.
information/ConfigItem: Instantiated 124 Downtimes.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 EventCommand.
information/ConfigItem: Instantiated 5581 Hosts.
information/ConfigItem: Instantiated 10458 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 51407 Services.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

```
/*
 * Generated by Icinga 2 node setup commands
 * on 2017-01-09 17:12:48 +0800
 */

object Endpoint "l-cn0qicingam1.ops.cn2" {
	host = "10.90.0.81"
	log_duration = 5m
}

object Endpoint "l-cn0qicingam2.ops.cn2" {
	host = "10.90.0.82"
	log_duration = 5m
}

object Endpoint "l-cn0qicingan1.ops.cn2" {
	host = "10.90.0.85"
	log_duration = 5m
}

object Endpoint "l-cn0qicingan2.ops.cn2" {
	host = "10.90.0.86"
	log_duration = 5m
}

object Endpoint "l-cn0qicingan3.ops.cn2" {
	host = "10.90.0.84"
	log_duration = 5m
}

object Zone "master" {
	endpoints = [ "l-cn0qicingam1.ops.cn2", "l-cn0qicingam2.ops.cn2" ]
}

object Zone "zone-cn0" {
	endpoints = [ "l-cn0qicingan1.ops.cn2", "l-cn0qicingan2.ops.cn2", "l-cn0qicingan3.ops.cn2" ]
	parent = "master"
}

/* sync global commands */
object Zone "global-templates" {
        global = true
}
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #5561

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please explain the change and add test output from before and after the patch.

**Comment by Al2Klimov** [comment]
Will be done after the user affected by the problem [has tested it](https://github.com/Icinga/icinga2/pull/5890#issuecomment-454069220).

**Comment by dnsmichi** [comment]
I'm more interested in the change from `now` towards `GetLastHardStateChange()` - please explain why this solves this in your opinion.

**Comment by Al2Klimov** [comment]
I just copied the formula from the enclosing if.

**Comment by dnsmichi** [comment]
There's a difference with `now` vs `GetLastHardStateChange` where it is unclear to me which consequences this has.

**Comment by mdetrano** [comment]
Hello, 

Finally had a chance to build and test with this fix merged in.  Looks good.  Notifications go out at the correct times when the begin time is not "0".  No longer matters if the "next notification" falls after or before the calculated "begin" time.  Should be sufficient to fix Issue #5561.

**Comment by dnsmichi** [comment]
Cool, thanks a lot for testing and also for keeping up with us busy developers :)

**Comment by dnsmichi** [comment]
Thank you @Al2Klimov for taking care here 👍

**Pull request merged**
