### PR TITLE
WIP: Tests: Checkresults should use non-paused objects

### PR DESCRIPTION
**Pull request by dnsmichi**
https://build.icinga.com/job/icinga2-snapshot/job/rpm-centos-6-1binary/arch=x86_64/349/console

```
        Start  73: base-icinga_checkresult/host_1attempt
 73/105 Test  #73: base-icinga_checkresult/host_1attempt ...................................***Exception: Other  0.02 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Notification triggered: PROBLEM
Second check result (ok)
Notification triggered: RECOVERY
Third check result (critical)
Notification triggered: PROBLEM
Fourth check result (ok)
Notification triggered: RECOVERY

*** No errors detected
terminate called without an active exception

        Start  74: base-icinga_checkresult/host_2attempts
 74/105 Test  #74: base-icinga_checkresult/host_2attempts ..................................***Exception: Other  0.09 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Second check result (critical)
Notification triggered: PROBLEM
Third check result (ok)
Notification triggered: RECOVERY
Fourth check result (critical)
Fifth check result (ok)

*** No errors detected
terminate called without an active exception

        Start  75: base-icinga_checkresult/host_3attempts
 75/105 Test  #75: base-icinga_checkresult/host_3attempts ..................................***Exception: Other  0.07 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Second check result (critical)
Third check result (critical)
Notification triggered: PROBLEM
Fourth check result (ok)
Notification triggered: RECOVERY
Fifth check result (critical)
Sixth check result (ok)

*** No errors detected
terminate called without an active exception

        Start  76: base-icinga_checkresult/service_1attempt
 76/105 Test  #76: base-icinga_checkresult/service_1attempt ................................***Exception: Other  0.06 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Notification triggered: PROBLEM
Second check result (ok)
Notification triggered: RECOVERY
Third check result (critical)
Notification triggered: PROBLEM
Fourth check result (ok)
Notification triggered: RECOVERY

*** No errors detected
terminate called without an active exception

        Start  77: base-icinga_checkresult/service_2attempts
 77/105 Test  #77: base-icinga_checkresult/service_2attempts ...............................***Exception: Other  0.06 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Second check result (critical)
Notification triggered: PROBLEM
Third check result (ok)
Notification triggered: RECOVERY
Fourth check result (critical)
Fifth check result (ok)

*** No errors detected
terminate called without an active exception

        Start  78: base-icinga_checkresult/service_3attempts
 78/105 Test  #78: base-icinga_checkresult/service_3attempts ...............................***Exception: Other  0.27 sec
Running 1 test case...
Before first check result (ok, hard)
First check result (unknown)
Second check result (critical)
Third check result (critical)
Notification triggered: PROBLEM
Fourth check result (ok)
Notification triggered: RECOVERY
Fifth check result (critical)
Sixth check result (ok)

*** No errors detected
terminate called without an active exception


100/105 Test #100: livestatus-livestatus/hosts .............................................***Exception: Other  0.06 sec
Running 1 test case...

*** No errors detected
terminate called without an active exception

        Start 101: livestatus-livestatus/services
101/105 Test #101: livestatus-livestatus/services ..........................................***Exception: Other  0.10 sec
Running 1 test case...

*** No errors detected
terminate called without an active exception
```

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Testbuilds running here:
* https://git.icinga.com/packaging/rpm-icinga2/pipelines/4269
* https://git.icinga.com/packaging/deb-icinga2/pipelines/4268

**Comment by lazyfrosch** [comment]
Tests still fail, with the exception of [sles-12.4](https://git.icinga.com/packaging/rpm-icinga2/-/jobs/13551)

**Comment by dnsmichi** [comment]
Seems to be timing related, GitHub CI works well enough, local tests too. I'll put it onto this week's agenda.

**Comment by dnsmichi** [comment]
Likely the fixture for spawning the IcingaApplication got broken, or how we mock these objects. I honestly don't like these tests that much, as the ProcessCheckResult function as well as the Livestatus queries are hard to reliably test.

**Comment by dnsmichi** [comment]
Note: Requires CentOS 7 to reproduce. Likely we're creating a thread which cannot be joined, or are referencing an object which already has been destroyed. Or try-catch with missing throw.

09b4b5853 was the last working commit.

**Comment by dnsmichi** [comment]
Tracking issue is now #7327.

**Comment by dnsmichi** [comment]
Superseded by #7331, thanks @Al2Klimov.

**Pull request closed without merging**
