### PR TITLE
Reset terminal on erroneous console exit

### LINKED ISSUE #6382: icinga2 console breaks the terminal on errors
When an errors occurs in icinga2 console, the terminal is broken and I have to run `reset`. This does not happen on normal exit.

## Steps to Reproduce (for bugs)

1. Run `icinga2 console --connect https://localhost:9999/` (choose an invalid IP/port)
2. Hit tab

The following error is displayed and the programme exits:
```
Icinga 2 (version: r2.8.4-1)
<1> => critical/TcpSocket: Invalid socket: Connection refused
critical/ConsoleCommand: HTTP query failed: std::exception
```
3. after that, the terminal is broken (the text that I type is not displayed), I have to run `reset` to fix it

## Context

I'm using bash, but I assume other shells are affected too. The problem is present both with and without libedit support.

## Your Environment

* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: Gentoo

### PR DESCRIPTION
**Pull request by mcktr**
This ensures that the terminal is reset on an erroneous exit when using the Icinga 2 console. The problematic state only occurs if Icinga 2 is compiled with `libedit` support.

## Test

1. Start the Icinga 2 console and choose an invalid port.

```
metis ~/Coding/icinga/icinga2/build_debug (fix/erroneous-console-exit) # /home/michael/bin/icinga2/sbin/icinga2 console --connect https://localhost:9999/
Icinga 2 (version: v2.9.1-50-g51b900b30)
Type $help to view available commands.
<1> =>
```

2. Now hit the _tab_ key. The console (correctly) terminates with an critical error because of the invalid port. 

```
metis ~/Coding/icinga/icinga2/build_debug (fix/erroneous-console-exit) # /home/michael/bin/icinga2/sbin/icinga2 console --connect https://localhost:9999/
Icinga 2 (version: v2.9.1-50-g51b900b30)
Type $help to view available commands.
<1> => critical/TcpSocket: Invalid socket: Connection refused
critical/ConsoleCommand: HTTP query failed: std::exception

```

3. Hit the _return_ key. 

```
metis ~/Coding/icinga/icinga2/build_debug (fix/erroneous-console-exit) # /home/michael/bin/icinga2/sbin/icinga2 console --connect https://localhost:9999/
Icinga 2 (version: v2.9.1-50-g51b900b30)
Type $help to view available commands.
<1> => critical/TcpSocket: Invalid socket: Connection refused
critical/ConsoleCommand: HTTP query failed: std::exception
metis ~/Coding/icinga/icinga2/build_debug (fix/erroneous-console-exit) #
```

4. The terminal stays intact.

fixes #6382

### CODE REVIEW

**Comment by Crunsher** [comment]
Nice, this has always been bugging me but never enough to fix it myself ^_^

**Comment by Crunsher** [comment]
While testing this I noticed I can't reproduce this anymore. Meaning the result with the master and your PR is the same. So I went and looked up `rl_deprep_terminal`:  
Function: void rl_deprep_terminal (void)  
    Undo the effects of rl_prep_terminal(), leaving the terminal in the state in which it was before the most recent call to rl_prep_terminal(). 

Is `rl_prep_terminal` called somehow by the library? Because we don't do so explicitly.

**Comment by dnsmichi** [comment]
## Current

screen shot 2018-09-13 at 13 15 54

## Fixed

screen shot 2018-09-13 at 13 32 46

**Comment by dnsmichi** [comment]
(Ok you cannot set it, but terminal 1 is broken, terminal 2 works)

**Pull request merged**
