### PR TITLE
Update event handler example for SSH

### PR DESCRIPTION
**Pull request by MarcusCaepio**
Hi All,

just updated the doc for EventHandler with a assign rule example and corrected the variable assignment like agreed with michi at https://monitoring-portal.org/index.php?thread/31728-eventhandler-einrichten/&postID=242172#post242172

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Looks good to me. Can you please squash those commits into a single commit and update the commit message to reflect what was changed? :)

**Comment by MarcusCaepio** [comment]
@gunnarbeutner Hi Gunnar. I will keep this in mind. This is my first pull ever, so I am just a little insecure how to do it right :D

**Comment by gunnarbeutner** [comment]
After careful examination we've found a problem with the first example service:

There's no "host" variable when you're using "object Service" (in line 1958). This variable is only available when using "apply". Can you please update the example? :)

**Comment by MarcusCaepio** [comment]
Done!

**Comment by dnsmichi** [comment]
I've rebased the PR against master, fixed conflicts and amended changes from the previous patch from @dgoetz in #5136 and #5090. It only makes sense to use "apply" here, instead of the standalone object.

I've force pushed your remote to cleanly merge this PR. Please create a new branch based off an up-to-date master next time. More details can be found in our CONTRIBUTING.md file :)

Thanks for the patch 👍

**Pull request merged**
