### PR TITLE
Re-send notifications previously suppressed by their time periods

### LINKED ISSUE #6167: Notification for a present problem, when timeperiod starts
Good morning,

I have a timeperiod “exthours” from 05:30am - 06:00pm. A host/ service going down at 04:11am and will not send notification - ok.

My question:
How can I realize a notification at 05:30am when the host/ service still down?

```
apply Service "dhcp-vlan4" {
        import "generic-service"
        check_command = "check-dhcp"

        vars.network = host.vars.dhcp_vlan4
        vars.sla = "exthours"

        vars.notification["mail"] = {
                groups = [ "operating", "windows" ]
        }

        assign where host.vars.dhcp_vlan4 != ""
}

object TimePeriod "exthours" {
  import "legacy-timeperiod"
  display_name = "Operating present"
  ranges = {
        "monday"        = "05:30-18:00"
        "tuesday"       = "05:30-18:00"
        "wednesday"     = "05:30-18:00"
        "thursday"      = "05:30-18:00"
        "friday"        = "05:30-16:00"
  }
}

template Service "generic-service" {
    max_check_attempts = 5
    check_interval = 3m
    retry_interval = 1m
    enable_flapping = true
}

template Notification "service-exthours" {
  interval = 1d

  command = "mail-service-notification"

  states = [ OK, Warning, Critical ]
  types = [ Problem, Acknowledgement, Recovery, Custom,
                        FlappingStart, FlappingEnd,
                        DowntimeStart, DowntimeEnd, DowntimeRemoved ]

  period = "exthours"
}
```

### LINKED ISSUE #7099: Inconsistent behavior between notifications outside timeperiods
## Expected Behavior

A critical state recovers outside of a timeperiod, the notification for recovery is sent, when the timeperiod is reached. 

## Current Behavior

When an object enters critical state outside of a timeperiod, the notification is sent when the timeperiod is reached
When an object recovers outside of a timeperiod no notification is sent, when the timeperiod is reached

## Possible Solution

Apply the same behavior for critical on recovery notification

## Steps to Reproduce (for bugs)

1. Create a timeperiod for an object
2. Inside the timeperiod set the object status to critical
3. Outside of the timeperiod let the object recover
4. Timeperiod begins and no notification is sent, that the state recovered

## Context

In the current scenario we have no clue, if the service already recovered outside the timeperiod. The only chance to check this is to have a look at the state itself.
People depending on the notification are somehow blind about the current state, when recovery notifications aren't sent.

## Your Environment

* Version used (`icinga2 --version`): 2.10.3

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #6167
fixes #7099

### CODE REVIEW

**Comment by dnsmichi** [comment]
When the docs are updated and @lippserd agrees, we can move this to 2.12.

**Comment by Al2Klimov** [comment]
Will add docs, but I don't agree with adding this to v2.12.

**Comment by N-o-X** [comment]
Forgot my test protocol.

## Config:
```
object Host "notification-test-host" {
  check_command = "dummy"
  enable_active_checks = false
  max_check_attempts = 1
}

object TimePeriod "exthours" {
  ranges = {
    "friday" = "11:15-17:00"
  }
}

object User "test-user" {
}

apply Notification "host-exthours" to Host {
  interval = 1d
  command = "mail-host-notification"

  period = "exthours"
  users = [ "test-user" ]

  assign where host.name == "notification-test-host"
}
```

## Test:

Processing check result with exit status 1:
```
curl -k -s -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/process-check-result' \
 -d '{ "filter": "host.name==\"notification-test-host\"", "type": "Host", "exit_status": 1, "plugin_output": "Host is not available." }'
```

Results in:
```
[2020-02-14 11:13:10 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'notification-test-host!host-exthours'
[2020-02-14 11:13:10 +0100] notice/Notification: Not sending notifications for notification object 'notification-test-host!host-exthours': not in timeperiod 'exthours'
```

2 Minutes later (in TP):
```
[2020-02-14 11:15:00 +0100] notice/NotificationComponent: Attempting to re-send previously suppressed notification 'notification-test-host!host-exthours'.
[2020-02-14 11:15:00 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'notification-test-host!host-exthours'.
```

**Comment by Al2Klimov** [comment]
Feel free to merge.

**Pull request merged**
