### PR TITLE
LegacyTimePeriod::ProcessTimeRangeRaw(): support ranges across midnight

### LINKED ISSUE #5261: Scheduled-Downtime over midnight will not be scheduled
## Behavior

I have set a scheduled downtime before and after midnight but only the time before 00:00 will be scheduled.

`vars.wiederkehrende_downtime= "20:00-24:00,00:00-04:00"`

There should be a downtime for 20:00-24:00 and 00:00-04:00 but only the downtime for 20:00-24:00 appears. Switching the times ("00:00-04:00,20:00-24:00") will still only accept the 20:00-24:00 downtime.

More info: https://monitoring-portal.org/index.php?thread/40408-scheduled-downtime-%C3%BCber-mitternacht-wird-nicht-eingerichtet/

## Steps to Reproduce (for bugs)

1. add to downtimes.conf:
```
apply ScheduledDowntime "wiederkehrende-downtime" to Host {
comment = "Wiederkehrende Downtime fuer Host"
author = "icingaadmin"
 ranges = {
  monday = host.vars.wiederkehrende_downtime
  tuesday = host.vars.wiederkehrende_downtime
  wednesday = host.vars.wiederkehrende_downtime
  thursday = host.vars.wiederkehrende_downtime
  friday = host.vars.wiederkehrende_downtime
  saturday = host.vars.wiederkehrende_downtime
  sunday = host.vars.wiederkehrende_downtime
 }
 assign where host.vars.wiederkehrende_downtime != ""
}
```
2. add to a host:
`vars.wiederkehrende_downtime= "20:00-24:00,00:00-04:00"`
3. _service icinga2 reload_
4. check your GUI or "_icinga2 object list --type downtime_"

## Context

How has this issue affected me? 
I cant set scheduled downtimes for daily/weekly backups so everytime the backup is running, icinga2 might not be able to check the host/service so it will send out alerts (sms) 

## My Environment

_icinga2 --version_
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 4.4.0-66-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.4
  Build host: lgw01-43
```

_icinga2 feature list_
```
Disabled features: debuglog gelf graphite icingastatus influxdb livestatus opentsdb syslog
Enabled features: api checker command compatlog ido-mysql mainlog notification perfdata statusdata
```

_icinga2 daemon -C_
```
information/cli: Icinga application loader (version: r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2.domain.local
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 6 NotificationCommands.
information/ConfigItem: Instantiated 5120 Notifications.
information/ConfigItem: Instantiated 210 CheckCommands.
information/ConfigItem: Instantiated 33 Downtimes.
information/ConfigItem: Instantiated 162 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 15 HostGroups.
information/ConfigItem: Instantiated 2 Comments.
information/ConfigItem: Instantiated 55 Dependencies.
information/ConfigItem: Instantiated 4 UserGroups.
information/ConfigItem: Instantiated 8 Users.
information/ConfigItem: Instantiated 1800 Services.
information/ConfigItem: Instantiated 8 TimePeriods.
information/ConfigItem: Instantiated 27 ServiceGroups.
information/ConfigItem: Instantiated 20 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ConfigItem: Instantiated 2 ExternalCommandListeners.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

_icinga2 object list --type Endpoint_
```
Object 'icinga2-sat.domain.local' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 20:1-20:49
  * __name = "icinga2-sat.domain.local"
  * host = "192.168.63.100"
    % = modified in '/etc/icinga2/zones.conf', lines 21:2-21:23
  * log_duration = 86400
  * name = "icinga2-sat.domain.local"
  * package = "_etc"
  * port = "5665"
  * templates = [ "icinga2-sat.domain.local" ]
    % = modified in '/etc/icinga2/zones.conf', lines 20:1-20:49
  * type = "Endpoint"
  * zone = ""

Object 'icinga2.domain.local' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * __name = "icinga2.domain.local"
  * host = "10.124.16.100"
    % = modified in '/etc/icinga2/zones.conf', lines 11:2-11:22
  * log_duration = 86400
  * name = "icinga2.domain.local"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 12:2-12:14
  * templates = [ "icinga2.domain.local" ]
    % = modified in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * type = "Endpoint"
  * zone = ""

```
_icinga2 object list --type Zone_
```
Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 7:3-7:15
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:30
  * type = "Zone"
  * zone = ""

Object 'SAT' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 24:1-24:21
  * __name = "SAT"
  * endpoints = [ "icinga2-sat.domain.local" ]
    % = modified in '/etc/icinga2/zones.conf', lines 25:2-25:50
  * global = false
  * name = "SAT"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 26:2-26:18
  * templates = [ "SAT" ]
    % = modified in '/etc/icinga2/zones.conf', lines 24:1-24:21
  * type = "Zone"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 15:1-15:20
  * __name = "master"
  * endpoints = [ "icinga2.domain.local" ]
    % = modified in '/etc/icinga2/zones.conf', lines 17:2-17:41
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 15:1-15:20
  * type = "Zone"
  * zone = ""
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #5261

### CODE REVIEW

**Comment by dnsmichi** [comment]
Doesn't work, the unit tests prove it.

```
michi@mbpmif ~/dev/icinga/icinga2 (bugfix/scheduled-downtime-over-midnight-5261 *<>) $ ./debug/Bin/Debug/boosttest-test-base --run_test=icinga_legacytimeperiod/advanced -l all
Initializing Application...
Initializing IcingaApplication...
Running 1 test case...
Entering test module "Master Test Suite"
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:9: Entering test suite "icinga_legacytimeperiod"
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:90: Entering test case "advanced"
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:106: info: check ts_beg == ts_beg_exp has passed
Begin date: 2019-05-06 22:00:00 +0000 expected 2019-05-06 22:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:108: error: in "icinga_legacytimeperiod/advanced": check ts_end == ts_end_exp has failed [1557122400 != 1557208800]
End date: 2019-05-06 06:00:00 +0000 expected 2019-05-07 06:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:124: info: check ts_beg == ts_beg_exp has passed
Begin date: 2009-05-06 09:00:00 +0000 expected 2009-05-06 09:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:126: error: in "icinga_legacytimeperiod/advanced": check ts_end == ts_end_exp has failed [1241715600 != 1241629200]
End date: 2009-05-07 17:00:00 +0000 expected 2009-05-06 17:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:141: error: in "icinga_legacytimeperiod/advanced": check ts_beg == ts_beg_exp has failed [1411635600 != 1411549200]
Begin date: 2014-09-25 09:00:00 +0000 expected 2014-09-24 09:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:143: error: in "icinga_legacytimeperiod/advanced": check ts_end == ts_end_exp has failed [1411797600 != 1411624800]
End date: 2014-09-27 06:00:00 +0000 expected 2014-09-25 06:00:00 +0000
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:90: Leaving test case "advanced"; testing time: 439us
/Users/michi/dev/icinga/icinga2/test/icinga-legacytimeperiod.cpp:9: Leaving test suite "icinga_legacytimeperiod"; testing time: 462us
Leaving test module "Master Test Suite"; testing time: 524us

*** 4 failures are detected in the test module "Master Test Suite"
```

**Comment by dnsmichi** [comment]
Added docs.

**Comment by lazyfrosch** [comment]
Gentleman, seems like the unit test needs some more care:
https://git.icinga.com/packaging/windows-icinga2/-/jobs/12477

**Comment by dnsmichi** [comment]
Seems the Windows box is off-by-one, DST highly likely.

**Comment by dnsmichi** [comment]
AppVeyor passed the build.

https://ci.appveyor.com/project/icinga/icinga2/builds/25089494

Is the Windows box in GitLab using UTC, or something else?

**Comment by lazyfrosch** [comment]
Yes that's a UTC system. I've seen that AppVeyor is fine

**Pull request merged**
