### PR TITLE
Windows agent: Default to lower case FQDN

### LINKED ISSUE #7407: Windows agent - Default to lower case FQDN
As described here https://community.icinga.com/t/windows-agent-hostname-case-sensitive/1899 the Setup Wizard of the Windows Agent might default to a FQDN where where lower and upper case letters are mixed. This might be a problem as icinga identifies host case sensitive. In my case using SNMP traps are complicated to handle because dnsresolver usually gives the fqdn in lower case.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7407

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

Bildschirmfoto 2020-11-02 um 13 58 24

## After

Bildschirmfoto 2020-11-02 um 14 05 24

**Review by julianbrost — APPROVED** [review]
Fine for me if you can confirm that this indeed only affects the GUI wizard (which I think it does).

**Comment by Al2Klimov** [comment]
Isn’t the issue only about the GUI?

**Review by julianbrost — APPROVED** [review]
Yes, I think the issue is only about the setup GUI. Just wanted to confirm that this PR indeed only changes that behavior and not anything else like automated setup scripts. Given that this change is within the class `SetupWizard` this is the case I guess.

**Pull request merged**
