### PR TITLE
ITL: Support --list argument to check_apt

### PR DESCRIPTION
**Pull request by atj**
Adds support for the check_apt --list argument.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please add the attribute to the docs too :)

**Comment by atj** [comment]
> Please add the attribute to the docs too :)

Done :)

**Comment by dnsmichi** [comment]
Thanks :)

**Comment by ekeih** [comment]
Nice, I was looking for this a few days ago and considered implementing it. Thanks @atj!

**Pull request merged**
