### PR TITLE
ApiListener: use Boost ASIO and coroutines for net I/O

### PR DESCRIPTION
**Pull request by Al2Klimov**
Technical requirements: #7041

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## TODO before merging

* [ ] Package Boost v1.66 for all distro versions not already shipping it on packages.icinga.com
* [ ] Include that packages in Travis...
* [ ] and Jenkins

**Comment by Al2Klimov** [comment]
@lazyfrosch Please could you start with CentOS 7? I'd like to put some packages on the testing system of ref/NC/588711 as a first step.

**Comment by Al2Klimov** [comment]
... before disappearing on vacation.

**Comment by Al2Klimov** [comment]
@dnsmichi Please assign me all issues which may have been addressed by this PR.

**Comment by dnsmichi** [comment]
> @dnsmichi Please assign me all issues which may have been addressed by this PR.

Roger roger 👍

**Comment by Al2Klimov** [comment]
@dnsmichi FYI: MF and I discovered a C++11 support bug in old GCCs:

If your function looks like this...

```c++
auto sum(unsigned long a, int b) -> decltype(a + b) {
  return a + b;
}
```

... you don't have `this` inside `decltype()`, e.g. you can't call an overridden method the same way as you'd do it inside the method itself – see 16de927.

If your function is templated, it gets even worse due to SFINAE – the function just disappears.

**Comment by Al2Klimov** [comment]
## TODO after merging

There below issues have either definitively or probably been addressed by this PR.

Once this has been merged, we should

* [ ] let the snapshot packages build and
* [ ] let the issue authors test them.

* #6981
* #6973
* #6930
* #6836
* #6559
* #3029

**Comment by Al2Klimov** [comment]
Got CentOS 7 packages. (Thx @lazyfrosch.) Contacted ref/NC/588711 . Will let you know once there's something to know.

**Comment by Al2Klimov** [comment]
TODO:

* [ ] Make it building w/o unity

**Comment by Al2Klimov** [comment]
@dnsmichi 8f12e1f4f and c70ef33cc have nothing to do with this one, have they?

**Comment by dnsmichi** [comment]
You've been on vacation, and need an update on what happened in the meantime. I've taken over this branch and will sort things out.

**Comment by Al2Klimov** [comment]
In addition 797c89f87, 4b69d9731 and 5d7994ac7 should be fixed by 4c997ede0.

**Comment by dnsmichi** [comment]
Right, I was about to do squash/implement this after rebasing against master. Thanks.

**Comment by Al2Klimov** [comment]
Poor man's test protocol:

```
➜  icinga2 git:(fa0b0b0d4) curl -k -s -u root:icinga 'https://localhost:5665/v1/config/stages/d' -X POST -H 'Accept: application/json' -d @m.conf

<h1>Bad Request</h1><p><pre>body limit exceeded</pre></p>%
➜  icinga2 git:(4c997ede0) curl -k -s -u root:icinga 'https://localhost:5665/v1/config/stages/d' -X POST -H 'Accept: application/json' -d @m.conf

{"error":500.0,"status":"Stage creation failed."}%
```

**Comment by dnsmichi** [comment]
One thing which got broken with 2.8.2 is the handling of the Accept header. When this is JSON, we should return a JSON error, instead of plain HTML.

**Comment by Al2Klimov** [comment]
Rewritten e65abd321 to 2d16b0252 due to improved Defer in the master.

**Comment by dnsmichi** [comment]
For some reason, the logging for refused connections in the cluster contains lots of empty lines. 

```
[2019-04-01 14:02:33 +0200] debug/ApiListener: Cannot connect to host '127.0.0.1' on port '5667'
Error: Connection refused





[2019-04-01 14:02:36 +0200] debug/CheckerComponent: Scheduling info for checkable 'icinga2a' (2019-04-01 14:02:36 +0200): Object 'icinga2a', Next Check: 2019-04-01 14:02:36 +0200(1.55412e+09).
```

I suspect that the DiagnosticInformation() calls don't work properly and do not include a full stack trace here.

**Pull request merged**
