### PR TITLE
[ITL] Added --datadir, --language and --perflimit for check_postgres

### LINKED ISSUE #8922: [ITL] The command definition for check_postgresql is lacking some important options
Some options necessary for some of the functionality of check_postgres are missing from the command definition in the ITL:

```
--datadir (location of the PostgreSQL data directory)
--language (language to use for messages)
--perflimit (limit the number of performance data to report)
```

The data directory must be specified for some of the plugin's functions, such as e.g. prepared transactions, locks, bloat and some more.

Specifying the language is required because the plugin tries to be "intelligent" and determine the language from the system language, among other things. In many cases that's not what is required in the monitoring environment, especially in notifications, so explicitly specifying the language is a much-needed option.

Limiting the number of performance data is necessary in some cases where a monitored database has lots of tables or indices and the amount of performance data returned causes performance issues and/or data bloat in the TSDB, if one is used.

* Version used: `icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.5-2)`
* Operating System and version: `AlmaLinux release 8.4 (Electric Cheetah)`
* Plugin version: `check_postgres.pl version 2.25.0`

### PR DESCRIPTION
**Pull request by peteeckel**
This PR contains the check command option definitions for the missing options specified in #8922.

fixes #8922

### CODE REVIEW

**Review by Al2Klimov — APPROVED** [review]
LGTM

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Rebase.

**Comment by bobapple** [comment]
@cla-bot check

**Comment by peteeckel** [comment]
> Rebase.

Done (after some rounds of pointlessly fighting with the CLA bot).

**Comment by Al2Klimov** [comment]
> pointlessly fighting with the CLA bot

Exactly. As the bot said:

> After that, please reply here with a comment and we'll verify.

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
