### PR TITLE
Config lexer: complain on EOF in heredocs, i.e. {{{abc<EOF>

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Can you please share a concrete example like a short test protocol? I don't get what the PR should fix. Thanks :)

**Comment by Al2Klimov** [comment]
At the moment we silently ignore `{{{abc<EOF>` (console: `{{{abc<ENTER>`). This one complains instead as with `"abc<EOF>`.

**Comment by dnsmichi** [comment]
The only "problem" with this patch - when using heredoc in the console, you cannot do multi-line with Enter anymore. But that's something minor compared to the error message we get with the config compiler.

**Comment by dnsmichi** [comment]
```
[2019-10-22 15:11:15 +0200] information/cli: Icinga application loader (version: v2.11.0-42-g28e1a2fe0; debug)
[2019-10-22 15:11:15 +0200] information/cli: Loading configuration file(s).
[2019-10-22 15:11:15 +0200] critical/config: Error: End-of-file while in string literal
Location: in etc-a/icinga2/zones.d/satellite/abc.conf: 5:11-8:0
etc-a/icinga2/zones.d/satellite/abc.conf(3):   vars.blubb = 10
etc-a/icinga2/zones.d/satellite/abc.conf(4):
etc-a/icinga2/zones.d/satellite/abc.conf(5):   notes = {{{ abc
                                                       ^^^^^^^
etc-a/icinga2/zones.d/satellite/abc.conf(6):

etc-a/icinga2/zones.d/satellite/abc.conf(7): }
                                             ^
etc-a/icinga2/zones.d/satellite/abc.conf(8):


[2019-10-22 15:11:15 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.

real	0m0.281s
user	0m0.191s
sys	0m0.089s
michi@mbpmif ~/dev/testing/i2-local-cluster (master *=) $ time ./icinga2a daemon

[2019-10-22 15:11:56 +0200] information/cli: Icinga application loader (version: v2.11.0-41-g32fd741ba; debug)
[2019-10-22 15:11:56 +0200] information/cli: Loading configuration file(s).
[2019-10-22 15:11:56 +0200] critical/config: Error: syntax error, unexpected new-line
Location: in etc-a/icinga2/zones.d/satellite/abc.conf: 8:0-8:0
etc-a/icinga2/zones.d/satellite/abc.conf(6):
etc-a/icinga2/zones.d/satellite/abc.conf(7): }
etc-a/icinga2/zones.d/satellite/abc.conf(8):
                                             ^

[2019-10-22 15:11:56 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.

real	0m1.351s
user	0m0.186s
sys	0m0.090s
```

**Pull request merged**
