### PR TITLE
Icinga DB: introduce icinga:downtime#scheduled_by

### PR DESCRIPTION
**Pull request by Al2Klimov**
refs Icinga/icingadb#231

### CODE REVIEW

**Comment by Al2Klimov** [comment]
```
➜  icinga2 git:(feature/icingadb-scheduleddowntime) cat 231.conf
include <itl>

object Host NodeName {
	check_command = "dummy"
}

object ScheduledDowntime "sd" {
	host_name = NodeName
	author = "me"
	comment = " "

	ranges = {
		"tuesday" = "23:00-23:30"
	}
}

object Downtime "d" {
	host_name = NodeName
	author = "me"
	comment = " "
	start_time = get_time() + 1m
	end_time = start_time + 5m
}

object IcingaDB "icingadb" {
	host = "127.0.0.1"
	port = 6379
}
➜  icinga2 git:(feature/icingadb-scheduleddowntime) prefix/sbin/icinga2 daemon -c 231.conf
[2021-02-09 18:41:40 +0100] information/cli: Icinga application loader (version: v2.12.0-504-gee5f6f4ad)
[2021-02-09 18:41:40 +0100] information/cli: Loading configuration file(s).
[2021-02-09 18:41:40 +0100] information/ConfigItem: Committing config item(s).
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 8 CheckCommands.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 1 Downtime.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 1 Host.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Instantiated 1 IcingaDB.
[2021-02-09 18:41:40 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-02-09 18:41:40 +0100] information/ConfigItem: Triggering Start signal for config items
[2021-02-09 18:41:40 +0100] information/IcingaDB: 'icingadb' started.
[2021-02-09 18:41:40 +0100] information/ConfigItem: Activated all objects.
[2021-02-09 18:41:40 +0100] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6379'
[2021-02-09 18:41:40 +0100] information/IcingaDB: Connected to Redis server
[2021-02-09 18:41:40 +0100] information/IcingaDB: Starting initial config/status dump
[2021-02-09 18:41:40 +0100] information/IcingaDB: Initial config/status dump finished in 0.00668883 seconds.
[2021-02-09 18:41:50 +0100] information/WorkQueue: #5 (IcingaDB) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2021-02-09 18:42:40 +0100] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!785a4995-7edb-4f7e-8c40-581e68a856cd' of type 'Downtime'.
[2021-02-09 18:42:40 +0100] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!785a4995-7edb-4f7e-8c40-581e68a856cd' between '2021-02-09 23:00:00' and '2021-02-09 23:30:00', author: 'me', fixed
^C[2021-02-09 18:44:44 +0100] information/Application: Received request to shut down.
[2021-02-09 18:44:44 +0100] information/Application: Shutting down...
[2021-02-09 18:44:44 +0100] information/IcingaDB: 'icingadb' stopped.
[2021-02-09 18:44:44 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-02-09 18:44:44 +0100] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(feature/icingadb-scheduleddowntime) redis-cli HGETALL icinga:config:downtime
1) "b6c5935411d14d82544e694280b6e17f4ea06de7"
2) "{\"author\":\"me\",\"comment\":\" \",\"creator\":\"scheduled_downtime\",\"entry_time\":1612892560459.0,\"environment_id\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"flexible_duration\":0.0,\"host_id\":\"5ffd3470e558666b25ccd505c329faa0f1932596\",\"is_flexible\":false,\"is_in_effect\":false,\"name\":\"Alexanders-MacBook-Pro.local!785a4995-7edb-4f7e-8c40-581e68a856cd\",\"name_checksum\":\"b8c5b7e2c8db94946f0959e0b89c0b3e14a56d75\",\"object_type\":\"host\",\"scheduled_end_time\":1612909800000.0,\"scheduled_start_time\":1612908000000.0}"
3) "2555faf206b2ba273cfb39c4d94b3fb5fba147c1"
4) "{\"author\":\"me\",\"comment\":\" \",\"creator\":\"user\",\"entry_time\":1612892500442.0,\"environment_id\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"flexible_duration\":0.0,\"host_id\":\"5ffd3470e558666b25ccd505c329faa0f1932596\",\"is_flexible\":true,\"is_in_effect\":false,\"name\":\"Alexanders-MacBook-Pro.local!d\",\"name_checksum\":\"5268e8fc3adf309cbcbaa01954f2331f0d6b0e48\",\"object_type\":\"host\",\"scheduled_end_time\":1612892860442.0,\"scheduled_start_time\":1612892560442.0}"
➜  icinga2 git:(feature/icingadb-scheduleddowntime)
```

**Comment by julianbrost** [comment]
Why not just use the value of `GetScheduledBy()`? This would provide even more information.

**Comment by Al2Klimov** [comment]
... about the ScheduledDowntimes which we don’t store anyway, yet.

**Comment by julianbrost** [comment]
Yet. But if we'd do at some point, this would have to be changed again. Also, the name could provide useful information by itself.

**Review by julianbrost — APPROVED** [review]

**Review by lippserd — APPROVED** [review]

**Pull request merged**
