### PR TITLE
Avoid syncing .authorititative marker received from < 2.11 parent nodes

### PR DESCRIPTION
**Pull request by dnsmichi**
I did not test this, just a short brain dump between GitLab and showoff.

Needs tests @lippserd @al2klimov

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Haven't I already fixed this in #7544?

**Comment by dnsmichi** [comment]
Your PR targets support/2.10 which requires a bump for 2.10.x. The problem with 2.11 persists as agent if an older master is used and sends this file. This is a more common scenario as I have learned.

**Comment by dnsmichi** [comment]
# Tests

- 1 Master with 2.10.5
- 1 Satellite with 2.11.0

Test the fix on the satellite and ensure that it does not dump the .authoritative file on disk.
@htriem

**Comment by dnsmichi** [comment]
@htriem tested this ok.

**Pull request merged**
