### PR TITLE
Add support for check_address as default in database CheckCommand objects

### PR DESCRIPTION
**Pull request by strajansebastian**
1. set the default hostname to the "$check_address$" for multiple CheckCommands
2. add support for  "$check_address$" for ping4 and ping6 commands which don't import the ipv4-or-ipv6 template

### CODE REVIEW

**Comment by strajansebastian** [comment]
closed the other pull and made a new request, have to improve my git skills in some areas

**Comment by dnsmichi** [comment]
Thanks, LGTM 👍

**Comment by dnsmichi** [comment]
One minor change - the documentation updates are missing, and MSSQL is true about the fact that `hostname` is optional and working in a similar fashion as oracle_health and connect. I'll amend.

**Comment by strajansebastian** [comment]
Good to know that for future changes. 

I was looking in the /usr/share/icinga2/include/plugins-contrib.d/ folder for template documentation purposes. 
Will use the https://github.com/Icinga/icinga2/blob/master/doc/10-icinga-template-library.md from now on.
Thanks!

**Comment by gunnarbeutner** [comment]
I took the liberty of cleaning up the patch a bit.

**Comment by dnsmichi** [comment]
Thanks @gunnarbeutner :)

**Pull request merged**
