### PR TITLE
DSL: introduce x?y:z

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@dnsmichi I know you don't like that, but I hope you like the already working `if(x){y}else{z}` even less.

**Comment by Al2Klimov** [comment]
## Test protocol

### Before

```
<1> => 1?2:3
        ^
syntax error, unexpected $undefined
```

### After

```
<1> => 0?2:3
3.000000
<2> => 1?2:3
2.000000
<3> => 4?5?6:7:8
6.000000
```

**Comment by Al2Klimov** [comment]
Fixed missing precedence and associativity:

```
<1> => 1 ? 2 : 3 ? 4 : 5 ? 6 : 7
2.000000
<2> => 0 ? 2 : 3 ? 4 : 5 ? 6 : 7
4.000000
<3> => 0 ? 2 : 0 ? 4 : 5 ? 6 : 7
6.000000
<4> => 0 ? 2 : 0 ? 4 : 0 ? 6 : 7
7.000000
<5> => 1 + 0 ? 2 : 3 + 4
2.000000
<6> => 0 + 0 ? 2 : 3 + 4
7.000000
<7> => (()=>{ return 1 ? 2 : 3 })()
2.000000
<8> => var x = 1 ? 2 : 3
null
<9> => x
2.000000
```

**Comment by dnsmichi** [comment]
Oh, I like this a lot for the DSL. Inside the C++ code, this gets overly complicated imho. I just need to figure out the operator precedence for the docs accordingly.

**Pull request merged**
