### PR TITLE
CLI: 'ca list' lists pending CSRs by default, add '--all' parameter

### PR DESCRIPTION
**Pull request by dnsmichi**
https://puppet.com/docs/puppet/5.5/man/cert.html

### CODE REVIEW

**Comment by dnsmichi** [comment]
@lippserd I'd like to include this in 2.11, what do you think?

**Comment by lippserd** [comment]
Sounds good to me!

**Comment by dnsmichi** [comment]
Perfect, then I'll align the docs :)

**Comment by dnsmichi** [comment]
# Tests

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/ca-list-all *<>) $ icinga2 ca list
Fingerprint                                                      | Timestamp                | Signed | Subject
-----------------------------------------------------------------|--------------------------|--------|--------
9eae900a671a8b54020f356516b8e5e508466b16e77afbe69e0c5063548a2fa0 | May 10 13:03:32 2019 GMT |        | CN = agent1
michi@mbpmif ~/dev/icinga/icinga2 (feature/ca-list-all *<>) $ icinga2 ca sign 9eae900a671a8b54020f356516b8e5e508466b16e77afbe69e0c5063548a2fa0
Closed FD 3 which we inherited from our parent process.
information/cli: Signed certificate for 'CN = agent1'.
michi@mbpmif ~/dev/icinga/icinga2 (feature/ca-list-all *<>) $ icinga2 ca list
Closed FD 3 which we inherited from our parent process.
Fingerprint                                                      | Timestamp                | Signed | Subject
-----------------------------------------------------------------|--------------------------|--------|--------
michi@mbpmif ~/dev/icinga/icinga2 (feature/ca-list-all *<>) $ icinga2 ca list --all
Fingerprint                                                      | Timestamp                | Signed | Subject
-----------------------------------------------------------------|--------------------------|--------|--------
9eae900a671a8b54020f356516b8e5e508466b16e77afbe69e0c5063548a2fa0 | May 10 13:03:32 2019 GMT | *      | CN = agent1
```

**Comment by dnsmichi** [comment]
This also solves the expectation of this being an historical view a bit - only `--all` shows them, and its help text now also notes that a cleanup happens automatically.

**Comment by dnsmichi** [comment]
Upgrade docs already have been written.

**Pull request merged**
