### PR TITLE
Icinga DB: don't write negative Downtime durations into Redis

### LINKED ISSUE #9774: icingadb service crashes on negative downtime duration or end before start
Hello,
I'd like to report minor issue for icingadb service we had faced to; caused by incorrect REST API request to create downtime object.
We noted, once incorrectly requested donwtime object creation via REST API is processed by the icingadb service, it crashes with bellow error (error data anonymized).
```
... icingadb[1934671]: strconv.ParseUint: parsing "-6947347": invalid syntax#012can't parse scheduled_duration into the uint64 Downtime
#ScheduledDuration: -6947347
#012github.com/icinga/icingadb/pkg/structify.structifyMapByTree
Icinga/icingadb#12#011github.com/icinga/icingadb/pkg/structify/structify.go:96
#012github.com/icinga/icingadb/pkg/structify.MakeMapStructifier.func1
Icinga/icingadb#12#011github.com/icinga/icingadb/pkg/structify/structify.go:41
#012github.com/icinga/icingadb/pkg/icingadb.structifyStream.func1
Icinga/icingadb#12#011github.com/icinga/icingadb/pkg/icingadb/runtime_updates.go:324
#012golang.org/x/sync/errgroup.(*Group).Go.func1
Icinga/icingadb#12#011golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
#012runtime.goexit
Icinga/icingadb#12#011runtime/asm_amd64.s:1571
#012can't structify map map[string]interface {}
{"author":"xxxxxxxx", "checksum":"90865fefb4af555359d08d9a6134550906b1bb67", "comment":"test", "duration":"-6947347", "entry_time":"1678820053120", "environment_id":"ddd076201b1f5e5c768744bad82811e42da61bca", "flexible_duration":"0", "host_id":"1c838e000b69d5fb84a44a67b833629a9f3df01b", "id":"6aa1374caed83675831c2b26de4e3b5eb99fe2bb", "is_flexible":"0", "is_in_effect":"0", "name":"xxxxxxxxxxxxxxx!7ec837a2-79a6-4c29-8d04-6704036f82ff", "name_checksum":"a282393a0bcc1a11f00d8006b6f09a2ba6e659b7", "object_type":"host", "redis_key":"icinga:downtime", "runtime_type":"upsert", "scheduled_duration":"-6947347", "scheduled_end_time":"1678802652652", "scheduled_start_time":"1678809600000", "zone_id":"c54805ce2030e6eefee1ad2983c09771c7090cfc", "zone_name":"xxxxx"}
```

We will try to sanity the input data on our site, but may be useful to sanity the data also on icinga site and not to process such incorrect REST API request (end time in past, duration in negative numbers, ...).

Thanks.

```
root@xxxx: ~
Wed Mar 15 07:35:24$ /usr/sbin/icingadb --version
Icinga DB version: v1.0.0

Build information:
  Go version: go1.18.1 (linux, amd64)
  Git commit: 0061888c404f87158d449d9b3ced82fca269a13b

System information:
  Platform: Ubuntu
  Platform version: 20.04.5 LTS (Focal Fossa)

```

### PR DESCRIPTION
**Pull request by Al2Klimov**
via `std::max(0, x)` not to crash the Go daemon which can't handle such.

fixes #9774

## Test cases (which don't crash anymore now)

* `curl -fvku root:123456 -X POST -H 'Accept: application/json' 'https://127.0.0.1:5665/v1/actions/schedule-downtime?type=Host&filter=true&start_time=14000&end_time=2000000000&author=ak&comment=-&fixed=0&duration=-14'`
* `curl -fvku root:123456 -X POST -H 'Accept: application/json' 'https://127.0.0.1:5665/v1/actions/schedule-downtime?type=Host&filter=true&start_time=2010000000&end_time=2000000000&author=ak&comment=-'`

### CODE REVIEW

**Comment by julianbrost** [comment]
What about any kind of input validation for new downtimes? `end_time <= start_time` and `fixed && duration <= 0` is guaranteed to result in broken/useless downtimes, so it doesn't make sense to accept that.

**Comment by Al2Klimov** [comment]
Sure. I have this on my to do list. But this PR doesn’t depend on that, does it?

**Comment by julianbrost** [comment]
This PR on its own doesn't make clear what exactly your plan is. Also you said nothing about why you're changing this in the Icinga DB specific code instead of earlier in the downtime code so that no other code has to have special cases for strange values. Is there something you expect to work better this way for later changes you're planning?

**Comment by Al2Klimov** [comment]
This code on its own just behaves like the other stuff which mitigates Icinga DB crashes.

Regarding preventing bad user behaviour in the future: the newly discovered existing ability to create end < start changes the whole picture of what's necessary for this (and for what you suggested). Whatever my plan was, it's now in the trash bin.

**Comment by julianbrost** [comment]
> Sure. I have this on my to do list.

Nobody besides you know that list, so please share what you're planning so that others can follow. This PR started as an alternative to #9773, so it would be much more helpful if the description included a summary what is different, what's in here and what isn't and what the plan is for things that aren't in here.

> But this PR doesn’t depend on that, does it?

When following #9774 to the word, yes, this PR probably fixes it. But #9773 started with some better validation which would still be useful, but probably in a more compatible way. If you want to treat that separately, please create an issue for this so that we don't forget it.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
