### PR TITLE
API: Fix http status codes

### LINKED ISSUE #5550: Verify error codes and returned log messages in API actions
Required arguments throw 404, sometimes 403.

### PR DESCRIPTION
**Pull request by N-o-X**
I think both 403 and 404 aren't suitable in most of the cases we used them.
Changed them to 400. Please feel free to correct me.

fixes #5550

### CODE REVIEW

**Comment by dnsmichi** [comment]
On-hold for after 2.8.

**Comment by Crunsher** [comment]
LGTM merging :3

**Comment by dnsmichi** [comment]
Both issues don't have a target version, which one should it be? :)

**Comment by Crunsher** [comment]
Do PRs with issues need a target version? It'll show up twice in the changelog

**Comment by dnsmichi** [comment]
Yep. Otherwise the logic with "backported" labels won't work.

**Pull request merged**
