### PR TITLE
GitHub actions: don't cache anything

### PR DESCRIPTION
**Pull request by Al2Klimov**
... for the same reason as #8217.

### CODE REVIEW

**Comment by lippserd** [comment]
I would wait here and see whether not uploading artifacts is sufficient.

**Comment by Al2Klimov** [comment]
FYI each ccache is <= 5G

**Review by lippserd — APPROVED** [review]

**Comment by lippserd** [comment]
We may still exceed the limits, so this one is free to merge.

**Comment by Al2Klimov** [comment]
@lippserd Any news on this?

**Comment by Al2Klimov** [comment]
All quiet on the western front = all good on the western front

**Pull request closed without merging**
