### PR TITLE
Fix problem with reminder notifications if the checkable is flapping

### PR DESCRIPTION
**Pull request by dnsmichi**

### CODE REVIEW

**Comment by dnsmichi** [comment]
@Crunsher as we've talked already before your vacation, this needs proper tests and a protocol with the results in here.

**Comment by Crunsher** [comment]
I tested this quite extensively already by getting a Host to start flapping with their last hard state being down.
Before the fix there were down reminder notifications, none after. I had a branch for this lying around, so to my knowledge this can be merged

**Comment by dnsmichi** [comment]
@N-o-X please test this one as well prior to merging.

**Comment by N-o-X** [comment]
Could you describe the expected behavior? I don't really know how those reminder notifications should act while a host/service is flapping.

**Comment by Crunsher** [comment]
They should not be sent, the problem only occurs in the following circumstances:
Service/Host is hard down and goes flapping with the same statechange. Expected and patched behavior is for only a flapping notification and no reminder notifications.

To reproduce this: Have a Host with a low flapping threshold and a host check that switches state with each result. To monitor notifications either have them written somewhere you can easily read them or activate the debug log and grep for NotificationComponent. I could also show you and explain next week

**Pull request merged**
