### PR TITLE
Prefix log messages with the current PID

### LINKED ISSUE #7328: Consider automatically prefixing log messages with the current PID
## Is your feature request related to a problem? Please describe.

We already have multiple Icinga processes at once during reload. With #7320 we'll have even more ones.

## Describe the solution you'd like

```
[2019-07-10 07:44:15 -0600] information/cli: icinga2[12964]: Closing console log.
```

## Describe alternatives you've considered

Put the PID earlier, but this would break the Director.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7328

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@Yonas-net Now it's the time for **you** to verify whether **I** did everything correctly. :)

Check out this branch, run Icinga and write a test protocol comparing the new behavior with the old one.

**Comment by Yonas-net** [comment]
Testprotcol:
So, at the moment the prefix log message has only the date time information and looks like this..
```
[2020-06-17 16:46:00 +0200] warning/Application: Failed to adjust resource limit for open file handles (RLIMIT_NOFILE) with error "Operation not permitted"
[2020-06-17 16:46:00 +0200] warning/Application: Failed to adjust resource limit for open file handles (RLIMIT_NOFILE) with error "Operation not permitted"
[2020-06-17 16:46:00 +0200] information/cli: Icinga application loader (version: v2.12.0-rc1-48-g6f708dfe1; debug)
[2020-06-17 16:46:00 +0200] information/cli: Loading configuration file(s).
[2020-06-17 16:46:00 +0200] information/ConfigItem: Committing config item(s).
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 User.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 3 Zones.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 11 Services.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-06-17 16:46:00 +0200] information/ConfigItem: Instantiated 1 FileLogger.
```
as you can see it doesn't look really nice and informative. After we have checked out our new branch and built icinga2, the output looks very nice and iformative, because the process ID was included, see below.
```
[2020-06-17 16:40:19 +0200] [PID 10171] warning/Application: Failed to adjust resource limit for open file handles (RLIMIT_NOFILE) with error "Operation not permitted"
[2020-06-17 16:40:19 +0200] [PID 10171] warning/Application: Failed to adjust resource limit for open file handles (RLIMIT_NOFILE) with error "Operation not permitted"
[2020-06-17 16:40:19 +0200] [PID 10171] information/cli: Icinga application loader (version: v2.11.0-544-g666ce6870; debug)
[2020-06-17 16:40:19 +0200] [PID 10203] information/cli: Loading configuration file(s).
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Committing config item(s).
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 User.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 UserGroup.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 3 Zones.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 11 Services.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 2 HostGroups.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 Host.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 12 Notifications.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 1 Endpoint.
[2020-06-17 16:40:19 +0200] [PID 10203] information/ConfigItem: Instantiated 235 CheckCommands.
```

**Comment by julianbrost** [comment]
What about [these concerns](https://github.com/Icinga/icinga2/issues/7328#issuecomment-512165647)? Have they been addressed or became irrelevant in the meantime?

**Comment by julianbrost** [comment]
Also, do we want to backport this to support branches? Would be nice as we just had a case where this information would have been useful, but I'm pretty sure this would break existing log parsing/analysis.

Maybe an alternative would be to have this as an attribute of the logger (either something like `log_pid` or more fancy by allowing to fully customize the format). Then it could be enables as needed without breaking any existing setup and could even be enabled in parallel (think like the debug log), to have the old format for existing log analysis and the new one for when you need the extra information.

**Comment by Al2Klimov** [comment]
What about moving the PID to the message itself?

**Comment by julianbrost** [comment]
I think by adding it to the end of the line, you'd get the best chances of avoiding to break existing parsing, but this would look kind of strange. Do you see a problem with adding a flag to optionally enable this?

**Comment by Al2Klimov** [comment]
Would it be better at the beginning of the message?

To be honest this customization feels wrong. I'd prefer to just add it (as is right now) along with an entry in the breaking changes changelog.

**Comment by julianbrost** [comment]
Then I'm coming back to this question:

> Also, do we want to backport this to support branches? Would be nice as we just had a case where this information would have been useful, but I'm pretty sure this would break existing log parsing/analysis.

If we only want to have this in 2.13, changing the log format should be fine.

**Comment by Al2Klimov** [comment]
I don’t see the need of having this in a minor version. But not all assignees have told their opinion, yet.

**Comment by julianbrost** [comment]
Just talked with @Thomas-Gelf about compatibility in Director: it should already be able to handle the new format. To verify this, deploy a broken config using Director (create a host using a template not setting check_command) and check that (1) the severity is colored and (2) the file name is a link.

@widhalmt What's the current state for Logstash? Would it cause any trouble if we want to release 2.13 with this in the near future?

**Comment by Al2Klimov** [comment]
## Migration plan

### v2.13

* new flag
* enabled by default
* already deprecated by .ti

### v2.14

* flag looses effect (no_storage?)
* stays settable and deprecated not to break config

**Comment by Al2Klimov** [comment]
Errm... colleagues? We have a problem: console log (no logger config object!) which matters especially in connection with Docker. Any ideas regarding the PR?

**Comment by julianbrost** [comment]
Looks like this would need to much rework of the logging now for a nice to have feature. Given that I'd like to rethink how we should do logging in the future (mainly switching over to syslog/journald, which would implicitly solve this issue), I've created #8857.

**Pull request closed without merging**
