### PR TITLE
ido_pgsql: do not set standard_conforming_strings to off

### LINKED ISSUE #8122: ido pgsql uses sets standard_conforming_strings to off without using it
## Describe the bug

https://github.com/Icinga/icinga2/blob/master/lib/db_ido_pgsql/idopgsqlconnection.cpp#L260 sets `standard_conforming_strings TO off` although it is not leveraging the functionality this setting provides (https://www.postgresql.org/docs/current/runtime-config-compatible.html). All query strings for which escaping is explicitly enabled are written as `E='" + Escape(value) + "'"`.

Since postgres 9.1, the setting defaults to true and we could omit the call.

### PR DESCRIPTION
**Pull request by MEschenbacher**
fixes #8122

### CODE REVIEW

**Comment by MEschenbacher** [comment]
Will do.

**Comment by MEschenbacher** [comment]
Progress so far:

- [x] looked through the whole postgres ido code: all strings which are executed with `Query(...)` within an `E'...'` literal are escaped using `Escape(...)`
- [x] Tested with postgres version 11.7
- [x] Tested with postgres version 9.0
- [ ] Tested with postgres version 9.1

**Comment by MEschenbacher** [comment]
Testing with postgres 9.1 is finished.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by MEschenbacher** [comment]
Done

**Review by julianbrost — APPROVED** [review]
LGTM, couldn't find any non `E'...'` strings either.

**Pull request merged**
