### PR TITLE
 check_nscp_api: Rewrite using Boost ASIO and Beast

### PR DESCRIPTION
**Pull request by dnsmichi**
# Analysis

https://github.com/Icinga/icinga2/pull/7142#issuecomment-495172167

Contains lots of programmatic attempts to overcome the wrong NSCP header.

```
HTTP/1.1 200
Content-Length: 379
Set-cookie: token=YT3CEW8K69rklPGtfUR2IZ2mB1S7NLt2; path=/
Set-cookie: uid=admin; path=/

{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]}
```

Correct would be

```
HTTP/1.1 200 OK
Content-Length: 379
Set-cookie: token=YT3CEW8K69rklPGtfUR2IZ2mB1S7NLt2; path=/
Set-cookie: uid=admin; path=/

{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]}
```

# Tests

https://github.com/Icinga/icinga2/pull/7142#issuecomment-495179420

Ugly workaround: Manual parsing of the HTTP string (header, body) and ignoring the bad status and bad reason errors given by Boost Beast.

# NSCP Problems

https://github.com/mickem/nscp/issues/610

### CODE REVIEW

**Comment by Al2Klimov** [comment]
AKAIK you've already opened an issue at NSCP. You could try to open also one at Beast.

But I'm afraid we can neither break present NSCP installations nor package a more recent Boost version (unless we build Icinga 2 w/ AppImage). So I'd just stall this... for a probably long time. Really, IMO we don't *have to* migrate *everything* to the new network stack.

**Comment by dnsmichi** [comment]
No, we won't stall this as I've already found out that you can overload such a beast parser to do certain actions on specific fields.

https://boostgsoc14.github.io/boost.http/#_implementing_boost_beast_parser_interface

Keeping the old legacy code is not an option. In doing so, we always have extra work with bugs and whatnot.

**Comment by dnsmichi** [comment]
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_http/custom_parsers.html

**Comment by dnsmichi** [comment]
Things I've tried such far:

# Beast HTTP Parser

## Read the header first and analyse the problem

```
	http::read_header(*tlsStream, buf, parser, ec);

	//This will always fail since NSClient's header is not RFC conform. https://github.com/mickem/nscp/issues/610
	if (ec)
		std::cerr << "Error reading header: " << ec.message();

```

```
	http::async_read(*tlsStream, buf, parser, [buf](boost::system::error_code ec, std::size_t length) {
			if (!ec)
				std::cout << "Got some data: " << boost::beast::buffers(buf.data());
			else
				std::cout << "Got error " << ec << " with data: " << boost::beast::buffers(buf.data());
		});
```

#4709 # Read and catch exceptions

An exception clears the read buffer unfortunately.

```
	try {
		http::read(*tlsStream, buf, parser);
	} catch (const boost::system::system_error& ex) {
		// Workaround for missing status/reason phrase in NSCP, https://github.com/mickem/nscp/issues/610
		if (ex.code() != http::error::bad_reason && ex.code() != http::error::bad_status) {
			std::cerr << "Failed to parse HTTP response from REST API at URL '" << url->Format(false, false) << "': "
					  << ex.what();
			throw ex;
		} else {

		}
	}
```

## Eager - don't stop on errors

Don't stop on errors. Doesn't work unfortunately.

```
	/* https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/using_http/buffer_oriented_parsing.html
	 *
	 * Normally the parser returns after successfully parsing a structured element (header, chunk header, or chunk body)
	 * even if there are octets remaining in the input. This is necessary when attempting to parse the header first, or
	 * when the caller wants to inspect information which may be invalidated by subsequent parsing, such as a chunk extension.
	 * The eager option controls whether the parser keeps going after parsing structured element if there are octets remaining
	 * in the buffer and no error occurs. This option is automatically set or cleared during certain stream operations to improve
	 * performance with no change in functionality.
	 */
	//parser.eager(true);
```

## Custom Parser Override

Method is never called.

```
template<
    bool isRequest,
    class Body,
    class Allocator = std::allocator<char>>
class nscp_parser : public boost::beast::http::parser<isRequest, Body, Allocator>
{
private:
	//The friend declaration is needed, otherwise the callbacks must be made public.
	friend class boost::beast::http::parser<isRequest, Body, Allocator>;

	void on_header_impl(boost::system::error_code& ec) {
		std::cout << "Reading the header is finished." << std::endl;

		//ec = {}; //ignore header parsing errors
		ec.assign(0, ec.category());
	}
};
```

```
	/* Use a custom parser which ignores header errors.
	 * Workaround for missing status/reason phrase in NSCP, https://github.com/mickem/nscp/issues/610
	 */
	/*
	nscp_parser<false, http::string_body> parser;
```

# Digging Deeper

Actually I've found out that a `buffer_body` is just a raw string representation, I had seen that already a while ago. I thought Beast would throw and error, but actually that only happens when the parser involves http::string_body. Tried to many things obviously.

## Raw Body Buffer + Custom Parsing

Since the returned header from NSCP is pretty useless (always OK, and some unwanted cookies), we can write a small algorithm which splits the raw data into lines and checks the first empty line, extracting the body afterwards.

This leads into more fun since there may be hidden Unicode chars.

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *=) $ check_nscp_api --host 10.0.10.120 --port 8443 --password icinga --query check_cpu --debug
Sending request to https://10.0.10.120:8443/query/check_cpu'.
Raw data: HTTP/1.1 200
Content-Length: 379
Set-cookie: token=CoRblsaqv6UpdvNIsNrmwUlN5u9t3tgj; path=/
Set-cookie: uid=admin; path=/

{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]}
Line: HTTP/1.1 200
Line: Content-Length: 379
Line: Set-cookie: token=CoRblsaqv6UpdvNIsNrmwUlN5u9t3tgj; path=/
Line: Set-cookie: uid=admin; path=/
Line:
Received body from NSCP: '{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]} '.
UNKNOWN - Cannot parse JSON response body '{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]} ', error: [json.exception.parse_error.101] parse error at line 1, column 380: syntax error while parsing value - invalid literal; last read: '"OK"}]}<U+0002>'; expected end of input
```

F*ck this. Say hello to boost::remove_if.

```
	// Strip any control characters
	body.erase(boost::remove_if(body, ::iscntrl), body.End());
```

## It works, finally.

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *=) $ check_nscp_api --host 10.0.10.120 --port 8443 --password icinga --query check_cpu --debug
Sending request to https://10.0.10.120:8443/query/check_cpu'.
Raw data: HTTP/1.1 200
Content-Length: 379
Set-cookie: token=OKlq8AzrHqDoGL4RHyqyX3g5Ayy61leD; path=/
Set-cookie: uid=admin; path=/

{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]}
Line: HTTP/1.1 200
Line: Content-Length: 379
Line: Set-cookie: token=OKlq8AzrHqDoGL4RHyqyX3g5Ayy61leD; path=/
Line: Set-cookie: uid=admin; path=/
Line:
Received body from NSCP: '{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]} '.
	JSON Body:
{
	header = {
		source_id = ""
	}
	payload = [ {
		command = "check_cpu"
		lines = [ {
			message = "OK: CPU load is ok."
			perf = [ {
				alias = "total 5m"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			}, {
				alias = "total 1m"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			}, {
				alias = "total 5s"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			} ]
		} ]
		result = "OK"
	} ]
}
check_cpu OK: CPU load is ok. | 'total 5m'=2%;80;90 'total 1m'=2%;80;90 'total 5s'=2%;80;90
```

The error parsing is not as robust as with other implementations, but actually I don't care about this unless NSCP fixes the header. The solution with nscp_api isn't optimal either, on the long run it will be replaced with something else.

Whenever the body is empty users get a generic error message and can use `--debug` to unveil more raw data. This is sufficient for the time being.

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *=) $ check_nscp_api --host 10.0.10.20 --port 8443 --password icinga --query check_cpu
UNKNOWN - No body received. Ensure that connection parameters are good and check the NSCP logs.
```

**Comment by dnsmichi** [comment]
Also found a way to deal only with the bad_status and bad_reason flags, to let the user know when there really was and HTTP error. Debug logs will always tell that we've just done a workaround - unless the API is fixed.

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *>) $ check_nscp_api --host 10.0.10.120 --port 8443 --password icinga --query check_cpu --debug
Sending request to https://10.0.10.120:8443/query/check_cpu'.
NSCP just sent a wrong status reason, we've ignored it. See https://github.com/Icinga/icinga2/pull/7142
Raw data: HTTP/1.1 200
Content-Length: 379
Set-cookie: token=CoRblsaqv6UpdvNIsNrmwUlN5u9t3tgj; path=/
Set-cookie: uid=admin; path=/

{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]}
Line: HTTP/1.1 200
Line: Content-Length: 379
Line: Set-cookie: token=CoRblsaqv6UpdvNIsNrmwUlN5u9t3tgj; path=/
Line: Set-cookie: uid=admin; path=/
Line:
Received body from NSCP: '{"header":{"source_id":""},"payload":[{"command":"check_cpu","lines":[{"message":"OK: CPU load is ok.","perf":[{"alias":"total 5m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 1m","int_value":{"critical":90,"unit":"%","value":2,"warning":80}},{"alias":"total 5s","int_value":{"critical":90,"unit":"%","value":2,"warning":80}}]}],"result":"OK"}]} '.
	JSON Body:
{
	header = {
		source_id = ""
	}
	payload = [ {
		command = "check_cpu"
		lines = [ {
			message = "OK: CPU load is ok."
			perf = [ {
				alias = "total 5m"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			}, {
				alias = "total 1m"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			}, {
				alias = "total 5s"
				int_value = {
					critical = 90.000000
					unit = "%"
					value = 2.000000
					warning = 80.000000
				}
			} ]
		} ]
		result = "OK"
	} ]
}
check_cpu OK: CPU load is ok. | 'total 5m'=2%;80;90 'total 1m'=2%;80;90 'total 5s'=2%;80;90
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *>) $
```

**Comment by dnsmichi** [comment]
Besides, this PR will fix code mistakes just like nested ternary operators and also the version handling - the plugin will just take the core version now.

```
michi@mbpmif ~/dev/icinga/icinga2 (feature/boost-asio-nscp *<>) $ check_nscp_api --version
Version: v2.10.4-698-g69a22d087
```

**Pull request merged**
