### PR TITLE
JsonRpcConnection#HandleAndWriteHeartbeats(): check !!#m_Endpoint

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@hardoverflow Please test whether v2.11.3 + this PR solves https://github.com/Icinga/icinga2/issues/7532#issuecomment-599966969 via packages from https://git.icinga.com/packaging/rpm-icinga2/-/jobs/45584 / "Job artifacts" / "Download".

**Comment by Al2Klimov** [comment]
Note: Commit is suitable for PR-ing into support/2.11.

**Comment by Al2Klimov** [comment]
@lippserd @htriem Do you agree that this may be included in v2.12?

**Comment by hardoverflow** [comment]
@Al2Klimov Installed v2.11.3-2-g3af1129 on the ConfigMaster.

**Comment by Al2Klimov** [comment]
Hello @hardoverflow!

Do you have already test results?

Best,
AK

**Comment by hardoverflow** [comment]
Last week, we deployed v2.11.3-2-g3af1129 on all masters and satellites in our env. We are still watching the following messages:
```
[2020-03-31 07:29:24 +0200] warning/JsonRpcConnection: Error while sending JSON-RPC message for identity 'client.fqdn'
Error: Connection reset by peer

        (0) icinga2: icinga::JsonRpcConnection::WriteOutgoingMessages(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >) (+0x274) [0xb65004]
        (1) /usr/lib64/icinga2/sbin/icinga2() [0xb653ea]
        (2) /usr/lib64/icinga2/sbin/icinga2() [0xb658c8]
        (3) libboost_context.so.1.69.0: make_fcontext (+0x2f) [0x7f76524a018f]

[2020-03-31 07:29:24 +0200] warning/JsonRpcConnection: API client disconnected for identity 'client.fqdn'
```
We could not observe that one of the masters crashed. However, we have observed the following.
2020-03-30 14_22_28-Icinga2 - Grafana
We have only seen this behavior once. We keep watching.

**Comment by Al2Klimov** [comment]
@lippserd Would you like to have this in v2.12?

**Comment by lippserd** [comment]
> @lippserd Would you like to have this in v2.12?

Yes indeed. Maybe even a 2.11.4.

**Pull request merged**
