### PR TITLE
Fix/cleanup init script

### PR DESCRIPTION
**Pull request by mphilipps**
hi,
Don't fancy myself much of a Bash programmer, but this is what I would do different.

Haven't tested it due to the required cmake interpolation, but each of the changes is pretty straight forward.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@lippserd There is something to complain about, but aren't we anyways waiting for SysVInit to die?

**Comment by dnsmichi** [comment]
@bsdlme Can you please have a look whether this fully works on FreeBSD?

**Comment by bsdlme** [comment]
FreeBSD uses its own rc-Script. So I'm fine with whatever you have. :)

**Comment by lippserd** [comment]
> @lippserd There is something to complain about, but aren't we anyways waiting for SysVInit to die?

If those changes fix something, we should have a look at them. But what do they fix? 😆

**Comment by lippserd** [comment]
Could anybody explain to me why and which changes are necessary at all? Do we have an issue/issues for reference?

**Comment by N-o-X** [comment]
@mphilipps please open separate PRs for your changes, if you think this is still needed. Also don't forget to add an explanation on why we need those changes. 

Thanks for your effort! 👍

**Pull request closed without merging**
