### PR TITLE
9443 Added examples for dynamic notification apply rule

### PR DESCRIPTION
**Pull request by Napsty**
Referring to https://dev.icinga.org/issues/9443. Added examples for dynamic/conditional notification apply rules in the documentation. Based on our discussion in http://www.monitoring-portal.org/wbb/index.php?page=Thread&postID=217609#post217609.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks! It looks like that you've accidently added everything below line 573 in a duplicated fashion. Can you please fix that? :)

Furthermore, please update the git author using your full name.

**Comment by gunnarbeutner** [comment]
Also, while you're at it: Replace "if(" with "if (" to match the style of the other examples in our documentation.

**Comment by Napsty** [comment]
Cleaned it up. Sorry, i must have mistakenly yanked too much content. 
Documentation style for the if clause is now also adapted. 
Full name (user.name) is set in my git client. Does it show up yet?

**Comment by dnsmichi** [comment]
Ok, thanks. One last thing - can you please squash these commits into a single one? :)

**Comment by Napsty** [comment]
Should be OK now, I hope. Please check.

**Comment by dnsmichi** [comment]
The if-conditions were missing a space, and overall I did a small review and edited serveral parts. Thanks for your contribution!

**Comment by Napsty** [comment]
OK so shall I apply the modifications back into my pull request or should I delete my branch?

**Comment by dnsmichi** [comment]
Please track the referenced commit at https://dev.icinga.org/issues/9443 - I've already fetched the patch, and amended my changes.

**Comment by Napsty** [comment]
OK all good then :+1:

**Pull request closed without merging**
