### PR TITLE
Overhaul Utility::FormatDateTime()

### PR DESCRIPTION
**Pull request by Al2Klimov**
* Backport of #10112

### CODE REVIEW

**Comment by yhabteab** [comment]
I don't think we should backport this to 2.13.x as it requires some codes that were not backported for their own reasons. I mean, do we really need this for a 2.13.10 bugfix release at all?

**Comment by julianbrost** [comment]
@Al2Klimov Why did you need to pull in the other PRs, i.e. what needs C++14?

**Comment by Al2Klimov** [comment]
> 'quoted' is not a member of 'std' [until C++14]

– https://github.com/Icinga/icinga2/actions/runs/10940187059/job/30372035371#step:4:2275

**Comment by julianbrost** [comment]
That function is only used in the tests three times for the error messages and can easily be replaced by adding the quotes manually to the surrounding strings. That sounds much more reasonable to me than bumping the C++ version for the old support branch just for this.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
