### PR TITLE
icinga2_execvpe(): use execvpe(3) where available

### PR DESCRIPTION
**Pull request by Al2Klimov**
to automatically use the latest available execvpe(3) version.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
No linker errors = fine.

**Comment by julianbrost** [comment]
I'm wondering: do we actually need an `execvpe()` implementation? Instead of `execvpe(file, argv, envp);`, shouldn't it be just fine to use `environ = envp; execvp(file, argv);` instead and thereby not rely on GNU extensions at all?

**Comment by Al2Klimov** [comment]
You mean to re-write the env by ourselves before execvp(3)?

**Comment by julianbrost** [comment]
Exactly.

**Comment by Al2Klimov** [comment]
Good idea. Not officially supported -hence not prio # 1- OS will profit from that, separate, construction area one day.

**Comment by julianbrost** [comment]
Subtle questions to watch out for when changing it that way:
- What happens if `PATH` is in `envp`?
- What effect would the change environment have on error handling?

**Comment by Al2Klimov** [comment]
Ah, I already see... this PR is far less dangerous than what you suggest. :)

**Pull request closed without merging**
