### PR TITLE
Add the Option to disable RetryWrites to CheckCommand of mongodb

### PR DESCRIPTION
**Pull request by atwebm**
This adds the Option to disable Retry Writes to the CheckCommand definition for mongodb.
This fixes a Problem in check_mongodb.py with newer MongoDB-Versions.
https://github.com/mzupan/nagios-plugin-mongodb/commit/0377f5de7cb65681ceae220c11e91eb4a8681f6b

### CODE REVIEW

**Comment by atwebm** [comment]
@cla-bot check

**Comment by atwebm** [comment]
The CLA comparision don`t work for my Github-Account.
But this is only a Configuration-Option from the Upstream Check Script. Nothing of any Invention.

**Comment by atwebm** [comment]
I've no Idea how to do that.
My main profession is Server-Infrastructure but not so much Dev.

**Comment by Al2Klimov** [comment]
Shall I fix it for you?

**Comment by atwebm** [comment]
That would be nice.

I only want to add the Config-Option from the Upstream-Project so that other User can use it as well as they need that for newer MongoDB.

**Comment by Al2Klimov** [comment]
Now **you** should (only if you're the author of all commits!):

* git checkout feature/itl-check-mongodb-retrywrites
* git reset --hard 99efdea8dd61ffca1d2eb913033480409439ae99
* git commit --amend --no-edit --reset-author
* git push -f

**Comment by atwebm** [comment]
Having an eMail-Address in the Github-Account and using a signed Commit was not enough for the cla-bot.
The Adding of an eMAil-Address to a Repo needs a new Commit.
This is the Reason, why there were two commits before.
With your help, I could striped this down to one commit.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
And the documentation?

**Review by Al2Klimov — APPROVED** [review]

**Comment by Al2Klimov** [comment]
## TODO (on our side) while merging

squash

**Pull request merged**
