### PR TITLE
Docs: Monitoring Basics: make Event Commands not a subsection of Dependencies

### PR DESCRIPTION
**Pull request by Al2Klimov**
but an own and equal section.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Please render it on the docs site (staging, not prod, of course) for before/after comparison.

**Review by Al2Klimov — COMMENTED** [review]
Not a must-have for 2.14, but a must-have for docs site – and 2.14 is the next latest tag 🤷‍♂️

## Before

Opera Momentaufnahme_2023-04-17_105745_localhost

## After

Opera Momentaufnahme_2023-04-17_110156_localhost

**Review by julianbrost — CHANGES_REQUESTED** [review]
It looks like the order of sections is wrong, not the level. `### Event Commands` should be a subsection of `## Commands`, but somehow `## Dependencies` ended up between `### Notification Commands` and `### Event Commands`.

**Review by Al2Klimov — COMMENTED** [review]
Opera Momentaufnahme_2023-04-17_134040_localhost

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
