### PR TITLE
Apply rules: import default templates first

### LINKED ISSUE #7914: no override for default service template on apply rules possible
## Expected Behavior
It should be possible to override variables and parameters of services, even if these definitions are initial in a default service template and apply rules are used.

## Current Behavior
Definition in a default service template could not be overwritten in a service that is applied on a host with services apply rules. For example if you enable enable_flapping in a default service template, it is not possible to disable this parameter for applied services. It works well for services without apply rules, but not for services with apply rules.

## Possible Solution
Looks like for apply rules the default template is not processed in the right order.

## Steps to Reproduce (for bugs)
```
template Service "default-service" default {
 vars.example01 = false
}

template Service "example-service" {
 vars.example02 = false
}

apply Service "apt" {
  import "example-service"
…
  enable_flapping = false
  vars.example01 = true
  vars.example02 = true
  vars.example03 = true
  assign where host.vars.agent && host.vars.operating_system == "linux"
}
```
Output for this object:
```
admin@icinga01:/etc/icinga2/zones.d# icinga2 object list --type service --name 'adminvm.domain.tld!apt'
Object 'adminvm.domain.tld!apt' of type 'Service':
  % declared in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
  * __name = "adminvm.domain.tld!apt"
  * action_url = ""
  * check_command = "apt"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 79:3-79:23
  * check_interval = 86400
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 80:3-80:21
  * check_period = "business-8x4"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 81:3-81:31
  * check_timeout = null
  * command_endpoint = "adminvm.domain.tld"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 83:3-83:45
  * display_name = "apt"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = true
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 84:3-84:25
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 2:3-2:24
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "adminvm.domain.tld"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "apt"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
  * retry_interval = 900
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 82:3-82:22
  * source_location
    * first_column = 1
    * first_line = 77
    * last_column = 19
    * last_line = 77
    * path = "/etc/icinga2/zones.d/global-templates/services.conf"
  * templates = [ "apt", "example-service", "default-service" ]
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 73:1-73:34
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 1:0-1:41
  * type = "Service"
  * vars
    * example01 = false
      % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 85:3-85:23
      % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 3:3-3:24
    * example02 = true
      % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 74:3-74:24
      % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 86:3-86:23
    * example03 = true
      % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 87:3-87:23
  * volatile = false
  * zone = "master"
    % = modified in '/etc/icinga2/zones.d/global-templates/services.conf', lines 77:1-77:19
```

In would expect that `example01 = true`, like all others. Without any apply rule, it works well btw, happens only with apply rules and default templates.

## Context
I just try to have flapping protections, or some other things global, but with an option to override this on some services only.

## Your Environmen
* Version used (`icinga2 --version`): r2.11.3-1
* Operating System and version: Ubuntu 18.04.4 incl all patches
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): Everything OK ;)

### PR DESCRIPTION
**Pull request by Al2Klimov**
... to allow to override the attributes they set.

fixes #7914

### CODE REVIEW

**Comment by Yonas-net** [comment]
Testprotocol:
The output looks like this without overriding variables and parameters of services, when if these definitions are initial in a default service template and apply rules are used.
```
Object 'yonas-yonas.int.netways.de!apt' of type 'Service':
  % declared in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * __name = "yonas-yonas.int.netways.de!apt"
  * action_url = ""
  * check_command = "apt"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 38:3-38:23
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "apt"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 39:3-39:25
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "yonas-yonas.int.netways.de"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "apt"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * retry_interval = 60
  * source_location
    * first_column = 1
    * first_line = 35
    * last_column = 19
    * last_line = 35
    * path = "/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf"
  * templates = [ "apt", "example-service", "default-service" ]
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 31:1-31:34
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 27:1-27:42
  * type = "Service"
  * vars
    * example01 = false
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 40:3-40:23
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 28:2-28:23
    * example02 = true
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 32:2-32:23
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 41:3-41:23
    * example03 = true
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 42:3-42:23
  * volatile = false
  * zone = ""
```
but with this branch you should be able to override variables and parameters and looks like this...
```
Object 'yonas-yonas.int.netways.de!apt' of type 'Service':
  % declared in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * __name = "yonas-yonas.int.netways.de!apt"
  * action_url = ""
  * check_command = "apt"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 38:3-38:23
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "apt"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 39:3-39:25
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "yonas-yonas.int.netways.de"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "apt"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * notes = ""
  * notes_url = ""
  * package = "_etc"
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
  * retry_interval = 60
  * source_location
    * first_column = 1
    * first_line = 35
    * last_column = 19
    * last_line = 35
    * path = "/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf"
  * templates = [ "apt", "default-service", "example-service" ]
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 35:1-35:19
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 27:1-27:42
    % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 31:1-31:34
  * type = "Service"
  * vars
    * example01 = true
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 28:2-28:23
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 40:3-40:23
    * example02 = true
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 32:2-32:23
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 41:3-41:23
    * example03 = true
      % = modified in '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/conf.d/services.conf', lines 42:3-42:23
  * volatile = false
  * zone = ""
```
I know you don't see a big difference there but if you take a closer look you can see that the default services come before the example services and the parameter example01 is set to true

**Review by yhabteab — DISMISSED** [review]

**Comment by Al2Klimov** [comment]
@Yonas-net Please share the config you added to the default one to make this test.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by dwt** [comment]
Out of interest and because I'm affected by this bug - what is the reason keeping this from being merged? I'd rather wait for the fix than invest time in workarounds, but if this takes another 2 years to get merged, I should rather get started adding pull requests that document the bug and how to work around it.

**Comment by dwt** [comment]
@Al2Klimov Could you give some input what is holding this up? It seems like a pretty desirable fix to me?

**Review by julianbrost — APPROVED** [review]
You'd naturally expect the following config to generate two identical services (apart from the name) as they set the exactly same attributes, just one uses `object` and the other one `apply`:

```
object Host "github-7929" {
	check_command = "dummy"
}

template Service "github-7929" default {
	vars.github7929_default1 = "template"
	vars.github7929_default2 = "template"
	vars.github7929_default3 += 1
	vars.github7929_default4 += 1
}

object Service "object" {
	host_name = "github-7929"

	check_command = "dummy"
	vars.github7929_default1 = "service"
	vars.github7929_default3 = 42
}

apply Service "apply" {
	assign where host.name == "github-7929"

	check_command = "dummy"
	vars.github7929_default1 = "service"
	vars.github7929_default3 = 42
}
```

### Before (cfa6f1c6a)

Both services get different attributes, due to one evaluating the default template first, and the other one last:

```console
$ curl -iskSu root:icinga -H 'Accept: application/json' -H 'X-HTTP-Method-Override: GET' 'https://127.0.0.1:5665/v1/objects/services' -d '{"services":["github-7929!apply","github-7929!object"], "attrs":["vars"], "pretty":true}'
HTTP/1.1 200 OK
Server: Icinga/v2.13.0-239-gcfa6f1c6a
Content-Type: application/json
Content-Length: 876

{
    "results": [
        {
            "attrs": {
                "vars": {
                    "github7929_default1": "template",
                    "github7929_default2": "template",
                    "github7929_default3": 43,
                    "github7929_default4": 1
                }
            },
            "joins": {},
            "meta": {},
            "name": "github-7929!apply",
            "type": "Service"
        },
        {
            "attrs": {
                "vars": {
                    "github7929_default1": "service",
                    "github7929_default2": "template",
                    "github7929_default3": 42,
                    "github7929_default4": 1
                }
            },
            "joins": {},
            "meta": {},
            "name": "github-7929!object",
            "type": "Service"
        }
    ]
}
```

### After (3a28b4a50: merge of f311dfb77 (this PR) and cfa6f1c6a (current master))

Now both services have identical attributes:

```console
$ curl -iskSu root:icinga -H 'Accept: application/json' -H 'X-HTTP-Method-Override: GET' 'https://127.0.0.1:5665/v1/objects/services' -d '{"services":["github-7929!apply","github-7929!object"], "attrs":["vars"], "pretty":true}'
HTTP/1.1 200 OK
Server: Icinga/v2.13.0-241-g3a28b4a50
Content-Type: application/json
Content-Length: 875

{
    "results": [
        {
            "attrs": {
                "vars": {
                    "github7929_default1": "service",
                    "github7929_default2": "template",
                    "github7929_default3": 42,
                    "github7929_default4": 1
                }
            },
            "joins": {},
            "meta": {},
            "name": "github-7929!apply",
            "type": "Service"
        },
        {
            "attrs": {
                "vars": {
                    "github7929_default1": "service",
                    "github7929_default2": "template",
                    "github7929_default3": 42,
                    "github7929_default4": 1
                }
            },
            "joins": {},
            "meta": {},
            "name": "github-7929!object",
            "type": "Service"
        }
    ]
}
```

Also the values correspond to the default template being imported first, just [as documented](https://icinga.com/docs/icinga-2/latest/doc/17-language-reference/#template-imports):

> Default templates are imported before any other user-specified statement in an object definition is evaluated.

**Pull request merged**
