### PR TITLE
snmpv3 CheckCommand section improved

### PR DESCRIPTION
**Pull request by ruzickap**
I improved the snmpv3 CheckCommand section - it was missing some parameters.

https://dev.icinga.org/issues/9827

Regards

PetrR

### CODE REVIEW

**Comment by ruzickap** [comment]
Tab added as required.

**Comment by lazyfrosch** [comment]
Can you please rebase/squash your commits and just force push to the same branch?

**Comment by ruzickap** [comment]
Hello.

I haven't done it before and I'm not very experienced with git. Anyway I used these two commands:

git rebase -i HEAD~2
git push --force

and I hope I did it right.

Please let me know.

Thank you

PetrR

**Comment by lazyfrosch** [comment]
LGTM :+1:

**Comment by dnsmichi** [comment]
There's one indent too much for the arguments section (3 instead of 2). I'll fix that while reviewing the patch, thanks.

**Comment by dnsmichi** [comment]
https://dev.icinga.org/issues/9827#note-5

**Pull request closed without merging**
