### PR TITLE
CLI: Allow to specify the cluster log replay duration, defaults to 0 for agents

### PR DESCRIPTION
**Pull request by dnsmichi**
refs #7796

### CODE REVIEW

**Comment by mcktr** [comment]
Added a small typo fix. Just fixing it was faster than comment/review. :-)

**Comment by dnsmichi** [comment]
Ah, thanks for catching this :)

**Comment by dnsmichi** [comment]
Undecided about the version, if that gets merged for 2.13, the upgrading docs need to be adjusted.

**Comment by dnsmichi** [comment]
Discussed this with @lippserd ... on the agent itself, this does not have much impact, aka no local agents. I will come up with a different PR for the master command_endpoint side.

**Pull request closed without merging**
