### PR TITLE
Dependency redundancy groups, take 2

### PR DESCRIPTION
**Pull request by nwf**
This subsumes #8218 (and preserves its commit as the base of the stack here; full credit where it's due!) while correcting a few minor issues, adding tests, and expanding a smidgen on documentation.

Ping @N-o-X, @lippserd, @julianbrost, and @efuss.

### CODE REVIEW

**Comment by efuss** [comment]
Thanks a lot for picking this up. It's ensuring to know that I may have not completely wasted my time as someone else goes into the trouble of correcting my mistakes, sensibly expanding the documentation and adding the tests.

After re-reading the documentation of `std::unordered_map::insert()`, you seem to be entirely correct in your correction in
71d26b41ce83a2f030f3b9103b96b2aab9afb102. The only thing I don't get is why you deleted the word _tentative_ in the comment. I wanted to make clear that the entry may get over-written by a fulfilled dependency later on (in contrast to a fulfilled one, which doesn't get overwritten).

Your additional commentary also seem perfectly reasonable.

Thanks for providing the tests.

**Comment by nwf** [comment]
Hm, I amn't sure why I removed _tentative_ either; I'll put that back.  Good catch.

**Comment by efuss** [comment]
Unfortunately, the CLA may be a substantial hurdle.

Icinga GmbH, a german company, is asking me, a german citizen, to accept a contract that is not only english-language, but also using anglo-american jurisdiction terms that have no german equivalent.

As my contribution was done as part of my work, I need approval by my employer (Universität Bonn) because they hold the _Verwertungsrechte_ on my work. In order to be able to do that, I would need the text of the agreement, but all I'm able to obtain so far is a raster image of one of the two forms of the CLA.

I'm afraid I'm going to have some fun with both Icinga GmbH and our _Justitiariat_ on the matter. It already cost me more time to dig into these matters than to look into @nwf's improvements/correction of #8218 (and understanding which mistakes I made using `std::unordered_map::insert()`).

**Comment by nwf** [comment]
The CLA seems... new?  (It was not flagged up when I originally opened the PR, which *also* seems like it might be a bug?)

My contribution here was done off company time, and so, I believe, does not interact with my employer, but nevertheless I will check with them.  The CLA being available only as a PNG, without a textual equivalent, is really not great, as is the fact that https://icinga.com/company/contributor-agreement/ links to those PNGs _behind a form gating access on an email address_, which suggests that the contract could be (subtly or otherwise) manipulated per user, making independent review essentially impossible.

FWIW, I'm happy for my changes here to be considered generically released under GPLv2-or-later, which should be all that is required for Icinga to use them, without any additional CLA in place.

**Comment by bobapple** [comment]
Thank you for your feedback! I agree that it is sometimes easier to review the CLA previously. Therefore I added the documents as PDFs to our website: https://icinga.com/company/contributor-agreement/

**Comment by nwf** [comment]
I'm happy to assign (C) of my (trivial) bits of this PR to Icinga GmbH, but that may be moot depending on @efuss's conclusion.  Any news there?

**Comment by efuss** [comment]
I've asked the university's legal department for advice and approval. I'm not allowed to sign anything without their consent.

If and when they approve it, the best way forward may be for me to incorporate @nwf's corrections to my erroneous use of `std::unordered_map::insert()` to #8218 so we have working code there. It would then be up to Icinga GmbH whether they incorporate @nwf's greatly improved documentation and his tests or insist on the CLA.

**Comment by efuss** [comment]
Status update: The legal departement has approved signing the CLA. However, we now need authority by the university's _Kanzler_ (head of administration), which may take a while.

Things were much easier in pre-CLA times.

**Comment by bobapple** [comment]
@cla-bot check

**Comment by efuss** [comment]
We got authority from the _Kanzler_, so I acceppted the CLA yesterday.

**Comment by efuss** [comment]
As proposed, I merged @nwf's fixes into #8218.

I guess I cant' do much about the tests or the greatly improved documentation.

**Pull request closed without merging**
