### PR TITLE
[WIP] Feature/notification rework

### PR DESCRIPTION
**Pull request by Crunsher**
This is an attempt in rewriting the NotificationComponent and aims to squash multiple issues we have with the current implementation.
The first step was adding a Scheduler for ReNotifications similar to that used in the CHeckerComponent.

In its current state this PR works, except for one or two Notifications Types, like the current one. The next Task is to find a solution for guaranteeing the execution of Notifications in a HA setup, moving more Notification related code from the lib/icinga to the NotificationComponent and writing Unit Tests.

refs #7161

Note: I rebased this on the master, squashing and reordering commits. It currently does not work.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please also add function header docs which allows to better understand the purpose.

**Comment by dnsmichi** [comment]
Please update the current status, and provide a list of open TODOs.

**Comment by Crunsher** [comment]
Currently the Component is in a state where a lot works and a lot dosen't. A few things are unclear yet but right now I'll be focusing on UnitTests.

TODOs:
* Clear up certain Notification interactions
* Downtimes currently do weird things
* Restart behaviour
* HA still is unsolved
* I started moving more notification functionality into NotificationComponent, ongoing
* Tests, getting the NotificationComponent to run with Unittests is my top priority right now

**Comment by Crunsher** [comment]
Update: Currently Problem, Recovery, Downtime and Flapping notifications work as far as I can tell. There is an issue with Acknowledgements and Custom Notifications are still TODO.

**Comment by dnsmichi** [comment]
This didn't go as planned, unfortunately I have to remove this.

**Pull request closed without merging**
