### PR TITLE
Validate Zone::GetLocalZone() before using

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Just FYI: W/o this a freshly installed Icinga 2 Git master (single node instance) crashes reproducibly after a few minutes.

**Comment by mcktr** [comment]
@Al2Klimov I can't reproduce the crash. I used the latest master at ed85d2528. Is there anything special I to trigger the crash?

**Comment by Al2Klimov** [comment]
No, [not really](https://youtu.be/xE9h15TWKWs).

**Comment by Al2Klimov** [comment]
Finally someone who accepts YT vids as POCs instead of complaining about them! 😉

**Pull request merged**
