### PR TITLE
Add vars for all check_swap args

### PR DESCRIPTION
**Pull request by dupondje**
The check_swap has support for some additional arguments.
This diff adds support for them.

Also the % was moved from the checkcommand args to the default values.
This way you could define a static value instead of a percentage.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
What about users who rely on the old behavior of the threshold arguments?

**Comment by dupondje** [comment]
Well with this patch its more general like the check_disk check which also has % only in the default vars assignment, and not in the CheckCommand itself.

Or we could add a vars.swap_wfree_int, and set the command arguments without % if swap_wfree_int is defined for example.
But I think this will make it more difficult then needed?

**Comment by gunnarbeutner** [comment]
Well, my point is that this breaks existing configs where users have custom values for swap_wfree/swap_cfree. I'd prefer a change that is backwards-compatible.

**Comment by dupondje** [comment]
This should do :)

**Comment by gunnarbeutner** [comment]
Icinga ticket: https://dev.icinga.org/issues/12392

**Pull request closed without merging**
