### PR TITLE
Allow to use local mode of hpasm. fixes #4985

### LINKED ISSUE #4985: Allow hpasm command from ITL to run in local mode
The `check_hpasm` Plugin allows for running as a local or remote plugin.

Local mode uses a HP CLI tool, remote uses SNMP.

Choosing between both modes works implicitely by setting or omitting the `-H` attribute. See https://labs.consol.de/nagios/check_hpasm/index.html for more information.

The current `CheckCommand` implementation for `hp_asm` automatically sets the `-H` to `check_address` and flags it as required. Since the documentation shows it the other way round (`-H` as optional) it seems like some patched the ITL integration later to have it look like all other commands not knowing that this one is special.

We should change the behaviour and add a note to the documentation so people don't think this is an error.

### PR DESCRIPTION
**Pull request by widhalmt**
Remove default value and "required" for `address` in hpasm ITL listing
Add a note to documentation why this special check should not have a default address

(I know I should have named the branch fix/hpasm-4985 but I thought this wouldn't matter with PRs - I'll use this naming scheme the next time)

### CODE REVIEW

**Comment by widhalmt** [comment]
Please note, if someone relies on the default values, this change might break the setup since this changes the default behaviour from remote to local. But since there is no way to "unset" the defaults this might be the only way.

**Comment by dgoetz** [comment]
You could have a look at CheckCommand swap or postgres for similar behaviour to get a non breaking change by adding an additional boolean attribute.

**Comment by widhalmt** [comment]
Thanks for the hint, @dgoetz . I'll look into it.

**Comment by widhalmt** [comment]
I changed this PR so the new version won't change the commands default behavior. Since I don't carry HP servers with me, I can't actually test it but I ran `icinga2 daemon -C` on it which succeeded. Maybe I can ask my customers tomorrow to test the new CheckCommand version.

**Comment by widhalmt** [comment]
Changed `hpasm_local` to `hpasm_remote`. Thanks to @sahnd for reporting the mixed up `set_if`. 

I'll try and have it tested today.

**Comment by gunnarbeutner** [comment]
Can you please squash your Git commits in such a way that temporary "internal" changes that happened during the development process are not externally visible as separate commits?

**Comment by widhalmt** [comment]
I tried to, but I failed. I will come to you so you can show me how to work this dark git magic you are talking about, @gunnarbeutner .

**Comment by dnsmichi** [comment]
Squashing three commits into one...

```
git rebase -i HEAD~3
```

`pick` the first one, change the rest to `squash`. Save and proceed. Edit the final rebased squashed commit with a proper commit message.

In case it's unclear just do a drive-by in meeting room E ;-)

**Comment by widhalmt** [comment]
Thank you! I hope this worked out. (I failed at leaving one `pick`, I changed all into `squash`)

**Comment by gunnarbeutner** [comment]
It seems there are still 5 commits. See https://github.com/Icinga/icinga2/pull/4986/commits for details.

**Comment by lazyfrosch** [comment]
How about using Squash & Merge from GitHub? You can even fixup his branch yourself :)

**Comment by dnsmichi** [comment]
We'll need sort of squash, rebase, amend/reword and merge here. That's not available via GUI, and as such requires cli commands to fix this. I'd like to see clean PRs in the future which is why it does not hurt to learn GitHub and rebasing together.

```
git remote add widhalmt https://github.com/widhalmt/icinga2.git
git fetch widhalmt
git checkout -b feature/itl-hpasm-4986 widhalmt/hpasm
git rebase master

-> fix conflicts
git rebase -i HEAD~4

pick -> squash except for the first line

git commit --amend -s
git checkout master
git merge feature/itl-hpasm-4986
```

I've slightly modified some words and grammar inside the documentation and amended those changes as well.

**Pull request closed without merging**
