### PR TITLE
Make notification mails more readable. Remove redundancy and cruft.

### PR DESCRIPTION
**Pull request by cycloon**
I tried to make Icinga's notification mails more readable, especially on mobile devices. Would be glad, if you could incorporate the changes:
- remove the Icinga 2 name.
- remove cruft around the primary status message
- do not precede URL with anything, it speaks for itself
- remove display names from table, as they are also in the subject and in the primary status message

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks. Opinions on layout and design always differ, and therefore these scripts are located in /etc/icinga2/scripts where user can modify them. Package updates won't override local user changes.

Imho we should leave the notification scripts as is for now. Waiting for others to comment.

**Comment by dnsmichi** [comment]
Been thinking about it for a while. Since we probably need to incorporate more changes for making HOSTADDRESS optional in #5474 it would be worthwhile to remove redundant details. Thanks for the pointer, I'll review the changes.

**Comment by dnsmichi** [comment]
Short note for future PRs: Please use a specific branch in your forked repository to commit changes for PRs. I will force push your master remotely via this PR now.

**Comment by dnsmichi** [comment]
https://www.icinga.com/2017/08/23/advisory-for-icinga-2-v2-7-update-and-mail-notification-scripts/

**Comment by cycloon** [comment]
Oh I missed this. Great, and thank you for reconsidering.

**Pull request merged**
