### PR TITLE
Raise .NET target version to 4.6

### LINKED ISSUE #7090: Windows Agent Wizard: Evaluate which .NET framework is required
## Describe the solution you'd like

Right now, we'll need .NET 2.0 provided by .NET 3.5, requiring an additional package during installation. Modern systems already provide 4.6.1 and newer.

Current target platforms:

- Server 2016/2019
- 10

Also, evaluate whether we can enhance the version getter with the new required OS versions.

## Additional context

- Windows Server 2012 was EOL on 9.10.2018: https://support.microsoft.com/de-de/lifecycle/search?alpha=windows%20server%202012
- Windows was EOL'd on 9.1.2018: https://support.microsoft.com/de-de/lifecycle/search?alpha=windows%208

### PR DESCRIPTION
**Pull request by mcktr**
This raises the target .NET framework version to 4.6 and drops support for .NET 2.0/3.5 as runtime platform. This also implements a check into our Windows installer for the required .NET framework version (at least .NET 4.6 is required).

**ToDo:**

- [x] Tests
    - [x] Windows Server 2008 R2 (+ .NET 4.6)
    - [x] Windows Server 2012 R2 (+ .NET 4.6)
    - [x] Windows 10
    - [x] Windows Server 2016
    - [x] Windows Server 2019
- [x] Installation documentation
- [x] Upgrading documentation
- [x] Development documentation
   
fixes #7090

### CODE REVIEW

**Comment by mcktr** [comment]
@lazyfrosch would it be possible to trigger a build in the Icinga build infrastructure based on this branch? Just to ensure everything will build fine prior merging.

**Comment by lazyfrosch** [comment]
I started a build here https://git.icinga.com/packaging/windows-icinga2/pipelines/3860

**Comment by lazyfrosch** [comment]
pinging @LordHepipud

**Comment by LordHepipud** [comment]
I have tested the Snapshot Builds on

* Windows 2012
* Windows 2016
* Windows 2019

Those systems were freshly installed and natively supported .NET Framework 4.6. The Agent Wizard worked without problems, so I see no problem here.
If anyone is still using older systems without .NET 4.6 installed, I would recommend them to update (which is normally pushed out by Microsoft anyway).

From my point I fully agree on this and see no reason why we shouldn't move on here.

**Comment by mcktr** [comment]
@LordHepipud Thanks for testing. Windows Server 2012 (R2) comes by default with .NET Framework 4.5, didn't the installation wizard complain about a missing .NET Framework 4.6?

**Comment by LordHepipud** [comment]
@mcktr Nope, neither on Windows 2012 nor Windows 2012 R2. Through Windows Updates you are receiving .NET 4.6

**Comment by dnsmichi** [comment]
Thanks for taking care, this solves a long-lasting headache.

**Pull request merged**
