### PR TITLE
Add documentation about automatic service restarts with systemd

### PR DESCRIPTION
**Pull request by ekeih**
Hi,

as discussed in #5721 I added some documentation about automatic service restarts with systemd. Please let me know if you think there is a better place in the docs.

Best regards
Max

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Looks good to me. 👍  I'll leave it to @dnsmichi to figure out whether this is really something we want. :)

**Comment by dnsmichi** [comment]
Imho this should not be put into "getting started", but is more of an advanced hint. Users who just read through getting started shouldn't need to deal with that.

I'll think about it after 2.8, thanks.

**Comment by ekeih** [comment]
I think it makes sense at this place because it is the only part of the docs about systemd. We could separate it from the rest with another headline "Tip" or something similar.

As an alternative we could add a new section "Running in Production / Best Practices" that includes tips like that. Currently this would be a very small section but maybe more people would add content to it.

I will wait for your feedback after 2.8. Good luck with the release! 👍

**Comment by dnsmichi** [comment]
To be honest, that's just my own level of perfection. I'll take your patch as is, thank you 👍

**Pull request merged**
