### PR TITLE
GHA: Drop ubuntu 23.{04,10} (EOL)

### PR DESCRIPTION
**Pull request by yhabteab**
https://ubuntu.com/about/release-cycle

### CODE REVIEW

**Comment by yhabteab** [comment]
Fixes https://github.com/Icinga/icinga2/actions/runs/12008161850/job/33470245406?pr=10210

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
# TODO

* [ ] https://git.icinga.com/packages/tooling/ci-templates/-/merge_requests/93

Also, if(!) this is due to EOL (this week doesn't match the EOL dates, though), why does 23.04 still work?

**Comment by yhabteab** [comment]
> Also, if(!) this is due to EOL (this week doesn't match the EOL dates, though), why does 23.04 still work?

Idk! But the GitHub Actions have been failing since last week, not just today. https://github.com/Icinga/icinga2/pull/10248.

**Comment by julianbrost** [comment]
> Also, if(!) this is due to EOL (this week doesn't match the EOL dates, though), why does 23.04 still work?

Dunno. Delays? Someone forgot it 6 months ago?

Anyway, now both seem to be gone:

```console
% docker run --rm -it ubuntu:23.04
Unable to find image 'ubuntu:23.04' locally
23.04: Pulling from library/ubuntu
6360b3717211: Pull complete 
Digest: sha256:5a828e28de105c3d7821c4442f0f5d1c52dc16acf4999d5f31a3bc0f03f06edd
Status: Downloaded newer image for ubuntu:23.04
root@d6b4d24829a0:/# apt update
Ign:1 http://security.ubuntu.com/ubuntu lunar-security InRelease
Err:2 http://security.ubuntu.com/ubuntu lunar-security Release
  404  Not Found [IP: 185.125.190.81 80]
Ign:3 http://archive.ubuntu.com/ubuntu lunar InRelease
Ign:4 http://archive.ubuntu.com/ubuntu lunar-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu lunar-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu lunar Release
  404  Not Found [IP: 91.189.91.82 80]
Err:7 http://archive.ubuntu.com/ubuntu lunar-updates Release
  404  Not Found [IP: 91.189.91.82 80]
Err:8 http://archive.ubuntu.com/ubuntu lunar-backports Release
  404  Not Found [IP: 91.189.91.82 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu lunar-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu lunar-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```console
% docker run --rm -it ubuntu:23.10
Unable to find image 'ubuntu:23.10' locally
23.10: Pulling from library/ubuntu
cd0bff360add: Pull complete 
Digest: sha256:fd7fe639db24c4e005643921beea92bc449aac4f4d40d60cd9ad9ab6456aec01
Status: Downloaded newer image for ubuntu:23.10
root@437567e3c930:/# apt update
Ign:1 http://security.ubuntu.com/ubuntu mantic-security InRelease
Err:2 http://security.ubuntu.com/ubuntu mantic-security Release
  404  Not Found [IP: 185.125.190.81 80]
Ign:3 http://archive.ubuntu.com/ubuntu mantic InRelease
Ign:4 http://archive.ubuntu.com/ubuntu mantic-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu mantic Release
  404  Not Found [IP: 91.189.91.82 80]
Err:7 http://archive.ubuntu.com/ubuntu mantic-updates Release
  404  Not Found [IP: 91.189.91.82 80]
Err:8 http://archive.ubuntu.com/ubuntu mantic-backports Release
  404  Not Found [IP: 91.189.91.82 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu mantic-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu mantic-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu mantic-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Review by julianbrost — APPROVED** [review]

**Comment by yhabteab** [comment]
@cla-bot check

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
