### PR TITLE
Add lmsensors CheckCommand definition

### PR DESCRIPTION
**Pull request by BarbUk**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Here I am not sure about the naming. `temp` is too generic, this could be meant for temporary files or temperature.

**Comment by BarbUk** [comment]
it was named like the check from https://github.com/jackbenny/check_temp.
I can change it to check_lmsensors to better reflect the software used.

**Comment by BarbUk** [comment]
I've merged the master into this branch to resolve the conflicts and renamed the checkcommand to check_lmsensors.

Let me know if it's ok or if you want a new PR.

**Comment by dnsmichi** [comment]
I don't mind with clear merges, this is part of a typical git workflow. Thanks!

**Pull request merged**
