### PR TITLE
ApiListener: wait at most 10s for the 1st byte

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
```
[2020-02-05 17:26:16 +0100] critical/ApiListener: Client TLS handshake failed (from [::ffff:127.0.0.1]:60900): Operation canceled
[2020-02-05 17:26:18 +0100] information/ApiListener: New client connection from [::ffff:127.0.0.1]:60901 (no client certificate)
[2020-02-05 17:26:28 +0100] information/ApiListener: No data received on new API connection from [::ffff:127.0.0.1]:60901. Ensure that the remote endpoints are properly configured in a cluster setup.
[2020-02-05 17:26:38 +0100] information/ApiListener: New client connection from [::ffff:127.0.0.1]:60905 (no client certificate)
[2020-02-05 17:26:38 +0100] information/HttpServerConnection: Request: GET /v1/ (from [::ffff:127.0.0.1]:60905), user: root, agent: curl/7.64.1).
```

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] #7809

**Comment by Al2Klimov** [comment]
@lippserd Would you like to have this in v2.12?

**Comment by lippserd** [comment]
@Al2Klimov 2.13. is fine for this feature.

**Comment by julianbrost** [comment]
This somewhat overlaps with #8769, but that one should catch more cases. Do we want this nonetheless? For now the other PR is quite generic and just some sort of last resort (but that might be subject to change).

**Comment by julianbrost** [comment]
If nobody objects, I'd close this in favor of #8769

**Pull request closed without merging**
