### PR TITLE
Add Edit button to Windows Setup Wizard

### LINKED ISSUE #4128: [dev.icinga.com #11611] Add "Edit" button to Windows wizard
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11611

**Created by mfriedrich on 2016-04-18 13:05:00 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-18 13:05:00 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

**Attachments**

* [windows_icinga2_setup_wizard_edit_button.png](https://dev.icinga.com/attachments/download/3299/windows_icinga2_setup_wizard_edit_button.png) mfriedrich - _2016-04-18 13:04:39 +00:00_

### PR DESCRIPTION
**Pull request by mcktr**
This adds an Edit button to the Windows setup wizard.

icinga2-win-edit-button

The button is only enabled when there are endpoint entries. 

fixes #4128

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Oh, that's pretty sweet! Can you merge your two commits into one though? :)

**Comment by mcktr** [comment]
Thanks. I squashed the two commits into one. :)

**Comment by dnsmichi** [comment]
One thing to note once this PR gets merged - the documentation screenshots need to be updated as well.

Keep the same details as before (you can fake them, don't need to have a running setup).

https://github.com/Icinga/icinga2/blob/master/doc/images/distributed-monitoring/icinga2_windows_setup_wizard_01.png
https://github.com/Icinga/icinga2/blob/master/doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02.png
https://github.com/Icinga/icinga2/blob/master/doc/images/distributed-monitoring/icinga2_windows_setup_wizard_03.png

If not part of this PR, there should be a reminder issue for v2.8 then for updating the docs.

**Comment by mcktr** [comment]
@N-o-X Good point. Changed the window title to "Edit Endpoint" (of course only when clicking the edit button). 

icinga2-win-edit-endpoint

I also updated the affected screenshots for the documentation. 

Should I squash the commits together? I don't know what the common practice is, after changes to a initial PR are made. Please let me know if I need to squash them.

**Comment by gunnarbeutner** [comment]
Ideally the Git branch should be organized in such a way that only new and "distinct" features/fixes have commits. What this means is that changes that really only affect the PR (e.g., correcting spelling mistakes, fixing bugs that only ever existed in the PR itself) should not be externally visible.

The rationale for that is that nobody really has to know that you fixed the window title because that bug never actually existed in the "master" branch. This also makes "git bisect" _a lot_ easier later on - when you don't have to test "temporary" commits (which in some cases might not even build correctly).

**Comment by mcktr** [comment]
Thanks for the good explanation :) 

Squashed my commits into a single one.

**Comment by gunnarbeutner** [comment]
This patch currently uses spaces instead of tabs (indentation). @N-o-X, can you have a look at this and merge the patch once that's fixed?

**Pull request merged**
