### PR TITLE
Add an example of multi-parents configuration.

### PR DESCRIPTION
**Pull request by mat813**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Shouldn't that be just `vars.parents = ...` rather than `host.vars.parents = ...`?

**Comment by mat813** [comment]
Absolutely, it should, too much copy & paste :-)

**Comment by gunnarbeutner** [comment]
Oh, also, "assign where x" is unnecessary when "x" is used as the loop variable in "for". Sorry for not noticing earlier. :)

**Comment by dnsmichi** [comment]
Thanks, squashed and merged 👍 

https://dev.icinga.org/issues/12832

**Pull request closed without merging**
