### PR TITLE
Lock not StatsFunctions for iterating, but copies

### PR DESCRIPTION
**Pull request by Al2Klimov**
to reduce the time consumers have to wait for each other.

ref/IP/37271

### CODE REVIEW

**Comment by julianbrost** [comment]
I doubt this will actually have an effect on the bug we're looking for. There, multiple requests for `/v1/status/IcingaApplication` where blocked with the following stack:

```
#6  Lock at ../base/objectlock.cpp:32
#7  ObjectLock at ../base/objectlock.cpp:25
#8  icinga::Namespace::Get at ../base/namespace.cpp:33
#9  StatusTargetProvider::GetTargetByName at ../remote/statushandler.cpp:41
#10 icinga::FilterUtility::GetFilterTargets  at ../remote/filterutility.cpp:206
#11 icinga::StatusHandler::HandleRequest  at ../remote/statushandler.cpp:103
```

So `StatusTargetProvider::FindTargets()` isn't involved there (it would only be if a filter was provided). Neither did I find traces of the other functions where you suggest to do a shallow clone in the stacks.

**Comment by Al2Klimov** [comment]
And if the locking thread disappeared just before our stack?

**Comment by julianbrost** [comment]
Currently I see the following possibilities:
* There was perfect timing to catch the very short moment where the mutex was released but none of the waiting threads got to acquire it yet.
* Some other active thread holding the mutex right now. Then that thread is not in one of the functions where you shallow clone now. I haven't checked every single thread if there's another one plausible holding that mutex.
* Somewhere the mutex was acquired and leaked.

I think the first option is highly unlikely and implies that the hanging requests should make progress at some point which we don't have an indication of. 

As we use scoped locks in most places, this should protect us, but it still has to be verified that this is done properly everywhere. This could go wrong if we directly call the underlying lock/unlock functions or using a scoped lock somewhere where it's not a local variable.

**Comment by Al2Klimov** [comment]
And if "some point" is beyond a timeout?

**Comment by julianbrost** [comment]
The logs we have available indicate that they were doing requests to `/v1/status/IcingaApplication` about every 5 seconds and there were 7 request threads waiting for that mutex. So it was locked (at least most of the time) for 35 seconds at the time the stacks were dumped.

For the proposed change to have an effect on that bug, the mutex should have been held for this time by one of the functions you now perform a shallow copy in. Sure, highly unlikely doesn't mean impossible, but I'd expect a thread in one of `CIB::GetFeatureStats`, `IcingaDB::GetStats` or `StatusTargetProvider::FindTargets` with high probability rather than hitting the very short time where the mutex is available and threads are waiting for it.

**Comment by Al2Klimov** [comment]
I agree, that stack snapshot is highly unlikely. But due to how Icinga 2 works I consider mutex leaks even less likely.

**Comment by Al2Klimov** [comment]
Sure.

**Comment by julianbrost** [comment]
I don't like this approach. If we want to do anything about this (I doubt that's even necessary), I'd rather make it possible to use a shared lock on the mutex added in #9627 for iterating over namespaces instead.

**Pull request closed without merging**
