### PR TITLE
Travis: Add support for Coverity

### PR DESCRIPTION
**Pull request by gunnarbeutner**
This adds Travis-CI support for Coverity.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Would it make sense to route such emails into our ticket system? @bobapple 

I'd prefer to have them sent to all involved devs on their @icinga.com address but I fear this is not possible with just one `notification_email` setting.

**Comment by bobapple** [comment]
I don't think it's a good idea to send these mails to the ticket system. There are too many people working with it hat are not involved in development.

The only thing I can think of is a mail alias (`team-core@icinga.com`) to distribute the notifications.

**Comment by bobapple** [comment]
Here you go: `icinga2@icinga.com`

**Comment by dnsmichi** [comment]
Thanks a lot ❤️

**Pull request merged**
