### PR TITLE
Don't send event::Heartbeat to unauthenticated peers

### LINKED ISSUE #7746: event::Heartbeat is sent to unauthenticated peers
## Describe the bug

A :5665 peer w/o even a cert sends just `icinga::Hello` as we do and gets `event::Heartbeat`s.

## To Reproduce

See above.

## Expected behavior

A such peer doesn't deserve such events.

## Your Environment

MacOS, single node, api enabled.

## Additional context

DDoS protection for the... *hrumph*... smart people who run their nodes not behind a VPN.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7746
closes #7698

### CODE REVIEW

**Comment by mcktr** [comment]
Hi,

I've created #7698 as a draft a while ago which also aims to fix the problem. I took another approach i.e. to not spawn a coroutine to send heartbeat messages on unauthenticated peers. #7698 has the disadvantage that the disconnect/timeout logic is not executed. 

Whats your opinion @Al2Klimov? Feel free to close #7698, so we can focus on/test one patch.

**Comment by Al2Klimov** [comment]
In opposite to #7698 I preserve [this one](https://github.com/Icinga/icinga2/pull/7747/files#diff-64b02486179e3e8a49582ccc4769493fR35).

**Comment by dnsmichi** [comment]
@lippserd I'd opt for adding this to 2.12, avoiding a possible leak.

**Comment by lippserd** [comment]
@dnsmichi Yep, sounds good!

**Comment by dnsmichi** [comment]
@lippserd Thanks 👍

**Pull request merged**
