### PR TITLE
JsonEncode(): encode non-[]/{} objects as strings, not null

### PR DESCRIPTION
**Pull request by Al2Klimov**
... to represent function custom vars as such in Icinga DB.

### CODE REVIEW

**Comment by lippserd** [comment]
What if the object is not a function? Do I get something like that then?

> Objectoftype'type'

**Comment by julianbrost** [comment]
You still get the spaces, that hacky string replacement is only there because in the line before, all spaces were removed to minify the JSON.

Will look something like that:
```
<1> => Json.encode({a={{0}}; b=Host(); c=Service(); d=CheckResult()})
"{\"a\":\"Object of type 'Function'\",\"b\":\"Object of type 'Host'\",\"c\":\"Object of type 'Service'\",\"d\":\"Object of type 'CheckResult'\"}"
```

**Comment by lippserd** [comment]
> You still get the spaces, that hacky string replacement is only there because in the line before, all spaces were removed to minify the JSON.
> 
> Will look something like that:
> 
> ```
> <1> => Json.encode({a={{0}}; b=Host(); c=Service(); d=CheckResult()})
> "{\"a\":\"Object of type 'Function'\",\"b\":\"Object of type 'Host'\",\"c\":\"Object of type 'Service'\",\"d\":\"Object of type 'CheckResult'\"}"
> ```

I see, thanks!

**Review by lippserd — APPROVED** [review]
I can't code-wise approve, but the encoding change looks good to me.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
