### PR TITLE
Windows MSI: don't bundle NSClient++

### PR DESCRIPTION
**Pull request by Al2Klimov**
to save 32/45 MB. Even if(!) someone still uses it if favor of our PS plugins collection, they can download it by themselves.

## TODO

* [x] testing

### CODE REVIEW

**Comment by Al2Klimov** [comment]
IMAO an awesome accompaniment to #9062!

**Comment by Al2Klimov** [comment]
Bildschirm­foto 2023-02-22 um 17 43 10
Bildschirm­foto 2023-02-22 um 17 43 18
Bildschirm­foto 2023-02-22 um 17 43 34

**Review by lippserd — DISMISSED** [review]
Please also remove documentation for NSClient++.

**Comment by julianbrost** [comment]
The documentation changes are strange as there were places that mentioned the checks shipped with Icinga 2 (very old) and NSClient++ (old), but not Icinga for Windows (new). And now, they mention only the very old stuff. I created #9765 for that.

**Review by yhabteab — COMMENTED** [review]
I only did some testing!

Bildschirmfoto 2023-05-22 um 09 25 14
Bildschirmfoto 2023-05-22 um 09 28 09
Bildschirmfoto 2023-05-22 um 09 28 54

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
