### PR TITLE
Implement support for user-defined post-creation validators/rules

### LINKED ISSUE #4722: [dev.icinga.com #12877] Define mandatory variable to host object
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12877

**Created by siyalrach on 2016-10-09 21:36:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-10 06:34:41 +00:00 (in Redmine)_

    Backport?: Not yet backported
    Include in Changelog: 1

---

Does any one know how to define a mandatory variable to a host object.

I have a scenario where all our hosts must have a custom variable with their location added to the object, but how do I check if it is satisfied before a deployment?

### PR DESCRIPTION
**Pull request by gunnarbeutner**
This adds support for two new keywords:

* rule (used to specify custom validator and post-creation rules)
* require (a short-cut for ("if (!<expr>) { throw ... })

Rules can be used to add arbitrary user-defined validation rules and modify objects after they've been created:

This rule specifies that all hosts must have a custom variable `type`:

```
rule Host {
        require vars.type
}
```

This specifies that all physical hosts must have a custom variable `location`:

```
rule Host {
        if (vars.type == "physical") {
                require vars.location
        }
}
```

This ensures that all hosts and services which use the `ping` check command have a check_interval that's less than one minute:

```
rule [Host, Service] {
        if (check_command == "ping") {
                require check_interval < 1m
        }
}
```

This creates a custom attribute 'z' for all objects which can have custom attributes (i.e. all objects which inherit from the CustomVarObject type):

```
rule CustomVarObject {
        vars.z = 3
}
```

This rule ensures that no objects (of any kind) exist whose name contains the letter "z":

```
rule {
       require !match("*z*", name)
}
```

```
critical/config: Error: Error while evaluating expression: Validation failed for object 'breeze' of type 'CheckCommand': User-defined validator failed.
Location: in /Users/gunnar/i2/etc/icinga2/conf.d/test.conf: 61:2-61:28
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(59):
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(60): rule {
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(61):  require !match("*z*", name)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(62): }
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(63):
```

This rule ensures that there's a service group for each host with the same name:

```
rule Host {
        require get_service_group(name)
}
```

TODOs:
* [ ] Documentation
* [x]  Closure support
* [ ]  Figure out whether we actually want this

fixes #4722

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Another (as of yet unimplemented) idea is general purpose "rules":

```
// Require all hosts to have a 'client' custom attribute
rule Host “*” {
	require vars.client
}

// Client-specific rule to set the check_interval to 30 seconds
// for all mysql checks.
rule Service “mysql*” {
	if (host.vars.client == “icinga” {
		check_interval = 30s
	}
}
```

This would affect objects no matter how they're created (config, API, etc.).

**Comment by dnsmichi** [comment]
Just thinking ... could we make these "rules" also being evaluated at runtime, e.g. a certain object state triggers a callback function, or similar... 

It is more of the "same" rule approach with alert rules defined in Prometheus and variants. Or virtual object states without the dummy check_command.

**Comment by gunnarbeutner** [comment]
Well, we kinda already have that:

```
Checkable.register_attribute_handler("next_check", (checkable) => {
        log("Check rescheduled for " + checkable.name + ": " + checkable.next_check)
})
```

Here's an idea for adding that functionality for rules:

```
rule Host when (state == HostDown) {
  log("Host " + name + " is down.")
}
```

But (and that's a big but)... I'm not sure rules are the right place for that. That way we'd be using them for two very different things: 1. Doing things at config time and 2. doing things at runtime - which seems somewhat counter-intuitive to me.

**Comment by gunnarbeutner** [comment]
Example:

```
rule Service "test-*" {
  if (vars.test > 0.3) {
    get_host(host_name).vars.bla = "blubb"
  }
}
```

**Comment by friesoft** [comment]
That would also allow to assign variables to hosts based on hostgroups, correct?
Something like
rule Host "grafana-graph-MySQL" {
    if ("MySQL" in groups) {
        get_host(host_name).vars.grafana_dashboard = "mysqlserver-dashboard"
    }
}

**Comment by dnsmichi** [comment]
Maybe. It is yet to decide if post modifications should be allowed. One problem which arises is the fact that you cannot re-evaluate apply rules at this state. Furthermore the current patch implements being evaluated after each object, and not entirely at the end of config compilation.

There's more things to discuss, test, and design. It may be skipped for 2.9 if those questions are not solved in the meantime.

**Comment by dnsmichi** [comment]
Removing this for 2.9 for now. @lippserd we should take this into a design round and tackle problems this would solve. A good candidate for sponsoring then.

**Comment by Napsty** [comment]
As mentioned in https://github.com/Icinga/icinga2/issues/6543 this would be a nice new feature/enhancement. Especially the possibility to apply variables to services will be very handy. 

However this needs some clarification. Will `rule` replace or extend `apply`?
Is there some hierarchy which needs to be respected? E.g. Host -> Service -> CustomVarObject ?

**Comment by dnsmichi** [comment]
The idea is good, the final design won't be used like this. Whenever I have the time to look into #4722 again, I'll come back to this.

**Pull request closed without merging**
