### PR TITLE
Remove parameter --commit from check_mysql_health command definition as it is not available

### PR DESCRIPTION
**Pull request by log1-c**
Parameter --commit is not available in the check_mysql_health plugin

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
And the ITL docs?

**Comment by log1-c** [comment]
Removed from the docs as well.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Please squash your commits.

**Comment by log1-c** [comment]
tbh I have no idea what I have to do.
I'm not very experienced with git/github. I did all changes on the github website and I couldn't find a squash option on github.

**Review by Al2Klimov — APPROVED** [review]
Fair enough.

**Review by julianbrost — COMMENTED** [review]
What happened to the `--commit` parameter? Like was it removed from `check_mysql_health`? Are there forks that have it? Did it never exist and was added accidentally here?

**Comment by log1-c** [comment]
I only know this parameter from the check_m**s**sql_health plugin.

The help output of check_mysql_health does not list the `--commit` parameterfor the current release.
```
# ./check_mysql_health -h
Copyright (c) 2009 Gerhard Lausser


  Check various parameters of MySQL databases

  Usage:
    check_mysql_health [-v] [-t <timeout>] [[--hostname <hostname>]
        [--port <port> | --socket <socket>]
        --username <username> --password <password>] --mode <mode>
        [--method mysql]
    check_mysql_health [-h | --help]
    check_mysql_health [-V | --version]

  Options:
    --hostname
       the database server's hostname
    --port
       the database's port. (default: 3306)
    --socket
       the database's unix socket.
    --username
       the mysql db user
    --password
       the mysql db user's password
    --database
       the database's name. (default: information_schema)
    --replication-user
       the database's replication user name (default: replication)
    --warning
       the warning range
    --critical
       the critical range
    --mode
       the mode of the plugin. select one of the following keywords:
       connection-time          (Time to connect to the server)
       uptime                   (Time the server is running)
       threads-connected        (Number of currently open connections)
       threadcache-hitrate      (Hit rate of the thread-cache)
       threads-created          (Number of threads created per sec)
       threads-running          (Number of currently running threads)
       threads-cached           (Number of currently cached threads)
       connects-aborted         (Number of aborted connections per sec)
       clients-aborted          (Number of aborted connections (because the client died) per sec)
       slave-lag                (Seconds behind master)
       slave-io-running         (Slave io running: Yes)
       slave-sql-running        (Slave sql running: Yes)
       qcache-hitrate           (Query cache hitrate)
       qcache-lowmem-prunes     (Query cache entries pruned because of low memory)
       keycache-hitrate         (MyISAM key cache hitrate)
       bufferpool-hitrate       (InnoDB buffer pool hitrate)
       bufferpool-wait-free     (InnoDB buffer pool waits for clean page available)
       log-waits                (InnoDB log waits because of a too small log buffer)
       tablecache-hitrate       (Table cache hitrate)
       table-lock-contention    (Table lock contention)
       index-usage              (Usage of indices)
       tmp-disk-tables          (Percent of temp tables created on disk)
       table-fragmentation      (Show tables which should be optimized)
       open-files               (Percent of opened files)
       slow-queries             (Slow queries)
       long-running-procs       (long running processes)
       cluster-ndbd-running     (ndnd nodes are up and running)
       sql                      (any sql command returning a single number)

    --name
       the name of something that needs to be further specified,
       currently only used for sql statements
    --name2
       if name is a sql statement, this statement would appear in
       the output and the performance data. This can be ugly, so
       name2 can be used to appear instead.
    --regexp
       if this parameter is used, name will be interpreted as a
       regular expression.
    --units
       one of %, KB, MB, GB. This is used for a better output of mode=sql
       and for specifying thresholds for mode=tablespace-free
    --labelformat
       one of pnp4nagios (which is the default) or groundwork.
       It is used to shorten performance data labels to 19 characters.

  In mode sql you can url-encode the statement so you will not have to mess
  around with special characters in your Nagios service definitions.
  Instead of
  --name="select count(*) from v$session where status = 'ACTIVE'"
  you can say
  --name=select%20count%28%2A%29%20from%20v%24session%20where%20status%20%3D%20%27ACTIVE%27
  For your convenience you can call check_mysql_health with the --mode encode
  option and it will encode the standard input.

  You can find the full documentation at
  https://labs.consol.de/nagios/check_mysql_health/

Send email to gerhard.lausser@consol.de if you have questions
regarding use of this software.
Please include version information with all correspondence (when possible,
use output from the --version option of the plugin itself).
```

**Comment by julianbrost** [comment]
I guess I know what happened. The `--commit` parameter and many others got explicitly added to the `mysql_health` definition in 1a85cfe427f87f54ff99d5190b64eb5b1a775cfe as a response to #4397. This issue mentions a 3.0.0 release which you will actually find on the [German check_mysql_health website](https://labs.consol.de/de/nagios/check_mysql_health/index.html) but not on the English one. This version is from 2016 and is labeled "Beta, Preview, Test" but it looks like it supports `--commit` and many other new parameters. So I think we should keep this parameter.

**Comment by Al2Klimov** [comment]
Good point.

**Pull request closed without merging**
