### PR TITLE
GitHub actions: drop Debian "jessie"

### PR DESCRIPTION
**Pull request by Al2Klimov**
... as it's EOL.

### CODE REVIEW

**Comment by N-o-X** [comment]
Please add a description.

**Comment by Yoda-BZH** [comment]
Hello,

I (unfortunately) still have to use jessie. The latest published release is 2.12.2-1.

However, this version has a memory leak, fixed in 2.12.4 (#8290)

Would it be possible to have this version (2.12.4) for jessie please ?

Thank you

**Comment by julianbrost** [comment]
Adding the old versions to our build infrastructure would be too much work. You can try to use the source package for stretch an build it on jessie yourself: https://packages.icinga.com/debian/pool/main/i/icinga2/icinga2_2.12.4-1.stretch.dsc The source packages usually only differ in the release name in the version.

**Comment by Al2Klimov** [comment]
I’m sorry, @Yoda-BZH. I’m afraid according to https://wiki.debian.org/LTS/Jessie "Jessie LTS is supported from 17th June 2018 to June 30, 2020". I.e. the distro release **didn’t receive security updates for >1 year**.

**Pull request merged**
