### PR TITLE
AtomicFile#Commit(): on Windows symlink m_Path -> m_TempFilename

### PR DESCRIPTION
**Pull request by Al2Klimov**
instead of renaming m_TempFilename -> m_Path.

    A file can't be replaced as long as e.g. the anti-virus keeps it open.
    But no one unintentionally keeps symlinks open, so they can be replaced.
    Just moving the newly created m_TempFilename+"-LINK" -> m_Path (also a symlink)
    doesn't work as expected, hence an NTFS transaction with symlink removal and
    creation. DeviceIoControl() requires ntifs.h from a charged SDK for
    readlink(2), hence the delayed cleanup of tempfiles older than 10m.
    Also useful to clean up tempfiles of crashed processes btw..

ref/IP/43468

## TODO

* [ ] review @julianbrost 
* [ ] consider more AtomicFile usages @Al2Klimov 
* [ ] consider reverting 05c8e7f36ff6876a15f65452b131a2a72ec7ae9e @Al2Klimov 

## Before

```
PS C:\Users\Administrator\icinga2\build> & '.\Icinga 2-2.13.0.492-win64.exe'
PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-11-30 10:48:30 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-11-30 10:48:30 +0000] information/cli: Icinga application loader (version: v2.13.0-492-gf855cfa15; debug)
[2022-11-30 10:48:30 +0000] information/cli: Loading configuration file(s).
[2022-11-30 10:48:30 +0000] information/ConfigItem: Committing config item(s).
[2022-11-30 10:48:30 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-11-30 10:48:30 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-11-30 10:48:30 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/30/2022  10:48 AM            539 icinga2.debug
-a----       11/30/2022  10:48 AM            434 icinga2.vars


PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-11-30 10:48:54 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-11-30 10:48:54 +0000] information/cli: Icinga application loader (version: v2.13.0-492-gf855cfa15; debug)
[2022-11-30 10:48:54 +0000] information/cli: Loading configuration file(s).
[2022-11-30 10:48:54 +0000] information/ConfigItem: Committing config item(s).
[2022-11-30 10:48:54 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-11-30 10:48:54 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-11-30 10:48:54 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/30/2022  10:48 AM            539 icinga2.debug
-a----       11/30/2022  10:48 AM            434 icinga2.vars


PS C:\Users\Administrator\icinga2\build> $file = [System.io.File]::Open("C:\Program Files (x86)\icinga2\var\cache\icinga2\icinga2.vars", 'Open', 'Read', 'None')
PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-11-30 10:49:28 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-11-30 10:49:28 +0000] information/cli: Icinga application loader (version: v2.13.0-492-gf855cfa15; debug)
[2022-11-30 10:49:28 +0000] information/cli: Loading configuration file(s).
[2022-11-30 10:49:28 +0000] information/ConfigItem: Committing config item(s).
[2022-11-30 10:49:28 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-11-30 10:49:28 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-11-30 10:49:28 +0000] warning/Utility: Renaming 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars.Sutgf7' to 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars' failed: Zugriff verweigert (trying up to 15 more times)
[2022-11-30 10:49:38 +0000] information/WorkQueue: #3 (DaemonUtility::LoadConfigFiles) items: 0, rate: 0.0666667/s (4/min 4/5min 4/15min);
[2022-11-30 10:49:45 +0000] critical/cli: Could not write vars file: Error: boost::filesystem::rename: Zugriff verweigert [system:5]: "C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars.Sutgf7", "C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars"
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/30/2022  10:49 AM            539 icinga2.debug
-a----       11/30/2022  10:48 AM            434 icinga2.vars
-a----       11/30/2022  10:49 AM            434 icinga2.vars.Sutgf7


PS C:\Users\Administrator\icinga2\build>
```

## After

```
PS C:\Users\Administrator\icinga2\build> & '.\Icinga 2-2.13.0.492-win64.exe'
PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-11-30 17:22:40 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-11-30 17:22:40 +0000] information/cli: Icinga application loader (version: v2.13.0-492-gf855cfa15; debug)
[2022-11-30 17:22:40 +0000] information/cli: Loading configuration file(s).
[2022-11-30 17:22:40 +0000] information/ConfigItem: Committing config item(s).
[2022-11-30 17:22:40 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-11-30 17:22:40 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-11-30 17:22:40 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> & '.\Icinga 2-2.13.0.518-win64.exe'
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/30/2022   5:22 PM            539 icinga2.debug
-a----       11/30/2022   5:22 PM            434 icinga2.vars


PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-12-01 10:32:59 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-12-01 10:32:59 +0000] information/cli: Icinga application loader (version: v2.13.0-517-g6ad32168d; debug)
[2022-12-01 10:32:59 +0000] information/cli: Loading configuration file(s).
[2022-12-01 10:32:59 +0000] information/ConfigItem: Committing config item(s).
[2022-12-01 10:32:59 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-12-01 10:32:59 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-12-01 10:32:59 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        12/1/2022  10:32 AM            539 icinga2.debug
-a---l        12/1/2022  10:32 AM              0 icinga2.vars
-a----        12/1/2022  10:32 AM            434 icinga2.vars.tmp.uMEnQb


PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-12-01 10:33:05 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-12-01 10:33:05 +0000] information/cli: Icinga application loader (version: v2.13.0-517-g6ad32168d; debug)
[2022-12-01 10:33:05 +0000] information/cli: Loading configuration file(s).
[2022-12-01 10:33:05 +0000] information/ConfigItem: Committing config item(s).
[2022-12-01 10:33:05 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-12-01 10:33:05 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-12-01 10:33:05 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        12/1/2022  10:33 AM            539 icinga2.debug
-a---l        12/1/2022  10:33 AM              0 icinga2.vars
-a----        12/1/2022  10:32 AM            434 icinga2.vars.tmp.uMEnQb
-a----        12/1/2022  10:33 AM            434 icinga2.vars.tmp.WO6uYb


PS C:\Users\Administrator\icinga2\build> $file = [System.io.File]::Open("C:\Program Files (x86)\icinga2\var\cache\icinga2\icinga2.vars", 'Open', 'Read', 'None')
PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-12-01 10:33:35 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-12-01 10:33:35 +0000] information/cli: Icinga application loader (version: v2.13.0-517-g6ad32168d; debug)
[2022-12-01 10:33:35 +0000] information/cli: Loading configuration file(s).
[2022-12-01 10:33:35 +0000] information/ConfigItem: Committing config item(s).
[2022-12-01 10:33:35 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-12-01 10:33:35 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-12-01 10:33:35 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        12/1/2022  10:33 AM            539 icinga2.debug
-a---l        12/1/2022  10:33 AM              0 icinga2.vars
-a----        12/1/2022  10:33 AM            434 icinga2.vars.tmp.MVw6Cc
-a----        12/1/2022  10:32 AM            434 icinga2.vars.tmp.uMEnQb
-a----        12/1/2022  10:33 AM            434 icinga2.vars.tmp.WO6uYb


PS C:\Users\Administrator\icinga2\build> & 'C:\Program Files\ICINGA2\sbin\icinga2.exe' daemon -C -z
[2022-12-01 11:11:57 +0000] warning/icinga-app: Registry key could not be read. Falling back to built-in paths.
[2022-12-01 11:11:57 +0000] information/cli: Icinga application loader (version: v2.13.0-517-g6ad32168d; debug)
[2022-12-01 11:11:57 +0000] information/cli: Loading configuration file(s).
[2022-12-01 11:11:57 +0000] information/ConfigItem: Committing config item(s).
[2022-12-01 11:11:57 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-12-01 11:11:57 +0000] information/ScriptGlobal: Dumping variables to file 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars'
[2022-12-01 11:11:57 +0000] warning/AtomicFile: Can't delete 'C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars.tmp.WO6uYb': boost::filesystem::remove: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird [system:32]: "C:/Program Files (x86)/icinga2/var/cache/icinga2/icinga2.vars.tmp.WO6uYb"
[2022-12-01 11:11:57 +0000] information/cli: Finished validating the configuration file(s).
PS C:\Users\Administrator\icinga2\build> dir 'C:/Program Files (x86)/icinga2/var/cache/icinga2'


    Verzeichnis: C:\Program Files (x86)\icinga2\var\cache\icinga2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        12/1/2022  11:11 AM            539 icinga2.debug
-a---l        12/1/2022  11:11 AM              0 icinga2.vars
-a----        12/1/2022  11:11 AM            434 icinga2.vars.tmp.MZQTS0
-a----        12/1/2022  10:33 AM            434 icinga2.vars.tmp.WO6uYb


PS C:\Users\Administrator\icinga2\build>
```

### CODE REVIEW

**Comment by Al2Klimov** [comment]
From your wording I derive your answer would be no.
Given that I agree with you.

But, especially in the (current) adult stage of my life, I had/have to deal with a large spread between what I want and what I **have to** do. Including the implementation details of this PR.

**Comment by julianbrost** [comment]
> The alternatives are either even more horrible or just don’t work. See OP. Hence my chose of this one as the best of all (bad ones).

So these are the alternatives you considered?

* "renaming m_TempFilename -> m_Path"
* "moving the newly created m_TempFilename+"-LINK" -> m_Path (also a symlink)"

Looks like these are all based on the assumption that a fixed file name must be used. But that should not be a requirement as we also control the code reading the file. So what renaming the new version of the file to `icinga2.vars.$COUNTER`, trying to remove older versions but leaving them alone if that fails due to the file being open/locked. Code reading the file would just have to list the directory and pick the file with the highest counter. Should work without using any discouraged APIs.

**Comment by Al2Klimov** [comment]
On which of our supported platforms?

**Comment by julianbrost** [comment]
Only on Windows. On POSIX, `rename()` as well-defined semantics just as we need them (after all, that's why it's built like this in the first place).

Just one thing that came to my mind now:

> consider more AtomicFile usages

What are these places? Could we run into the same issue for example with an incoming config sync? (Might be strange if we'd have to deviate from "everything `*.conf` is loaded" there.)

**Comment by Al2Klimov** [comment]
It's my task to look for these places **after** we have finished the ongoing discussion.

So you want to

1. rather than doing strange things behind the user's back and letting the paths more-or-less as-is, to export the strange-ness to the filesystem by using $FILENAME.$VERSION
2. strictly speaking make the paths different on the platforms?

**Comment by julianbrost** [comment]
This approach does not work. Interestingly not due to Transactional NTFS but rather due to symlinks.

To see this yourself, just install the [MSI](https://git.icinga.com/packaging/windows-icinga2/-/jobs/236437/artifacts/browse) on a clean system and watch the service even fail to start. The event log reveals the following error:

```
critical/cli: Could not write vars file: Error: Function call 'CreateSymbolicLinkTransactedA' for file 'C:\ProgramData\icinga2\var\cache\icinga2/icinga2.vars' failed with error code 1314, "A required privilege is not held by the client."
```

Why? Symlinks on Windows are fun. Looks like unprivileged processes can only create them on Windows 10+ and only with developer mode enabled(?!), see also: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

**Comment by julianbrost** [comment]
Regarding approaches that change the file names involved: other things may have assumptions on the file names, so that would break, like for example [this function in the powershell framework](https://github.com/Icinga/icinga-powershell-framework/blob/d80ea57bf8a580fd54f098c0b5976b9becb356fa/lib/core/icingaagent/tests/Test-IcingaStateFile.psm1#L8).

So I'm really not sure if there's a good way to proceed from here rather than tell user to not use software that prevents other software from accessing their own files.

One approach that might be feasible would be to keep the fixed file names, but when those can't be written, use a temporary file name and try to recover at a later point. But until this recovery happens, everything that's not aware of the recovery procedure will make wrong assumptions about that file.

**Comment by Al2Klimov** [comment]
> unprivileged processes can only create them on Windows 10+ and only with developer mode enabled

**Pull request closed without merging**
