### PR TITLE
Improve error message for serializing objects with recursive references

### PR DESCRIPTION
**Pull request by gunnarbeutner**
This improves error reporting somewhat for the issue reported in #6409.

### CODE REVIEW

**Comment by dnsmichi** [comment]
This needs two things:

- the exception needs to be handled by upper levels, supressing the stacktrace (should be a config error)
- more context e.g. attribute name affected, etc.

**Comment by gunnarbeutner** [comment]
How about this?:

```
gunnar@abyss ~ $ icinga2 daemon -C
[2018-08-02 11:05:45 +0200] information/cli: Icinga application loader (version: v2.9.1-50-gb661adeda; debug)
[2018-08-02 11:05:45 +0200] information/cli: Loading configuration file(s).
[2018-08-02 11:05:45 +0200] information/ConfigItem: Committing config item(s).
[2018-08-02 11:05:45 +0200] information/ApiListener: My API identity: abyss.beutner.name
[2018-08-02 11:05:45 +0200] critical/config: Error: Validation failed for object 'test' of type 'Host'; Attribute 'vars' -> 'x' -> 'y' -> 'z': Circular references are not allowed
Location: in /Users/gunnar/i2/etc/icinga2/conf.d/test.conf: 1:0-1:17
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(1): object Host "test" {
                                                  ^^^^^^^^^^^^^^^^^^
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(2):   import "generic-host"
/Users/gunnar/i2/etc/icinga2/conf.d/test.conf(3):   vars.x.y.z = vars

[2018-08-02 11:05:45 +0200] critical/config: 1 error
gunnar@abyss ~ $
```

**Comment by dnsmichi** [comment]
Awesome, thanks :)

**Comment by dnsmichi** [comment]
```
mbmif /usr/local/icinga2/etc/icinga2 (master *) # icinga2 daemon -C
[2018-08-03 11:02:37 +0200] information/cli: Icinga application loader (version: v2.9.1-50-g56cf64f59; debug)
[2018-08-03 11:02:37 +0200] information/cli: Loading configuration file(s).
[2018-08-03 11:02:37 +0200] information/ConfigItem: Committing config item(s).
[2018-08-03 11:02:37 +0200] information/ApiListener: My API identity: mbmif.int.netways.de
[2018-08-03 11:02:37 +0200] critical/config: Error: Validation failed for object 'selfref' of type 'Host'; Attribute 'vars' -> 'x' -> 'y' -> 'z': Circular references are not allowed
Location: in /usr/local/icinga2/etc/icinga2/tests/selfreference.conf: 1:0-1:20
/usr/local/icinga2/etc/icinga2/tests/selfreference.conf(1): object Host "selfref" {
                                                            ^^^^^^^^^^^^^^^^^^^^^
/usr/local/icinga2/etc/icinga2/tests/selfreference.conf(2):   check_command = "dummy"
/usr/local/icinga2/etc/icinga2/tests/selfreference.conf(3):

[2018-08-03 11:02:37 +0200] critical/config: 1 error
```

**Pull request merged**
