### PR TITLE
Fixed --details switch

### PR DESCRIPTION
**Pull request by cstegm**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you please clarify what this patch changes? I don't see any semantic changes but maybe I'm missing something here.

**Comment by dgoetz** [comment]
I think what is intended to be fixed here is already addressed in https://github.com/Icinga/icinga2/issues/4826

**Comment by cstegm** [comment]
Hi, die Reihenfolge der Argumente führt zu Problemen. 

Ohne Details funktioniert alles wunderbar:
`/usr/bin/icingacli businessprocess check process --config Example_Config blah`

Schaltet man Details an wird daraus
`/usr/bin/icingacli businessprocess check process --config Example_Config --details blah`

 was dann zu Fehlermeldungen 
> The node "" doesn't exist
 
führt. Also habe ich die Reihenfolge angepasst...

**Comment by dnsmichi** [comment]
I'm currently reviewing, testing and writing docs for #4826. Please wait until this is merged and released. This is a duplicate, thanks anyways.

**Pull request closed without merging**
