### PR TITLE
check_network fixed performance data

### PR DESCRIPTION
**Pull request by Black-Dragon131**
check_network.exe doesn't use well formated performance data.

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you please create a ticket for this at dev.icinga.org? Also, please update your patch so it contains your real name in the 'Author' field.

**Comment by Crunsher** [comment]
According to [the guidelines](https://www.monitoring-plugins.org/doc/guidelines.html#AEN201) a UOM is required in the performance output. Then again we don't conform to the types of units allowed...
The 'netI=' to '$inerfacename=' change is definitely correct and needed though

**Comment by dnsmichi** [comment]
Did you create an issue yet? If so please link it here. 

I assume https://dev.icinga.org/issues/10544 is related as well.

**Comment by Crunsher** [comment]
Fixed with 370a1 and 370a1

**Pull request closed without merging**
