### PR TITLE
Handle process spawner I/O errors

### LINKED ISSUE #8090: 2.11.4 - crash on satellite - [json.exception.parse_error.101] parse error at line 1, column 28: syntax error while parsing value - unexpected '{'; expected end of input
## Describe the bug

Yesterday we updated our Icinga prod stage to 2.11.4. During the night one of our satellites died.
Today we found the following crash log. Its very long this time. This is only an excerpt.

### Crash log

```
Caught unhandled exception.
Current time: 2020-07-07 02:12:24 +0200

  Application version: 2.11.4-1

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.8 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1127.10.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-ltrjqz9n-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: [json.exception.parse_error.101] parse error at line 1, column 28: syntax error while parsing value - unexpected '{'; expected end of input


        (0) icinga2: icinga::JsonDecode(icinga::String const&) (+0xe99) [0x908d29]
        (1) icinga2: icinga::Process::DoEvents() (+0x284) [0x960f54]
        (2) icinga2: icinga::Process::IOThreadProc(int) (+0x399) [0x962509]
        (3) libstdc++.so.6: <unknown function> (+0xb5070) [0x7f32f8ccd070]
        (4) libpthread.so.0: <unknown function> (+0x7ea5) [0x7f32f84ebea5]
        (5) libc.so.6: clone (+0x6d) [0x7f32f82148dd]



***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

```
## To Reproduce

Unknown so far. One hour before the crash OS patches were automatically applied.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): **satellite**
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.4-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.8 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1127.10.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-ltrjqz9n-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Enabled features (`icinga2 feature list`): **satellite**
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus notification opentsdb perfdata statusdata syslog
Enabled features: api checker mainlog
```
* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.3
Git Commit
    06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version
    7.1.8
Git Commit Datum
    2019-10-18
Copyright
    © 2013-2020 Das Icinga Projekt 
```
* Config validation (`icinga2 daemon -C`): **satellite**
```
[2020-07-07 08:24:37 +0200] information/cli: Icinga application loader (version: 2.11.4-1)
[2020-07-07 08:24:37 +0200] information/cli: Loading configuration file(s).
[2020-07-07 08:24:39 +0200] information/ConfigItem: Committing config item(s).
[2020-07-07 08:24:39 +0200] information/ApiListener: My API identity: dxemsat01
[2020-07-07 08:24:39 +0200] warning/CheckerComponent: Attribute 'concurrent_checks' for object 'checker' of type 'CheckerComponent' is deprecated and should not be used.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 85 HostGroups.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 12541 Hosts.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 34 Downtimes.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 3 Comments.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 14 Zones.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 12 Endpoints.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 311 CheckCommands.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 6 TimePeriods.
[2020-07-07 08:24:44 +0200] information/ConfigItem: Instantiated 50082 Services.
[2020-07-07 08:24:44 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-07-07 08:24:44 +0200] information/cli: Finished validating the configuration file(s).
```

### LINKED ISSUE #8384: crash while reloading
## Describe the bug

icinga2 was reloaded via ansible, shortly thereafter icinga2 crashed.

## To Reproduce

1. service icinga2 reload

## Expected behavior

no crash

## Your Environment

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1127.18.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Enabled features (`icinga2 feature list`):
Enabled features: api checker graphite ido-pgsql mainlog notification syslog

## Additional context

Last log messages: (munnvmonpmac11 is the local server in question)
```
[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'munnvmonpmac11' (PID: 24772, arguments: '/usr/lib64/nagios/plugin
s/check_procs' '-a' 'syslog-ng' '-c' '1:1' '-p' '1' '-u' 'root' '-w' '1:9999') terminated with exit code 128, output: PROCS OK: 1 process with a
rgs 'syslog-ng', PPID = 1, UID = 0 (root) | procs=1;1:9999;1:1;0;

[2020-10-15 07:50:41 +0000] critical/Process: Fork failed with error code 0 (Success)
Context:
        (0) Executing remote check for object 'munnvmonpmac11'

[2020-10-15 07:50:41 +0000] warning/Process: PID 24771 ('/usr/lib64/nagios/plugins/check_ping' '-4' '-H' 'mlsnvmonpqmc01' '-c' '5000,100%' '-w' 
'3000,80%') died mysteriously: waitpid failed
[2020-10-15 07:50:41 +0000] warning/Process: PID 24794 ('/usr/lib64/nagios/plugins/check_ping' '-4' '-H' '10.2.130.17' '-c' '5000,100%' '-w' '30
00,80%') died mysteriously: waitpid failed
[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'mlsnvmonpqmc01' (PID: 24771, arguments: '/usr/lib64/nagios/plugin
s/check_ping' '-4' '-H' 'mlsnvmonpqmc01' '-c' '5000,100%' '-w' '3000,80%') terminated with exit code 128, output: PING OK - Packet loss = 0%, RT
A = 0.46 ms|rta=0.461000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0

[2020-10-15 07:50:41 +0000] warning/PluginCheckTask: Check command for object 'munnvpdehc1pes7' (PID: 24794, arguments: '/usr/lib64/nagios/plugi
ns/check_ping' '-4' '-H' '10.2.130.17' '-c' '5000,100%' '-w' '3000,80%') terminated with exit code 128, output: PING OK - Packet loss = 0%, RTA 
= 0.57 ms|rta=0.571000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0

[2020-10-15 07:50:41 +0000] critical/Application: Error: [json.exception.parse_error.101] parse error at line 1, column 27: syntax error while p
arsing value - unexpected '{'; expected end of input



Additional information is available in '/var/log/icinga2/crash/report.1602748241.329181'
```

The crash file contains the following backtrace:

```
        (0) icinga2: icinga::JsonDecode(icinga::String const&) (+0xe99) [0x908be9]
        (1) icinga2: icinga::Process::DoEvents() (+0x284) [0x991fa4]
        (2) icinga2: icinga::Process::IOThreadProc(int) (+0x399) [0x993559]
        (3) libstdc++.so.6: <unknown function> (+0xb5070) [0x7fccd5f8d070]
        (4) libpthread.so.0: <unknown function> (+0x7ea5) [0x7fccd57abea5]
        (5) libc.so.6: clone (+0x6d) [0x7fccd54d48dd]
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #8384
fixes #8090

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@lippserd @N-o-X @julianbrost FYI if this PR's description turns out to be true, we should make a v2.12.2 and v2.11.7.

**Comment by lippserd** [comment]
Why is the process spawner sending invalid JSON at all?

I have a customer with something like this right after a deployment:

```
Error: [json.exception.parse_error.101] parse error at line 1, column 27: syntax error while parsing value - unexpected '{'; expected end of input


        (0) icinga2: icinga::JsonDecode(icinga::String const&) (+0x103b) [0x96343b]
        (1) icinga2: icinga::Process::DoEvents() (+0x431) [0x9656b1]
        (2) icinga2: icinga::Process::IOThreadProc(int) (+0x34a) [0x966b9a]
        (3) /usr/lib64/icinga2/sbin/icinga2() [0xa868bf]
        (4) /lib64/libpthread.so.0() [0x3a23a07aa1]
        (5) libc.so.6: clone (+0x6d) [0x3a236e8c4d]
```

With this PR, I would now get a critical log message. I can't do anything with that, except that Icinga doesn't die.

**Comment by Al2Klimov** [comment]
I think because it shuts down due to the reload. You as a user don't _have to_ do anything. Everything's fine – once the reload completes.

**Comment by lippserd** [comment]
> I think because it shuts down due to the reload. You as a user don't _have to_ do anything. Everything's fine – once the reload completes.

Then we have to handle that gracefully.

**Comment by julianbrost** [comment]
> I think because it shuts down due to the reload. You as a user don't _have to_ do anything. Everything's fine – once the reload completes.

"unexpected '{'; expected end of input" sounds like more than expected is received, during a shutdown I would expect it to be interrupted in the middle of sending at most, i.e. less than expected should be received.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Review by julianbrost — CHANGES_REQUESTED** [review]
Error handling in itself is always a good idea. However, once such an error occurred, you have to consider this connection failed and can't continue to use it. So if any of these cases is triggered, a new connection should be established (which I think basically means starting a new process with the current code).

The "[json.exception.parse_error.101] parse error at line 1, column 21: syntax error while parsing value - unexpected '{'; expected end of input" reported in some issues can be the result of `recv()` failing with `EINTR`, which means the connection went out of sync and you're reading a responses for the wrong commands here, see also #9631.

**Comment by Al2Klimov** [comment]
> > I think because it shuts down due to the reload. You as a user don't _have to_ do anything. Everything's fine – once the reload completes.
> 
> Then we have to handle that gracefully.

Yes, if possible. As per #9631.

**Pull request closed without merging**
