### PR TITLE
Systemd: don't kill any running check plugins

### LINKED ISSUE #6873: Restarting Icinga service causes lots of alerts (systemd)
## Expected Behavior
`systemctl restart icinga2` - no alerts after.

## Current Behavior
After restarting the service lots of alerts appear on the dashboard. All checks that were running will return `critical`.

## Possible Solution
Do not alert on <terminated by signal 15>

## Steps to Reproduce (for bugs)
1. systemctl restart icinga2
2. see alerts

<details><summary>Screenshot</summary>

screen

</details>

## Your Environment

* Version used (`icinga2 --version`): `version: r2.10.2-1`
* Operating System and version: `CentOS Linux release 7.6.1810 (Core)`
* Enabled features (`icinga2 feature list`): `api checker command compatlog graphite ido-pgsql influxdb livestatus mainlog notification`
* Icinga Web 2 version and modules (System - About): `2.6.2`
* Config validation (`icinga2 daemon -C`): 

<details><summary>output</summary>

```
[2019-01-03 11:23:34 +1100] information/cli: Icinga application loader (version: r2.10.2-1)
[2019-01-03 11:23:34 +1100] information/cli: Loading configuration file(s).
[2019-01-03 11:23:34 +1100] information/ConfigItem: Committing config item(s).
[2019-01-03 11:23:34 +1100] warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
[2019-01-03 11:23:34 +1100] warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
[2019-01-03 11:23:34 +1100] warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
[2019-01-03 11:23:34 +1100] warning/ApiListener: Please read the upgrading documentation for v2.8: https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
[2019-01-03 11:23:34 +1100] information/ApiListener: My API identity: HOST_FQDN_REDACTED
[2019-01-03 11:23:35 +1100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
[2019-01-03 11:23:35 +1100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
[2019-01-03 11:23:35 +1100] warning/ApplyRule: Apply rule 'xmpp_host' (in /etc/icinga2/conf.d/notifications_xmpp.conf: 29:1-29:38) for type 'Notification' does not match anywhere!
[2019-01-03 11:23:35 +1100] warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 4937 Services.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 LivestatusListener.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 367 Hosts.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 FileLogger.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 10 NotificationCommands.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 4003 Notifications.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 46 HostGroups.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 ApiListener.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 Downtime.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 15 Comments.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 4 Zones.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 3 Endpoints.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 ApiUser.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 CompatLogger.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 15 Users.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 226 CheckCommands.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 9 UserGroups.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 28 ServiceGroups.
[2019-01-03 11:23:35 +1100] information/ConfigItem: Instantiated 4 TimePeriods.
[2019-01-03 11:23:36 +1100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-01-03 11:23:36 +1100] information/cli: Finished validating the configuration file(s).
```

</details>

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
<details><summary>output</summary>

```
icinga2 object list --type Endpoint
Object 'external_host_fqdn' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 3:1-3:45
  * __name = "external_host_fqdn"
  * host = "10.10.1.34"
    % = modified in '/etc/icinga2/zones.conf', lines 4:3-4:21
  * log_duration = 86400
  * name = "external_host_fqdn"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 5:3-5:13
  * source_location
    * first_column = 1
    * first_line = 3
    * last_column = 45
    * last_line = 3
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "external_host_fqdn" ]
    % = modified in '/etc/icinga2/zones.conf', lines 3:1-3:45
  * type = "Endpoint"
  * zone = ""

Object 'primary_host_fqdn' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 13:1-13:48
  * __name = "master_host_fqdn"
  * host = "localhost"
    % = modified in '/etc/icinga2/zones.conf', lines 14:3-14:20
  * log_duration = 86400
  * name = "master_host_fqdn"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 15:3-15:13
  * source_location
    * first_column = 1
    * first_line = 13
    * last_column = 48
    * last_line = 13
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "primary_host_fqdn" ]
    % = modified in '/etc/icinga2/zones.conf', lines 13:1-13:48
  * type = "Endpoint"
  * zone = ""

Object 'internal_host_fqdn' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 8:1-8:50
  * __name = "internal_host_fqdn"
  * host = "10.10.1.11"
    % = modified in '/etc/icinga2/zones.conf', lines 9:3-9:23
  * log_duration = 86400
  * name = "internal_host_fqdn"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 10:3-10:13
  * source_location
    * first_column = 1
    * first_line = 8
    * last_column = 50
    * last_line = 8
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "internal_host_fqdn" ]
    % = modified in '/etc/icinga2/zones.conf', lines 8:1-8:50
  * type = "Endpoint"
  * zone = ""
  ```

  </details>

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #6873

### CODE REVIEW

**Comment by dnsmichi** [comment]
I'm not sure which impact this has, I'd like to discuss with @lippserd prior to merging.

**Comment by dnsmichi** [comment]
@lazyfrosch I'd like to hear your opinion too on this matter, anything you'd see breaking or problematic with this? Thanks.

**Comment by dgoetz** [comment]
If the check plugin processes can still send their check result to the new main process and it is sure that both of the icinga2 processes always exit, then switching the killmode make sense.
Will the new main process also enforce the timeout on old check plugin processes? If not we should ensure they get killed somehow, so Killmode=mixed would be an option.

**Comment by lippserd** [comment]
I also opt for mixed mode. I think it is safe to change this. With kill mode mixed the following happens:

- SIGTERM is send to to the Icinga 2 main process only. As opposed to the default kill mode where all processes in the control group get killed.
- Icinga 2 will shut down and waits for all check plugins to complete. If there are long running check plugins, Icinga 2 will kill them because we have a hard? timeout.
- If by any chance Icinga 2 did not kill all of its child processes when it exists, systemd will kill them.
- If any of this takes longer than `TimeoutStopSec` which defaults to 90s, systemd will kill Icinga 2 and all of its child processes.

Sounds good to me 😆

**Comment by lazyfrosch** [comment]
:+1: for mixed

**Comment by dnsmichi** [comment]
@lippserd thanks for the detailed explanation, now I fully understand it :-)

**Comment by Al2Klimov** [comment]
ref/NC/591065

**Comment by dnsmichi** [comment]
Waiting for customer feedback.

**Comment by Al2Klimov** [comment]
What for? The issue's author reported that this change works.

**Comment by dnsmichi** [comment]
Didn't see that, my impression was that this needs feedback from the linked `ref/NC/591065`.

**Pull request merged**
