### PR TITLE
Introduce Checkable#next_update

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please explain the algorithm for calculating the value. Also, this qualifies for a unit test similar to flapping.

**Comment by Al2Klimov** [comment]
It's the same as in our IDO queries: `last check + (interval + duration) * 2`

**Comment by dnsmichi** [comment]
Docs are needed, please keep this in mind for future PRs. I've now added them in a separate commit.

**Comment by nilmerg** [comment]
Just saw #2564 again. Does this include a check's time period in the calculation?

**Comment by dnsmichi** [comment]
No, because the scheduler cannot plan ahead in this regard. The timeperiod segments are pre-calculated for roughly a day, everything else is a performance/memory problem. Therefore future timeperiods are evaluated at the very moment the check is executed. 

That being said, whenever timeperiods would apply, this needs an extra step, or a rewrite of our scheduler/timeperiod code (not something I'd like to do in the next months).

**Pull request merged**
