### PR TITLE
RPM packaging updates

### LINKED ISSUE #5177: Issues Packing icinga 2.6.3 tar.gz to RPM
## General summary
Scenario I'm working on it is a one where I'm no able to run RPMs because I don't have access to root user. So we provide RPMs to a team that have root access and install it without any option, I guess they simple run "rpm -i package.rpm". It is the reason why we want to build RPM from your tar gz. First of our shoot failed which consist to run with the spec is inside the tar.gz file.

## Expected Behavior
As I've haven't changed anything in the spec file I expect the RPM files created without errors.

## Current Behavior
It is failing during the creation of the RPM file. Giving this error ouput:

-- Found BISON: /usr/bin/bison (Required is at least version "2.3.0")
-- Found FLEX: 2.5.35 (Required is at least version "2.5.31")
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib64/mysql
-- MySQL client libraries: mysqlclient
-- Found PostgreSQL: /usr/lib64/libpq.so
-- NOTE: boost::test-based targets and tests cannot be added: boost >= 1.34.0 required but not found. (found: '' want >=103400) BUILD_TESTING disabled, so continuing anyway.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/third-party/mmatch
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/third-party/yajl/src
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/third-party/execvpe
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/third-party/socketpair
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/tools/mkclass
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/tools/mkembedconfig
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/tools/mkunity
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/base
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/cli
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/config
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/remote
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/remote
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/icinga
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/methods
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/checker
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/compat
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/db_ido
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/db_ido
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/db_ido_mysql
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/db_ido_pgsql
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/livestatus
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/notification
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/lib/perfdata
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/icinga-app
   used as include directory in directory /root/rpmbuild/BUILD/icinga2-2.6.3/icinga-app

-- Configuring incomplete, errors occurred!
See also "/root/rpmbuild/BUILD/icinga2-2.6.3/CMakeFiles/CMakeOutput.log".
See also "/root/rpmbuild/BUILD/icinga2-2.6.3/CMakeFiles/CMakeError.log".
error: Bad exit status from /var/tmp/rpm-tmp.2IxdGR (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.2IxdGR (%build)

## Steps to Reproduce (for bugs)

1. Creating RPM

cat >/etc/yum.repos.d/devtools-2.repo <<REPO
[testing-devtools-2-centos-\$releasever]
name=testing 2 devtools for CentOS $releasever
baseurl=http://people.centos.org/tru/devtools-2/\$releasever/\$basearch/RPMS
gpgcheck=0
REPO

#change repo link
#https://superuser.com/questions/866420/why-doesnt-the-centos-devtools-repo-work-on-redhat

[testing-devtools-2-centos-$releasever]
name=testing 2 devtools for CentOS
baseurl=http://people.centos.org/tru/devtools-2/6/$basearch/RPMS
gpgcheck=0
End Step 1

2. Install requirements

                yum -y install libedit-devel

                yum -y install ncurses-devel

                yum -y install openssl-devel 

                yum -y install cmake

                yum -y install     boost-devel       

                yum -y install mysql-devel
        

                yum -y install postgresql-devel

                yum -y install httpd

yum install -y gcc-c++

yum install -y flex 

yum install -y bison 

yum install -y libstdc++-devel

yum install -y devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-binutils

yum -y install rpmdevtools

yum -y install boost-devel

3. Creating rpm tree

rpmdev-setuptree

mkdir ~/tar; cd ~/tar; wget https://github.com/Icinga/icinga2/archive/v2.6.3.tar.gz
cd ~/tar; tar -xvzf v2.6.3.tar.gz
cp ~/tar/icinga2-2.6.3/icinga2.spec ~/rpmbuild/SPECS
cp ~/tar/v2.6.3.tar.gz ~/rpmbuild/SOURCES

4. Configuration

export LD_LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib:$LD_LIBRARY_PATH
export PATH=/opt/rh/devtoolset-2/root/usr/bin:$PATH
ln -sf /opt/rh/devtoolset-2/root/usr/bin/ld.bfd /opt/rh/devtoolset-2/root/usr/bin/ld
for file in `find /opt/rh/devtoolset-2/root/usr/include/c++ -name c++config.h`; do
  echo '#define _GLIBCXX__PTHREADS' >> $file
done

5. Building RPM

cd ~/rpmbuild/SPECS
rpmbuild -ba icinga2.spec

## Context

I'm trying to create RPM file from tar.gz

This is rpmbuild tree:
├── BUILD
│   └── icinga2-2.6.3
├── BUILDROOT
├── RPMS
├── SOURCES
│   └── v2.6.3.tar.gz
├── SPECS
│   └── icinga2.spec
└── SRPMS
I'm following this [link](https://github.com/Icinga/icinga2/blob/master/INSTALL.md#sles-11) to create rpm.
## Your Environment

* Version used (`icinga2 --version`): 2.6.3 
* Operating System and version:
Linux scsblnx-4352025 2.6.32-642.3.1.el6.x86_64 #1 SMP Sun Jun 26 18:16:44 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

### LINKED ISSUE #5188: Boost >= 1.48 required
During investigating #5177 and #5179 I noticed that our documented depencency against Boost >= 1.41 is incorrect.

It seems like we require at least 1.48 (like in EPEL for el5 and el6) (Note: to be tested)

Note: Our buildsystem provides 1.53 by packages...

### PR DESCRIPTION
**Pull request by lazyfrosch**
fixes #5177 - correcting Boost dependencies against EPEL and/or Icinga Repo
fixes #5188 - Depending on a newer release package

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Please don't merge this yet.

I was wondering why we previously did this: @gunnarbeutner ?

    export PATH=/opt/rh/devtoolset-2/root/usr/bin:$PATH
    ln -sf /opt/rh/devtoolset-2/root/usr/bin/ld.bfd /opt/rh/devtoolset-2/root/usr/bin/ld
    for file in `find /opt/rh/devtoolset-2/root/usr/include/c++ -name c++config.h`; do
      echo '#define _GLIBCXX__PTHREADS' >> $file
    done

I dropped the lines for now - it builds at least on CentOS6.

**Comment by dnsmichi** [comment]
AFAIK that's only necessary on el5, but I did not test that.

**Comment by lazyfrosch** [comment]
@dnsmichi Tested build on EL5 without this changes, against EPEL Boost + Icinga Boost

So I guess we could drop it for now - unless @gunnarbeutner has objections...

**Comment by dnsmichi** [comment]
I don't know why exactly we've added such, but it could be related to a broken boost version on el5/6 which was then resolved with 1.53 from packages.icinga.com. As said earlier, I wasn't aware that we depend on our own boost rpms for older RHEL versions. Might be a good time to clean things up after ~3 years :-)

**Comment by lazyfrosch** [comment]
If so it would be a runtime error, I tested the build against 1.48 (EPEL)

**Comment by lazyfrosch** [comment]
Please review and merge, this has been tested nearly everywhere.

Changes are already applied to https://github.com/icinga/icinga-packaging/tree/rpm/snapshot

**Comment by dnsmichi** [comment]
Thanks, looks good 👍  e669e998326112d87d2623c8144bb78505be0040 is already fixed in master (separate PR), I'm leaving that out.

**Comment by dnsmichi** [comment]
Created a separate issue for the suse g++ compiler version, just a cosmetic change - #5218.

**Comment by dnsmichi** [comment]
Rebased, reworded and merged to master, thanks.

**Pull request closed without merging**
