### PR TITLE
FilteredAddTarget(): just don't include an object on filter error

### LINKED ISSUE #8128: Icinga API filter functions (e.g. len(), contains()) malfunction when their subject is null on any configuration object
## Describe the bug

We are using the API to query objects containing certain variables, e.g. the variable "test" on the object "service-1". The filter `vars.contains("test")` works perfectly.

However, if there is _any_ service in the Icinga environment that _does not_ have any variables, it fails to find anything at all and comes back with a 404 error.

## To Reproduce

Set up an otherwise empty Icinga2 server and define the following objects:

```
object Host "host-1" {
    address = "host-1"

    check_command = "dummy"
}

object Service "service-1" {
    check_command = "dummy"

    host_name = "host-1"

    vars = {
        test = "test"
    }
}
```

Now, query for the service using the aforementioned filter:

```
# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars.contains(%22test%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "results": [
    {
      "attrs": {
        "vars": {
          "test": "test"
        }
      },
      "joins": {},
      "meta": {},
      "name": "host-1!service-1",
      "type": "Service"
    }
  ]
}
```

Now add a second service without any vars:

```
object Service "service-2" {
    check_command = "dummy"
 
    host_name = "host-1"
}
```

The same query that was used successfully above will now fail completely:

```
# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars.contains(%22test%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "error": 404,
  "status": "No objects found."
}
```

## Expected behavior

An API query should return the same result regardless if there are objects that do not (or cannot) match the query. 

## Your Environment

* Version used (`icinga2 --version`): 2.11.4-1 (reproducible with other versions as well)
* Operating System and version: CentOS 7.7
* Enabled features (`icinga2 feature list`): api checker ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.8.1
* Config validation (`icinga2 daemon -C`): 
```
# icinga2 daemon -C 
[2020-07-21 18:11:01 +0000] information/cli: Icinga application loader (version: 2.11.4-1)
[2020-07-21 18:11:01 +0000] information/cli: Loading configuration file(s).
[2020-07-21 18:11:01 +0000] warning/config: Ignoring directory '/etc/icinga2/zones.d/haj' for unknown zone 'haj'.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Committing config item(s).
[2020-07-21 18:11:01 +0000] information/ApiListener: My API identity: master1.dev.evi.dfs
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 Host.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 4 Zones.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 4 Endpoints.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 3 ApiUsers.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 203 CheckCommands.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
[2020-07-21 18:11:01 +0000] information/ConfigItem: Instantiated 2 Services.
[2020-07-21 18:11:01 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-07-21 18:11:01 +0000] information/cli: Finished validating the configuration file(s).
```

## Additional context

The problem is not limited to the vars dictionary. It can be reproduced on deeper indentation levels as well: `contains()` on a variable that is not available on all objects will break the whole query.

The problem will not arise when there are no elements in vars, but vars is not null. 

```
object Service "service-2" {
    check_command = "dummy"

    host_name = "host-1"

    vars = {
    }
}
```

```
# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars.contains(%22test%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "results": [
    {
      "attrs": {
        "vars": {
          "test": "test"
        }
      },
      "joins": {},
      "meta": {},
      "name": "host-1!service-1",
      "type": "Service"
    }
  ]
}
```

It can also be worked around by modifying the query so that it checks vars before using `contains()`:

```
# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars%26%26service.vars.contains(%22test%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "results": [
    {
      "attrs": {
        "vars": {
          "test": "test"
        }
      },
      "joins": {},
      "meta": {},
      "name": "host-1!service-1",
      "type": "Service"
    }
  ]
}
```

And the same can be reproduced with arrays and with more deeply nested variables as well:

```
object Service "service-1" {
    check_command = "dummy"

    host_name = "host-1"

    vars = {
        test = [ "test1", "test2" ]
    }
}

object Service "service-2" {
    check_command = "dummy"

    host_name = "host-1"

    vars = {
        other_variable = "test"
    }
}
```

```
# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars.test.contains(%22test2%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "error": 404,
  "status": "No objects found."
}

# curl -s -k "https://192.168.110.111:5665/v1/objects/services?attrs=vars&filter=service.vars.test%26%26service.vars.test.contains(%22test2%22)" -H 'Accept: application/json' -u 'user:password' | jq
{
  "results": [
    {
      "attrs": {
        "vars": {
          "test": [
            "test1",
            "test2"
          ]
        }
      },
      "joins": {},
      "meta": {},
      "name": "host-1!service-1",
      "type": "Service"
    }
  ]
}
```

### LINKED ISSUE #8831: API request with Logical Operators (<, >)
I was trying to filter Hosts by utilizing the filter option of the Icinga2API. 

`curl -k -s -u username:password -H 'Accept: application/json' -X GET 'https://1.2.3.4:5665/v1/objects/hosts' -d '{ "type": "Host", "filter": "host.vars.reboot>0" }'`

`response: { "error": 404.0, "status": "No objects found." }`

When using "==" operator I get a correct response.

`curl -k -s -u username:password -H 'Accept: application/json' -X GET 'https://1.2.3.4:5665/v1/objects/hosts' -d '{ "type": "Host", "filter": "host.vars.reboot==1" }'`

`response: [...some hosts where vars.reboot == 1...]`

but when I filter for a default variable like `state` it does function

`curl -k -s -u username:password -H 'Accept: application/json' -X GET 'https://1.2.3.4:5665/v1/objects/hosts' -d '{ "type": "Host", "filter": "host.state>0" }'`

`response: [...some hosts where state > 0...]`

I tried `host.vars.reboot` as string and integer.

My current workaround
`curl -k -s -u username:password -H 'Accept: application/json' -X GET 'https://1.2.3.4:5665/v1/objects/hosts' -d '{ "type": "Host", "filter":"host.vars.reboot!=0 && host.vars.reboot!=null"}'`

`response: [...correctly filtered hosts ...]`

[The original Icinga forum topic](https://community.icinga.com/t/api-request-with-logical-operators-in-filter/7465)

### PR DESCRIPTION
**Pull request by Al2Klimov**
... instead of failing on the whole request.

fixes #8128
fixes #8831

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
$ curl -k -s -u root:3d0ce6310a7e367b -H 'Accept: application/json' 'https://localhost:5665/v1/objects/services?pretty=1&filter=service.vars.len()'
{
    "error": 404.0,
    "status": "No objects found."
}
```

```
[2020-07-30 11:51:04 +0200] information/ApiListener: New client connection from [::1]:55309 (no client certificate)
[2020-07-30 11:51:04 +0200] information/HttpServerConnection: Request: GET /v1/objects/services?pretty=1&filter=service.vars.len() (from [::1]:55309), user: root, agent: curl/7.64.1).
[2020-07-30 11:51:04 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:55309)
```

## After

```
$ curl -k -s -u root:3d0ce6310a7e367b -H 'Accept: application/json' 'https://localhost:5665/v1/objects/services?pretty=1&filter=service.vars.len()'
{
    "results": [
        {
            "attrs": {
                "__name": "alexanders-mbp.int.netways.de!load",
...
```

```
[2020-07-30 11:51:50 +0200] information/ApiListener: New client connection from [::1]:55318 (no client certificate)
[2020-07-30 11:51:50 +0200] information/HttpServerConnection: Request: GET /v1/objects/services?pretty=1&filter=service.vars.len() (from [::1]:55318), user: root, agent: curl/7.64.1).
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] warning/FilterUtility: Argument is not a callable object.
[2020-07-30 11:51:50 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:55318)
```

**Review by julianbrost — CHANGES_REQUESTED** [review]
I think this shouldn't log a message for every single object. A single HTTP request shouldn't cause that many log messages.

**Comment by Al2Klimov** [comment]
But the messages _could be_ different per object.

**Comment by julianbrost** [comment]
Sure they can, but would you expect 100k+ log lines from a single request with a typo in a large setup? Maybe collect all the error messages in a set and print the first few ones. Or count how often they occurred and print the ones that happened most often.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by Al2Klimov** [comment]
Top five – fine?

**Comment by julianbrost** [comment]
When looking at this again, the messages itself provide no context information on where this warning comes from. So with multiple concurrent requests or other logging in between, these messages will be hard to attribute to something.

Implementing any of the suggested improvements would require adding some aggregation of error messages across multiple calls to `FilteredAddTarget()`. So instead of somehow ranking the messages and logging the top messages, wouldn't it be an option to include them in the HTTP response? Then the messages will find their way back to the source that caused it. Also, in a response that could contain 100k objects, I don't see much harm in sending 100k error messages instead.

We just have to be careful with errors that come from the permission filter that is checked in the same function. These errors probably shouldn't be sent to the client because they might reveal information about objects the user isn't supposed to see. These would also make more sense to show up in the Icinga log as they are relevant for the administrator. If there's a permission filter set up that fails to execute on some object, this is relevant independent from the specific request that caused it. (But still, this shouldn't flood the log, so when actually logging, some form of rate-limiting is desirable.)

**Comment by Al2Klimov** [comment]
Idea: instead still fail on the whole request, but with the first user filter error – OK?

**Comment by julianbrost** [comment]
That would indeed be in line with what apply rules do. There it's also an error and this should behave the same as filters in the API:

```
[2023-02-01 11:09:37 +0100] critical/config: Error: Argument is not a callable object.
Location: in /etc/icinga2/zones.d/global-templates/services.conf: 119:15-119:48
/etc/icinga2/zones.d/global-templates/services.conf(117): 
/etc/icinga2/zones.d/global-templates/services.conf(118): apply Service "apply-error-test" {
/etc/icinga2/zones.d/global-templates/services.conf(119):  assign where host.vars.foofsdfkjs.bar.baz.len()
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/zones.d/global-templates/services.conf(120): }
/etc/icinga2/zones.d/global-templates/services.conf(121): 
```

How would you handle errors from the permission filter?

**Comment by Al2Klimov** [comment]
As requests already fail completely I guess it won't hurt to just s/404/500/ and to log the (first) error.

**Comment by julianbrost** [comment]
So, on first error:
- if permission filter error: log error, send 5xx error with a message that says that there's a configuration error and a permission filter failed and that more information can be found in the server log.
- if user filter error: send 4xx error with more detailed error message.

Sounds like a plan.

Please make the logged error message contain a bit more context information (something like "evaluating permission filter of user "$user" failed on Host object "$object": $error" would be helpful).

**Pull request closed without merging**
