### PR TITLE
Log: trim trailing newlines

### LINKED ISSUE #7828: Log: trim trailing newlines
## Is your feature request related to a problem? Please describe.

Sometimes I get log messages like these:

```
[2020-02-12 15:02:36 +0100] warning/JsonRpcConnection: Error while sending JSON-RPC message for identity 'localhost'
Error: Broken pipe





[2020-02-12 15:02:36 +0100] warning/JsonRpcConnection: API client disconnected for identity 'localhost'
```

## Describe the solution you'd like

Log trims trailing newlines.

## Describe alternatives you've considered

None.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7828

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
[2020-02-19 11:20:51 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local' (PID: 42482, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping' '-H' '127.0.0.1' '-c' '5000,100%' '-w' '3000,80%') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping) failed: No such file or directory

[2020-02-19 11:20:54 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local!http' (PID: 42483, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_http' '-I' '127.0.0.1' '-u' '/') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_http) failed: No such file or directory

[2020-02-19 11:20:59 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local!ping6' (PID: 42484, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping' '-6' '-H' '::1' '-c' '200,15%' '-w' '100,5%') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping) failed: No such file or directory
```

## After

```
[2020-02-19 11:22:09 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local!http' (PID: 42786, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_http' '-I' '127.0.0.1' '-u' '/') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_http) failed: No such file or directory
[2020-02-19 11:22:14 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local!ping6' (PID: 42787, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping' '-6' '-H' '::1' '-c' '200,15%' '-w' '100,5%') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_ping) failed: No such file or directory
[2020-02-19 11:22:19 +0100] warning/PluginCheckTask: Check command for object 'Alexanders-MacBook-Pro.local!disk' (PID: 42788, arguments: '/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_disk' '-c' '10%' '-w' '20%' '-X' 'none' '-X' 'tmpfs' '-X' 'sysfs' '-X' 'proc' '-X' 'configfs' '-X' 'devtmpfs' '-X' 'devfs' '-X' 'mtmfs' '-X' 'tracefs' '-X' 'cgroup' '-X' 'fuse.gvfsd-fuse' '-X' 'fuse.gvfs-fuse-daemon' '-X' 'fdescfs' '-X' 'overlay' '-X' 'nsfs' '-X' 'squashfs' '-m') terminated with exit code 128, output: execvpe(/Users/aklimov/NET/WS/icinga2/prefix/usr/lib/nagios/plugins/check_disk) failed: No such file or directory
```

**Review by julianbrost — COMMENTED** [review]
This will also affect some of the multi-line log messages we have, most notably stack traces, which currently look like this:

```
[2020-12-23 11:22:58 +0000] notice/JsonRpcConnection: Error while reading JSON-RPC message for identity 'agent-2': Error: stream truncated


	(0) icinga2: icinga::JsonRpcConnection::HandleIncomingMessages(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >) (+0x19f) [0x561059e1d96f]
	(1) icinga2: <unknown function> (+0x6a6d6e) [0x561059e1dd6e]
	(2) icinga2: <unknown function> (+0x6aec62) [0x561059e25c62]
	(3) libboost_context.so.1.67.0: make_fcontext (+0x2f) [0x7ffb36b791ef]



[2020-12-23 11:22:58 +0000] warning/JsonRpcConnection: API client disconnected for identity 'agent-2'
```

So maybe we just want to trim trailing `\n` if it is a single line log message? But it also won't hurt much to trim the empty lines there, the number of those feels arbitrary anyways.

**Comment by Al2Klimov** [comment]
> This will also affect some of the multi-line log messages

Wouldn't it be OK for you?

**Comment by julianbrost** [comment]
I'm fine with both, I just wanted to point this out as another case affected by this change. Will fire up the code to test it myself with a few examples and then submit another review.

**Review by julianbrost — APPROVED** [review]
#### Test Code
```cpp
	Log(LogNotice, "Test") << "Hello\n\nWorld\n\n";
	Log(LogNotice, "Test") << "Foo";
	Log(LogNotice, "Test") << "Bar\n";
	Log(LogNotice, "Test") << "Baz\n\n";
	try {
		throw std::exception();
	} catch (const std::exception& ex) {
		Log(LogNotice, "Test") << "Exception: " << DiagnosticInformation(ex);
	}
```

#### Test Output
```
[2020-12-23 13:17:41 +0000] notice/Test: Hello

World
[2020-12-23 13:17:41 +0000] notice/Test: Foo
[2020-12-23 13:17:41 +0000] notice/Test: Bar
[2020-12-23 13:17:41 +0000] notice/Test: Baz
[2020-12-23 13:17:41 +0000] notice/Test: Exception: Error: std::exception


	(0) icinga2: <unknown function> (+0x6b01fb) [0x55d91e3931fb]
	(1) icinga2: <unknown function> (+0x6b92c5) [0x55d91e39c2c5]
	(2) libboost_context.so.1.67.0: make_fcontext (+0x2f) [0x7f9e28cb01ef]
[2020-12-23 13:17:41 +0000] [...]
```

**Pull request merged**
