### PR TITLE
ConfigObjectUtility#CreateObject(): check config objects for duplicates

### LINKED ISSUE #7094: Icinga2 API removes config file on creation of an already existing service object in HA mode
## Describe the bug
Icinga2 removes the config file for a service object, which was created using API, if you try to create it again. This happens only on one of the nodes in a master zone of a HA environment, but it could be any node of the two.

## To Reproduce
1. Create a host and a service for it:
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X PUT https://node1.domain.com:5665/v1/objects/hosts/newhost -d '{ "attrs": { "check_command": "hostalive", " address": "127.0.0.1" } }'
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X PUT https://node1.domain.com:5665/v1/objects/services/newhost!newservice -d '{ "attrs": { "check_command": "passive" } }'
```
2. Create a the service check again:
```
curl -u USERNAME:PASSWORD -k -H 'Accept: application/json' -X PUT https://node1.domain.com:5665/v1/objects/services/newhost!newservice -d '{ "attrs": { "vars.app_env": "debug", "check_command": "passive" } }'
{
    "results": [
        {
            "code": 500.0,
            "errors": [
                "Error: An object with type 'Service' and name 'newhost!newservice' already exists (in /var/lib/icinga2/api/packages/_api/node1.domain.com-1528367700-0/conf.d/services/newhost!newservice.conf: 1:0-1:26), new declaration: in /var/lib/icinga2/api/packages/_api/node1.domain.com-1528367700-0/conf.d/services/newhost!newservice.conf: 1:0-1:26\nLocation: in /var/lib/icinga2/api/packages/_api/node1.domain.com-1528367700-0/conf.d/services/newhost!newservice.conf: 1:0-1:26"
            ],
            "status": "Object could not be created."
        }
    ]
}
```
3. Check for config files on both Icinga2 master nodes:
```
# node1.domain.com
find /var/lib/icinga2 -name '*newhost*'
/var/lib/icinga2/api/packages/_api/node1.domain.com-1528367700-0/conf.d/hosts/newhost.conf

# node2.domain.com
find /var/lib/icinga2 -name '*newhost*'
/var/lib/icinga2/api/packages/_api/node2.domain.com-1528367700-0/conf.d/services/newhost!newservice.conf
/var/lib/icinga2/api/packages/_api/node2.domain.com-1528367700-0/conf.d/hosts/newhost.conf
```
4. systemctl reload icinga2 only fixes the issue if there are no depending notification objects for the 'newservice' object. If 'newservice' has a notification for it - Icinga2 is not able to reload anymore and in case of a restart it does not start anymore, because of the obvious config violation.

## Expected behavior
A re-creation of a service object should not remove a config file or in cases like these - resync should be initiated.

## Suggestion
Could Icinga2 be a little less restrictive and display a warning for missing objects when starting instead of failing completely?

## Your Environment

* Version used (`icinga2 --version`): 2.10.4
* Operating System and version: RHEL7.6
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql influxdb mainlog notification
* Icinga Web 2 version and modules (System - About): v2.6.1 with monitoring v2.6.1
* Config validation (`icinga2 daemon -C`): all good
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
object Endpoint "node1.domain.com" {
}

object Endpoint "node2.domain.com" {
  host = "node2.domain.com";
  port = "5665";
}

object Zone "master" {
  endpoints = ["node1.domain.com","node2.domain.com"];
}
```
node1 is config master, node2 mainly serves as an active node for Icingaweb2.

### LINKED ISSUE #7726: API - Using PUT on already exiting object results in deletion of its configuration file
## Describe the bug

Service object gets removed when PUT method is used on already existing object through Icinga2 API resulting in an inconsistent configuration leading to anomalies and inability reload/restart Icinga2 process.

Happens when objects are being modified through API when using PUT instead of POST. It happens only to services and only when using PUT on already existing object (API returns 500 code). It does not trigger using POST or if object does not exists.

It is a bit difficult to trigger as the inconsistency in configuration can sometime be "fixed" by repeatedly adding hosts/services, but not always. I can trigger this fairly consistently on our production site with around 550 hosts and 5000 services, but using a separate instance for testing purposes with smaller amount of hosts seems to not trigger the bug as often.

This could be dupe of [7094](https://github.com/Icinga/icinga2/issues/7094) but our configuration is not using HA. And possibly related to [7330](https://github.com/Icinga/icinga2/issues/7330) as at first I thought it was done by the cascade delete. Bug is present in v2.10.3 v2.10.5 and latest v2.11.2. I will note that triggering the bug in latest version requires much more objects being pushed through the API then in 10.x.x versions.

## To Reproduce

1. Create several hosts with services through API. Around 30 host with 10 services with notifications each should suffice to trigger the bug. It's much easier to trigger on a busy site.

2. Repeat the step 1, again creating the same hosts/services using the PUT method

3. Validate configuration a attempt to restart Icinga

## Expected behavior

Using API with PUT on existing object should not damage server configuration and object states.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): **r2.11.2-1**
* Operating System and version: **Debian 9**
* Enabled features (`icinga2 feature list`): **api checker command compatlog ido-mysql influxdb livestatus mainlog notification**
* Icinga Web 2 version and modules (System - About):  **2.7.3**
* Config validation (`icinga2 daemon -C`): no errors
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context
I can supply additional logs if needed. I would also repeat that is it much easier to trigger on larger and busy site. I had not much luck replicating this in my test environment.

LOGS:
icinga2.log
```
[2019-12-23 12:43:03 +0100] information/HttpServerConnection: Request: PUT /v1/objects/services/some.server1.domain.cz!check_procs (from [172.20.0.1]:41912), user: painkiller, agent: ansible-httpget).
[2019-12-23 12:43:03 +0100] critical/config: Error: An object with type 'Service' and name 'some.server1.domain.cz!check_procs' already exists (in /var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf: 1:0-1:27), new declaration: in /var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf: 1:0-1:27
Location: in /var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf: 1:0-1:27
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf(1): object Service "check_procs" {
                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf(2):  check_command = "nrpe"
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/services/some.server1.domain.cz!check_procs.conf(3):  enable_flapping = true

[2019-12-23 12:43:03 +0100] critical/config: 1 error
[2019-12-23 12:43:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [172.20.0.1]:41912)
```

/usr/sbin/icinga2 daemon --validate
```
[2019-12-23 12:43:13 +0100] critical/config: Error: Notification object refers to a host/service which doesn't exist.
Location: in /var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/notifications/some.server1.domain.cz!check_procs!mail-service-notification.conf: 1:0-1:46
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/notifications/some.server1.domain.cz!check_procs!mail-service-notification.conf(1): object Notification "mail-service-notification" {
                                                                                                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/notifications/some.server1.domain.cz!check_procs!mail-service-notification.conf(2):  command = "mail-service-notification"
/var/lib/icinga2/api/packages/_api/3310de52-fff2-44e6-aa2f-7ec494c84a3c/conf.d/notifications/some.server1.domain.cz!check_procs!mail-service-notification.conf(3):  host_name = "some.server1.domain.cz"
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
... not to delete already existing objects during a trial of re-creation.

fixes #7726
fixes #7094

### CODE REVIEW

**Comment by Al2Klimov** [comment]
```
➜  icinga2 git:(master) ✗ curl -skSu root:123456 -H 'Accept: application/json' -X PUT -d '{"attrs":{"check_command":"disk"}}' 'https://127.0.0.1:5665/v1/objects/services/lolcat!disk'
{"results":[{"code":200.0,"status":"Object was created"}]}
➜  icinga2 git:(master) ✗ prefix/sbin/icinga2 daemon -C -x critical
➜  icinga2 git:(master) ✗ prefix/sbin/icinga2 object list --type service --name 'lolcat!disk'
Object 'lolcat!disk' of type 'Service':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 1:0-1:20
  * __name = "lolcat!disk"
  * action_url = ""
  * check_command = "disk"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 2:2-2:23
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "disk"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "lolcat"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 3:2-3:21
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "disk"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * retry_interval = 60
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 20
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf"
  * templates = [ "disk" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 1:0-1:20
  * type = "Service"
  * vars = null
  * volatile = false
  * zone = "Alexanders-MacBook-Pro.local"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 5:2-5:38
➜  icinga2 git:(master) ✗ curl -skSu root:123456 -H 'Accept: application/json' -X PUT -d '{"attrs":{"check_command":"disk"}}' 'https://127.0.0.1:5665/v1/objects/services/lolcat!disk'
{"results":[{"code":500.0,"errors":["Object 'lolcat!disk' already exists."],"status":"Object could not be created."}]}
➜  icinga2 git:(master) ✗ prefix/sbin/icinga2 daemon -C -x critical
➜  icinga2 git:(master) ✗ prefix/sbin/icinga2 object list --type service --name 'lolcat!disk'
Object 'lolcat!disk' of type 'Service':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 1:0-1:20
  * __name = "lolcat!disk"
  * action_url = ""
  * check_command = "disk"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 2:2-2:23
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "disk"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "lolcat"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 3:2-3:21
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "disk"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * retry_interval = 60
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 20
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf"
  * templates = [ "disk" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 1:0-1:20
  * type = "Service"
  * vars = null
  * volatile = false
  * zone = "Alexanders-MacBook-Pro.local"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/f41b1965-ece4-4fb7-96f5-0fc6c0a8c6e6/conf.d/services/lolcat!disk.conf', lines 5:2-5:38
➜  icinga2 git:(master) ✗
```

**Comment by julianbrost** [comment]
I'm still looking at the code to figure out the path it took when this initially happened. Do you know why this isn't already captured by the if right above the code you added?

**Comment by Al2Klimov** [comment]
I guess because I'm adding stuff _via API_.

**Comment by julianbrost** [comment]
Started trying to figure out why this is not caught by https://github.com/Icinga/icinga2/blob/e25f32836fc42d18030f5e3168a1a9186a3a4d91/lib/remote/configobjectutility.cpp#L155

Turns out that the map used for the lookup contains the following keys:
* for Host: All Host templates and objects (generic-host, agent-1, ...)
* for Service: Only Service templates (generic-service, ...) but no actual Service objects

Let's see if I can figure out why this happens. Might be a bug, might be something special about services due to apply rules.

**Comment by julianbrost** [comment]
So because services have composite names, they don't end up in the map used for the lookup but in a vector `m_UnnamedItems` instead: https://github.com/Icinga/icinga2/blob/11394498e70a8caa46710e1e3a9bb561aeaf226a/lib/config/configitem.cpp#L322-L325

What the second check now does is basically the same what `get_object()` in the Icinga 2 config language does. But I'm not sure what to do with this information. Do we need both checks? Is the new one sufficient and can replace the old one?

**Comment by Al2Klimov** [comment]
Yes, one is enough.

```
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 api setup -x critical
Enabling feature api. Make sure to restart Icinga 2 for these changes to take effect.
Done.

Now restart your Icinga 2 daemon to finish the installation!

➜  icinga2 git:(bugfix/api-put-object-deletion-7726) perl -pi -e 's/\bpassword = ".*?"/password = "123456"/' prefix/etc/icinga2/conf.d/api-users.conf
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 daemon -d
[2020-12-16 16:41:22 +0100] information/cli: Icinga application loader (version: v2.12.0-398-gc5626bd79)
[2020-12-16 16:41:22 +0100] information/cli: Closing console log.
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) curl -skSu root:123456 -H 'Accept: application/json' -X PUT -d '{"attrs":{"check_command":"disk"}}' 'https://127.0.0.1:5665/v1/objects/hosts/lolcat'
{"results":[{"code":200.0,"status":"Object was created"}]}
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) curl -skSu root:123456 -H 'Accept: application/json' -X PUT -d '{"attrs":{"check_command":"disk"}}' 'https://127.0.0.1:5665/v1/objects/services/lolcat!disk'
{"results":[{"code":200.0,"status":"Object was created"}]}
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 daemon -C -x critical
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 object list --type service --name 'lolcat!disk' |grep -Ee '^Object'
Object 'lolcat!disk' of type 'Service':
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) curl -skSu root:123456 -H 'Accept: application/json' -X PUT -d '{"attrs":{"check_command":"disk"}}' 'https://127.0.0.1:5665/v1/objects/services/lolcat!disk'
{"results":[{"code":500.0,"errors":["Object 'lolcat!disk' already exists."],"status":"Object could not be created."}]}
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 daemon -C -x critical
➜  icinga2 git:(bugfix/api-put-object-deletion-7726) prefix/sbin/icinga2 object list --type service --name 'lolcat!disk' |grep -Ee '^Object'
Object 'lolcat!disk' of type 'Service':
➜  icinga2 git:(bugfix/api-put-object-deletion-7726)
```

**Review by julianbrost — APPROVED** [review]
LGTM. Probably a candidate for backporting.

**Pull request merged**
