### PR TITLE
Avoid "type" key in dicts being part of object state attrs

### LINKED ISSUE #8186: Icinga2 crashes when sending notifications
## Describe the bug
Yesterday, after a config reload, our icinga2 master kept crashing with the same stack strace.
At first it crashed after 20-30 Seconds, after a while directly after validating the configuration. This went on for an hour.

```
        (0) libc.so.6: gsignal (+0xcf) [0x7f0597314fff]
        (1) libc.so.6: abort (+0x16a) [0x7f059731642a]
        (2) libc.so.6: <unknown function> (+0x2be67) [0x7f059730de67]
        (3) libc.so.6: <unknown function> (+0x2bf12) [0x7f059730df12]
        (4) icinga2: icinga::NotificationComponent::NotificationTimerHandler() (+0x159b) [0x561d3dec965b]
        (5) icinga2: <unknown function> (+0x338271) [0x561d3db5b271]
        (6) icinga2: icinga::Timer::Call() (+0x2d) [0x561d3daf94bd]
        (7) icinga2: <unknown function> (+0x341e0d) [0x561d3db64e0d]
        (8) icinga2: boost::asio::detail::executor_op<boost::asio::detail::work_dispatcher<bool icinga::ThreadPool::Post<std::function<void ()> >(std::function<void ()>, icinga::SchedulerPolicy)::{lambda()#1}>, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete(void*, std::allocator<void>*, boost::system::error_code const&, unsigned long) (+0xe3) [0x561d3e0018b3]
        (9) icinga2: <unknown function> (+0x27d5f6) [0x561d3daa05f6]
        (10) icinga2: <unknown function> (+0x7dbae5) [0x561d3dffeae5]
        (11) icinga2: boost_asio_detail_posix_thread_function (+0xf) [0x561d3da93aff]
        (12) libpthread.so.0: <unknown function> (+0x74a4) [0x7f0598a8d4a4]
        (13) libc.so.6: clone (+0x3f) [0x7f05973cad0f]
```

After debugging a little, we figured that it is related to notifications. We disabled all notifications and icinga2 was able to start again without crashing. Then we were able to reactivate all notifications, as it seems that there was a buggy notification queued that caused the crash. Our theory is, that disabling all notifications cleared the buggy icinga2 state.

## To Reproduce
We have no idea what caused this bug, except the fact that it seems to be related to notifications.

## Expected behavior
No crashes.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

  Application version: r2.12.0-1

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-13-amd64
  Architecture: x86_64

Disabled features: compatlog debuglog elasticsearch gelf graphite icingadb livestatus opentsdb perfdata statusdata
Enabled features: api checker command ido-mysql influxdb mainlog notification syslog

Icinga Web 2: 2.8.2

Config validation:
```
[2020-08-21 08:18:46 +0200] information/cli: Icinga application loader (version: r2.12.0-1)
[2020-08-21 08:18:46 +0200] information/cli: Loading configuration file(s).
[2020-08-21 08:18:46 +0200] information/ConfigItem: Committing config item(s).
[2020-08-21 08:18:46 +0200] information/ApiListener: My API identity: monty1.uni-paderborn.de
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'notify_host_imt_srv_mail' (in /etc/icinga2/zones.d/master/notifications.conf: 369:1-369:53) for type 'Notification' does not match anywhere!
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'notify_service_imt_srv_mail' (in /etc/icinga2/zones.d/master/notifications.conf: 378:1-378:59) for type 'Notification' does not match anywhere!
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'mysql_backup_check_exists' (in /etc/icinga2/zones.d/master/services/mysql_cluster.conf: 19:1-19:41) for type 'Service' does not match anywhere!
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'check_http_content' (in /etc/icinga2/zones.d/master/services/solr.conf: 1:0-1:33) for type 'Service' does not match anywhere!
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'check_ipmi' (in /etc/icinga2/zones.d/master/services/sun.conf: 1:0-1:25) for type 'Service' does not match anywhere!
[2020-08-21 08:18:53 +0200] warning/ApplyRule: Apply rule 'check_windows-failover_sp' (in /etc/icinga2/zones.d/master/services/windows.conf: 13:1-13:41) for type 'Service' does not match anywhere!
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 SyslogLogger.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 904 Hosts.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 455 Downtimes.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 7 NotificationCommands.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 253 Comments.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 23810 Notifications.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 140 HostGroups.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 EventCommand.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 6774 Dependencies.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 463 Zones.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 463 Endpoints.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 498 ApiUsers.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 176 CheckCommands.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 7 TimePeriods.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 10 UserGroups.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 31 Users.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 10515 Services.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 42 ServiceGroups.
[2020-08-21 08:18:53 +0200] information/ConfigItem: Instantiated 181 ScheduledDowntimes.
[2020-08-21 08:18:53 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-08-21 08:18:53 +0200] information/cli: Finished validating the configuration file(s).
```

## Additional context
We are running a single master node without HA.

### PR DESCRIPTION
**Pull request by Al2Klimov**
not to confuse the state file deserializator with e.g. `"type":32` on startup.
That would unexpectedly restore null (not `{"type":32}`) as there's no type "32".

fixes #8186

### CODE REVIEW

**Comment by julianbrost** [comment]
What happened to the graceful handling for existing "broken" state files that you(?) suggested?

**Comment by Al2Klimov** [comment]
Didn’t they already vanish?

**Comment by julianbrost** [comment]
How? I don't see a reason why this shouldn't happen again. And if the fix included, the recommendation for that bug can be "upgrade Icinga, the new version will start successfully with that state file" rather than "sorry, please delete the state file".

**Comment by julianbrost** [comment]
Everyone who ran into this issue so far: most likely they deleted their state file. But others will probably run into the same issue in the future after we released a fix because they are running an old version. They can then upgrade instead of having to delete the state file.

**Comment by julianbrost** [comment]
What would prevent me from running into this bug with Icinga 2.13.2?

**Comment by Al2Klimov** [comment]
Errm.. nothing?

**Comment by julianbrost** [comment]
Oh, and all that's needed for this would be an `if (!unstashedNotification) { continue; }`, possibly with an additional log message that a broken stashed notification was discarded.

**Comment by Al2Klimov** [comment]
> an additional log message that a broken stashed notification was discarded

Do you consider that part actually helpful?

**Comment by julianbrost** [comment]
It's a situation that shouldn't happen after this bug is fixed, so it's more like a hint in case a similar bug ever appears in the future.

**Review by julianbrost — CHANGES_REQUESTED** [review]
Please add that additional `nullptr` check suggested in my previous comments.

**Comment by Al2Klimov** [comment]
During cold startup provoke a notification and turn off.

**Comment by Al2Klimov** [comment]
Hmm.. what about: instead of constructing $WHATEVER, stop Icinga 2 and monkey-patch the state file with the desired content? After all the users got a such state file, too. Then start Icinga $VERSION and see whether it crashes.

**Comment by julianbrost** [comment]
I'd prefer a full test of stashed notifications with a restore from state file as this obviously was never done before (#8186 is triggered reliably under these circumstances).

**Comment by Al2Klimov** [comment]
I have no idea. https://github.com/Icinga/icinga2/pull/9123#issuecomment-1005039893 seems not to work, but state file monkey-patching clearly does.

**Review by julianbrost — APPROVED** [review]
To reproduce, you can start only one node in a HA zone, and within 30 seconds, send a custom notification and stop it again.

So with my trusty test cluster starting with a current master build (30e1e8d3f47530a962db9ab9ea92d4457c2dc0d4):

```
$ docker compose up -d master-1; \
    sleep 5; \
    curl -ksSu root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/send-custom-notification' -d '{"type": "Host", "host": "master-1", "author": "test", "comment": "test", "force": true, "pretty": true}'; \
    sleep 5; \
    docker compose logs master-1 | grep -i stash; \
    docker compose down
[+] Running 1/1
 ⠿ Container cluster-master-1-1  Started                                                                                                                  0.5s
{
    "results": [
        {
            "code": 200,
            "status": "Successfully sent custom notification for object 'master-1'."
        }
    ]
}
cluster-master-1-1  | [2022-01-19 11:28:40 +0100] notice/Notification: Notification 'master-1!dummy-host-notification': object authority hasn't been updated, yet. Stashing notification.
[+] Running 2/2
 ⠿ Container cluster-master-1-1  Removed                                                                                                                  6.4s
 ⠿ Network cluster_default       Removed  
```

This wrote a stashed notification to the state file:
```
$ netstring-to-lines < data/master-1/var/lib/icinga2/icinga2.state | grep 'master-1!dummy-host-notification' | jq -r .update.stashed_notifications
[
  {
    "author": "test",
    "cr": {
      [...]
    },
    "force": true,
    "reminder": false,
    "text": "test",
    "type": 8
  }
]
```

Now starting just master-1 again reproduces the crash:
```
$ docker compose up master-1
[...]
cluster-master-1-1  | [2022-01-19 11:32:59 +0100] notice/NotificationComponent: Attempting to send stashed notification 'master-1!dummy-host-notification'.
cluster-master-1-1  | icinga2: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199: T* boost::intrusive_ptr<T>::operator->() const [with T = icinga::Dictionary]: Assertion `px != 0' failed.
[...]
cluster-master-1-1 exited with code 134
```

Now switching to a build of this PR merged into master (e9e555468 + 463b15941) and starting the same node again, it no longer crashes (there is no observable output as the stashed notification still deserializes as `null` and is silently discarded).

Next, executing above command again to generate yet another stashed notification and then starting master-1 again:
```
$docker compose up -d master-1; \
    sleep 5; \
    curl -ksSu root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/send-custom-notification' -d '{"type": "Host", "host": "master-1", "author": "test", "comment": "test", "force": true, "pretty": true}'; \
    sleep 5; \
    docker compose logs master-1 | grep -i stash; \
    docker compose down; \
    sleep 5; \
    docker compose up master-1 | grep 'master-1!dummy-host-notification'
[+] Running 2/2
 ⠿ Network cluster_default       Created                                                                                                                  0.0s
 ⠿ Container cluster-master-1-1  Started                                                                                                                  0.5s
{
    "results": [
        {
            "code": 200,
            "status": "Successfully sent custom notification for object 'master-1'."
        }
    ]
}
cluster-master-1-1  | [2022-01-19 11:43:26 +0100] notice/Notification: Notification 'master-1!dummy-host-notification': object authority hasn't been updated, yet. Stashing notification.
[+] Running 2/2
 ⠿ Container cluster-master-1-1  Removed                                                                                                                  2.8s
 ⠿ Network cluster_default       Removed                                                                                                                  0.2s
[+] Running 2/2
 ⠿ Network cluster_default       Created 0.1s
 ⠿ Container cluster-master-1-1  Created 0.1s
[...]
cluster-master-1-1  | [2022-01-19 11:44:22 +0100] notice/NotificationComponent: Attempting to send stashed notification 'master-1!dummy-host-notification'.
cluster-master-1-1  | [2022-01-19 11:44:22 +0100] notice/Notification: Attempting to send notifications of type 'Custom' for notification object 'master-1!dummy-host-notification'.
cluster-master-1-1  | [2022-01-19 11:44:22 +0100] notice/Notification: Not checking notification filters for notification object 'master-1!dummy-host-notification': Notification was forced.
cluster-master-1-1  | [2022-01-19 11:44:22 +0100] notice/Notification: Not checking notification filters for notification object 'master-1!dummy-host-notification' and user 'dummy': Notification was forced.
cluster-master-1-1  | [2022-01-19 11:44:22 +0100] information/Notification: Sending 'Custom' notification 'master-1!dummy-host-notification' for user 'dummy'
[...]
```

**Pull request merged**
