### PR TITLE
Reload logs after logrotate across distros

### PR DESCRIPTION
**Pull request by leeclemens**
refs: 10935
refs: 10730

### CODE REVIEW

**Comment by leeclemens** [comment]
This will avoids using service or systemctl altogether, and suppresses errors if the pid file does not exist similar to rsyslog on CentOS 7's approach

**Comment by leeclemens** [comment]
ok to test

**Comment by leeclemens** [comment]
Tried to run tests again, but still fails with something seemingly unrelated, livestatus-livestatus.

**Comment by Crunsher** [comment]
Merged with commit 7bf01

**Pull request closed without merging**
