### PR TITLE
Update 6-object-types.md

### PR DESCRIPTION
**Pull request by jschanz**
endpoint description for attribute log_duration extended

https://dev.icinga.org/issues/11905

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you use a duration literal (1d, 12h or something else) in the first example? Other than that the patch is fine. :)

**Comment by jschanz** [comment]
As I understand, there are only **seconds** allowed, so no duration literal is required. There are a lot of suggestions to set log_duration to _0d_ or 10m, but nothing worked for me, so I think to define it in seconds is the best way. Maybe someone could check this in the code, so a duration literal could be set to the example.

**Comment by gunnarbeutner** [comment]
While you're correct that the value is in seconds Icinga's duration literals are really just a way to express intervals in a more human-friendly way. For example, internally 10m is actually just 600 (10 * 60). Icinga does not have a separate type for durations. You can try this by running `icinga2 console` and evaluating some duration literals:

    $ icinga2 console
    Icinga 2 (version: v2.4.10-440-g88dff68)
    <1> => 6h
    21600.000000
    <2> => 10m
    600.000000
    <3> => 1d
    86400.000000
    <4> =>

**Comment by jschanz** [comment]
Tested ... Works also with 0d instead of 0 to skip replaying log.

**Comment by gunnarbeutner** [comment]
Merged. Thank you. :)

**Pull request closed without merging**
