### PR TITLE
[needs upstream release] Add check_mailq -d argument for mailq_configdir

### LINKED ISSUE #5254: itl: Add configdir to check_mailq configuration
Add support for -d/--configdir to the check_mailq command.

To support multiple Postfix queues, this issue has been created: https://github.com/nagios-plugins/nagios-plugins/issues/278

If implemented, Icinga ITL command configuration should be amended accordingly.

### PR DESCRIPTION
**Pull request by leeclemens**
Fixes #5254

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks. Please also add the additional parameter to the documentation :) (amend your changes to the commit and force push it)

**Comment by leeclemens** [comment]
Good catch, @dnsmichi!

I noted it in the Issue, but worth pointing out here as well that this depends upon nagios-plugins making the change as well.
Depends on: https://github.com/nagios-plugins/nagios-plugins/pull/277

**Comment by gunnarbeutner** [comment]
We should probably stall this until your other change has been merged into the plugins repo. Btw, can you also try to get your patch merged into the official upstream repo as opposed to just the Nagios fork? As in, [monitoring-plugins/monitoring-plugins](https://github.com/monitoring-plugins/monitoring-plugins/).

**Comment by leeclemens** [comment]
I agree, @gunnarbeutner , I wasn't sure the best approach to note a dependency on an outside repo/pr.

I was led to nagios-plugins from the rpm package info. Thanks for that pointer, I made similar changes:
https://github.com/monitoring-plugins/monitoring-plugins/pull/1490

**Comment by leeclemens** [comment]
Update:
The required plugin's update has been merged in to nagios-plugins:release-2.3.0-working branch.
No response to the PR at monitoring-plugins to date.

**Comment by dnsmichi** [comment]
This has been sitting here too long. Please create a new PR once both upstream's have this released. Meanwhile we have to live with the fact that it does not exist.

**Comment by leeclemens** [comment]
Can I reopen this? It is marked milestone 2.3, but EPEL seems to have included it (possibly for some time now).

**Comment by dnsmichi** [comment]
There's a chance for inconsistency here, since we focus on monitoring-plugins while EPEL still uses nagios-plugins. I'm merely waiting for https://github.com/monitoring-plugins/monitoring-plugins/pull/1490 being merged.

**Comment by RincewindsHat** [comment]
is merged

**Pull request closed without merging**
