### PR TITLE
Fix no re-notification for non OK state changes with time delay

### LINKED ISSUE #8545: No (re-)notification for non-ok state changes if delayed notifications are configured
## Describe the bug
If renotifications are disabled (`interval = 0`) and a delay is configured (say `times = { begin = 2s }`), then there will
be no notification for state changes in the non-`OK` area (e.g. `WARNING` -> `CRITICAL`).

## To Reproduce

1. Configure like this:
```
apply Notification "A" to Service {
  ...
  interval = 0
  times = {
    begin = 2s
  }
}
apply Notification "B" to Service {
  ...
  interval = 0
}
```
2. Set state from `OK`  to `WARNING`
3. Receive notifications `A` and `B`
4. Set state to `CRITICAL`
5. Receive only notification `B`

## Expected behavior
Notification `A` gets also triggered by State Change in the non-`OK` area

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.2-1)
Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-10-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version:
Debian buster on x86_64

* Enabled features (`icinga2 feature list`):
api checker command graphite ido-pgsql mainlog notification syslog

* Icinga Web 2 version and modules (System - About): 
> Icinga Web 2 Version
>     2.8.2
> Git commit
>     8a89839af94a247ee2149b2336c73b8251b477c0
> PHP Version
>     7.3.19-1~deb10u1
> Git commit date
>     2020-08-17

* Config validation (`icinga2 daemon -C`):
```
[2020-12-10 00:53:30 +0100] information/cli: Icinga application loader (version: r2.12.2-1)
[2020-12-10 00:53:30 +0100] information/cli: Loading configuration file(s).
[2020-12-10 00:53:31 +0100] information/ConfigItem: Committing config item(s).
[2020-12-10 00:53:31 +0100] information/ApiListener: My API identity: lamp.vulgrim.de
[2020-12-10 00:53:31 +0100] warning/ApplyRule: Apply rule 'disk-windows' (in /etc/icinga2/zones.d/global-templates/services.conf: 45:1-45:28) for type 'Service' does not match anywhere!
[2020-12-10 00:53:31 +0100] warning/ApplyRule: Apply rule 'load-windows' (in /etc/icinga2/zones.d/global-templates/services.conf: 51:1-51:28) for type 'Service' does not match anywhere!
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 SyslogLogger.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 9 Hosts.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 3 NotificationCommands.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 186 Notifications.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 6 Zones.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 240 CheckCommands.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 4 TimePeriods.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 1 UserGroup.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 2 Users.
[2020-12-10 00:53:31 +0100] information/ConfigItem: Instantiated 84 Services.
[2020-12-10 00:53:31 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-12-10 00:53:31 +0100] information/cli: Finished validating the configuration file(s).
```

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context
Spotted this first on CentOS (8?), so this is probably not specific to debian.

### PR DESCRIPTION
**Pull request by Yonas-net**
resolves #8545

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Write a test protocol. Test cases: #8545

**Comment by Yonas-net** [comment]
**Testprotocol**:

**Before**: [Here](https://github.com/Icinga/icinga2/issues/8545#issuecomment-743150255)

**After**:
Scenario 1.

```bash
[2020-12-14 11:42:11 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:42:11 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:42:11 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:42:11 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8145, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output: 
[2020-12-14 11:42:39 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:42:39 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:42:39 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:42:39 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8163, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output: 
[2020-12-14 11:43:07 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:43:07 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:43:07 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:43:07 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8172, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output:
```

Scenario 2:

```bash
[2020-12-14 11:48:35 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from OK to WARNING detected.
[2020-12-14 11:48:35 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:48:35 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:48:35 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:48:35 +0100] notice/Process: Running command 'bash' '-c' 'exit 42': PID 8435
[2020-12-14 11:48:35 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:48:35 +0100] notice/Process: PID 8435 ('bash' '-c' 'exit 42') terminated with exit code 42
[2020-12-14 11:48:35 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8435, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output: 
[2020-12-14 11:48:38 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 11:48:38 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
```

Scenario 3:

```powershell
[2020-12-14 11:50:28 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:50:28 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:50:28 +0100] notice/Notification: Not sending notifications for notification object 'Icinga!Icinga-Service!Yonas-Notification': before specified begin time (2 seconds)
[2020-12-14 11:50:31 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 11:50:36 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 11:50:36 +0100] notice/NotificationComponent: Attempting to send reminder notification 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:50:36 +0100] notice/Notification: Attempting to send reminder notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:50:36 +0100] information/Notification: Sending reminder 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:50:36 +0100] notice/Process: Running command 'bash' '-c' 'exit 42': PID 8560
[2020-12-14 11:50:36 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:50:36 +0100] notice/Process: PID 8560 ('bash' '-c' 'exit 42') terminated with exit code 42
[2020-12-14 11:50:36 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8560, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output: 
[2020-12-14 11:50:41 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 11:50:51 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
[2020-12-14 11:50:56 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from WARNING to CRITICAL detected.
[2020-12-14 11:50:56 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 11:50:56 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:50:56 +0100] notice/Notification: Not sending notifications for notification object 'Icinga!Icinga-Service!Yonas-Notification': before specified begin time (2 seconds)
[2020-12-14 11:51:01 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 11:51:01 +0100] notice/NotificationComponent: Attempting to send reminder notification 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:51:01 +0100] notice/Notification: Attempting to send reminder notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 11:51:01 +0100] information/Notification: Sending reminder 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 11:51:01 +0100] notice/Process: Running command 'bash' '-c' 'exit 42': PID 8572
[2020-12-14 11:51:01 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 11:51:01 +0100] notice/Process: PID 8572 ('bash' '-c' 'exit 42') terminated with exit code 42
[2020-12-14 11:51:01 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 8572, arguments: 'bash' '-c' 'exit 42') terminated with exit code 42, output: 
[2020-12-14 11:51:06 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
```

**Comment by Al2Klimov** [comment]
Huh? Only one/two "exit 42" in the logs of scenario 2/3? Please re-test w/ `s/exit 42/exit 42 # $service.state$/` in the config.

**Comment by Yonas-net** [comment]
Scenario 2:

```powershell
[2020-12-14 12:05:19 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from OK to WARNING detected.
[2020-12-14 12:05:19 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 12:05:19 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:05:19 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 12:05:19 +0100] notice/Process: Running command 'bash' '-c' 'exit 42 # WARNING': PID 9063
[2020-12-14 12:05:19 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 12:05:19 +0100] notice/Process: PID 9063 ('bash' '-c' 'exit 42 # WARNING') terminated with exit code 42
[2020-12-14 12:05:19 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 9063, arguments: 'bash' '-c' 'exit 42 # WARNING') terminated with exit code 42, output: 
[2020-12-14 12:05:22 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 12:05:22 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.

[...]

[2020-12-14 12:05:48 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from WARNING to CRITICAL detected.
[2020-12-14 12:05:48 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 12:05:48 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:05:48 +0100] information/Notification: Sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 12:05:48 +0100] notice/Process: Running command 'bash' '-c' 'exit 42 # CRITICAL': PID 9084
[2020-12-14 12:05:48 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 12:05:48 +0100] notice/Process: PID 9084 ('bash' '-c' 'exit 42 # CRITICAL') terminated with exit code 42
[2020-12-14 12:05:48 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 9084, arguments: 'bash' '-c' 'exit 42 # CRITICAL') terminated with exit code 42, output: 
[2020-12-14 12:05:52 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
```

Scenario 3:

```powershell
[2020-12-14 12:09:26 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from OK to WARNING detected.
[2020-12-14 12:09:26 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 12:09:26 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:09:26 +0100] notice/Notification: Not sending notifications for notification object 'Icinga!Icinga-Service!Yonas-Notification': before specified begin time (2 seconds)
[2020-12-14 12:09:33 +0100] notice/NotificationComponent: Attempting to send reminder notification 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:09:33 +0100] notice/Notification: Attempting to send reminder notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:09:33 +0100] information/Notification: Sending reminder 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 12:09:33 +0100] notice/Process: Running command 'bash' '-c' 'exit 42 # WARNING': PID 9274
[2020-12-14 12:09:33 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 12:09:33 +0100] notice/Process: PID 9274 ('bash' '-c' 'exit 42 # WARNING') terminated with exit code 42
[2020-12-14 12:09:33 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 9274, arguments: 'bash' '-c' 'exit 42 # WARNING') terminated with exit code 42, output: 
[2020-12-14 12:09:38 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 12:09:38 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.

[...]

[2020-12-14 12:09:55 +0100] notice/Checkable: State Change: Checkable 'Icinga!Icinga-Service' hard state change from WARNING to CRITICAL detected.
[2020-12-14 12:09:55 +0100] information/Checkable: Checkable 'Icinga!Icinga-Service' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-12-14 12:09:55 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:09:55 +0100] notice/Notification: Not sending notifications for notification object 'Icinga!Icinga-Service!Yonas-Notification': before specified begin time (2 seconds)
[2020-12-14 12:09:58 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 12:10:03 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 12:10:03 +0100] notice/NotificationComponent: Attempting to send reminder notification 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:10:03 +0100] notice/Notification: Attempting to send reminder notifications of type 'Problem' for notification object 'Icinga!Icinga-Service!Yonas-Notification'.
[2020-12-14 12:10:03 +0100] information/Notification: Sending reminder 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for user 'Yonas'
[2020-12-14 12:10:03 +0100] notice/Process: Running command 'bash' '-c' 'exit 42 # CRITICAL': PID 9284
[2020-12-14 12:10:03 +0100] information/Notification: Completed sending 'Problem' notification 'Icinga!Icinga-Service!Yonas-Notification' for checkable 'Icinga!Icinga-Service' and user 'Yonas' using command 'fail'.
[2020-12-14 12:10:03 +0100] notice/Process: PID 9284 ('bash' '-c' 'exit 42 # CRITICAL') terminated with exit code 42
[2020-12-14 12:10:03 +0100] warning/PluginNotificationTask: Notification command for object 'Icinga!Icinga-Service' (PID: 9284, arguments: 'bash' '-c' 'exit 42 # CRITICAL') terminated with exit code 42, output: 
[2020-12-14 12:10:08 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0.0333333
[2020-12-14 12:10:08 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
```

**Comment by Al2Klimov** [comment]
Warning, critical, ... where's the unknown notification?

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
`SetNoMoreNotifications()` theoretically affects reminder notifications. Test also the following:

1. Re-enable reminder notifications by commenting out interval=0 and wait for some actual reminder notifications
2. Re-disable reminder notifications (see above) and wait for the same amount of time, ensure reminder notifications won't fire

**Comment by Yonas-net** [comment]
If there is no re-notification interval and no time delay configured, no reminders will be sent at all but with configured time delay the reminders will be sent exactly at the same time with and without intervals.

**Comment by Al2Klimov** [comment]
_Sigh._ My mistake: ["Defaults to 30 minutes."](https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#notification)

What happens within 10m w/ interval=3m and what with interval=0 ?

**Comment by Yonas-net** [comment]
Re-notification interval set to 0 only such messages are displayed.

```powershell
[2020-12-14 14:21:18 +0100] notice/NotificationComponent: Reminder notification 'Icinga!Icinga-Service!Yonas-Notification': Notification was sent out once and interval=0 disables reminder notifications.
```

But if e.g. Interval is set to 3m, reminders are also sent when a notification problem is sent.

**Review by Al2Klimov — APPROVED** [review]

**Review by julianbrost — CHANGES_REQUESTED** [review]
LGTM apart from the small style issue.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
