### PR TITLE
Re-send suppressed notifications

### LINKED ISSUE #5919: Notification behaviour after Downtime ends
## Expected Behavior
I schedule a fixed downtime for a service.
The service goes CRITICAL within the downtime.
The service is still CRITICAL when the downtime ends.
I expect to be notified right when the downtime ends.

## Current Behavior
When the downtime ends, the notification for one contact fires right away, but the notification for a second contact is delayed.

## Possible Solution
Experiments show that the interval setting for a notification is the key: The one contact that gets the notification right after the downtime ends has notification interval of 0 (zero).
The other contact has an interval setting of 600 seconds (10m), and he gets the notification 10 minutes after the hard state change happened (during the downtime).

## Steps to Reproduce (for bugs)
Please take a look at the attached screenshot which shows the history of such a behaviour:
* Schedule downtime of 5 minutes for a (passive) service
* Trigger hard state change to CRITICAL after a couple of seconds in the downtime
* After downtime has ended, pstiffel is notified right away (the attached notification object has interval of 0)
* 5 minutes after the downtime has ended (and 10 minutes after the hard state change), jmueller is notified (the attached notification object has interval of 10m)
2017-12-29_10h12_28

## Context
IMHO, the notification should happen immediately after the downtime has ended, no matter which interval was set.
I guess, I watched the same behaviour when using timeperiods which are not 24x7, i.e. when using notification period 9to17 and a outtage happens before that time. The contact attached to notification object with interval 0 is notified right when the notification period starts, the contact attached to a notification object with an interval, is delayed until the next regular interval after the outtage.

The background: Our contact with interval 0 is a ticket system which should only receive one notification, while our staff should be re-informed every hour.

## Your Environment
* icinga2-Version r2.8.0-1
* Clustered master setup with two nodes
* Debian 8

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #5919

### CODE REVIEW

**Comment by Al2Klimov** [comment]
ref/IC/14729

**Comment by dnsmichi** [comment]
@Al2Klimov please use `ref/IP` as label in the future.

**Comment by dnsmichi** [comment]
Note: Whenever a notification was skipped by a downtime where `interval=0` was set, this needs to be taken into account as well.

**Comment by Al2Klimov** [comment]
# Test protocol (so far)

1. Install a *fresh* Icinga 2
2. Run `icinga2 api setup`
3. Clear `/etc/icinga2/conf.d/` and create `/etc/icinga2/conf.d/config.conf` (see below)
4. Start Icinga 2
5. 1x `curl -LkisSu root:123456 -H 'Accept: application/json' -X POST https://192.0.2.1:5665/v1/actions/schedule-downtime -d '{"type": "Host", "filter": "true", "author": "me", "comment": "-", "start_time": '"$(perl -e 'print time')"', "end_time": '"$(perl -e 'print time+30')"'}'`
6. 3x `curl -LkisSu root:123456 -H 'Accept: application/json' -X POST https://192.0.2.1:5665/v1/actions/process-check-result -d '{"type": "Host", "filter": "true", "exit_status": 1, "plugin_output": " "}'`

`/etc/icinga2/conf.d/config.conf`:

```
object IcingaApplication "app" { }

object ApiUser "root" {
	password = "123456"
	permissions = [ "*" ]
}

object NotificationCommand "noop" {
	command = [ "/bin/true" ]
}

object Host "example.com" {
	check_command = "dummy"
	enable_active_checks = false
}

object User "icingaadmin" {
}

object Notification "noop" {
	host_name = "example.com"
	users = [ "icingaadmin" ]
	command = "noop"
	//interval = 30m
	types = [ Problem, Recovery, Custom, DowntimeStart, DowntimeEnd ]
	states = [ Up, Down ]
}
```

## Before

```
[2019-07-03 03:56:32 -0600] information/Notification: Sending 'DowntimeEnd' notification 'example.com!noop' for user 'icingaadmin'
[2019-07-03 03:56:32 -0600] information/Notification: Completed sending 'DowntimeEnd' notification 'example.com!noop' for checkable 'example.com' and user 'icingaadmin' using command 'noop'.
```

## After

```
[2019-07-03 04:09:03 -0600] information/Notification: Sending 'Problem' notification 'example.com!noop' for user 'icingaadmin'
[2019-07-03 04:09:03 -0600] information/Notification: Completed sending 'Problem' notification 'example.com!noop' for checkable 'example.com' and user 'icingaadmin' using command 'noop'.
```

```
[2019-07-03 04:09:30 -0600] information/Notification: Sending 'DowntimeEnd' notification 'example.com!noop' for user 'icingaadmin'
[2019-07-03 04:09:30 -0600] information/Notification: Completed sending 'DowntimeEnd' notification 'example.com!noop' for checkable 'example.com' and user 'icingaadmin' using command 'noop'.
```

**Comment by Al2Klimov** [comment]
@dnsmichi Please have a look whether you can reproduce the re-sending added here in general. I'll get back to taking care of the check interval and the other stuff soon.

**Comment by Al2Klimov** [comment]
@lippserd As far as I've tested if your problem occurs during a downtime and persists after that downtime, you *don't* get notified. (@dnsmichi Please correct me if I'm wrong.) So IMO we shouldn't ask whether there will be a check soon (likely), but just notify.

**Comment by Al2Klimov** [comment]
@lippserd Also I'm not quite sure *whether* we should take care of the re-notification interval (as this PR is about *the initial* notification) and *how* we'd do that (as this PR delays notifications on "checkable layer" and different notifications may have different intervals).

**Comment by lippserd** [comment]
It is perfectly fine that this PR "only" covers initial notifications. As discussed w/ @Al2Klimov stashing the notifications here makes sense in order to properly fire them after the downtime ends.
Thanks for the "wait for the next check if it's soon" feature. One minute seems like a good value.

**Comment by Al2Klimov** [comment]
Had a quite misunderstandingful offline discussion with @lippserd about whether to include flapping here or not. Flapping *during* a downtime doesn't matter, but flapping *outside* a downtime does. This PR effectively provides that (desired) behavior.

**Comment by dnsmichi** [comment]
If you don't want to wait for me - code comments and function header docs are missing. Especially the algorithm with storing things, firing again with a certain threshold must be explained in there.

**Comment by Al2Klimov** [comment]
Done. (IMO)

**Comment by dnsmichi** [comment]
# Review

## Config

Ensure that the host's interval is greater than your downtime test window, e.g. 1h. Then you don't need to disable the active checks.

```
object Host "downtime" {
  check_command = "dummy"
  check_interval = 1h
  retry_interval = 1h
}

object NotificationCommand "downtime" {
  command = "downtime"
}
object User "downtime" {}
object Notification "downtime" {
  host_name = "downtime"
  //interval = 0
  //interval = 1h
  command = "downtime"
  users = [ "downtime" ]
}
```

## Tests

OK/UP.

```
curl -k -s -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/process-check-result' \
-d '{ "type": "Host", "filter": true, "exit_status": 1, "plugin_output": "PING CRITICAL - Packet loss = 100%", "performance_data": [ "rta=5000.000000ms;3000.000000;5000.000000;0.000000", "pl=100%;80;100;0" ], "check_source": "example.localdomain", "pretty": true }'

```

Downtime.

```
curl -k -s -u root:icinga -H 'Accept: application/json'  -X POST 'https://localhost:5665/v1/actions/schedule-downtime'  -d "$(jo -p pretty=true type=Host filter=true author=icingaadmin comment="abc" fixed=true start_time=$(gdate +%s -d "+0 hour") end_time=$(gdate +%s -d "+5 min"))"

```

CRIT/DOWN.

```
curl -k -s -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/process-check-result' \
-d '{ "type": "Host", "filter": true, "exit_status": 0, "plugin_output": "OK", "check_source": "example.localdomain", "pretty": true }'

```


### After

```
[2019-07-09 17:19:12 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:60278), user: root, agent: curl/7.54.0).
[2019-07-09 17:19:12 +0200] information/Checkable: Checkable 'times-begin-host' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:19:12 +0200] information/Checkable: Checkable 'random' has 0 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:19:12 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:19:12 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60278)
```

Schedule the downtime.

```
[2019-07-09 17:19:30 +0200] information/ApiListener: New client connection from [::1]:60282 (no client certificate)
[2019-07-09 17:19:30 +0200] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [::1]:60282), user: root, agent: curl/7.54.0).

[2019-07-09 17:19:30 +0200] information/ConfigObjectUtility: Created and activated object 'downtime!22c51727-3fc3-473e-9899-221172b4d1a9' of type 'Downtime'.
[2019-07-09 17:19:30 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60282)

[2019-07-09 17:19:35 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:19:35 +0200] information/Notification: Sending 'DowntimeStart' notification 'downtime!downtime' for user 'downtime'
[2019-07-09 17:19:35 +0200] information/Notification: Completed sending 'DowntimeStart' notification 'downtime!downtime' for checkable 'downtime' and user 'downtime' using command 'downtime'.
[2019-07-09 17:19:35 +0200] warning/PluginNotificationTask: Notification command for checkable 'downtime' and notification 'downtime!downtime' (PID: 29046, arguments: 'sh' '-c' 'downtime') terminated with exit code 127, output: sh: downtime: command not found
```

Forcefully put the host into DOWN state, triggering the downtime.

```
[2019-07-09 17:19:42 +0200] information/ApiListener: New client connection from [::1]:60286 (no client certificate)
[2019-07-09 17:19:42 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:60286), user: root, agent: curl/7.54.0).
[2019-07-09 17:19:42 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60286)
[2019-07-09 17:19:44 +0200] information/ApiListener: New client connection from [::1]:60288 (no client certificate)
[2019-07-09 17:19:44 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:60288), user: root, agent: curl/7.54.0).
[2019-07-09 17:19:44 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60288)
[2019-07-09 17:19:44 +0200] information/ApiListener: New client connection from [::1]:60289 (no client certificate)
[2019-07-09 17:19:44 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:60289), user: root, agent: curl/7.54.0).
[2019-07-09 17:19:44 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60289)
[2019-07-09 17:19:45 +0200] information/ApiListener: New client connection from [::1]:60290 (no client certificate)
[2019-07-09 17:19:45 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:60290), user: root, agent: curl/7.54.0).
[2019-07-09 17:19:45 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:60290)
```

The downtime ends, the host is still in a problem state.

```
[2019-07-09 17:24:30 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:24:30 +0200] information/Notification: Sending 'DowntimeEnd' notification 'downtime!downtime' for user 'downtime'
[2019-07-09 17:24:30 +0200] information/Notification: Completed sending 'DowntimeEnd' notification 'downtime!downtime' for checkable 'downtime' and user 'downtime' using command 'downtime'.
[2019-07-09 17:24:30 +0200] warning/PluginNotificationTask: Notification command for checkable 'downtime' and notification 'downtime!downtime' (PID: 29135, arguments: 'sh' '-c' 'downtime') terminated with exit code 127, output: sh: downtime: command not found

[2019-07-09 17:24:33 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-09 17:24:33 +0200] information/Notification: Sending 'Problem' notification 'downtime!downtime' for user 'downtime'
[2019-07-09 17:24:33 +0200] information/Notification: Completed sending 'Problem' notification 'downtime!downtime' for checkable 'downtime' and user 'downtime' using command 'downtime'.
[2019-07-09 17:24:33 +0200] warning/PluginNotificationTask: Notification command for checkable 'downtime' and notification 'downtime!downtime' (PID: 29139, arguments: 'sh' '-c' 'downtime') terminated with exit code 127, output: sh: downtime: command not found
```

**Comment by dnsmichi** [comment]
@lippserd thus far, it looks good and I nearly finished it today. Will test again tomorrow morning and then review/merge.

**Comment by dnsmichi** [comment]
# Review

## Code 

- [x] Standalone delay for notifications
- [x] Timer for firing the supressed notifications
- [x] Cluster events for syncing the new stateful attribute `suppressed_notifications` 
- [x] My previous remark on the global static timer was wrong, this cannot be assigned into an object.
- [ ] Technical concept docs for new cluster message, object types with runtime attribute
- [ ] Function docs header
- [ ] Maybe more debug logs

I'll take care of the latter while testing further.

**Comment by dnsmichi** [comment]
Clang warnings.

```
[ 48%] Building CXX object lib/icinga/CMakeFiles/icinga.dir/checkable-dependency.cpp.o
/Users/michi/dev/icinga/icinga2/lib/icinga/checkable-check.cpp:464:42: warning: self-comparison always evaluates to true [-Wtautological-compare]
                        if (suppressed_types_after & conflict == conflict) {
                                                              ^
/Users/michi/dev/icinga/icinga2/lib/icinga/checkable-check.cpp:464:31: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                        if (suppressed_types_after & conflict == conflict) {
                                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/michi/dev/icinga/icinga2/lib/icinga/checkable-check.cpp:464:31: note: place parentheses around the '==' expression to silence this warning
                        if (suppressed_types_after & conflict == conflict) {
                                                   ^
                                                     (                   )
/Users/michi/dev/icinga/icinga2/lib/icinga/checkable-check.cpp:464:31: note: place parentheses around the & expression to evaluate it first
                        if (suppressed_types_after & conflict == conflict) {
                                                   ^
                            (                                )
```

**Comment by dnsmichi** [comment]
@Al2Klimov sorry, didn't see your changes, I was working on them already and have now force pushed the branch.

**Comment by dnsmichi** [comment]
# HA Tests

2 masters, test config in zones.d/master. Same procedure with scheduling downtime and triggering a notification on master1, listening on port 5665 too.

## Both are active

Everything is synced properly.

```
[2019-07-10 17:10:30 +0200] information/ApiListener: New client connection from [::1]:59020 (no client certificate)
[2019-07-10 17:10:30 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:59020), user: root, agent: curl/7.54.0).
[2019-07-10 17:10:30 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:59020)
[2019-07-10 17:10:30 +0200] information/Checkable: Checkable 'sync-agent' has 0 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:30 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:34 +0200] information/ApiListener: New client connection from [::1]:59021 (no client certificate)
[2019-07-10 17:10:34 +0200] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [::1]:59021), user: root, agent: curl/7.54.0).
[2019-07-10 17:10:34 +0200] information/ConfigObjectUtility: Created and activated object 'sync-agent!b7972d69-4b40-42d9-a85b-792311111d0c' of type 'Downtime'.
[2019-07-10 17:10:34 +0200] information/ConfigObjectUtility: Created and activated object 'downtime!7f5c22ca-5517-4cc5-986e-f2b542f4dd1b' of type 'Downtime'.
[2019-07-10 17:10:34 +0200] information/ConfigObjectUtility: Created and activated object 'horst!2a05cc6e-7ebd-4cd9-80b9-caf12a0bb3c6' of type 'Downtime'.
[2019-07-10 17:10:34 +0200] information/ConfigObjectUtility: Created and activated object 'icinga2a!7faf7c37-fc41-4d00-b7da-63796e70cf56' of type 'Downtime'.
[2019-07-10 17:10:34 +0200] information/ConfigObjectUtility: Created and activated object 'master1!9868a4c5-0df0-4301-8a82-b64c11c9ee49' of type 'Downtime'.
[2019-07-10 17:10:34 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:59021)
[2019-07-10 17:10:35 +0200] information/Checkable: Checkable 'sync-agent' has 0 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:35 +0200] information/Checkable: Checkable 'downtime' has 1 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:36 +0200] information/ApiListener: Reconnecting to endpoint 'agent' via host '127.0.0.1' and port '5667'
[2019-07-10 17:10:36 +0200] information/Checkable: Checkable 'horst' has 0 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:36 +0200] information/Checkable: Checkable 'icinga2a' has 0 notification(s). Proceeding with filters, successful sends will be logged.
[2019-07-10 17:10:36 +0200] critical/ApiListener: Cannot connect to host '127.0.0.1' on port '5667': Connection refused
[2019-07-10 17:10:38 +0200] information/ApiListener: New client connection from [::1]:59025 (no client certificate)
[2019-07-10 17:10:38 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:59025), user: root, agent: curl/7.54.0).
[2019-07-10 17:10:38 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:59025)
[2019-07-10 17:10:40 +0200] information/ApiListener: New client connection from [::1]:59027 (no client certificate)
[2019-07-10 17:10:40 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:59027), user: root, agent: curl/7.54.0).
[2019-07-10 17:10:40 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:59027)
[2019-07-10 17:10:40 +0200] information/ApiListener: New client connection from [::1]:59029 (no client certificate)
[2019-07-10 17:10:40 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:59029), user: root, agent: curl/7.54.0).
[2019-07-10 17:10:40 +0200] information/HttpServerConnection: HTTP client disconnected (from [::1]:59029)
[2019-07-10 17:10:41 +0200] information/ApiListener: New client connection from [::1]:59031 (no client certificate)
[2019-07-10 17:10:41 +0200] information/HttpServerConnection: Request: POST /v1/actions/process-check-result (from [::1]:59031), user: root, agent: curl/7.54.0).
```

```
$ watch -n 1 -c "icinga2 console --connect 'https://root:icinga@localhost:5666/' --eval 'var h = get_host(\"downtime\"); h.downtime_depth.to_string() + \" \" + h.suppressed_notifications.to_string()'"
```

Screen Shot 2019-07-10 at 17 14 20

Then the downtime expires and the notification is sent for the problem type with the host still be in a problem state. The counts are reset to zero.

Screen Shot 2019-07-10 at 17 16 47


## Replay Log

master1 active, master2 offline. Do the downtime thingy, but before it expires, switch master2 back on. Wait until replay log is finished and watch the values and wait for the notification.

Screen Shot 2019-07-10 at 17 21 40

After ~5 minutes after DowntimeStart (left side, master1), the problem notification is sent after the downtime stopped (right side, master2).

Screen Shot 2019-07-10 at 17 29 04

**Comment by dnsmichi** [comment]
@lippserd since there's a new cluster message, upgrading docs are required as well - the fix only works reliably if both masters are upgraded to 2.11.

**Comment by dnsmichi** [comment]
@Al2Klimov any specific reason to set `no_user_view` for `supressed_notifications`? I had to use the debug console to get access to the attribute, it would be easier for debugging if it would be visible on the checkable object.

**Comment by Al2Klimov** [comment]
That's my default for *somewhat internal* stuff. Feel free to undo this (in all of such PRs of mine) if you think the user should see this.

**Comment by dnsmichi** [comment]
Ok, I was not sure about this, and with the granted bitmask we're using, this will be hard to document, or rely on. Forget the idea, and thanks for the feedback 👍 

I'll continue with the doc changes, will add another commit and then merge.

**Pull request merged**
