### PR TITLE
DSL: support R"EOF(c++heredoc)EOF"

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] #7769

**Comment by Al2Klimov** [comment]
This one has not to be merged until v2.12 is out.

**Comment by Al2Klimov** [comment]
```
<1> => R"EOF(c++heredoc)EOF"
"c++heredoc"
<2> => R"EOF(c++heredoc)EOF
       ^^^^^^^^^^^^^^^^^^^^
End-of-file while in string literal
```

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by julianbrost** [comment]
Is there a good reason for this? Otherwise I'd avoid making the DSL more complex than needed.

**Comment by Al2Klimov** [comment]
Sure, there's already `{{{abc}}}`. _abc_ can be literally anything... ex. `}}}`. Reason: with this one you control the delimiter.

**Comment by Al2Klimov** [comment]
Apropos complex, we can also have

```
<<'SHELL'
Here doc
SHELL
```

if you prefer.

**Comment by julianbrost** [comment]
How about neither? The goal of our config language is not to add every feature that exists in some other programming language. As far as I can tell, there wasn't even a request for this feature. And even if someone had a reason to put `}}}` inside a string, they can still resort to `"{{{"`, which is definitely a feasible workaround - if someone even needs it at all.

**Pull request closed without merging**
