### PR TITLE
Revert "Remove Downtime objects w/o reference to ScheduledDowntime objects"

### LINKED ISSUE #6542: /var/log/icinga2/icinga2.log is growing very fast on satellites
We have a HA configuration with 2 master nodes, 2 satellites in the Network Zone and 2 satellites in the Server Zone. For configuration we use the director. 

Since some time - we noticed it after upgrade to Version 2.9.1 - that icinga2.log ist growing and growing very fast from one point to another. But only on the satellites in the Network Zone. It seems it happend after deployment with the director. 

For example: that are times when there was a deplolyment today:

deployment_director

That is the visualisation with grafana where you can see the growing of the log file:
grafana

and direct in the bash:
filesystem

I think the problem are the ServiceSets which wie generate with the director (see also https://github.com/Icinga/icingaweb2-module-director/issues/1589). Because it will deploy them at every node. So if the ServerSet is for example for the Server Zone, the satellite in the Network Zone won't find the devices to apply. And if I take a look into the icinga2.log at the time of the depolyment ist is full of Messages like this:
apply_rule

the only work arround is to empty the file with 
_> icinga2.log_

## Your Environment

•Director version (System - About): Git Master 71ad855
•Icinga Web 2 version and modules (System - About): 2.6.1
•Icinga 2 version (icinga2 --version): r2.9.1-1
•Operating System and version: CentOS 7
•Webserver, PHP versions: Apache 2.4.6-80.el7, rh-php 7.1.8-1.el7

### PR DESCRIPTION
**Pull request by Al2Klimov**
This reverts commit 8f03adf76f59e5108c6c9e13fe03646da20ec504.

fixes #6542

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@lippserd I'd *not* merge this before building custom packages and testing them on the customer's system.

**Comment by dnsmichi** [comment]
Can you please provide a test protocol on what exactly changes here? Why is the config_owner restriction removed here?

**Comment by lippserd** [comment]
I also miss an explanation why this fixes the referenced issue. And please don't upload a video for that 😆

**Comment by Al2Klimov** [comment]
In v2.10.2 the ScheduledDowntimes create Downtimes as expected – periodically and if not already created. However the newly created downtimes [disappear quite soon](https://github.com/Icinga/icinga2/issues/6542#issuecomment-442383270) (sorry @lippserd, the vid has already been uploaded before today). As the ScheduledDowntimes aren't aware about that they keep re-creating Downtimes periodically.

This change seems to fix it. I'm also missing an explanation from Icinga 2 – but hey, it works. 😉

Seriously, for some strange reason the ScheduledDowntime getter isn't working and Icinga 2 thinks that the respective ScheduledDowntime disappeared and deletes the Downtime.

I created this PR anyway as (1) this is better than the v2.10.2 behavior and (2) I was told that ScheduledDowntimes aren't a critical feature.

**Comment by dnsmichi** [comment]
Changing the logic here will break the fix for #4048.

This leaves us in the state that a downtime is deleted only if it is expired. If the ScheduledDowntime object was removed from the configuration, this downtime won't be deleted and becomes stale. Such a downtime cannot be deleted via the web interface/API.

Either the downtime already is expired, or the SD object was removed is the condition to keep downtimes in sync after a restart. 

In terms of your explanation, I don't quite understand what the following means.

> However the newly created downtimes disappear quite soon (sorry @lippserd, the vid has already been uploaded before today). As the ScheduledDowntimes aren't aware about that they keep re-creating Downtimes periodically.

Can you elaborate by a simple example with timestamps and step by step? This sounds more like a bug within the condition to create downtimes from SD objects.

**Comment by Al2Klimov** [comment]
You can't delete them via API? Holy sh...

According to @lippserd this won't be merged anyway as we need to fix this the brainy way.

Anyway I can show you the problem offline, just ping me.

**Comment by dnsmichi** [comment]
> Anyway I can show you the problem offline, just ping me.

The reason I am asking for a problem description step-by-step is visibility, history and knowledge transfer. If one finds this PR in the future, it should contain everything needed to understand the reasoning. The past has shown and proven that little (or zero) information takes a lot of time to analyse and fix things.

> You can't delete them via API? Holy sh...

That's a wanted behaviour. If the admin deploys a scheduled downtime object configuration, the expectation is that it generates a persistent downtime for that defined time range. If another user now decides to remove this downtime via the Web interface as command, there's an inconsistent state. Past implementations without the "config owner" reference had this bug, and users often reported this, taking long rounds of troubleshooting before.

Cheers,
Michael

**Comment by Al2Klimov** [comment]
Fine... v2.10.2:

img_20181129_152209r

img_20181129_152229r

The "w/o owner" part of the condition is broken – I couldn't figure out why.

This leads to false positive on downtime deletions. After the downtimes were deleted by themselves, they're re-created by their ScheduledDowntimes.

**Comment by Al2Klimov** [comment]
I'm afraid I was quite wrong. The scenario I described seems to be caused by the actual absence of the respective ScheduledDowntime – on master-2. Of course, if the ScheduledDowntime is in conf.d on master-1 and its Zone is explicitly unset... #ElephantOversight

> Mistakes are quite good as long as you're young. But you shouldn't take them with you in your old age.

– J. W. v. Goethe

**Comment by Al2Klimov** [comment]
Closing in favor of #6821.

**Pull request closed without merging**
