### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Crunsher**
Adds a short security.md linking our security email and explaining how we only support the most recent version.

### CODE REVIEW

**Comment by dnsmichi** [comment]
I'd like to avoid duplicated information with gpg keys, etc. - imho we should just link to https://icinga.com/contact/security/ ... yet better, just link from README.md or inside the docs. Opinions @lippserd @bobapple ?

**Comment by Crunsher** [comment]
The idea on duplication instead of just linking was to have it in two different places and within the code for those who clone the repo

**Comment by bobapple** [comment]
I agree with @dnsmichi, linking to the website make more sense to me than duplicate content. The amount of people who report security issues is very low. I would assume that all of them have an internet connection to open the website.

**Comment by Crunsher** [comment]
Updated

**Comment by dnsmichi** [comment]
It has a typo, `infornation`. Before proceeding with further changes, we should find a format which fits all projects first. I would like to see all information, including the latest version support, on icinga.com and only have README.md link to that page.

**Comment by dnsmichi** [comment]
Closing in favor of #7267.

**Pull request closed without merging**
