### PR TITLE
Change cluster check output

### LINKED ISSUE #5444: Display endpoints in the second line of the ClusterCheckTask output
## Expected Behavior
I would like to see the output of the Cluster check displayed in 2 rows to keep IcingaWeb2 cleaner, if allot of endpoints (clients) are configured. 

## Current Behavior
All output of the check is displayed in 1 row, including all the endpoint names.

## Possible Solution
Output Lines:
1. Icinga2 Cluster is running: Connected Endpoints: 500
2. Connected Endpoints:
4.    - endpoint1.local
5.    - endopint2.local
6. ....

## Context
File where problem is in: https://github.com/Icinga/icinga2/blob/0a77f7033e466a74254c2bacdfb81738f074920c/lib/methods/clusterchecktask.cpp

## Environment

* Version used (`icinga2 --version`):  v2.6.3
* Operating System and version: Centos 7
* Enabled features (`icinga2 feature list`):  api checker command debuglog ido-pgsql mainlog notification
* Icinga Web 2 version and modules (System - About): v2.4.1
* Satellite Zones: 6
* Clients/Endpoints: 1500

### PR DESCRIPTION
**Pull request by mcktr**
This changes the cluster check output to get a cleaner and a more readable Icinga Web 2 output.

Critical state:
28841293-0a734b1e-76fa-11e7-93e3-f1d574629c5a

OK state:
screenshot at 2017-08-02 20 33 19

fixes #5444

### CODE REVIEW

**Comment by dnsmichi** [comment]
Hmmm, is it really necessary to change FormatArray() and put one Endpoint on each line? That will break any web interface with more than 50 endpoints. I'd prefer a single line with the existing list.

**Comment by mcktr** [comment]
This is a very good point I hadn't thought about. I changed FormatArray() back to the original state and changed only the output text a bit:

CRITICAL state:
```
Icinga 2 Cluster Problem: Not Connected Endpoints: 2

Not connected Endpoints:
stretch-icinga2a-3, stretch-icinga2a-2
```

OK state: 
```
Icinga 2 Cluster is running: Connected Endpoints: 2

Connected Endpoints:
stretch-icinga2a-3, stretch-icinga2a-2
```

**Comment by dnsmichi** [comment]
Cutting the patch down to just a newline ... does it still make sense?

**Comment by mcktr** [comment]
Just adding a new line is not a proper solution for the linked issue, I guess. I close this PR for now.

**Pull request closed without merging**
