### PR TITLE
LegacyTimePeriod::ScriptFunc: fix DST edge-cases

### PR DESCRIPTION
**Pull request by yhabteab**
Backport of #9048

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
The changeset should be smaller or equal than the original. (Remember our whiteboard discussion.)

**Review by julianbrost — CHANGES_REQUESTED** [review]
This also imports half of #8921 but not enough for the current state of this PR to compile. That one should either be backported completely (in a separate PR ideally) or not at all.

I opt for backporting it since there are some dependencies between the PRs. If you would want to backport only one PR, you'd have to actually adapt it to the older version (and check if that would even make sense).

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
If backporting both radically reduces conflicts: backport both.

**Review by julianbrost — COMMENTED** [review]
Please create a second PR for the backport of the second PR. Just creating a branch with the first two commit from this PR and opening a PR should do the trick.

**Comment by yhabteab** [comment]
# Blocked by

- #9253

**Review by julianbrost — CHANGES_REQUESTED** [review]
The dependency was merged, please update the PR.

**Review by julianbrost — APPROVED** [review]

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
