### PR TITLE
Add command definition for "check_snmp_win.pl"

### PR DESCRIPTION
**Pull request by Gregger83**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks 👍  Can you please add a configuration section into the docs too, similar to existing CheckCommand documentation?

**Comment by Tontonitch** [comment]
Hello,

This definition won't work as the -f option is not implemented in the manubulon plugin check_snmp_win.pl. Also, imho, the variable names don't follow the CheckCommand definition "best practices".

Personaly, I use the following definition.

```
/**
 * snmp service
 *   Url reference: http://nagios.manubulon.com/snmp_windows.html
 */

object CheckCommand "snmp-service" {
	import "snmp-manubulon-command"

	command = [ ManubulonPluginDir + "/check_snmp_win.pl" ]

	arguments += {
		"-n" = {
			value = "$snmp_service_name$"
			description = "Comma separated names of services (perl regular expressions can be used for every one). By default, it is not case sensitive. eg. ^dns$"
		}
		"-N" = {
			value = "$snmp_service_count$"
			description = "Compare matching services with <n> instead of the number of names provided."
		}
		"-s" = {
			set_if = "$snmp_service_showall$"
			description = "Show all services in the output, instead of only the non-active ones."
		}
		"-r" = {
			set_if = "$snmp_service_noregexp$"
			description = "Do not use regexp to match NAME in service description."
		}
	}
	
	vars.snmp_service_name = ".*"
}
```

I prefer to not open another PR as this one already handle this addition.

BR,
Yannick

**Comment by dnsmichi** [comment]
@Tontonitch I'll appreciate it if you could send a PR including documentation already. I did not look deeply into the available command arguments, thanks for the hint.

**Comment by Tontonitch** [comment]
ok, I will propose a PR asap

**Comment by dnsmichi** [comment]
Thx, closing this one.

**Comment by Gregger83** [comment]
@Tontonitch I copied the command definition for "snmp-service"-command from the "snmp-process"-command definition above. 

The name of the variable of the -F-Parameter of the "snmp-process"-command doesn't follow these "BestPractices" either, does it?

**Comment by Gregger83** [comment]
Thanks to all for adding the "missing" command definition 😄

**Pull request closed without merging**
