### PR TITLE
Don't use deprecated RSA_generate_key

### LINKED ISSUE #4635: [dev.icinga.com #12647] OpenSSL: RSA_generate_key is deprecated
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12647

**Created by mfrosch on 2016-09-05 11:12:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-05 11:12:18 +00:00 (in Redmine)_

    Icinga Version: 2.5.0
    Backport?: Not yet backported
    Include in Changelog: 1

---

Please replace.

    /home/markus/devel/icinga/icinga2/lib/base/tlsutility.cpp: In function ‘int icinga::MakeX509CSR(const icinga::String&, const icinga::String&, const icinga::String&, const icinga::String&, bool)’:
    /home/markus/devel/icinga/icinga2/lib/base/tlsutility.cpp:327:13: warning: ‘RSA* RSA_generate_key(int, long unsigned int, void (*)(int, int, void*), void*)’ is deprecated [-Wdeprecated-declarations]
      RSA *rsa = RSA_generate_key(4096, RSA_F4, NULL, NULL);
                 ^~~~~~~~~~~~~~~~
    In file included from /usr/include/openssl/x509.h:31:0,
                     from /usr/include/openssl/ssl.h:50,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsutility.hpp:26,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsstream.hpp:27,
                     from /home/markus/devel/icinga/icinga2/lib/base/tlsstream.cpp:20,
                     from /home/markus/devel/icinga/icinga2/build/lib/base/base_unity.cpp:60:
    /usr/include/openssl/rsa.h:193:6: note: declared here
     DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
          ^~~~~~~~~~~~~~~~

### PR DESCRIPTION
**Pull request by Crunsher**
fixes #4635

### CODE REVIEW

**Comment by Crunsher** [comment]
```
/home/jflach/git/icinga2/lib/base/tlsutility.cpp: In function ‘int icinga::MakeX509CSR(const icinga::String&, const icinga::String&, const icinga::String&, const icinga::String&, bool)’:
/home/jflach/git/icinga2/lib/base/tlsutility.cpp:341:49: warning: NULL used in arithmetic [-Wpointer-arith]
  if (RSA_generate_key_ex(rsa, 4096, e, NULL) == NULL) {
```

Nooooooo

**Comment by Crunsher** [comment]
Is this possibly something for 2.8.0? The branch has been lying around finished for a while.

Tested it with API requests and cluster commu

**Comment by Crunsher** [comment]
(I missclicked)
Is this possibly something for 2.8.0? The branch has been lying around finished for a while.
Tested with API request and cluster communication.

**Comment by dnsmichi** [comment]
I'd say, 2.9 will work out. 2.8 is frozen and only requires remaining issues being resolved.

**Comment by gunnarbeutner** [comment]
This conflicts with #5555. We still need to figure out what to do about V2 tickets.

**Comment by dnsmichi** [comment]
@Crunsher please update or close the PR.

**Comment by Crunsher** [comment]
It's on my TODO once I'm done with the non-Icinga stuff

**Comment by Crunsher** [comment]
#5555 makes this PR unnecessary.

**Pull request closed without merging**
