### PR TITLE
ApiListener: Add support for dynamic port handling

### PR DESCRIPTION
**Pull request by lazyfrosch**
- [x] Update docs for constants

Requires #6506 in merge base

### CODE REVIEW

**Comment by dnsmichi** [comment]
I'm going to change the Dictionary::Ptr values into std::pair<String, String> which saves us unnecessary lookups here.

**Comment by dnsmichi** [comment]
Already rebased, ApiListener output looks like:

```
[2018-08-08 17:14:35 +0200] information/ApiListener: Started new listener on '[::]:5665'
```

```
michi@mbmif ~/coding/icinga/icinga2 (feature/apilistener-dynamic-port *<>) $ cat /usr/local/icinga2/var/cache/icinga2/api-state.json
{"host":"::","port":"5665"}
```

The file is not removed on shutdown which means that other services checking on this might have problems.

**Comment by dnsmichi** [comment]
Implemented the removal of the file on shutdown.

screen shot 2018-08-09 at 11 50 16

screen shot 2018-08-09 at 11 50 31

**Comment by nilmerg** [comment]
Thanks, the only thing that leaves me wondering is why the port is a string, not a number. Provides me some fun trying to decode this with go though. :roll_eyes:

**Pull request merged**
