### PR TITLE
Fix for logrotate on error.log

### PR DESCRIPTION
**Pull request by Mikesch-mp**

### CODE REVIEW

**Comment by dnsmichi** [comment]
Can you please explain which problem is being fixed here?

**Comment by Mikesch-mp** [comment]
If log gets rotated icinga is not able to write to it anymore. with copytruncate its still using the same file.

**Comment by dnsmichi** [comment]
`copytruncate` might not exist for all distributions, and we had problems in the past. If a distribution is affected, this likely should be fixed in the packages themselves.

**Comment by dnsmichi** [comment]
Thanks for the patch, but I'll close this.

**Pull request closed without merging**
