### PR TITLE
Allow to easily upgrade Windows dev and CI env's Boost and OpenSSL versions

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Does this sound like a plan?

**Comment by julianbrost** [comment]
What's the deal with https://build-deps.icinga.com/?

But it's still a quite cumbersome task given that you have to touch three places. If I remember correctly, both Boost and OpenSSL are just "unpack into a folder" installers, so maybe they can be downloaded and unpacked at build time (somewhat similar to what we do with NSCP on Windows)?

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by Al2Klimov** [comment]
Colleagues, do you consider [this effort](https://github.com/Icinga/icinga2/blob/852d674ec07041dd7f97bbaa10017696dc02c3da/RELEASE.md#update-packagesicingacom) reasonable?

**Comment by Al2Klimov** [comment]
Whether it’s reasonable not to have the automatic cache utilized here and therefore to have to ssh and wget every time.

**Comment by julianbrost** [comment]
Compared to
1. checking for the existence of a new version,
2. updating the version number in the repo,
3. testing with the new version,
having to place the new version on our download server does not carry weight.

On the other hand, having that caching proxy is one more service that we have to maintain. So in my opinion, the current way is just fine.

**Comment by Al2Klimov** [comment]
Comprehensible.

**Pull request closed without merging**
