### PR TITLE
CheckResult#output: auto-sanitize UTF-8

### LINKED ISSUE #5395: Malformed characters - invalid continuation byte
Hi,

we use SNMP to check our Ricoh printers; "Unabhängiger Tonerzulieferer" seems to be a value that comes from the printer itself. At least snmpwalk gives answers like this:

```
...
iso.3.6.1.2.1.43.17.6.1.5.1.1 = STRING: "Power"
iso.3.6.1.2.1.43.17.6.1.5.1.2 = STRING: "Fehler am Drucker"
iso.3.6.1.2.1.43.17.6.1.5.1.3 = STRING: "Datenempfang"
...
```

Running the check on console:
```
...
OK - Unabh�ngiger Tonerzulieferer {30136}( 4 5 10 1 30136 1)
```

I can do a curl API query for my "Alerts" service object like this, and it gives me the result I expected:
```
# curl -k -s -u root:<password> 'https://localhost:5665/v1/objects/services/miro!Alerts'
{"results":[{"attrs":{"__name":"miro!Alerts","acknowledgement":0.0,"acknowledgement_expiry":0.0,"action_url":"","active":true,"check_attempt":1.0,"check_command":"dfki_printer","check_interval":300.0,"check_period":"","check_timeout":null,"command_endpoint":"","display_name":"Alerts","downtime_depth":0.0,"enable_active_checks":true,"enable_event_handler":true,"enable_flapping":false,"enable_notifications":true,"enable_passive_checks":true,"enable_perfdata":true,"event_command":"","flapping":false,"flapping_last_change":1499159071.3040699959,"flapping_negative":1485.0,"flapping_positive":0.0,"flapping_threshold":30.0,"force_next_check":false,"force_next_notification":false,"groups":["toner"],"ha_mode":0.0,"host_name":"miro","icon_image":"","icon_image_alt":"","last_check":1499159071.3040030003,"last_check_result":{"active":true,"check_source":"<icingamaster>","command":["/usr/lib/nagios/plugins/check_printer3","a.b.c.d","xxx","1","alerts"],"execution_end":1499159071.3038980961,"execution_start":1499159071.2458488941,"exit_status":0.0,"output":"OK - Unabh�ngiger Tonerzulieferer {30136}( 4 5 10 1 30136 1)","performance_data":[],"schedule_end":1499159071.3040030003,"schedule_start":1499159071.2455990314,"state":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"last_hard_state":0.0,"last_hard_state_change":1499142615.2016129494,"last_reachable":true,"last_state":0.0,"last_state_change":1499142615.2016129494,"last_state_critical":1496313811.382529974,"last_state_ok":1499159071.3040568829,"last_state_type":1.0,"last_state_unknown":1491035429.6507360935,"last_state_unreachable":1482921137.0362250805,"last_state_warning":1499142555.3537349701,"max_check_attempts":3.0,"name":"Alerts","next_check":1499159368.364071846,"notes":"","notes_url":"","original_attributes":null,"package":"director","paused":false,"retry_interval":60.0,"state":0.0,"state_type":1.0,"templates":["Alerts","DFKI Printer Check","Printer Queries","DFKI Service","host var overrides (Director)"],"type":"Service","vars":{"grafana_graph_disable":true,"printer_command":"alerts"},"version":0.0,"volatile":false,"zone":"<icingamaster>"},"joins":{},"meta":{},"name":"miro!Alerts","type":"Service"}]}
```

However - the same query with python -m json.tool fails:
```
# curl -k -s -u root:<password> 'https://localhost:5665/v1/objects/services/miro!Alerts' | python -m json.tool
'utf8' codec can't decode byte 0xe4 in position 10: invalid continuation byte
```

This seems to be the reason why clicking "Inspect" leads to a stacktrace:
```
Parsing JSON result failed: Malformed UTF-8 characters, possibly incorrectly encoded
```
screen shot 2017-06-30 at 13 31 57

Seems to be a bigger issue than I thought? So closing [#987](https://github.com/Icinga/icingaweb2-module-director/issues/987) now and opening this one instead. Feel free to contact me in case you need further information.

Cheers,
  Marianne

## Steps to Reproduce (for bugs)

In this case:
1. Take a printer with weird software.
2. Tell him so speak German.
3. Do SNMP queries with umlaut results.

But as Thomas said: _"Related data should either not be accepted or normalized when "entering" the core. Shipping invalid JSON with any kind of "graceful" JSON parsing is not an option at all, no matter where it appears."_

## Context

Users think the whole monitoring is broken always when they see stacktraces.

## Your Environment

* Director version (System - About): 1.3.1 // 4d240976a3e1ffe1eb9555fa23067da4aed25a58
* Icinga Web 2 version and modules (System - About): 2.4.0 // 7a2d8eda8dd8c37198d0e754218cdedd12e3fde4
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: apache2-2.4.18, php7-7.0.18

### LINKED ISSUE #6828: Illegal utf8 byte sequence in plugin output causes IDO to fail
If a plugin returns output that contains an (specific) illegal utf8 sequence, postgres complains which causes the IDO inserts to fail thus breaking icinga IDO updates.

## Expected Behavior
does not break. (illegal characters are escaped or ignored)

## Current Behavior
icinga fails to write updates to IDO

## Possible Solution
remove illegal bytes or escape them  

## Steps to Reproduce (for bugs)

1. use nscp on a japanese windows installation. Have an error occur so that nscp relays the system message.

Example (from icinga.log)

```
[2018-12-06 17:07:40 +0000] critical/IdoPgsqlConnection: Error "ERROR:  invalid byte sequence for encoding "UTF8": 0xc1 0x82
" when executing query "UPDATE icinga_servicestatus SET acknowledgement_type = E'0',  active_checks_enabled = E'1',  check_command = E'nscp_api',  check_source = E'XXXXXX',  check_type = E'0',  current_check_attempt = E'1',  current_notification_number = E'1',  current_state = E'3',  endpoint_object_id = 11094,  event_handler_enabled = E'1', 
 execution_time = E'2.130000',  flap_detection_enabled = E'0',  has_been_checked = E'1',  instance_id = 1,  is_flapping = E'0',  is_reachable = E'1',  last_check = TO_TIMESTAMP
(1544116060) AT TIME ZONE 'UTC',  last_hard_state = E'3',  last_hard_state_change = TO_TIMESTAMP(1544115999) AT TIME ZONE 'UTC',  last_notification = TO_TIMESTAMP(1544115999) AT TIME ZONE 'UTC',  last_state_change = TO_TIMESTAMP(1544115826) AT TIME ZONE 'UTC',  last_time_unknown = TO_TIMESTAMP(1544116060) AT TIME ZONE 'UTC',  latency = E'0',  long_ou
tput = E'\\nCaught exception: Error: Unknown exception\\n\\n\\n\\n\\n\\nUNKNOWN: No data received.',  max_check_attempts = E'5',  next_check = TO_TIMESTAMP(1544116117) AT TIME 
ZONE 'UTC',  next_notification = TO_TIMESTAMP(1544115996) AT TIME ZONE 'UTC',  normal_check_interval = E'1',  notifications_enabled = E'1',  original_attributes = E'null',  out
put = E'[2018-12-07 02:07:40 +0900] critical/TcpSocket: Invalid socket: 10061, "�Ώۂ̃R���s���[�^�[�ɂ��<C1><82>ċ��ۂ��ꂽ���߁A�ڑ��ł��܂����ł����B"',  passive_checks_enabled = E'1',  
percent_state_change = E'0',  perfdata = E'',  problem_has_been_acknowledged = E'0',  process_performance_data = E'1',  retry_check_interval = E'0.500000',  scheduled_downtime_
depth = E'0',  service_object_id = 16143,  should_be_scheduled = E'1',  state_type = E'1',  status_update_time = TO_TIMESTAMP(1544116060) AT TIME ZONE 'UTC' WHERE service_object_id = 16143"
[2018-12-06 17:07:40 +0000] warning/IdoPgsqlConnection: Exception during database operation: Verify that your database is operational!
```

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.14.4.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Enabled features (`icinga2 feature list`):
```
Enabled features: api checker graphite ido-pgsql mainlog notification
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #6828
fixes #5395

### CODE REVIEW

**Comment by Al2Klimov** [comment]
# Test protocol

## Check plugin

```perl
#!/usr/bin/perl

print "GARBAGE OK: \x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff"
```

## `curl ... '.../v1/objects/services/...!garbage?pretty=1' |hexdump -C` on 75e06e9c0

```
000007c0  20 20 20 20 20 20 20 22  6f 75 74 70 75 74 22 3a  |       "output":|
000007d0  20 22 47 41 52 42 41 47  45 20 4f 4b 3a 20 80 81  | "GARBAGE OK: ..|
000007e0  82 83 84 85 86 87 88 89  8a 8b 8c 8d 8e 8f 90 91  |................|
000007f0  92 93 94 95 96 97 98 99  9a 9b 9c 9d 9e 9f a0 a1  |................|
00000800  a2 a3 a4 a5 a6 a7 a8 a9  aa ab ac ad ae af b0 b1  |................|
00000810  b2 b3 b4 b5 b6 b7 b8 b9  ba bb bc bd be bf c0 c1  |................|
00000820  c2 c3 c4 c5 c6 c7 c8 c9  ca cb cc cd ce cf d0 d1  |................|
00000830  d2 d3 d4 d5 d6 d7 d8 d9  da db dc dd de df e0 e1  |................|
00000840  e2 e3 e4 e5 e6 e7 e8 e9  ea eb ec ed ee ef f0 f1  |................|
00000850  f2 f3 f4 f5 f6 f7 f8 f9  fa fb fc fd fe ff 22 2c  |..............",|
00000860  0a 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |.               |
00000870  20 20 20 20 20 22 70 65  72 66 6f 72 6d 61 6e 63  |     "performanc|
```

## `curl ... '.../v1/objects/services/...!garbage?pretty=1' |hexdump -C` on b84090243

```
000007c0  20 20 20 20 20 20 22 6f  75 74 70 75 74 22 3a 20  |      "output": |
000007d0  22 47 41 52 42 41 47 45  20 4f 4b 3a 20 ef bf bd  |"GARBAGE OK: ...|
000007e0  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
000007f0  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000800  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000810  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
00000820  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000830  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000840  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
00000850  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000860  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000870  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
00000880  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000890  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
000008a0  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
000008b0  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
000008c0  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
000008d0  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
000008e0  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
000008f0  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000900  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
00000910  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000920  bd ef bf bd ef bf bd ef  bf bd ef bf bd ef bf bd  |................|
00000930  ef bf bd ef bf bd ef bf  bd ef bf bd ef bf bd ef  |................|
00000940  bf bd ef bf bd ef bf bd  ef bf bd ef bf bd ef bf  |................|
00000950  bd ef bf bd ef bf bd ef  bf bd ef bf bd 22 2c 0a  |.............",.|
00000960  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
00000970  20 20 20 20 22 70 65 72  66 6f 72 6d 61 6e 63 65  |    "performance|
```

**Comment by dnsmichi** [comment]
We shouldn't hide such logic in the ti files, but override the getter/setter when needed in the cpp variants. 

Either way, I'm still not a friend of fixing this partially but in a common effort for anything related (with #6812).

**Comment by Al2Klimov** [comment]
AFAIK this method of overriding them is technically state of the art and making them virtual may decrease the performance. What about #6832 as an alternative or addition?

**Comment by peteeckel** [comment]
Sorry if I interrupt. I fully understand the cause of finding a good solution for this, but in this case a quick-fix until the final solution is ready would be a good idea - last week the issue brought the monitoring environment for a few hundred hosts to a halt, which can happen at any time and in any other environment as well when a mere plugin misbehaves.

**Comment by peteeckel** [comment]
I absolutely understand that, and I agree fully. 

On the other hand, some misbehaving plugin (and in this case it isn't just another plugin, it's nsclient++, i.e. almost ubiquitous, at least if there are Windows machine around) that can bring down the whole environment is kind of a ticking time-bomb ... in this case the servers are not (yet) productive, but that was sheer luck.

**Comment by Al2Klimov** [comment]
@LordHepipud Haven't you told me that one can set Windows' global codepage to e.g. UTF-8?

@peteeckel There's your quick fix.

**Comment by peteeckel** [comment]
> @peteeckel There's your quick fix.

Not sure if global changes to customer's machines codepages are something they can/will do. I rather hope there is some setting in nsclient++ to that effect - that could be rolled out immediately.

**Comment by Al2Klimov** [comment]
I'm afraid I don't know much about NSClient... but @Crunsher does.

**Pull request closed without merging**
