### PR TITLE
Fix Dictionary Move Constructor

### LINKED ISSUE #9193: Dictionary has a constructor that looks like it should move but doesn't
`DictionaryData` is currently defined as a vector: https://github.com/Icinga/icinga2/blob/185fab3761dc4283844bab85e689ed543ee43160/lib/base/dictionary.hpp#L16

Whereas `Dictionary` internally stores its data as a map:
https://github.com/Icinga/icinga2/blob/185fab3761dc4283844bab85e689ed543ee43160/lib/base/dictionary.hpp#L77

Directory has a constructor that looks like it should move from `DirectoryData`:
https://github.com/Icinga/icinga2/blob/185fab3761dc4283844bab85e689ed543ee43160/lib/base/dictionary.hpp#L39

However, it internally just copies:
https://github.com/Icinga/icinga2/blob/185fab3761dc4283844bab85e689ed543ee43160/lib/base/dictionary.cpp#L22-L26

**Task**: Figure out if `DictionaryData` can be made a map that can actually be moved into a `Dictionary`.

### PR DESCRIPTION
**Pull request by sreyhani**
now it actually moves the data using move_iterator, instead of copying it

Fixes #9193

### CODE REVIEW

**Comment by sreyhani** [comment]
> Thank you for your pull request. Before we can look at it, you'll need to sign a Contributor License Agreement (CLA).
> 
> **Please follow instructions at https://icinga.com/company/contributor-agreement to sign the CLA.**
> 
> After that, please reply here with a comment and we'll verify.
> 
> Contributors that have not signed yet: @sreyhani

i have signed it already

**Comment by sreyhani** [comment]
@cla-bot check

**Comment by sreyhani** [comment]
@cla-bot recheck

**Comment by sreyhani** [comment]
@cla-bot check

**Comment by Al2Klimov** [comment]
Colleagues, correct me if I'm wrong, but IMAO this

1. doesn’t actually change anything
2. except readability.

**Comment by sreyhani** [comment]
> Colleagues, correct me if I'm wrong, but IMAO this
> 
> 1. doesn’t actually change anything
> 2. except readability.

I've tested both methods, and it seems you're right. it was already being move.

but its more elegant, isn't it :smile: ?
```C++
#include <iostream>
#include <map>
#include <vector>
#include <algorithm>

int main()
{
	std::vector<std::pair<std::string, int>> simple_move_values = {
		{"one", 1},
		{"two", 2},
		{"three", 3}
	};

	std::vector<std::pair<std::string, int>> move_iterator_values = {
		{"one", 1},
		{"two", 2},
		{"three", 3}
	};

	std::map<std::string, int> move_iterator_map;
	std::map<std::string, int> simple_move_map;

	for (auto& pair : simple_move_values)
		simple_move_map.insert(std::move(pair));

  std::for_each(std::make_move_iterator(move_iterator_values.begin()), std::make_move_iterator(move_iterator_values.end()),
                [&](std::pair<std::string, int>&& pair) { move_iterator_map.insert(std::move(pair)); });
                
	for (const auto &entry: simple_move_map) {
		std::cout << "simple_move_map values: {" << entry.first << ", " << entry.second << "}" << std::endl;
	}

	for (const auto &entry: simple_move_values) {
		std::cout << "simple_move_values values: {" << entry.first << ", " << entry.second << "}" << std::endl;
	}

	for (const auto &entry: move_iterator_map) {
		std::cout << "move_iterator_map values: {" << entry.first << ", " << entry.second << "}" << std::endl;
	}

	for (const auto &entry: move_iterator_values) {
		std::cout << "move_iterator_values values: {" << entry.first << ", " << entry.second << "}" << std::endl;
	}

	return 0;
}
```

output:
```
simple_move_map values: {one, 1}
simple_move_map values: {three, 3}
simple_move_map values: {two, 2}
simple_move_values values: {, 1}
simple_move_values values: {, 2}
simple_move_values values: {, 3}
move_iterator_map values: {one, 1}
move_iterator_map values: {three, 3}
move_iterator_map values: {two, 2}
move_iterator_values values: {, 1}
move_iterator_values values: {, 2}
move_iterator_values values: {, 3}
```

**Comment by Al2Klimov** [comment]
No.

**Pull request closed without merging**
