### PR TITLE
Add Agent System Requirements to Docs 10-icinga2-client.md

### PR DESCRIPTION
**Pull request by TechIsCool**
Update Windows System Requirements

### CODE REVIEW

**Comment by dnsmichi** [comment]
Thanks - could you please update the author to <first last name>, which follows our AUTHORS guidelines? Then I'll happily apply it.

**Comment by TechIsCool** [comment]
Done. Adjusted the Authors and included myself let me know if you need more than just that one file updated.

**Comment by lazyfrosch** [comment]
@TechIsCool what Michi meant is your GIT commit.

```
git config --global user.name "David Beck"
git config --global user.email "techiscool@gmail.com"
```

Our AUTHORS file is generated from GIT :)

Please change your first commit (amend) and only push that one.

**Comment by TechIsCool** [comment]
@lazyfrosch Completed, Sorry about that I have recommitted with the updated information.

**Comment by TechIsCool** [comment]
Woops closed that unintentionally sorry about that I read it as close and comment like the box. Lesson learned.

**Comment by dnsmichi** [comment]
Please always link the referencing issue - https://dev.icinga.org/issues/9180

**Comment by dnsmichi** [comment]
Thanks, merged :+1:

**Pull request closed without merging**
