### PR TITLE
Fix wrong calculation of check_swap windows plugin

### LINKED ISSUE #5815: swap-windows check delivers wrong result
The server on which the problem was detected has its own partition for swap. This partition is 10GB in size.

In the system settings for virtual memory, the size is limited to 10GB initial and maximum.

The pagefile is currently also about 10GB in size.

In Icinga / Icingaweb2 but also with manual execution you get totally different results.

The current value is ~19GB and the maximum possible is said to be ~25GB.

Wrong counters seem to be used here.

2017-11-28 15_44_11-win-swap_02
2017-11-28 15_37_46-win-swap_01

### PR DESCRIPTION
**Pull request by mcktr**
This fixes the wrong calculation of the check_swap windows plugin.

# Tests

All tests where performed on Windows 10 

## Pagefile size managed by Windows: 

```
> wmic pagefile list /format:list

AllocatedBaseSize=2618
CurrentUsage=83
Description=C:\pagefile.sys
InstallDate=20180514213224.700702+120
Name=C:\pagefile.sys
PeakUsage=2086
Status=
TempPageFile=FALSE

> "C:\Program Files\ICINGA2\sbin\check_swap.exe"
SWAP OK - 96.8296% free | swap=2535MB;;;0;2618
```
## Pagefile size set to fixed a size of 4096 MB: 

```
> wmic pagefileset where name="C:\\pagefile.sys" set InitialSize=4096,MaximumSize=4096
Eigenschaften von "\\DESKTOP-DMDRR7Q\ROOT\CIMV2:Win32_PageFileSetting.Name="c:\\pagefile.sys"" werden aktualisiert
Eigenschaft(en) wurde(n) aktualisiert.

> shutdown -r -t 0

> wmic pagefile list /format:list

AllocatedBaseSize=4096
CurrentUsage=126
Description=C:\pagefile.sys
InstallDate=20180514213224.700702+120
Name=C:\pagefile.sys
PeakUsage=1932
Status=
TempPageFile=FALSE

> "C:\Program Files\ICINGA2\sbin\check_swap.exe"

SWAP OK - 96.8994% free | swap=3969MB;;;0;4096
```
## Two pagefiles with a fixed size of 4096 MB and 2048 MB

```
> wmic pagefileset create name="E:\pagefile.sys"
Instanz wurde erstellt.

> wmic pagefileset where name="E:\\pagefile.sys" set InitialSize=2048,MaximumSize=2048
Eigenschaften von "\\DESKTOP-DMDRR7Q\ROOT\CIMV2:Win32_PageFileSetting.Name="E:\\pagefile.sys"" werden aktualisiert
Eigenschaft(en) wurde(n) aktualisiert.

> shutdown -r -t 0

> wmic pagefile list /format:list & 

AllocatedBaseSize=4096
CurrentUsage=135
Description=C:\pagefile.sys
InstallDate=20180514213224.700702+120
Name=C:\pagefile.sys
PeakUsage=1308
Status=
TempPageFile=FALSE

AllocatedBaseSize=2048
CurrentUsage=18
Description=E:\pagefile.sys
InstallDate=20180516213038.633031+120
Name=E:\pagefile.sys
PeakUsage=434
Status=
TempPageFile=FALSE

> "C:\Program Files\ICINGA2\sbin\check_swap.exe"

SWAP OK - 97.5098% free | swap=5991MB;;;0;6144
```

fixes #5815

### CODE REVIEW

**Comment by mcktr** [comment]
Some documentation:

* [EnumPageFiles function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682625(v=vs.85).aspx)
* [EnumPageFilesProc callback function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682627(v=vs.85).aspx)

Some other information:
* https://blogs.technet.microsoft.com/markrussinovich/2008/11/17/pushing-the-limits-of-windows-virtual-memory/
* http://microsoft.public.de.german.entwickler.dotnet.vb.narkive.com/dV4FIfe5/windows-auslagerungsdatei

**Comment by mcktr** [comment]
@dnsmichi Which version of Windows and Compiler do you use? From a quick research, I learned that between two releases of Windows 10 there was an update to the `Psapi` header file containing changes in the `PENUM_PAGE_FILE_CALLBACKW` definition.

**Comment by mcktr** [comment]
With MSVC 14.0 I was able to reproduce the build error. I updated the commit and now I am able to build with MSVC 14.0 and MSVC 14.1.

**Comment by Crunsher** [comment]
Started [a build for this branch](https://build.icinga.com/job/icinga2-windows-package/702/console) (it's easier than trying to remember the rdesktop command to check the compiler version ^_^)

**Comment by dnsmichi** [comment]
I'm using 14.1 which is VS 2017.

**Comment by dnsmichi** [comment]
I'll leave this open for 2.9.1+ or 2.10, one needs to have a deeper look.

**Comment by dnsmichi** [comment]
screen shot 2018-09-27 at 10 07 18

**Pull request merged**
