### PR TITLE
Fix wrong PerfData normalization

### PR DESCRIPTION
**Pull request by Welrub**
refs #9634

### CODE REVIEW

**Comment by Welrub** [comment]
done

**Comment by bobapple** [comment]
@cla-bot check

**Comment by Welrub** [comment]
signed27.06.2023, 16:02, "Blerim Sheqa" ***@***.***>:
@cla-bot check

**Review by julianbrost — CHANGES_REQUESTED** [review]
First of all, thanks for you interest in contributing to Icinga.

This change makes the test cases fail as it will always render all trailing `;`, even if they aren't needed. You can find these tests in [`test/icinga-perfdata.cpp`](https://github.com/Icinga/icinga2/blob/master/test/icinga-perfdata.cpp). I think it would be nicer if the returned string would be kept minimal, i.e. remove `;` at the end if it's not required (something the old code tried, but not quite correctly).

It would also be nice if you could add a test case for the problem you're fixing here. (Note: if you're adding an entirely new test function, it has to be added to [`test/CMakeLists.txt`](https://github.com/Icinga/icinga2/blob/master/test/CMakeLists.txt) as well.)

**Pull request closed without merging**
