### PR TITLE
Put `-latomic` to the other `-l`s

### PR DESCRIPTION
**Pull request by Al2Klimov**
to make it compiling on Raspberry Pi OS bullseye.

### CODE REVIEW

**Review by julianbrost — APPROVED** [review]
### Before

https://git.icinga.com/packaging/raspbian-icinga2/-/jobs/134283

```
[100%] Linking CXX executable ../Bin/None/icinga2
cd /builds/packaging/raspbian-icinga2/build/icinga2/obj-arm-linux-gnueabihf/icinga-app && /usr/bin/cmake -E cmake_link_script CMakeFiles/icinga-app.dir/link.txt --verbose=1
/usr/lib/ccache/c++ -g -O2 -ffile-prefix-map=/builds/packaging/raspbian-icinga2/build/icinga2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -pthread -Winvalid-pch -flto -std=c++0x -Wl,-z,relro -flto -latomic -rdynamic CMakeFiles/icingaloader.dir/icinga.cpp.o ../third-party/mmatch/CMakeFiles/mmatch.dir/mmatch.c.o ../third-party/socketpair/CMakeFiles/socketpair.dir/socketpair.c.o ../lib/base/CMakeFiles/base.dir/application-version.cpp.o ../lib/base/CMakeFiles/base.dir/journaldlogger.cpp.o ../lib/base/CMakeFiles/base.dir/base_unity.cpp.o ../third-party/execvpe/CMakeFiles/execvpe.dir/execvpe.c.o ../lib/config/CMakeFiles/config.dir/config_lexer.cc.o ../lib/config/CMakeFiles/config.dir/config_parser.cc.o ../lib/config/CMakeFiles/config.dir/config_unity.cpp.o ../lib/remote/CMakeFiles/remote.dir/remote_unity.cpp.o ../lib/cli/CMakeFiles/cli.dir/cli_unity.cpp.o ../lib/icinga/CMakeFiles/icinga.dir/icinga-itl.cpp.o ../lib/icinga/CMakeFiles/icinga.dir/icinga_unity.cpp.o ../lib/methods/CMakeFiles/methods.dir/methods-itl.cpp.o ../lib/methods/CMakeFiles/methods.dir/methods_unity.cpp.o ../lib/checker/CMakeFiles/checker.dir/checker_unity.cpp.o ../lib/compat/CMakeFiles/compat.dir/compat_unity.cpp.o ../lib/db_ido/CMakeFiles/db_ido.dir/db_ido-itl.cpp.o ../lib/db_ido/CMakeFiles/db_ido.dir/db_ido_unity.cpp.o ../lib/db_ido_mysql/CMakeFiles/db_ido_mysql.dir/db_ido_mysql_unity.cpp.o ../lib/db_ido_pgsql/CMakeFiles/db_ido_pgsql.dir/db_ido_pgsql_unity.cpp.o ../lib/livestatus/CMakeFiles/livestatus.dir/livestatus_unity.cpp.o ../lib/notification/CMakeFiles/notification.dir/notification_unity.cpp.o ../lib/perfdata/CMakeFiles/perfdata.dir/perfdata_unity.cpp.o ../lib/icingadb/CMakeFiles/icingadb.dir/icingadb_unity.cpp.o -o ../Bin/None/icinga2  -Wl,-rpath,:::::::::::::::::::::::::::::::::::: -ldl /usr/lib/arm-linux-gnueabihf/libboost_coroutine.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_context.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_date_time.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_filesystem.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_thread.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_system.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_program_options.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_regex.so.1.74.0 -lssl -lcrypto -lsystemd -ledit -ltermcap -lpthread /usr/lib/arm-linux-gnueabihf/libboost_atomic.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_chrono.so.1.74.0 
/usr/bin/ld: /tmp/check_nscp_api.sQ1RQT.ltrans0.ltrans.o: in function `FetchData(icinga::String const&, icinga::String const&, icinga::String const&, icinga::String const&) [clone .lto_priv.0]':
/usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:548: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /tmp/check_nscp_api.sQ1RQT.ltrans2.ltrans.o: in function `void icinga::intrusive_ptr_release<boost::asio::ssl::context>(icinga::Shared<boost::asio::ssl::context>*)':
/usr/include/c++/10/bits/atomic_base.h:558: undefined reference to `__atomic_fetch_sub_8'
[...]
```

### After

https://git.icinga.com/packaging/raspbian-icinga2/-/jobs/134370

```
[100%] Linking CXX executable ../Bin/None/icinga2
cd /builds/packaging/raspbian-icinga2/build/icinga2/obj-arm-linux-gnueabihf/icinga-app && /usr/bin/cmake -E cmake_link_script CMakeFiles/icinga-app.dir/link.txt --verbose=1
/usr/lib/ccache/c++ -g -O2 -ffile-prefix-map=/builds/packaging/raspbian-icinga2/build/icinga2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -pthread -Winvalid-pch -flto -std=c++0x -Wl,-z,relro -flto -rdynamic CMakeFiles/icingaloader.dir/icinga.cpp.o ../third-party/mmatch/CMakeFiles/mmatch.dir/mmatch.c.o ../third-party/socketpair/CMakeFiles/socketpair.dir/socketpair.c.o ../lib/base/CMakeFiles/base.dir/application-version.cpp.o ../lib/base/CMakeFiles/base.dir/journaldlogger.cpp.o ../lib/base/CMakeFiles/base.dir/base_unity.cpp.o ../third-party/execvpe/CMakeFiles/execvpe.dir/execvpe.c.o ../lib/config/CMakeFiles/config.dir/config_lexer.cc.o ../lib/config/CMakeFiles/config.dir/config_parser.cc.o ../lib/config/CMakeFiles/config.dir/config_unity.cpp.o ../lib/remote/CMakeFiles/remote.dir/remote_unity.cpp.o ../lib/cli/CMakeFiles/cli.dir/cli_unity.cpp.o ../lib/icinga/CMakeFiles/icinga.dir/icinga-itl.cpp.o ../lib/icinga/CMakeFiles/icinga.dir/icinga_unity.cpp.o ../lib/methods/CMakeFiles/methods.dir/methods-itl.cpp.o ../lib/methods/CMakeFiles/methods.dir/methods_unity.cpp.o ../lib/checker/CMakeFiles/checker.dir/checker_unity.cpp.o ../lib/compat/CMakeFiles/compat.dir/compat_unity.cpp.o ../lib/db_ido/CMakeFiles/db_ido.dir/db_ido-itl.cpp.o ../lib/db_ido/CMakeFiles/db_ido.dir/db_ido_unity.cpp.o ../lib/db_ido_mysql/CMakeFiles/db_ido_mysql.dir/db_ido_mysql_unity.cpp.o ../lib/db_ido_pgsql/CMakeFiles/db_ido_pgsql.dir/db_ido_pgsql_unity.cpp.o ../lib/livestatus/CMakeFiles/livestatus.dir/livestatus_unity.cpp.o ../lib/notification/CMakeFiles/notification.dir/notification_unity.cpp.o ../lib/perfdata/CMakeFiles/perfdata.dir/perfdata_unity.cpp.o ../lib/icingadb/CMakeFiles/icingadb.dir/icingadb_unity.cpp.o -o ../Bin/None/icinga2  -Wl,-rpath,:::::::::::::::::::::::::::::::::::: -latomic -ldl /usr/lib/arm-linux-gnueabihf/libboost_coroutine.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_context.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_date_time.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_filesystem.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_thread.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_system.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_program_options.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_regex.so.1.74.0 -lssl -lcrypto -lsystemd -ledit -ltermcap -lpthread /usr/lib/arm-linux-gnueabihf/libboost_atomic.so.1.74.0 /usr/lib/arm-linux-gnueabihf/libboost_chrono.so.1.74.0 
make[4]: Leaving directory '/builds/packaging/raspbian-icinga2/build/icinga2/obj-arm-linux-gnueabihf'
```

**Comment by Al2Klimov** [comment]
@julianbrost Shall we really backport it? v2.14 has it. v2.13.x will get a patch due to v2.13.2. And.. v2.12.x? Are you serious? If someone upgrades the **whole OS** to bullseye, ... you know?

**Comment by julianbrost** [comment]
> v2.13.x will get a patch due to v2.13.2

So that's a backport (but you probably mean 2.13.3). But if we do a 2.12.7, why not include it as well? Don't we build all our support releases for all our supported distributions?

**Comment by Al2Klimov** [comment]
1. No.
2. No. v2.13.2.
3. On a completely new OS can't you install a completely new Icinga?

**Comment by julianbrost** [comment]
So you want to keep this as a local patch in the raspbian-icinga2 repo for 2.13 only?

**Comment by Al2Klimov** [comment]
Confirmed.

**Comment by julianbrost** [comment]
Backported to support/2.13 by #9164, let's see if it will also needed for support/2.12

**Pull request merged**
