### PR TITLE
fix varios typos

### PR DESCRIPTION
**Pull request by hailthemelody**
No further description seems necessary.

### CODE REVIEW

**Comment by dnsmichi** [comment]
Please create a new issue next time :)

https://dev.icinga.org/issues/11902

**Comment by dnsmichi** [comment]
And please update your commit to use a valid git author.

Author: hailthemelody@rm-laptop04 <hailthemelody@rm-laptop04>

->

git config --global user.name = "..."
git config --global user.email = "..."

**Comment by hailthemelody** [comment]
Sorry @dnsmichi , new to the Git and learning the best practices.

I will create a new ticket in the future and thank you for doing so on my behalf. I have removed the domain suffix from my username and resubmitted the commit (see d994f7a) per your request.

**Comment by gunnarbeutner** [comment]
Your author name + mail address is currently 'hailthemelody <rainman@hailthemelody.com>'. Please update this to include your real name.

**Comment by hailthemelody** [comment]
Hi @gunnarbeutner , unfortunately I'm not able to provide more information than that for the moment.

**Comment by gunnarbeutner** [comment]
Thank you for your effort. Unfortunately we won't be able to merge it without a proper 'Author' header.

**Comment by hailthemelody** [comment]
That is unfortunate. The email address is valid and I'd be happy to respond to any verification emails you send. I have several corrections to the documentation prepared as well, would you be willing to accept them at https://dev.icinga.org/ ?

**Comment by gunnarbeutner** [comment]
We require a valid 'Author' header for all patches, no matter whether you submit them via GitHub or dev.icinga.org - at the end of the day they all end up in the same Git repository anyway.

**Comment by hailthemelody** [comment]
Please note that I opened a separate issue before being aware of your policies (regarding author names that don't make actual names), available at https://dev.icinga.org/issues/11907 . Should I cancel that?

I have a lot of typos I'd like to correct in the program and documentation but if you're not willing to accept my work then it will have to wait until I'm able to share my actual name.

May I ask why your policy is this way?

**Comment by gunnarbeutner** [comment]
I've closed the dev.icinga.org ticket for you. We require real names for our auto-generated AUTHORS file.

**Comment by dnsmichi** [comment]
We are an open community and sharing the real name is the least one could expect for a personal patch. If we have some questions for patch authors at some later point, it is also helpful to know whom we are going to contact. 

More on that over here: https://wiki.icinga.org/display/Dev/Developer+Guidelines#DeveloperGuidelines-PatchQualityandAuthor

**Comment by hailthemelody** [comment]
I agree in people being accessibly in the long term, which is why the email address I provided is valid and will reach me indefinitely, and is checked several times a day. I am proud of the work I do though for reasons I can't elaborate I must use a pseudonym. I am passionate about Icinga and I wish a valid and frequently-checked email would be enough.

**Comment by mjbrooks** [comment]
We are a community of real people creating real software used by real enterprises around the world. Allowing pseudonyms would be unprofessional and would ultimately cause people to place less of a value on the project.

Feel free to ping me out of band here or on IRC if you need more of an explanation; but as it stands, by using a pseudonym, the git commit does not meet the quality requirements outlined in the developer guidelines that dnsmichi linked previously.

We're glad you are passionate about Icinga and hope that whatever is keeping you from revealing yourself is no longer hanging over your head in the future so you will be able to contribute freely.

**Comment by hailthemelody** [comment]
Thank you for your detailed message @mjbrooks , it is helpful to me to understand the reasoning behind it. I look forward to a time when I can freely contribute!

**Pull request closed without merging**
