### PR TITLE
Refactor environment for API connections

### LINKED ISSUE #6507: Variable name conflict in constants.conf / Problem with TLS verification, CN and Environment variable
Hello,

yesterday I updated our stage environment from 2.8.4 to 2.9.1 and it went horribly wrong. After the update icingaweb2 stopped to display new results/hosts/checks.
In the logs of all masters and satellites I got the following warnings every few minutes:

```
[2018-07-31 09:43:34 +0200] warning/ApiListener: Unexpected certificate common name while connecting to endpoint 'stage.master01:stage': got 'stage.master01'
Context:
        (0) Handling new API client connection
```

The funny thing is that it says `warning` but it really means `this is a fatal error and your cluster is unable to connect`.

After a lot of debugging I found this commit: https://github.com/Icinga/icinga2/commit/9c1e00eb94e811a708e4afc296329cf17b6a1055 and the  related PR: https://github.com/Icinga/icinga2/pull/6305

So you may ask: Why does it break our cluster? We already used a `Environment=stage` variable in our constants.conf. Of course for another purpose. Well, when you know about the PR that introduced the new variable it is pretty obvious that our variable would break the cluster - but I did not know 😉

I have some thoughts about this:
- The warning about the unexpected CN should be an error!
- What is the actual purpose of this variable? I read the PR and the description in the docs but it does not really explain why you added it and what users could use it for. Maybe you could extend the docs about this. (@gunnarbeutner)
- Could we add a way to distinguish between variables with a predefiend meaning and new variables defined by the user?
- In our case we added a prefix to our variable `companyNameEnvironment`.
- We could add a note to the docs with the advise to use a prefix for custom variables to avoid conflicts with new predefined variables in the future.
- (Calling values in constants.conf variables is confusing.)

I am looking forward to hear other opinions about this. How can we avoid variable name conflicts in the future? What do you think?

Best regards
Max

## Your Environment

* Version used (`icinga2 --version`): r2.9.1-1
* Operating System and version: Ubuntu 16.04.5 LTS

### PR DESCRIPTION
**Pull request by lazyfrosch**
* Handling moved to ApiListener
* Now a property of IcingaApplication
* Empty by default

Requires #6506

fixes #6507

### CODE REVIEW

**Comment by lazyfrosch** [comment]
This will need rebasing after #6506 has been merged

**Comment by dnsmichi** [comment]
Tasks

- [ ] Rename to `Environment` instead of `ApiEnvironment`
- [ ] Figure out if the ApiListener object attribute is needed
- [ ] Re-add the FeatureStats `environment` attribute, this will be used in our new backend
- [ ] Upgrading docs and docs review

**Comment by dnsmichi** [comment]
Rebased, will continue with reviewing the changes.

**Comment by lazyfrosch** [comment]
We could also move environment to IcingaApplication, but IMHO it should be an object property.

**Comment by dnsmichi** [comment]
Discussed it with @lippserd, we've agreed on using the IcingaApplication object since this one holds all the information we need for IcingaDB as well.

**Comment by dnsmichi** [comment]
Took me a while to move this into IcingaApplication, since we cannot link from libremote to libicinga. This puts the static getters into libbase and the Application class, and will be reworked after #6509 has been merged. Bonus of this is 

```
michi@mbmif ~/coding/icinga/icinga2 (feature/sni-environment *<>) $ curl -k -s -u root:icinga 'https://localhost:5665/v1/objects/icingaapplications/app?pretty=1&attrs=environment'
{
    "results": [
        {
            "attrs": {
                "environment": "staging"
            },
            "joins": {

            },
            "meta": {

            },
            "name": "app",
            "type": "IcingaApplication"
        }
    ]
}
```

and clean getter/setter methods for our features and interfaces.

```
michi@mbmif ~/coding/icinga/icinga2 (feature/sni-environment *<>) $ icinga2 console --connect 'https://root:icinga@localhost:5665/'
Icinga 2 (version: v2.9.1-84-g515a82a11)
Type $help to view available commands.
<1> => var ia = get_object(IcingaApplication, "app")
null
<2> => ia.environment
"staging"
```

I will take a note to do the same with the `version` attribute.

**Comment by dnsmichi** [comment]
```
mbmif /usr/local/icinga2/etc/icinga2 (master *) # cat tests/app.conf
object IcingaApplication "app" {
  environment = "bumsti"
}
```

```
michi@mbmif ~/coding/icinga/icinga2 (feature/sni-environment *<>) $ curl -k -s -u root:icinga 'https://localhost:5665/v1/objects/icingaapplications/app?pretty=1&attrs=environment'
{
    "results": [
        {
            "attrs": {
                "environment": "bumsti"
            },
            "joins": {

            },
            "meta": {

            },
            "name": "app",
            "type": "IcingaApplication"
        }
    ]
}
```

If you don't set any configuration bits for `Environment`, you pass such via `-D`. The configuration wins at last.

**Comment by dnsmichi** [comment]
By default, we don't set any value for `Environment`. This works best with the SNI environments, and we'll handle this in Icinga DB then as well. The good thing with the object getter is that this makes it more easy to fetch in these code regions then too.

**Comment by dnsmichi** [comment]
```
mbmif /usr/local/icinga2/etc/icinga2 (master *) # icinga2 daemon -DEnvironment=abc
```

```
michi@mbmif ~/coding/icinga/icinga2 (feature/sni-environment *<>) $ curl -k -s -u root:icinga 'https://localhost:5665/v1/objects/icingaapplications/app?pretty=1&attrs=environment'
{
    "results": [
        {
            "attrs": {
                "environment": "abc"
            },
            "joins": {

            },
            "meta": {

            },
            "name": "app",
            "type": "IcingaApplication"
        }
    ]
}
```

**Comment by dnsmichi** [comment]
```
michi@mbmif ~/coding/icinga/icinga2 (feature/sni-environment *=) $ curl -k -s -u root:icinga 'https://localhost:5665/v1/status/IcingaApplication?pretty=1'
{
    "results": [
        {
            "name": "IcingaApplication",
            "perfdata": [

            ],
            "status": {
                "icingaapplication": {
                    "app": {
                        "enable_event_handlers": true,
                        "enable_flapping": true,
                        "enable_host_checks": true,
                        "enable_notifications": true,
                        "enable_perfdata": true,
                        "enable_service_checks": true,
                        "environment": "icingadb",
                        "node_name": "mbmif.int.netways.de",
                        "pid": 72110.0,
                        "program_start": 1533898847.8452889919,
                        "version": "v2.9.1-86-g02009525a"
                    }
                }
            }
        }
    ]
}
```

**Pull request merged**
