### PR TITLE
ITL: apt: render vars.apt_[dist_]upgrade=true as --[dist-]upgrade, not --[dist-]upgrade=true

### PR DESCRIPTION
**Pull request by Al2Klimov**
but preserve vars.apt_[dist_]upgrade=-s as --[dist-]upgrade=-s.

closes #9432

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Tested

```
include "/etc/icinga2/constants.conf"
include <command-plugins.conf>

object CheckerComponent "checker" { }

for (k in [ "apt_upgrade", "apt_dist_upgrade" ]) {
	for (v in [ "none", null, false, true, 0, 1, "false", "true", "0", "1", "-s", "lolcat" ]) {
		object Host Json.encode([ k, v ]) use(k, v) {
			check_command = "apt"
			check_interval = 1h
			retry_interval = 1h

			if (v != "none") {
				vars[k] = v
			}
		}
	}
}
```

with `-x notice`. All commandlines matched the host names.

**Comment by julianbrost** [comment]
For reference: this are the commands generated now (as returned by `curl -skSu root:icinga -H 'Accept: application/json' https://localhost:5665/v1/objects/hosts --data-urlencode pretty=1 --data-urlencode 'filter=match("github-9447-*", host.name)' -G | jq '.results[] | [.attrs.vars,.attrs.last_check_result.command]`):

| Variables | Command |
|---|---|
| `null` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": "-s -qq -o Foo::Bar=baz" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade=-s -qq -o Foo::Bar=baz" ]` |
| `{ "apt_dist_upgrade": "-s" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade=-s" ]` |
| `{ "apt_dist_upgrade": "0" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": "1" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade" ]` |
| `{ "apt_dist_upgrade": "false" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": "lolcat" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": "null" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": "true" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade" ]` |
| `{ "apt_dist_upgrade": 0 }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": 1 }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade" ]` |
| `{ "apt_dist_upgrade": false }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": null }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_dist_upgrade": true }` | `[ "/usr/lib/nagios/plugins/check_apt", "--dist-upgrade" ]` |
| `{ "apt_upgrade": "-s -qq -o Foo::Bar=baz" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade=-s -qq -o Foo::Bar=baz" ]` |
| `{ "apt_upgrade": "-s" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade=-s" ]` |
| `{ "apt_upgrade": "0" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": "1" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade" ]` |
| `{ "apt_upgrade": "false" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": "lolcat" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": "null" }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": "true" }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade" ]` |
| `{ "apt_upgrade": 0 }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": 1 }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade" ]` |
| `{ "apt_upgrade": false }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": null }` | `[ "/usr/lib/nagios/plugins/check_apt" ]` |
| `{ "apt_upgrade": true }` | `[ "/usr/lib/nagios/plugins/check_apt", "--upgrade" ]` |

> All commandlines matched the host names.

Well, not really clear what "match" means in this context. I wouldn't say it's clear/obvious that your `"lolcat"` example results in no parameter passed.

Also, no explanation is given on why `match()` is used.

**Comment by julianbrost** [comment]
> Also, no explanation is given on why `match()` is used.

I thought some Director behavior was part of that decision? I mean it could also be `typeof(macro("$...$")) == String` which should handle all the cases within Icinga 2 just fine.

**Comment by Al2Klimov** [comment]
Well, you can also specify "false" by yourself.

**Comment by julianbrost** [comment]
> Well, you can also specify "false" by yourself.

But why would you want to do this? The point of me asking isn't to ask stupid question but to have the reasons why a change was done in a certain way documented together with the change.

But looks like I have to write this down myself.

So first, I think someone claimed that with Director, you can't set `vars.x = false` but rather just `vars.x = "false"`, making it necessary to handle strings here to keep the command definition compatible with Director (I have not verified this claim, I'm just trying to recite from the top of my head).

And then for returning the macro value rather than some boolean value, the reasoning seems to be something along the lines of keeping the behavior as similar as possible to if `set_if = "$apt_upgrade$"` was used.

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
