### PR TITLE
Icinga DB: icinga:*:state: rename acknowledgement to is_acknowledged and commandline to check_commandline

### PR DESCRIPTION
**Pull request by Al2Klimov**
to match Go and PHP code expectations

### CODE REVIEW

**Comment by julianbrost** [comment]
> to match Go and PHP code expectations

That means these keys are what the other code expects, it's broken at the moment, this PR will fix it and there will be no other related PRs?

**Comment by Al2Klimov** [comment]
... ex. backports.

**Comment by julianbrost** [comment]
That means these keys are what the other code expects, it's broken at the moment, this PR will fix it and there will be no other related PRs in the icingadb and icingadb-web repos?

**Comment by Al2Klimov** [comment]
Yes.

**Comment by julianbrost** [comment]
Wait, isn't this PR just a subset of #9413. Please pull the latest master and check if what you're trying to fix here is actually an issue.

**Comment by Al2Klimov** [comment]
Oh. 🐘

**Pull request closed without merging**
