### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by usev6**

### CODE REVIEW

**Comment by usev6** [comment]
Sorry, fo me the process for signing the CLA is too much work -- for the minimal patch.

Please feel free to close this PR and commit the typo fix yourself.

**Comment by Al2Klimov** [comment]
@bobapple Please consider letting us handling trivial changes differently.

**Comment by RincewindsHat** [comment]
Is in #9013 . This can be closed

**Comment by usev6** [comment]
Thanks, I'm closing the PR.

**Pull request closed without merging**
