### PR TITLE
adjusted language precedence table

### PR DESCRIPTION
**Pull request by tkoeck**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
The `adjusted satellite node description` commit seems to be unrelated to what this PR was initially about. Is that on purpose?

**Comment by tkoeck** [comment]
Yes. Should I have created a second PR for this?

**Comment by gunnarbeutner** [comment]
Yes, please. One PR for each feature.

**Comment by tkoeck** [comment]
Thank's for the advice.

**Comment by gunnarbeutner** [comment]
Hi, the other commit is still in this PR. Can you please remove it so we can merge this?

**Comment by tkoeck** [comment]
Sorry I cannot find the option to remove one commit from the PR. I'll close the PR and create to of them again.

**Comment by dnsmichi** [comment]
You can do so by locally rebasing your git branch. Look here for details: https://github.com/Icinga/icinga2/blob/master/CONTRIBUTING.md#-rebase-a-branch

**Pull request closed without merging**
