### PR TITLE
Add activation priority for config object types

### LINKED ISSUE #6057: Icinga2 sends notifications without logging about it and despite having a downtime
## Expected Behavior
1. Every notifications send generates a Icinga2 log entry
2. A downtimed host shouldn't send notifications

## Current Behavior
We found that Icinga2 sends notifications without logging about it and despite having a downtime set.

Steps we do/see:
1. Host and services are included and monitored from Icinga2 and all checks are UP/OK
2. Host gets downtimed via API call
3. Host gets normally stopped
4. Icinga2 checks the host/sercices - checks are going into DOWN/CRITICAL state
6. Icinga2 regularly gets reloaded because of config changes being synced 
5. After some time (minutes/perhaps 1-2 hours) another reload happens
* While this reload happens, a notifications get set to the user telling about the DOWN state of the host
* We never saw any notifications for services, only for hosts
* This notification isn't logged by Icinga2 (`.*information/Notification: Sending 'Problem' notification.*`), it gets only logged by our notification script.

Notification script log:
```
{"date": "2018-02-01 15:58:47", "type": "email", "destination": "foobar@example.org", "notification_type": "PROBLEM", "service": "", "host": "my-fancy-hostname"}
```

Icinga2 log of the master which send the notification (and reloaded) from 15:58:*
```
[2018-02-01 15:58:00 +0100] information/HttpServerConnection: No messages for Http connection have been received in the last 10 seconds.
[2018-02-01 15:58:23 +0100] warning/TlsStream: TLS stream was disconnected.
[2018-02-01 15:58:23 +0100] warning/JsonRpcConnection: API client disconnected for identity 'master01'
[2018-02-01 15:58:23 +0100] warning/ApiListener: Removing API client for endpoint 'master01'. 0 API clients left.
[2018-02-01 15:58:28 +0100] information/ApiListener: New client connection for identity 'master01' from [89.89.89.89]:47040
[2018-02-01 15:58:28 +0100] information/ApiListener: Sending config updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for zone 'bki' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for zone 'blu' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for zone 'master' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtbki' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtblu' to endpoint 'master01'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Finished sending config file updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:28 +0100] information/ApiListener: Syncing runtime objects to endpoint 'master01'.
[2018-02-01 15:58:29 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'master01'.
[2018-02-01 15:58:29 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:29 +0100] information/ApiListener: Sending replay log for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:29 +0100] information/ApiListener: Finished sending replay log for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:29 +0100] information/ApiListener: Finished syncing endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying config update from endpoint 'master01' of zone 'master'.
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/bki//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/bki' (17 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.852829), Current timestamp '2018-02-01 15:39:11 +0100' (1517495951.020393).
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/blu//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/blu' (17 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.819657), Current timestamp '2018-02-01 15:39:11 +0100' (1517495951.050538).
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/globals.d//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/globals.d' (17 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.823386), Current timestamp '2018-02-01 15:39:10 +0100' (1517495950.980507).
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/master//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/master' (17 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.823882), Current timestamp '2018-02-01 15:39:11 +0100' (1517495951.024695).
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/mgmtbki//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/mgmtbki' (17 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.826017), Current timestamp '2018-02-01 15:39:11 +0100' (1517495951.026952).
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/mgmtblu//.timestamp
[2018-02-01 15:58:30 +0100] information/ApiListener: Updating configuration file: /var/lib/icinga2/api/zones/mgmtblu//_etc/hosts.conf
[2018-02-01 15:58:30 +0100] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones/mgmtblu' (105135 Bytes). Received timestamp '2018-02-01 15:58:28 +0100' (1517497108.824826), Current timestamp '2018-02-01 15:39:10 +0100' (1517495950.981618).
[2018-02-01 15:58:30 +0100] information/ApiListener: Restarting after configuration change.
[2018-02-01 15:58:30 +0100] warning/TlsStream: TLS stream was disconnected.
[2018-02-01 15:58:30 +0100] warning/JsonRpcConnection: API client disconnected for identity 'satellite06'
[2018-02-01 15:58:30 +0100] warning/ApiListener: Removing API client for endpoint 'satellite06'. 0 API clients left.
[2018-02-01 15:58:31 +0100] information/WorkQueue: #17 (JsonRpcConnection, #7) items: 2365, rate: 373.167/s (22390/min 22390/5min 22390/15min);
[2018-02-01 15:58:31 +0100] information/Application: Got reload command: Starting new instance.
[2018-02-01 15:58:41 +0100] information/ApiListener: Reconnecting to endpoint 'satellite06' via host 'satellite06.example.org' and port '5665'
[2018-02-01 15:58:41 +0100] information/ApiListener: New client connection for identity 'satellite06' to [89.89.89.88]:5665
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite06' via host 'satellite06.example.org' and port '5665'
[2018-02-01 15:58:41 +0100] information/ApiListener: Sending config updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite06'.
[2018-02-01 15:58:41 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite06' signed by our CA.
[2018-02-01 15:58:41 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtblu' to endpoint 'satellite06'.
[2018-02-01 15:58:41 +0100] information/JsonRpcConnection: The certificate for CN 'satellite06' cannot be renewed yet.
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite06'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite06'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Sending replay log for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:41 +0100] information/ApiListener: Finished syncing endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:45 +0100] information/ApiListener: New client connection from [127.0.0.1]:58126 (no client certificate)
[2018-02-01 15:58:45 +0100] information/HttpServerConnection: Request: GET /v1/status (from [127.0.0.1]:58126, user: icingabeat)
[2018-02-01 15:58:46 +0100] information/Application: Received request to shut down.
[2018-02-01 15:58:46 +0100] information/Application: Shutting down...
[2018-02-01 15:58:46 +0100] information/ApiListener: 'api' stopped.
[2018-02-01 15:58:46 +0100] information/CheckerComponent: 'checker' stopped.
[2018-02-01 15:58:46 +0100] information/ExternalCommandListener: 'command' stopped.
[2018-02-01 15:58:57 +0100] information/NotificationComponent: 'notification' started.
[2018-02-01 15:58:57 +0100] information/ApiListener: Adding new listener on port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite04' via host 'satellite04.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite03' via host 'satellite03.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite06' via host 'satellite06.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite01' via host 'satellite01.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite02' via host 'satellite02.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'master01' via host 'master01.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Reconnecting to endpoint 'satellite05' via host 'mgmtsatellite01.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'satellite01' to [89.89.89.87]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite01' via host 'satellite01.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Sending config updates for endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'bki' to endpoint 'satellite01'.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite01' signed by our CA.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: The certificate for CN 'satellite01' cannot be renewed yet.
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'satellite06' to [89.89.89.88]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite06' via host 'satellite06.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Sending config updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtblu' to endpoint 'satellite06'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite06'.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite06' signed by our CA.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: The certificate for CN 'satellite06' cannot be renewed yet.
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'master01' to [89.89.89.89]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'master01' via host 'master01.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Sending config updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtbki' to endpoint 'master01'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'master' to endpoint 'master01'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'blu' to endpoint 'master01'.
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'satellite04' to [89.89.89.86]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite04' via host 'satellite04.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: Sending config updates for endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'blu' to endpoint 'satellite04'.
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'satellite02' to [89.89.89.85]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite02' via host 'satellite02.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/ApiListener: New client connection for identity 'satellite03' to [89.89.89.84]:5665
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite03' via host 'satellite03.example.org' and port '5665'
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite02' signed by our CA.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: The certificate for CN 'satellite02' cannot be renewed yet.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite04' signed by our CA.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: The certificate for CN 'satellite04' cannot be renewed yet.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite03' signed by our CA.
[2018-02-01 15:58:57 +0100] information/JsonRpcConnection: The certificate for CN 'satellite03' cannot be renewed yet.
[2018-02-01 15:58:57 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite06'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite01'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtblu' to endpoint 'master01'.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for zone 'bki' to endpoint 'master01'.
[2018-02-01 15:58:57 +0100] information/CheckerComponent: 'checker' started.
[2018-02-01 15:58:57 +0100] information/DbConnection: 'ido-mysql' started.
[2018-02-01 15:58:57 +0100] information/ExternalCommandListener: 'command' started.
[2018-02-01 15:58:57 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite04'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'master01'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite06'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite04'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite06' in zone 'mgmtblu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending config updates for endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for zone 'bki' to endpoint 'satellite02'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite02'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite01'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite02'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'master01'.
[2018-02-01 15:58:58 +0100] information/ApiListener: New client connection for identity 'satellite05' to [89.89.89.84]:5665
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished reconnecting to endpoint 'satellite05' via host 'mgmtsatellite01.example.org' and port '5665'
[2018-02-01 15:58:58 +0100] information/JsonRpcConnection: Received certificate request for CN 'satellite05' signed by our CA.
[2018-02-01 15:58:58 +0100] information/JsonRpcConnection: The certificate for CN 'satellite05' cannot be renewed yet.
[2018-02-01 15:58:58 +0100] information/ApiListener: Applying config update from endpoint 'master01' of zone 'master'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite02'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite02' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending config updates for endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for zone 'blu' to endpoint 'satellite03'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite03'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite01'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite01' in zone 'bki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending config updates for endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for zone 'mgmtbki' to endpoint 'satellite05'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing configuration files for global zone 'globals.d' to endpoint 'satellite05'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite05'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite04'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite04' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Syncing runtime objects to endpoint 'satellite03'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'master01'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Replayed 353 messages.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite05'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite05' in zone 'mgmtbki'.
[2018-02-01 15:58:58 +0100] information/DbConnection: Resuming IDO connection: ido-mysql
[2018-02-01 15:58:58 +0100] information/IdoMysqlConnection: 'ido-mysql' resumed.
[2018-02-01 15:58:58 +0100] information/IdoMysqlConnection: MySQL IDO instance id: 1 (schema version: '1.14.3')
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'satellite03'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Sending replay log for endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'satellite03' in zone 'blu'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished sending replay log for endpoint 'master01' in zone 'master'.
[2018-02-01 15:58:58 +0100] information/ApiListener: Finished syncing endpoint 'master01' in zone 'master'.
```

We also have debuglog from this point in time but i would be really hard to anonymize. Please tell me if you think this would help debugging this and we probably find a way to get it to you.

## Possible Solution
?

## Steps to Reproduce (for bugs)
Not really sure yet on a small test setup. I can more or less frequently reproduce it on our setup.

## Context
We're trying to avoid sending notifications to users for hosts which are normally stopped.

## Your Environment

* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04.3
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.5.0, monitoring/custom
* Config validation (`icinga2 daemon -C`):
```
root@master02:/var/log/icinga2# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: master02
information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 2, rate: 8214.58/s (492875/min 492875/5min 492875/15min);
information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
information/WorkQueue: #7 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
...
Some apply rule warnings
...
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Zones.
information/ConfigItem: Instantiated 8 Endpoints.
information/ConfigItem: Instantiated 5 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 90709 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 11 CheckCommands.
information/ConfigItem: Instantiated 2595 Downtimes.
information/ConfigItem: Instantiated 444 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2738 Hosts.
information/ConfigItem: Instantiated 259 Comments.
information/ConfigItem: Instantiated 257 UserGroups.
information/ConfigItem: Instantiated 51944 Dependencies.
information/ConfigItem: Instantiated 413 Users.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 60952 Services.
information/ConfigItem: Instantiated 1 ServiceGroup.
information/ConfigItem: Instantiated 262 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
object Endpoint NodeName {
  host = "10.0.0.1"
}

object Endpoint "satellite05"  {
  host = "mgmtsatellite01.example.org"
}

object Endpoint "master02"  {
  host = "master02.example.org"
}

object Endpoint "satellite05"  {
  host = "satellite06.example.org"
}

object Endpoint "satellite03"  {
  host = "satellite03.example.org"
}

object Endpoint "satellite04"  {
  host = "satellite04.example.org"
}

object Endpoint "satellite01"  {
  host = "satellite01.example.org"
}

object Endpoint "satellite02"  {
  host = "satellite02.example.org"
}

object Zone "bki"  {
  endpoints = [ "satellite01", "satellite02", ]
  parent = "master"
}

object Zone "blu"  {
  endpoints = [ "satellite03", "satellite04", ]
  parent = "master"
}

object Zone "globals.d"  {
  global = true
}

object Zone "master"  {
  endpoints = [ "master01", "master02", ]
}

object Zone "mgmtbki"  {
  endpoints = [ "satellite05", ]
  parent = "master"
}

object Zone "mgmtblu"  {
  endpoints = [ "satellite05", ]
  parent = "master"
}

```

### LINKED ISSUE #6231: icinga2.8 - Notifications are sent even in downtime
We have icinga master1-2 /satellite/client setup running with version 2.8. We are facing issue that we are still receiving alert notification even in downtime, Downtime is set thorugh web-UI and it shows in UI but still icinga is triggering alert notification mails. I observed that,  no of servers doesnot match between master1 and master 2  server in /var/lib/icinga2/api/packages/_api/<server>/conf.d/downtimes directory 

icinga: 2.8.0-1
icingaweb2: 2.4.1

Master 1  - api.conf is set to false for accept_config but master 2 is set to true

### PR DESCRIPTION
**Pull request by Crunsher**
This PR adds an `activation_priority` option to all icinga objects. Objects are activated in order of their activation, with the lowest going first and the highest last.
The default is 0.

Currently the priorities are as follows
- -100:
Loggers (FileLogger, SyslogLogger) We want these first to make sure any errors are logged
- 0:
Everything else. Mostly Config items (Hosts, Services, Downtimes...) 
- 50:
ApiListener. Stated after config but as the first feature since we want it available asap. A bit of premature optimization possibly.
- 100:
Features (CheckerComponent, CheckResultReader, CompatLogger, ExternalCommandListener, StatusDataWriter, IdoConnections, LivestatusListener, NotificationComponent, ElasticSearchWriter, GelfWriter, GraphiteWriter, InfluxdbWriter, OpenTsdbWriter) These are activated last to make sure they don't act before all config objects are there.

fixes #6057 
fixes #6231

### CODE REVIEW

**Comment by Crunsher** [comment]
This is still a WIP (there are debug messages and a sleep to help debug). Please use this PR to discuss changes to the Priorities.

**Comment by dnsmichi** [comment]
So far, this works fine in my tests in provoking notifications prior to a downtime object.

**Comment by dnsmichi** [comment]
Squashed, amended and rebased. Looks good to me.

**Comment by dnsmichi** [comment]
Technical note: 

The patch adds a feature to our class compiler which parses the .ti files into actual code. This renders it easier to specify the priority just for the type instance from any library. This is necessary since lib/config doesn't know anything about our config object types.

The major change happens in the config compiler within ActivateItems() where the type sort order relies on the priority and enforces that on the config object activation order.

**Comment by dnsmichi** [comment]
Note aside: This is a big change and should be tested with the snapshot packages once available. Backports are only an option after successful tests with the snapshot packages.

**Comment by ekeih** [comment]
Thank you for this fix! Especially @Crunsher 🎉

**Pull request merged**
