### PR TITLE
Avoid name clashes on case-insensitive file systems

### PR DESCRIPTION
**Pull request by efuss**
On case-insensitive file systems (i.e. macOS), the `VERSION` file collides with the Boost-provided `version` file on `#include <version>`.

Work around by re-naming `VERSION` to `ICINGA2_VERSION`.

### CODE REVIEW

**Comment by julianbrost** [comment]
This probably fixes #8484.

**Comment by efuss** [comment]
> This probably fixes #8484.
Yes, that's exactly the problem I faced. I didn't know there already was an open Issue for it, I just fixed it.

**Review by Al2Klimov — COMMENTED** [review]
Seems not to break anything:

```
➜  icinga2 git:(718ebe3cb) prefix/sbin/icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.12.0-450-g718ebe3cb)
```

**Comment by Al2Klimov** [comment]
## Tasks

* Checkout d82e4987b
* Reproduce #8484
* Checkout this PR
* Test whether it fixes #8484

**Comment by efuss** [comment]
> * Test whether it fixes #8484
I have the same change as patches in my local pkgsrc tree and it does:

% icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.3-1)

[...]

System information:
  Platform: macOS
  Platform version: 11.1
  Kernel: Darwin
  Kernel version: 20.2.0
  Architecture: arm64

Build information:
  Compiler: Clang 12.0.0.12000032
[...]

**Comment by Yonas-net** [comment]
**Before**.
```cxx
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.cpp:3:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.hpp:6:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/i2-base.hpp:38:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config.hpp:44:
/Users/yhabteab/Downloads/boost_1_73_0/boost/config/detail/select_stdlib_config.hpp:24:14: warning: non-portable path to file '<VERSION>'; specified path differs in case
      from file name on disk [-Wnonportable-include-path]
#    include <version>
             ^~~~~~~~~
             <VERSION>
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application-environment.cpp:3:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.hpp:6:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/i2-base.hpp:38:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config.hpp:44:
/Users/yhabteab/Downloads/boost_1_73_0/boost/config/detail/select_stdlib_config.hpp:24:14: warning: non-portable path to file '<VERSION>'; specified path differs in case
      from file name on disk [-Wnonportable-include-path]
#    include <version>
             ^~~~~~~~~
             <VERSION>
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.cpp:3:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.hpp:6:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/i2-base.hpp:38:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config.hpp:44:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config/detail/select_stdlib_config.hpp:24:
/Users/yhabteab/Workspace/icinga2/version:1:1: error: unknown type name 'Version'
Version: 2.12.0In file included from 
/Users/yhabteab/Workspace/icinga2/lib/base/application-environment.cpp^:
3:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/application.hpp:6:
In file included from /Users/yhabteab/Workspace/icinga2/lib/base/i2-base.hpp:38:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config.hpp:44:
In file included from /Users/yhabteab/Downloads/boost_1_73_0/boost/config/detail/selecIn file included from t_stdlib_config.hpp:24:
/Users/yhabteab/Workspace/icinga2/version:1:1: error: unknown type name 'Version'
Version: 2.12.0
^
/Users/yhabteab/Workspace/icinga2/version:1:8: error: expected unqualified-id
Version: 2.12.0
       ^
```

**After**:

```cxx
+./build.sh:12> make -j4 -C build
[  2%] Built target socketpair
[  3%] Built target mmatch
[  3%] Built target execvpe
[  5%] Built target mkclass
[  5%] Built target mkembedconfig
[  6%] Built target pgsql_shim
Scanning dependencies of target base
[  6%] Building CXX object lib/base/CMakeFiles/base.dir/application.cpp.o
[  6%] Building CXX object lib/base/CMakeFiles/base.dir/application-version.cpp.o
[  7%] Building CXX object lib/base/CMakeFiles/base.dir/application-environment.cpp.o
[  7%] Building CXX object lib/base/CMakeFiles/base.dir/array.cpp.o
[  7%] Building CXX object lib/base/CMakeFiles/base.dir/array-script.cpp.o
[  8%] Building CXX object lib/base/CMakeFiles/base.dir/base64.cpp.o
[  8%] Building CXX object lib/base/CMakeFiles/base.dir/boolean.cpp.o
[  8%] Building CXX object lib/base/CMakeFiles/base.dir/boolean-script.cpp.o
[  9%] Building CXX object lib/base/CMakeFiles/base.dir/configobject.cpp.o
[  9%] Building CXX object lib/base/CMakeFiles/base.dir/configobject-script.cpp.o
[  9%] Building CXX object lib/base/CMakeFiles/base.dir/configtype.cpp.o
[ 10%] Building CXX object lib/base/CMakeFiles/base.dir/configuration.cpp.o
[ 10%] Building CXX object lib/base/CMakeFiles/base.dir/configwriter.cpp.o
[ 10%] Building CXX object lib/base/CMakeFiles/base.dir/console.cpp.o
[...]
```

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
