### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by Al2Klimov**
closes #9442

### CODE REVIEW

**Comment by julianbrost** [comment]
Why is this needed? Is there some "only add stuff" logic?

**Comment by Al2Klimov** [comment]
Probot will add only new authors since last change. This shall be the new last change.

**Review by julianbrost — APPROVED** [review]
Let's see if this helps

**Comment by Al2Klimov** [comment]
Actually I just do what Probot shall do, but... see for yourself: #9442

**Pull request merged**
