### PR TITLE
API: Harden default cipher list

### PR DESCRIPTION
**Pull request by dnsmichi**
According to https://www.acunetix.com/blog/articles/tls-ssl-cipher-hardening/

### CODE REVIEW

**Comment by dnsmichi** [comment]
@dgoetz @bsdlme opinions?

**Comment by dnsmichi** [comment]
@lippserd I remember this being discussed with #5555, should likely be easy to follow-up.

**Comment by dgoetz** [comment]
It is the same list like in the Mozilla Wiki I added to the docs for hardening. +1 on my side for more secure defaults and as we already have chosen this way for tls version no more possible clients should be excluded by the cipher list.

Can you also change the defaults in the docs?

**Comment by dnsmichi** [comment]
@dgoetz Yep, I just wanted to see whether this change is wanted or not. Docs are intentionally left out this time :)

**Pull request merged**
