### PR TITLE
Allow downtimes starting in the past added by Downtime#AddDowntime() to be triggered

### LINKED ISSUE #7896: Fixed downtime that starts in the past never sends DOWNTIMESTART notification
## Describe the bug
If you create a downtime on a service (or host) that starts in the past even slightly it never send the DOWNTIMESTART notification to any configured notification scripts. This is problematic since if you do not change the start time a downtime created via the webinterface will almost always start in the past (since it uses page load as the start time).

## To Reproduce

1. Setup a notification script with at least DOWNTIMESTART enabled
2. Create a downtime which starts slightly into the future (5 seconds)
3. See a notification happen
4. Create a new downtime which start slightly into the past
5. See no notification happen

## Expected behavior

I expect the DOWNTIMESTART to always get triggered.

## Your Environment

* Version used (`icinga2 --version`): r2.11.2-1
* Operating System and version: Debian Stretch
* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog debuglog elasticsearch gelf graphite opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb livestatus mainlog notification
```
* Icinga Web 2 version and modules (System - About): 2.7.3

### PR DESCRIPTION
**Pull request by Al2Klimov**
... not to loose downtime start notifications.

fixes #7896

### CODE REVIEW

**Comment by Yonas-net** [comment]
Testprotocol:
Until now, it was not possible to start ``downtimes Notification`` successfully that are added in the past but it occured an Error instead like below.
```
[2020-06-18 17:00:43 +0200] information/Notification: Sending reminder 'Problem' notification 'yonas-yonas.int.netways.de!mail-icingaadmin' for user 'icingaadmin'
[2020-06-18 17:00:43 +0200] information/Notification: Completed sending 'Problem' notification 'yonas-yonas.int.netways.de!mail-icingaadmin' for checkable 'yonas-yonas.int.netways.de' and user 'icingaadmin' using command 'mail-host-notification'.
[2020-06-18 17:00:43 +0200] warning/PluginNotificationTask: Notification command for object 'yonas-yonas.int.netways.de' (PID: 7708, arguments: '/home/yonas/Workspace/icinga2/prefix/etc/icinga2/scripts/mail-host-notification.sh' '-4' '127.0.0.1' '-6' '::1' '-b' '' '-c' '' '-d' '2020-06-18 17:00:43 +0200' '-l' 'yonas-yonas.int.netways.de' '-n' 'yonas-yonas.int.netways.de' '-o' 'execvpe(/home/yonas/Workspace/icinga2/prefix/lib/nagios/plugins/check_ping) failed: No such file or directory' '-r' 'icinga@localhost' '-s' 'DOWN' '-t' 'PROBLEM' '-v' 'false') terminated with exit code 1, output: mail not found in $PATH. Consider installing it.
```
but now icinga2 is able to ``start downtimes Notification`` successfully. It does't matter when they are created. And the output looks like below.....
```
[2020-06-18 16:53:47 +0200] information/Checkable: Checkable 'yonas-yonas.int.netways.de!ping4' has 1 notification(s). Checking filters for type 'DowntimeStart', sends will be logged.
[2020-06-18 16:53:47 +0200] information/Notification: Sending 'DowntimeStart' notification 'yonas-yonas.int.netways.de!ping4!mail-icingaadmin' for user 'icingaadmin'
[2020-06-18 16:53:47 +0200] information/Notification: Completed sending 'DowntimeStart' notification 'yonas-yonas.int.netways.de!ping4!mail-icingaadmin' for checkable 'yonas-yonas.int.netways.de!ping4' and user 'icingaadmin' using command 'mail-service-notification'.
```

**Review by yhabteab — DISMISSED** [review]

**Comment by julianbrost** [comment]
I didn't see through all the downtime code yet, especially the differences between fixed/flexible downtimes and started/triggered events. These seem to be surprisingly different code paths.

However, I noticed the following in `Downtime::Start()` which looks like code for a similar case for flexible downtimes: https://github.com/Icinga/icinga2/blob/91ffa89dad41fce6d9feee1209bb8273dd523cf0/lib/icinga/downtime.cpp#L120-L129

So maybe this could also be solved by triggering the downtime there if the current time in in the downtime period?

**Comment by Al2Klimov** [comment]
IMAO that would only cover flexible downtimes.

**Review by julianbrost — COMMENTED** [review]
Now I'm totally confused as it looks like I can't even replicate the issue with the current master (9219f68c83dbdebaf58374420037773c907f60da). I'm scheduling a fixed downtime starting 1 minute in the past and ending 1 minute in the future:

```
$ curl -skSu root:icinga -H 'Accept: application/json' -X POST "https://localhost:5665/v1/actions/schedule-downtime" -d '{"type":"Host", "filter":"host.name == \"master-1\"", "start_time":'$(date -d -1min +%s)', "end_time":'$(date -d +1min +%s)', "author":"icingaadmin", "comment":"42", "pretty":true}'
{
    "results": [
        {
            "code": 200.0,
            "legacy_id": 154.0,
            "name": "master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0",
            "status": "Successfully scheduled downtime 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' for object 'master-1'."
        }
    ]
}
```

Fetching it from the API shows that this downtime was entered (nice, even more confusing wording in addition to started/triggered) about a minute after its start time:

```
$ curl -skSu root:icinga -H 'Accept: application/json' 'https://localhost:5665/v1/objects/downtimes/master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0?pretty=1&attrs=start_time&attrs=end_time&attrs=entry_time&attrs=fixed'
{
    "results": [
        {
            "attrs": {
                "end_time": 1611657731.0,
                "entry_time": 1611657671.211077,
                "fixed": true,
                "start_time": 1611657611.0
            },
            "joins": {},
            "meta": {},
            "name": "master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0",
            "type": "Downtime"
        }
    ]
}
```

And the logs show that a DowntimeStart notification was generated (second to last line):

```
master-1_1         | [2021-01-26 10:41:11 +0000] information/ConfigObjectUtility: Created and activated object 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' of type 'Downtime'.
master-1_1         | [2021-01-26 10:41:11 +0000] information/Downtime: Added downtime 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' between '2021-01-26 10:40:11' and '2021-01-26 10:42:11', author: 'icingaadmin', fixed
master-1_1         | [2021-01-26 10:41:11 +0000] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [::ffff:172.26.0.1]:58488), user: root, agent: curl/7.74.0, status: OK).
master-2_1         | [2021-01-26 10:41:11 +0000] information/ConfigObjectUtility: Created and activated object 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' of type 'Downtime'.
master-2_1         | [2021-01-26 10:41:12 +0000] information/Downtime: Triggering downtime 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' for checkable 'master-1'.
master-1_1         | [2021-01-26 10:41:14 +0000] information/Checkable: Checkable 'master-1' has 1 notification(s). Checking filters for type 'DowntimeStart', sends will be logged.
master-1_1         | [2021-01-26 10:41:14 +0000] information/Notification: Sending 'DowntimeStart' notification 'master-1!dummy-host-notification' for user 'icingaadmin'
master-1_1         | [2021-01-26 10:41:14 +0000] information/Downtime: Triggering downtime 'master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0' for checkable 'master-1'.
master-2_1         | [2021-01-26 10:41:14 +0000] information/Checkable: Checkable 'master-1' has 1 notification(s). Checking filters for type 'DowntimeStart', sends will be logged.
master-1_1         | [2021-01-26 10:41:14 +0000] information/Notification: Completed sending 'DowntimeStart' notification 'master-1!dummy-host-notification' for checkable 'master-1' and user 'icingaadmin' using command 'dummy'.
master-1_1         | [2021-01-26 10:41:39 +0000] information/HttpServerConnection: Request: GET /v1/objects/downtimes/master-1!3db483a9-5cb6-4a07-b4d0-6302df280fb0?pretty=1&attrs=start_time&attrs=end_time&attrs=entry_time&attrs=fixed (from [::ffff:172.26.0.1]:58498), user: root, agent: curl/7.74.0, status: OK).
```

I also don't see which of the conditions in `Downtime::CanBeTriggered()` you need to bypass with the new `Downtime::GetCanBeTriggered()`, none of them should prevent a fixed downtime from starting/triggering if its start time is in the past:

https://github.com/Icinga/icinga2/blob/9219f68c83dbdebaf58374420037773c907f60da/lib/icinga/downtime.cpp#L360-L374

**Comment by kyrias** [comment]
@julianbrost If you can reproduce it in v1.12.3, could you bisect between that tag and master to see what might have accidentally fixed it?

I haven't tested doing it manually through the API yet, but I can consistently reproduce it in IcingaWeb2 with v1.12.3.

**Comment by Al2Klimov** [comment]
@cla-bot check

**Comment by julianbrost** [comment]
This should have been fixed by #9131. With that information, I probably couldn't reproduce the problem in https://github.com/Icinga/icinga2/pull/7962#pullrequestreview-576232967 because the notification was only missing if the checkable is in a problem state.

**Pull request closed without merging**
