### PR TITLE
add the checkCommand for check_iostats

### PR DESCRIPTION
**Pull request by claenjoy**
should work fine with this plugin https://github.com/dnsmichi/icinga-plugins/blob/master/scripts/check_iostats
that give more information than check_iostat

### CODE REVIEW

**Comment by dnsmichi** [comment]
Hi,

can you update the documentation as well please? :)

Kind regards,
Michael

**Comment by claenjoy** [comment]
@dnsmichi 
yep here https://github.com/Icinga/icinga2/pull/100

**Comment by gunnarbeutner** [comment]
Can you please update your patch to include your real name and your real e-mail address in the 'Author' field?

Also, I'd suggest renaming the custom variables to 'iostats_warning_xxx' and 'iostats_critical_xxx' to make them more readable.

**Comment by gunnarbeutner** [comment]
Your patches still have the wrong author btw. Can you please update that as well?

**Comment by gunnarbeutner** [comment]
Merged, thanks.

**Pull request closed without merging**
