### PR TITLE
Fix IDO MySQL schema version

### PR DESCRIPTION
**Pull request by Al2Klimov**
... to match the latest upgrade script.

### CODE REVIEW

**Review by lippserd — APPROVED** [review]

**Comment by julianbrost** [comment]
Should this migration really be in a file `2.13.1.sql` given that it wasn't included in that release? Also, do we want to backport this and if yes, where should we put it? Would be somewhat strange to ship a file called 2.13.x in a 2.12.x release.

**Comment by Al2Klimov** [comment]
2.12.x? What for?

**Comment by julianbrost** [comment]
The discrepancy seems to already exist in support/2.12:
https://github.com/Icinga/icinga2/blob/support/2.12/lib/db_ido_mysql/schema/upgrade/2.11.0.sql#L89
https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/upgrade/2.13.0.sql

But seems like 2.12 would need version 1.15.0 and 2.13 version 1.15.1, so maybe the solution is to ship a file `2.12.7.sql` setting it to `1.15.0` and a file `2.13.3.sql` setting it to `1.15.1`.

**Comment by julianbrost** [comment]
Oh, and this PR places the upgrade file into the wrong directory. So I would create the following PRs:
* On `master`: rename `2.13.1.sql` to `2.13.3.sql` and move it into `schema/upgrades/`, add `2.12.7.sql` for completeness (so that upgrading from 2.12.7 to 2.13.3 or later doesn't make schema files disappear)
* On `support/2.13`: backport `2.13.3.sql` and `2.12.7.sql`
* On `support/2.12`: backport `2.12.7.sql`

**Comment by Al2Klimov** [comment]
* #9138
* #9139
* #9140

**Pull request merged**
